### ISSUE TITLE
Lack of simplifying case of `<symbol> & <mask>` is confusing

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#5819] opened 2024-08-02 11:22 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.2.5811-dev Personal (83861943)
- OS: [e.g. manjaro Linux]
- OS Version: Linux version 6.9.10-1-MANJARO (builduser@fv-az1386-904) (gcc (GCC) 14.1.1 20240522, GNU ld (GNU Binutils) 2.42.0) #1 SMP PREEMPT_DYNAMIC Fri Jul 19 15:08:51 UTC 2024
- CPU Architecture: x64

**Bug Description:**
see the picture

**Steps To Reproduce:**
F5

**Screenshots/Video Recording:**
![image](https://github.com/user-attachments/assets/7cfe6051-0cbd-40be-9b69-d911c1f24d5b)

![image](https://github.com/user-attachments/assets/06b3ceb3-7db6-4ac0-8395-ad30f41cb9de)

**Comment by xusheng6** [comment] 2024-08-02 11:25
Please provide with us a binary so that we can reproduce it

**Comment by negasora** [comment] 2024-08-02 11:35
That looks right to me - `0xffffffff0000ffff & 0xffff0000ffffffff & 0xffffffffffff == 0xffff`

Is there something I'm missing?

**Comment by bb33bb** [comment] 2024-08-02 13:10
let me check if I am right:
((arg1 - *(uint64_t*)(memstart_addr & 0xffff)) | 0xffffffc000000000)
memstart_addr is a global and in Android , it is any data, 
memstart_addr & 0xffff
will be a 0x????
i hope I am right


then, it will be a pointer with type of uint64_t*
and then ,calculate the data it is pointing
*0x????
this address is very low.
I hope i am not wrong .
plz if any possible , I will respond quickly

**Comment by bb33bb** [comment] 2024-08-02 13:15
[krwx.ko.gz](https://github.com/user-attachments/files/16470888/krwx.ko.gz)

**Comment by bb33bb** [comment] 2024-08-02 13:21
I am going to debug it , and check it again deeply.
After it was finished , if still not ok ,i will make it open again.

**Comment by bb33bb** [comment] 2024-08-02 17:13
ghidra decompiled it as following
printk(0xffffff8009edc13a,(ulong)param_2 - _memstart_addr | 0xffffffc000000000);

ida pro 8.1 decompiled as following
 printk(0LL, addr, (addr - *(_QWORD *)cc_copy_from_user) | 0xFFFFFFC000000000LL);

Ninja decompiled as following
printk(0x629a, arg1, ((arg1 - *(uint64_t*)(memstart_addr & 0xffff)) | 0xffffffc000000000));

**Comment by bb33bb** [comment] 2024-08-02 17:26
in order to check it deeply, the first file is here
https://github.com/Vector35/binaryninja-api/issues/5819#issuecomment-2265384852
I am a little afraid that maybe the only file is not enough to prove this issue.
So i recompile the fuction into kernel and checked again
ghidra give the same decompiled source code as 
```
printk(s_virtual_addr:%llx_ffffff8009edc13a,(ulong)param_2 - memstart_addr | 0xffffffc000000000);
```

but ninja did not give the same ans.
May be ninja load contents from memory and do more calculation
here is the ans from krwx.ko
```
printk(0x629a, arg1, ((arg1 - *(uint64_t*)(memstart_addr & 0xffff)) | 0xffffffc000000000));
```

and 
```
printk("virtual_addr:%llx\n", ((((uint64_t)v) + 1) | 0xffffffc000000000));
```

**Comment by negasora** [comment] 2024-08-02 17:39
Looks like our `movk` lifting is bad - I'll rename the issue to track that

**Comment by negasora** [comment] 2024-08-02 17:56
Sorry, nevermind - our lifting is right.

We just don't simplify `memstart_addr & 0xffff` -> `memstart_addr`.

In this case it's equivalent since `memstart_addr` is `0x71e8`.

**Comment by bb33bb** [comment] 2024-08-03 01:04
> Sorry, nevermind - our lifting is right.
> 
> We just don't simplify `memstart_addr & 0xffff` -> `memstart_addr`.
> 
> In this case it's equivalent since `memstart_addr` is `0x71e8`.

I agree.
If the file is dumped from memory, and we asume the memory is/will not changed , maybe this is the time we need to use constant folding or something like that.
If patched, i will try to re test again.

**Comment by xusheng6** [comment] 2024-08-05 03:44
It seems like things are working as expected, so I am closing this

**Closed by xusheng6** 2024-08-05 03:44 UTC
