### ISSUE TITLE
Paste shortcut does not work in "Encryption key" dialog for transformations

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#2685] opened 2021-10-07 22:11 UTC
**Binary Ninja Version**
2.4.3045-dev

**Describe the bug**
Paste shortcut does not work in "Encryption key" dialog for transformations.

**To Reproduce**
1. Make a selection in Linear View.
2. Right click and select 'Transform > RC4' or 'Transform > XOR'
3. Attempt to use system 'Paste' shortcut to paste content into dialog.
4. Observe that the paste does not occur.

**Expected behavior**
Contents of clipboard should paste into the dialog, in the same manner as when 'Paste' is selected from the right-click menu.

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.3045-dev
 - OS: macOS 11.4, Windows 10

**Additional context**
The 'Paste' action in the right-click menu __does__ work, and on Windows and macOS the shortcut is shown on the menu. The shortcut just doesn't work.

**Comment by plafosse** [comment] 2021-10-11 17:37
Duplicate of #2075

**Closed as completed by plafosse** 2021-10-11 17:37 UTC
Labels: State: Duplicate, Component: UI, Impact: Low, Effort: Low
