### ISSUE TITLE
Add support for Mach-O bundle

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#461] opened 2016-09-09 02:47 UTC
Doesn't seem like there is support for Mach-O Bundles. It just opens up in Hex View with no option for graph. It shows the option for a Mach-O view type stays as Raw when clicked.

An example of one that is a not a FAT binary:

```
/System/Library/Frameworks//AddressBook.framework/Versions/A/Resources/vCardSpotlightBundle.bundle/Contents/MacOS/vCardSpotlightBundle
```

**Comment by plafosse** [comment] 2016-09-09 02:47
Dupe of #135

**Comment by plafosse** [comment] 2016-09-09 02:48
_Not_ a fat binary

**Comment by plafosse** [comment] 2017-07-14 01:55
Fixed in dev

**Closed by plafosse** 2017-07-14 01:55 UTC
