### ISSUE TITLE
Missing the beginning of the function

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4321] opened 2023-05-19 12:25 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4286-dev, 58311b01
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

This disassembly

```
00048b0a                                00 bf                                                                        ..

00048b0c  int32_t data_48b0c = -0x1f40

00048b10                                                  08 b1                                                            ..

00048b12  int32_t j_sub_c7106(void* arg1)

00048b12  7ef0f8ba   b       #sub_c7106

00048b16                                                                    01 48 70 47 00 bf                                    .HpG..

00048b1c  int32_t data_48b1c = -0x1f40
```

ought to look like this instead but BN misses the beginning of the function at `0x48b10`

```
00048b0a                                00 bf                                                                        ..

00048b0c  int32_t data_48b0c = -0x1f40

00048b10  int32_t sub_48b10(int32_t arg1)

00048b10  08b1       cbz     r0, #0x48b16

00048b12  7ef0f8ba   b       #sub_c7106

00048b16  0148       ldr     r0, [pc, #4]  {data_48b1c}  {0xffffe0c0}
00048b18  7047       bx      lr

00048b1a                                                                                00 bf                                        ..

00048b1c  int32_t data_48b1c = -0x1f40
```

Anyone from V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by joelreymont** [comment] 2023-05-19 12:26
Duplicate of #4245.

**Comment by fuzyll** [comment] 2023-05-19 20:17
I agree that this looks like a duplicate of #4245, closing as such.

**Closed by fuzyll** 2023-05-19 20:17 UTC
Labels: State: Duplicate
