### ISSUE TITLE
Feature request: local labels

### ISSUE THREAD

**Issue by Maykeye** [Vector35/binaryninja-api#1955] opened 2020-09-05 17:40 UTC
Binary Ninja Version: 2.1.2263, 4d2bf25a
Platform: Windows 10 Version 1903

Sometimes it is desirable to have simple names for branches(especially in giant functions), e.g. `loop_start`, `loop_end`.
Problem is, the simpler name, the bigger chance I want to reuse it. 

Right now I can't use the same name twice, as it'll complain"There's already symbol by name loop_end. Overwrite?"

NASM for example uses dot prefix for [local labels](http://www.tortall.net/projects/yasm/manual/ru/html/nasm-local-label.html) and internally substitutes dot with last non local label:

```
label1  ; some code
.loop   ; some more code
label2  ; some code
.loop   ; some more code
label3  ; some more code
        ; and some more
        jmp label1.loop
```

Right now if you try to make label `.foobar`, BN will create label named `_.foobar`, so it's not like labels with doth in the beginning are used anyway. 

If instead of underscore BN prepended function name and renamed these local labels when function itself gets renamed and did something smart if function got undefined(e.g. renamed func.foobar to _0x4201c0.foobar) and didn't render function name(so func.foobar would look like .foobar), we'd have nasm-like local labels.

**Comment by plafosse** [comment] 2020-09-09 18:17
Duplicate of #185

**Closed by plafosse** 2020-09-09 18:17 UTC
Labels: duplicate
