### ISSUE TITLE
undefining a function does not update analysis

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2247] opened 2021-01-26 18:59 UTC
The UI does not update when undefining a function, nor does the analysis update (which will for example cause child-functions from the original to be removed as well). Easily fixed by running any command in the python console which will update analysis, or using the UI to trigger analysis, but kinda annoying.

**Comment by jeffli678** [comment] 2021-02-02 02:08
I tried but it seems we do update the analysis after undefining a function. Could you provide an example binary so I can see what went wrong? Also, there is a chance that we update the analysis, but due to some other bug, the analysis update does not have the desired effect.

**Comment by psifertex** [comment] 2021-02-02 22:59
Reproduction steps:
1. New empty file
2. Unlock write-traction (really need to change this for raw views I think)
3. Paste the following "from raw hex": 9090e801000000c39090c3
4. Create a function at the start
5. Notice in your function list you have two functions created.
6. Undefine the first function.
7. Check `bv.functions` you'll see that there shouldn't be /any/ functions anymore since the second auto function should have been removed.
8. Navigate to the second function and "re-analyze" and it will disappear.

**Comment by jeffli678** [comment] 2021-02-03 05:43
Thanks for the reproduction steps. I debugged this issue and it is the result of (or related to) three minor issues:

1. We are missing an analysis update when the user undefines a function. This is fixed by me. 
2. In graph view, the user can force it to show an already undefined function. To achieve it, first navigate to the address in linear view (linear view will display the hex bytes of it), and then select graph view in the lower-right corner. Then graph view will happily show the graph of an already undefined function. I am working on addressing this.
3. In graph view, when the user undefines a function, the user is sent to the entry point. Although I understand the reason to do so, in many cases, we should send the user to the last view, if possible.

**Comment by jeffli678** [comment] 2021-02-17 02:57
was fixed in 2.2.2633

**Closed by jeffli678** 2021-02-17 02:57 UTC
Labels: Effort: Low, Impact: Low, bug, ui
