### ISSUE TITLE
High GPU usage while moving around in Mini Graph

### ISSUE THREAD

**Issue by michalmalik** [Vector35/binaryninja-api#1678] opened 2020-05-16 20:08 UTC
Binary Ninja Version: 2.0.2153-dev Personal, b5661dc1
Platform: Windows 10 Version 1909

I have this file http://devrandom.sk/binja/arm5.zip

When I am in the graph view of function `__uClibc_main` and start moving around in Mini Graph, usage of my GPU goes up to 40% (confirmed with HWInfo, GPU Core Load goes to 40%). If I keep moving around, it stays at ~30%. If I stop, it goes to 0. It doesn't seem to be specific to one architecture or even how big of a function it is.

Thanks!

**Comment by plafosse** [comment] 2020-05-16 20:33
I'm not exactly sure what the issue is. QT does use the GPU to render things. This is as designed. I'm closing this as won't fix, if there's something I'm not understanding please comment below.

**Closed by plafosse** 2020-05-16 20:33 UTC

**Comment by michalmalik** [comment] 2020-05-16 20:46
I seem to be confused as to why should moving in a graph use 40% of the GPU?

**Comment by psifertex** [comment] 2020-05-16 20:51
Given that it's such an infrequent thing to even do, the fact that QT happens to use more GPU while moving a window is very unlikely to be worth the time to investigate versus other more important features and bug-fixes. If it was always consuming more that would be a big problem and we'd want to address it for sure. But as is, this doesn't seem worthwhile to focus on.

**Comment by michalmalik** [comment] 2020-05-16 20:58
Indeed, I agree it's not important. However, I disagree with "infrequent thing to do": I find that the graphs in Binary Ninja are very wide, so I move around in them often. The issue with high GPU usage doesn't seem to be limited to Mini Graph, turns out it happens every time I start moving in a graph. And actually, certain movement in the graph (especially around very long edges) seems to be laggy, possibly due to the usage spiking even to 60%. But yes, I agree you have more important things to focus on, but I wanted to report it as it doesn't seem okay.
