### ISSUE TITLE
copy/paste does not work in types view depending on the direction you select

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#3522] opened 2022-10-12 07:46 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3751-dev
- OS: Windows
- OS Version:: 11
- CPU Architecture: x64
- 
**Bug Description:**
With the types view up and a struct selected, if you highlight from top to bottom (e.g click 'struct' and drag down) everything works as espected. If you click at the bottom and drag upwards, the last token that's selected will be 'struct' which will be individually copied.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Pull open the types view, find any struct
2. Click on the closing brace, hold the mouse and drag up to the initial 'struct'
3. Copy
4. Paste
5. See error

**Expected Behavior:**
I copy a structure, regardless of which direction I drag my mouse

**Screenshots:**
![binja-drag-copy](https://user-images.githubusercontent.com/8716677/195281764-93b7cb67-12c4-47fe-a040-dc420fdbf239.gif)

**Comment by CouleeApps** [comment] 2022-10-21 17:22
Yeah see, what happened here is when you selected the lines, you moused over the "struct" token at the end of your drag. This selected that token inside the selected lines, which confused the copy/paste code into thinking you wanted to copy just the "struct" token. Underlying bug looks more like "you can select tokens WHILE selecting lines."

**Comment by cxnder** [comment] 2022-10-22 18:26
Duplicate of #3440

**Closed by cxnder** 2022-10-22 18:26 UTC
Labels: bug, ui, Impact: Low
