### ISSUE TITLE
Thumb function referencing quirk

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4253] opened 2023-04-20 09:54 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4242-dev, 2e3a4286
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

**Bug Description:**

BN knows that I'm in Thumb mode and hides +1 when showing function references in data structures.

If I click through the pointer and to the function definition, BN will not show any cross-references to the function if I select the function name. There are no code references to the function, only data structure references. These are only shown when I select the first instruction of the function, though.

BN should recognize that I'm in Thumb mode and automatically show data references (adding +1 to the address) even when I click on the function name.

**Comment by plafosse** [comment] 2023-06-19 23:48
Duplicate of #4317

**Closed** 2023-06-19 23:52 UTC
Labels: State: Duplicate, Type: Enhancement, Component: Architecture, Arch: ARM/Thumb, Effort: Medium, Impact: Medium
