### ISSUE TITLE
Binary Ninja doesn't detect string in .data

### ISSUE THREAD

**Issue by pbiernat** [Vector35/binaryninja-api#506] opened 2016-10-03 04:50 UTC
[Sample Binary](https://puu.sh/rvXpB/7442934146) 

Binary Ninja doesn't find strings in scenarios like the attached binary. globalStr is defined as a global char[] and used in the `test` function. It will also not appear in the strings list after manually defining it. 

I'm running 1.0.7 personal in case that matters. Same issue in the dev branch.

**Comment by psifertex** [comment] 2016-10-03 23:55
Duplicate of #303 

Thanks for the clean test case though, that's always helpful.

**Closed by psifertex** 2016-10-03 23:55 UTC
