### ISSUE TITLE
fastcall Calling convention incorrectly recognized

### ISSUE THREAD

**Issue by v-p-b** [Vector35/binaryninja-api#1105] opened 2018-08-07 20:46 UTC
I created a dummy C program and compiled it using MinGW as a 32-bit PE executable (see [fastcall.zip](https://github.com/Vector35/binaryninja-api/files/2267981/fastcall.zip)). 

One of the functions of the program is called using fastcall:

```c
__attribute__((fastcall)) int foo1(int a, int b, int c, int d) 
{
    
    printf("0x%x 0x%x 0x%x 0x%x\n",a,b,c,d);
    int ret= a*c+b*d;
    printf("Ret: %d\n",ret);
    return ret;
}
```

Based on the function signature on the GUI Binary Ninja 1.1.1259 (build f51163e8) correctly detects that the first two parameters are passed in ECX and EDX:

```
int32_t __stdcall sub_401570(int32_t arg1 @ ecx, int32_t arg2 @ edx, ...
```

... but still annotes the function as stdcall:

```
>>> current_function.calling_convention.name
'stdcall'
```

Edit: I get the same result when compiling with VS2017 and even supplying Binary Ninja with the PDB.

**Comment by plafosse** [comment] 2019-02-06 20:15
Determining number of parameters is a difficult problem that we're never going to have a complete solution to. It is an issue that BN isn't trusting the PDB though.

**Comment by v-p-b** [comment] 2019-02-09 07:11
Thank you for picking this up!

I'm curious: if ECX and EDX appear as src operands first inside a function, isn't it a clear case for register-based argument passing, that rules out stdcall (among others) entirely? As I mentioned previously, Binary Ninja seems to detect this (ECX, EDX holding function arguments) nicely, so it's strange that it still sticks with stdcall afterwards.

**Comment by psifertex** [comment] 2019-06-26 18:50
This is actually a duplicate of #1031, close it as such.

**Closed by psifertex** 2019-06-26 18:50 UTC
Labels: bug, duplicate
