### ISSUE TITLE
Function is called without a parameter even though its type requires one

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4971] opened 2024-01-26 10:15 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4797-dev, 6be9a1f4
- OS: macos
- OS Version: 14.3
- CPU Architecture: arm64

**Bug Description:**
In the example below, I have a function called `buggy_func` with the prototype `int64_t buggy_func(void* arg1)`, which is detected by BN as an automatic type, meaning it was not created by me (I only changed its name). However, when I check the cross-references for that function, I can see that almost all calls do not include a parameter.

<img width="288" src="https://github.com/Vector35/binaryninja-api/assets/109607896/aa659bc7-476b-46ae-a003-75f61c6b1f02">

When I attempt to change the function type and accept it without making any actual changes, the issue is resolved. However, I believe this behavior indicates some sort of bug.

**Steps To Reproduce:**
It's difficult to reproduce in another binary, but I can share the binary file on slack.

**Expected Behavior:**
I expect BN to display that parameter without requiring any interaction from me.

**Comment by xusheng6** [comment] 2024-01-30 13:34
Please share the binary with me

**Comment by plafosse** [comment] 2024-02-06 14:19
I believe this is a duplicate of this issue #3927

**Closed by plafosse** 2024-02-06 14:19 UTC
Labels: Type: Bug, State: Duplicate, Component: Core, Effort: Medium, Impact: Medium

**Comment by plafosse** [comment] 2024-02-06 14:22
This is a really frustrating edge case in our analysis that we need to address. We will be looking into this soon.
