### ISSUE TITLE
Identify Indirect TailCalls

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4247] opened 2023-04-19 13:45 UTC
![Uploading Screenshot 2023-04-19 at 16.46.27.png…]()
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4242-dev, 2e3a4286
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

**Bug Description:**

You can see the tag with the subject at the question mark (0xcb00e) location below.

```
0000cb008  void sub_cb008(void* arg1)

0000cb008  036a       ldr     r3, [r0, #0x20]
0000cb00a  0bb1       cbz     r3, #0xcb010

0000cb00c  406a       ldr     r0, [r0, #0x24]
❓0000cb00e  1847       bx      r3

0000cb010  7047       bx      lr
```

The HLIL code that's produced is incorrect 

```
0000cb008  void sub_cb008(void* arg1)

0000cb008      int32_t r3 = *(arg1 + 0x20)
0000cb00a      if (r3 == 0)
0000cb010          return 
0000cb00c      *(arg1 + 0x24)
❓0000cb00e      jump(r3)
```

I know because IDA generates this 

```
int __fastcall sub_CB008(int result)
{
  int (__fastcall *v1)(_DWORD); // r3

  v1 = *(int (__fastcall **)(_DWORD))(result + 32);
  if ( v1 )
    return v1(*(_DWORD *)(result + 36));
  return result;
}
```

**Comment by joelreymont** [comment] 2023-04-20 08:38
BN has created these for some reason. 0x13F470 is where it's trying to jump.

```
00013f470  void* __builtin_memcpy(void* dest, void* src, uint32_t n) = 
00013f470                                                  00 00 00 00                                                      ....
00013f474  void* __builtin_memset(void* s, int32_t c, uint32_t n) = 
00013f474                                                              00 00 00 00                                              ....
00013f478  char* __builtin_strcpy(char* dest, char const* src) = 
00013f478                                                                          00 00 00 00                                      ....
00013f47c  char* __builtin_strncpy(char* dest, char const* src, uint32_t n) = 
```

**Comment by joelreymont** [comment] 2023-05-19 13:14
I deleted the segment at the end and BN created the synthetic intrinsics section. Unfortunately, the references in the database weren't updated.

For example, the synthetics are at `0xf0...` but the error still refers to addresses without the prefix.

Re-analyzing doesn't help.


```
f013f470  extern void* __builtin_memcpy(void* dest, void* src, uint32_t n)
f013f474  extern void* __builtin_memset(void* s, int32_t c, uint32_t n)
f013f478  extern char* __builtin_strcpy(char* dest, char const* src)
f013f47c  extern char* __builtin_strncpy(char* dest, char const* src, uint32_t n)
f013f480  extern wchar32* __builtin_wcscpy(wchar32* dest, wchar32 const* src)
```

![Screenshot 2023-05-19 at 4 12 17 PM](https://github.com/Vector35/binaryninja-api/assets/18791/a82c776f-08c5-48dc-98c9-7e81838cbcaa)

**Comment by tripleoxygen** [comment] 2023-06-06 12:16
Pitching in another sample if needed, since this also bites me on some ARMv6 binaries with branches from indirections/vtables. Same warning from Binary Ninja (3.4.4271 (stable/personal) @ x86_64 Linux).

Sample: [zip](https://www.tripleoxygen.net/files/devices/zeebo/content/mods/tectoy_no_error_1_727.zip) (load as armv7, base address 0x1000_0000 and go to sub @0x10068ba4).

At address 0x10068c34 it breaks the flow and stops disassembling. Data following it becomes raw but should be instructions. Then it tries to create a new function after it, but it's just the continuation of the same fn. Other tools does it correctly.

BN
```
10068c20  09908fe0   add     r9, pc, r9
10068c24  040019e5   ldr     r0, [r9,  #-0x4]  {data_100001fc}
10068c28  08e08fe2   adr     lr, data_10068c38
10068c2c  301090e5   ldr     r1, [r0,  #0x30]
10068c30  0b00a0e1   mov     r0, r11
❓10068c34  11ff2fe1   bx      r1

10068c38  data_10068c38:
10068c38                                                                          00 00 55 e3 00 a0 a0 e1                          ..U.....
10068c40  09 00 00 1a 14 00 9d e5 18 00 90 e5 00 00 50 e3 05 00 00 0a 04 10 19 e5 04 e0 8f e2 30 10 91 e5  ..............P.............0...
10068c60  11 ff 2f e1                                                                                      ../.

10068c64  int32_t sub_10068c64(int32_t arg1, void* arg2 @ r4, int32_t arg3 @ r9, void* arg4)

10068c64  000050e3   cmp     r0, #0
10068c68  0300001a   bne     0x10068c7c
```

Ghidra (flow type can be overridden)
```
        10068c20 09908fe0        add                 r9,pc,r9
        10068c24 040019e5        ldr                 param_1,[r9,#-0x4]=>DAT_100001fc
        10068c28 08e08fe2        adr                 lr,0x10068c38
        10068c2c 301090e5        ldr                 r1,[param_1,#0x30]
        10068c30 0b00a0e1        cpy                 param_1,r11
        10068c34 11ff2fe1        bx                  r1
                               -- Flow Override: CALL (COMPUTED_CALL)
        10068c38 000055e3        cmp                 r5,#0x0
        10068c3c 00a0a0e1        cpy                 r10,param_1
        10068c40 0900001a        bne                 LAB_10068c6c
        10068c44 14009de5        ldr                 param_1,[sp,#local_2c]
        10068c48 180090e5        ldr                 param_1,[param_1,#0x18]
        10068c4c 000050e3        cmp                 param_1,#0x0
        10068c50 0500000a        beq                 LAB_10068c6c
        10068c54 041019e5        ldr                 r1,[r9,#-0x4]=>DAT_100001fc
        10068c58 04e08fe2        adr                 lr,0x10068c64
        10068c5c 301091e5        ldr                 r1,[r1,#0x30]
        10068c60 11ff2fe1        bx                  r1
                               -- Flow Override: CALL (COMPUTED_CALL)
        10068c64 000050e3        cmp                 param_1,#0x0
        10068c68 0300001a        bne                 LAB_10068c7c
...
```

**Comment by plafosse** [comment] 2023-06-08 17:56
The root cause of this is that we're not recognizing indirect tailcalls i.e. a TailCall whose address isn't known when its called.

**Comment by plafosse** [comment] 2023-09-22 20:57
Closing as duplicate of #1060

**Closed by plafosse** 2023-09-22 20:57 UTC
Labels: Type: Bug, State: Duplicate, Component: Core, Impact: High, Effort: Low
