### ISSUE TITLE
Consistent crashes/hangs when navigating binaries

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#3171] opened 2022-06-06 20:36 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3482-dev
- OS: Windows
- OS Version: 10.0.25131.1000
- CPU Architecture: x64

**Bug Description:**
Binary Ninja tends to crash or hang when navigating around a binary. It takes 30-60 minutes for the problem to occur in a normal reversing session, but it can be triggered reliably within 10-20s by rapidly navigating over a wide area with the feature map.

The problem tends to manifest as a hang on smaller binaries and a crash on larger binaries, so there might be different issues at play here.

**Steps To Reproduce:**
Grab any binary from the `Binaries` folder here: https://drive.google.com/drive/folders/1as90hOalwG8djJNNzbkFpKNT4t2eqFzk

Load up the binary and let analysis complete, then navigate randomly. A good way to trigger the crashes/hangs in a timely fashion is to rapidly flick the mouse around in the feature map for 10-20s, going back and forth between code and data sections.

**Expected Behavior:**
No crashes.

**Additional Information:**
If there's a way to get Binary Ninja to print a stack trace when crashing, I can provide them.

**Comment by plafosse** [comment] 2022-06-09 19:20
A few of us have tried unsuccessfully to reproduce this issue. Do you happen to have any plugins installed?

**Comment by alexrp** [comment] 2022-06-09 19:43
I do, but they don't appear to have anything to do with the issue. I tried removing the plugins directory from my BN user directory and then rapidly navigated around in `Tl.exe` and `TERA.exe` from the above Google Drive folder, and I am still able to reproduce both crashes and hangs. In fact, they seem to happen much more quickly when flicking around in the feature map now - within 2-3s.

I have noticed that saving the BNDB frequently while working seems to drastically reduce the chance of such a crash happening during a session.

Is there an easy way for me to get a stack trace out of the crash at least?

In case it matters, here are my user settings:

```json
{
	"analysis.experimental.parseDebugInfo" : true,
	"analysis.hlil.maxConditionComplexity" : 2048,
	"analysis.hlil.maxConditionReduceIterations" : 2048,
	"analysis.limits.maxFunctionUpdateCount" : 0,
	"analysis.types.TemplateSimplifier" : true,
	"analysis.types.parserName" : "ClangTypeParser",
	"analysis.unicode.utf32" : false,
	"corePlugins.debugger" : true,
	"corePlugins.idbImport" : false,
	"python.binaryOverride" : "C:\\Program Files\\Python310\\python.exe",
	"python.interpreter" : "C:/Program Files/Python310/python310.dll",
	"rendering.hlil.scopingStyle" : "bracesNewLine",
	"rendering.strings.maxAnnotationLength" : 120,
	"triage.analysisMode" : "full",
	"triage.linearSweep" : "full",
	"ui.developerMode" : true,
	"ui.files.openWithOptions" : 
	[
		"COFF",
		"ELF",
		"Mach-O",
		"Mapped",
		"PE",
		"Universal"
	],
	"ui.font.app.name" : "Cascadia Code PL",
	"ui.font.app.size" : 14,
	"ui.font.emoji.name" : "Cascadia Code PL",
	"ui.font.emoji.style" : "Regular",
	"ui.font.view.name" : "Cascadia Code PL",
	"ui.font.view.size" : 14,
	"ui.font.view.style" : "Regular",
	"ui.log.maxSize" : 100000,
	"ui.maxXrefItems" : 1000,
	"ui.panes.statusBarOptions" : true,
	"ui.pluginManager.warnCommunityInstall" : false,
	"ui.recentCommandLimit" : 10,
	"ui.scripting.historySize" : 100000,
	"ui.settings.displayIdentifiers" : true,
	"ui.sidebar.mode" : "staticSize",
	"ui.sidebar.openOnStartup" : true,
	"ui.symbolList.showExportedDataVars" : true,
	"ui.symbolList.showLocalDataVars" : true,
	"ui.view.common.disassemblyWidth" : 120,
	"ui.view.graph.carousel" : 
	[
		"Disassembly",
		"HighLevelIL",
		"PseudoC"
	],
	"ui.view.graph.il" : "PseudoC",
	"ui.view.linear.carousel" : 
	[
		"Disassembly",
		"HighLevelIL",
		"PseudoC"
	],
	"ui.view.linear.il" : "PseudoC",
	"workflows.enable" : true
}
```

**Comment by alexrp** [comment] 2022-06-17 16:32
I'm getting 5+ crashes per session at this point. Every crash usually means losing some 5-10 mins of work that I then have to redo, on top of waiting ~3 mins for the BNDB to load again (~52 MB binary). I try to mitigate the problem by saving frequently, but this can only get me so far since saving such a huge BNDB takes 1-2 min; I can't do that all the time or I would barely make progress. This issue ends up being a big productivity killer. 😞

I completely understand there isn't much you can do on your end without the ability to reproduce the issue. So, considering how easy it is for me to reproduce this both in an artificial way and during a normal reversing session, is there a way we can work together to debug this?

**Comment by alexrp** [comment] 2022-06-18 03:14
@negasora

> * What IL level are you navigating in?

95%+ of the time I'm in Pseudo C.

I occasionally switch to MLIL to fix the type of a variable containing a vtable pointer, or Disassembly when I need to deal with some calling convention issues or create memory scanning patterns.

> * Could it be due to OOM?

I've never seen BN go over 16 GB of memory and my system has 64 GB. I don't have anything else that's memory-hungry going on.

**Comment by alexrp** [comment] 2022-06-23 22:54
Just to rule this angle out: After pruning the BNDB (see #3217) the crashes are still easy to reproduce.

**Comment by negasora** [comment] 2022-06-23 23:25
I'm still unable to repro, can you run under windbg and share the trace?

**Comment by alexrp** [comment] 2022-06-23 23:44
@negasora

Stack:

```
[0x0]   binaryninjacore!BNWriteWebsocketClientData + 0x68b   
[0x1]   binaryninjacore!BNZlibDecompress + 0x10d8   
[0x2]   binaryninjacore!BNNewLinearViewObjectReference + 0xbebd   
[0x3]   binaryninjacore!BNSeekLinearViewCursorToPathAndAddress + 0xfb4   
[0x4]   binaryninjacore!BNSetLicense + 0x3291e   
[0x5]   binaryninjacore!BNSetLicense + 0x320ba   
[0x6]   binaryninjacore!BNGetLinearViewCursorLines + 0x32   
[0x7]   binaryninjaui!CrossReferenceWidget::wheelEvent + 0x13f933   
[0x8]   binaryninjaui!LinearView::cachePreviousLines + 0x83   
[0x9]   binaryninjaui!LinearView::updateCache + 0xa9   
[0xa]   binaryninjaui!LinearView::navigateToLine + 0x5e9   
[0xb]   binaryninjaui!LinearView::navigate + 0x72   
[0xc]   binaryninjaui!FeatureMap::scrollTo + 0x1bd   
[0xd]   binaryninjaui!FeatureMap::mouseMoveEvent + 0x44   
[0xe]   Qt6Widgets!QWidget::event + 0x126   
[0xf]   Qt6Widgets!QApplicationPrivate::notify_helper + 0x10d   
[0x10]   Qt6Widgets!QApplication::notify + 0x735   
[0x11]   Qt6Core!QCoreApplication::notifyInternal2 + 0xc4   
[0x12]   Qt6Widgets!QApplicationPrivate::sendMouseEvent + 0x3ef   
[0x13]   Qt6Widgets!QWidgetPrivate::shouldDiscardSyncRequest + 0x3e36   
[0x14]   Qt6Widgets!QWidgetPrivate::shouldDiscardSyncRequest + 0x16c5   
[0x15]   Qt6Widgets!QApplicationPrivate::notify_helper + 0x10d   
[0x16]   Qt6Widgets!QApplication::notify + 0x187f   
[0x17]   Qt6Core!QCoreApplication::notifyInternal2 + 0xc4   
[0x18]   Qt6Gui!QGuiApplicationPrivate::processMouseEvent + 0x78f   
[0x19]   Qt6Gui!QWindowSystemInterface::sendWindowSystemEvents + 0xe8   
[0x1a]   Qt6Core!QEventDispatcherWin32::processEvents + 0x90   
[0x1b]   Qt6Gui!QWindowsGuiEventDispatcher::processEvents + 0x19   
[0x1c]   Qt6Core!QEventLoop::exec + 0x19e   
[0x1d]   Qt6Core!QCoreApplication::exec + 0x15c   
[0x1e]   binaryninja + 0x46883   
[0x1f]   binaryninja + 0x246410   
[0x20]   KERNEL32!BaseThreadInitThunk + 0x1d   
[0x21]   ntdll!RtlUserThreadStart + 0x28   
```

(Other threads just seem to be waiting, doing nothing interesting.)

Disassembly:

```asm
00007ff9`a9d8be9b 75f3                   jne     00007FF9A9D8BE90
00007ff9`a9d8be9d 4533c0                 xor     r8d, r8d
00007ff9`a9d8bea0 4c894500               mov     qword ptr [rbp], r8
00007ff9`a9d8bea4 48c745080f000000       mov     qword ptr [rbp+8], 0Fh
00007ff9`a9d8beac 448845f0               mov     byte ptr [rbp-10h], r8b
00007ff9`a9d8beb0 4532f6                 xor     r14b, r14b
00007ff9`a9d8beb3 4c89442450             mov     qword ptr [rsp+50h], r8
00007ff9`a9d8beb8 4885c9                 test    rcx, rcx
00007ff9`a9d8bebb 0f8452060000           je      00007FF9A9D8C513
00007ff9`a9d8bec1 0f1f4000               nop     dword ptr [rax]
00007ff9`a9d8bec5 6666660f1f840000000000 nop     word ptr [rax+rax]
00007ff9`a9d8bed0 4c8945e0               mov     qword ptr [rbp-20h], r8
00007ff9`a9d8bed4 48c745e80f000000       mov     qword ptr [rbp-18h], 0Fh
00007ff9`a9d8bedc c645d000               mov     byte ptr [rbp-30h], 0
00007ff9`a9d8bee0 488b4c2450             mov     rcx, qword ptr [rsp+50h]
00007ff9`a9d8bee5 48038dc0000000         add     rcx, qword ptr [rbp+0C0h]
00007ff9`a9d8beec 0fb601                 movzx   eax, byte ptr [rcx]
00007ff9`a9d8beef 8844243c               mov     byte ptr [rsp+3Ch], al
00007ff9`a9d8bef3 0fb64101               movzx   eax, byte ptr [rcx+1]
00007ff9`a9d8bef7 8844243d               mov     byte ptr [rsp+3Dh], al
00007ff9`a9d8befb 0fb64102               movzx   eax, byte ptr [rcx+2] <--------
00007ff9`a9d8beff 8844243e               mov     byte ptr [rsp+3Eh], al
00007ff9`a9d8bf03 0fb64103               movzx   eax, byte ptr [rcx+3]
00007ff9`a9d8bf07 8844243f               mov     byte ptr [rsp+3Fh], al
00007ff9`a9d8bf0b 0fb64628               movzx   eax, byte ptr [rsi+28h]
00007ff9`a9d8bf0f 884588                 mov     byte ptr [rbp-78h], al
00007ff9`a9d8bf12 488b5e30               mov     rbx, qword ptr [rsi+30h]
00007ff9`a9d8bf16 48895d90               mov     qword ptr [rbp-70h], rbx
00007ff9`a9d8bf1a 488dbb48010000         lea     rdi, [rbx+148h]
00007ff9`a9d8bf21 4885db                 test    rbx, rbx
00007ff9`a9d8bf24 740d                   je      00007FF9A9D8BF33
00007ff9`a9d8bf26 488b8348010000         mov     rax, qword ptr [rbx+148h]
00007ff9`a9d8bf2d 488bcf                 mov     rcx, rdi
00007ff9`a9d8bf30 ff5008                 call    qword ptr [rax+8]
00007ff9`a9d8bf33 4183cd10               or      r13d, 10h
00007ff9`a9d8bf37 44896c2444             mov     dword ptr [rsp+44h], r13d
00007ff9`a9d8bf3c 488b03                 mov     rax, qword ptr [rbx]
00007ff9`a9d8bf3f 488bcb                 mov     rcx, rbx
00007ff9`a9d8bf42 ff10                   call    qword ptr [rax]
```

Registers:

```
rax=0000000000000000 rbx=0000024d0d372880 rcx=0000024b6f842ffe
rdx=0000005227af9900 rsi=00000250bae82700 rdi=0000024d0d3729c8
rip=00007ff9a9d8befb rsp=0000005227af9700 rbp=0000005227af9800
 r8=0000000000000000  r9=00007ffa67b91404 r10=00007ffa67b90000
r11=0000005227af96c0 r12=0000005227af99e0 r13=000000000000005f
r14=0000000000000000 r15=000000000000002d
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
```

Memory:

```
0000024b`6f842efe  00 00 c0 07 2b 16 4b 02-00 00 21 c3 82 42 01 00  ....+.K...!..B..
0000024b`6f842f0e  00 00 00 05 2b 16 4b 02-00 00 00 06 2b 16 4b 02  ....+.K.....+.K.
0000024b`6f842f1e  00 00 40 07 4f 16 4b 02-00 00 f0 49 d3 b1 50 02  ..@.O.K....I..P.
0000024b`6f842f2e  00 00 40 03 2b 16 4b 02-00 00 63 3d 3f 5d 00 00  ..@.+.K...c=?]..
0000024b`6f842f3e  00 00 21 ff 21 80 80 80-80 80 80 80 80 80 80 80  ..!.!...........
0000024b`6f842f4e  80 80 80 2e 56 6f 6c 75-6d 65 70 c2 82 42 01 00  ....Volumep..B..
0000024b`6f842f5e  00 00 70 c2 82 42 01 00-00 00 71 c2 82 42 01 00  ..p..B....q..B..
0000024b`6f842f6e  00 00 73 74 72 5f 4f 6e-47 61 6d 65 5f 53 74 79  ..str_OnGame_Sty
0000024b`6f842f7e  6c 65 53 68 6f 70 5f 53-65 74 50 61 70 65 72 44  leShop_SetPaperD
0000024b`6f842f8e  6f 6c 6c 00 9c 6f 4b 02-00 00 d6 e0 c8 40 01 00  oll..oK......@..
0000024b`6f842f9e  00 00 00 78 76 ad f9 7f-00 00 03 00 00 00 4b 02  ...xv.........K.
0000024b`6f842fae  00 00 73 75 62 5f 31 34-31 30 30 38 32 34 30 00  ..sub_141008240.
0000024b`6f842fbe  00 00 0d 00 00 00 00 00-00 00 0f 00 00 00 00 00  ................
0000024b`6f842fce  00 00 54 00 6f 00 47 00-61 00 6d 00 65 00 5f 00  ..T.o.G.a.m.e._.
0000024b`6f842fde  53 00 74 00 79 00 6c 00-65 00 53 00 68 00 6f 00  S.t.y.l.e.S.h.o.
0000024b`6f842fee  70 00 5f 00 42 00 65 00-6e 00 65 00 66 00 69 00  p._.B.e.n.e.f.i.
0000024b`6f842ffe  74 00 ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  t.??????????????
0000024b`6f84300e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f84301e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f84302e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f84303e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f84304e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f84305e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f84306e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f84307e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f84308e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f84309e  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f8430ae  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f8430be  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f8430ce  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f8430de  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f8430ee  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
0000024b`6f8430fe  ??                                               ?
```

(Looks like strings from the binary I'm analyzing.)

Let me know if I can provide more information.

**Comment by alexrp** [comment] 2022-06-23 23:45
Oh, and this is with build 3.1.3530-dev.

**Comment by alexrp** [comment] 2022-06-23 23:50
Did a few more runs under WinDbg and the crash always has the same stack trace.

Will see if I can still reproduce the hang on small binaries.

**Comment by alexrp** [comment] 2022-06-24 00:02
Caught what appears to be a hang:

<details>

```
[0x0]   binaryninjacore + 0x40b42e   
[0x1]   binaryninjacore!BNShowReportCollection + 0xca3d   
[0x2]   binaryninjacore!BNShowReportCollection + 0x195c3   
[0x3]   binaryninjacore!BNShowReportCollection + 0x15249   
[0x4]   binaryninjacore!BNShowReportCollection + 0x19478   
[0x5]   binaryninjacore!BNShowReportCollection + 0x146ca   
[0x6]   binaryninjacore!BNShowReportCollection + 0x18f57   
[0x7]   binaryninjacore!BNShowReportCollection + 0x11741   
[0x8]   binaryninjacore!BNShowReportCollection + 0x18fd3   
[0x9]   binaryninjacore!BNShowReportCollection + 0x146ca   
[0xa]   binaryninjacore!BNShowReportCollection + 0x18f57   
[0xb]   binaryninjacore!BNShowReportCollection + 0x115f4   
[0xc]   binaryninjacore!BNShowReportCollection + 0x18fd3   
[0xd]   binaryninjacore!BNShowReportCollection + 0x146ca   
[0xe]   binaryninjacore!BNShowReportCollection + 0x18f57   
[0xf]   binaryninjacore!BNShowReportCollection + 0x11741   
[0x10]   binaryninjacore!BNShowReportCollection + 0x18fd3   
[0x11]   binaryninjacore!BNShowReportCollection + 0x146ca   
[0x12]   binaryninjacore!BNShowReportCollection + 0x18f57   
[0x13]   binaryninjacore!BNShowReportCollection + 0x1aca5   
[0x14]   binaryninjacore!BNCreateLinearViewMediumLevelILSSAForm + 0x17c4a   
[0x15]   binaryninjacore!BNSetLicense + 0x3211e   
[0x16]   binaryninjacore!BNGetLinearViewCursorLines + 0x32   
[0x17]   binaryninjaui!CrossReferenceWidget::wheelEvent + 0x13f933   
[0x18]   binaryninjaui!LinearView::cacheNextLines + 0x46   
[0x19]   binaryninjaui!LinearView::updateCache + 0x58   
[0x1a]   binaryninjaui!LinearView::refreshLines + 0xfa   
[0x1b]   binaryninjaui!LinearView::navigateToLine + 0x30a   
[0x1c]   binaryninjaui!LinearView::navigate + 0x72   
[0x1d]   binaryninjaui!FeatureMap::scrollTo + 0x1bd   
[0x1e]   binaryninjaui!FeatureMap::mouseMoveEvent + 0x44   
[0x1f]   Qt6Widgets!QWidget::event + 0x126   
[0x20]   Qt6Widgets!QApplicationPrivate::notify_helper + 0x10d   
[0x21]   Qt6Widgets!QApplication::notify + 0x735   
[0x22]   Qt6Core!QCoreApplication::notifyInternal2 + 0xc4   
[0x23]   Qt6Widgets!QApplicationPrivate::sendMouseEvent + 0x3ef   
[0x24]   Qt6Widgets!QWidgetPrivate::shouldDiscardSyncRequest + 0x3e36   
[0x25]   Qt6Widgets!QWidgetPrivate::shouldDiscardSyncRequest + 0x16c5   
[0x26]   Qt6Widgets!QApplicationPrivate::notify_helper + 0x10d   
[0x27]   Qt6Widgets!QApplication::notify + 0x187f   
[0x28]   Qt6Core!QCoreApplication::notifyInternal2 + 0xc4   
[0x29]   Qt6Gui!QGuiApplicationPrivate::processMouseEvent + 0x78f   
[0x2a]   Qt6Gui!QWindowSystemInterface::sendWindowSystemEvents + 0xe8   
[0x2b]   Qt6Core!QEventDispatcherWin32::processEvents + 0x90   
[0x2c]   Qt6Gui!QWindowsGuiEventDispatcher::processEvents + 0x19   
[0x2d]   Qt6Core!QEventLoop::exec + 0x19e   
[0x2e]   Qt6Core!QCoreApplication::exec + 0x15c   
[0x2f]   binaryninja + 0x46883   
[0x30]   binaryninja + 0x246410   
[0x31]   KERNEL32!BaseThreadInitThunk + 0x1d   
[0x32]   ntdll!RtlUserThreadStart + 0x28   
```

</details>

**Comment by plafosse** [comment] 2022-06-24 01:12
Awesome thanks for the stack trace I was able to track down the cause of it. Looks like you must have some unicode code blocks enabled. Those aren't typically turned on. If you turn them off the crashes will stop occurring.

**Comment by psifertex** [comment] 2022-06-24 01:38
Should be fixed in builds >= 3532. Going to leave open though for you to confirm since we don't have a good test-case handy.

**Comment by alexrp** [comment] 2022-06-24 08:59
> Looks like you must have some unicode code blocks enabled.

I don't *think* so; that setting is set to the default `[]`. The only change I've made regarding Unicode is turning off UTF-32 strings.

> Going to leave open though for you to confirm since we don't have a good test-case handy.

I can't reproduce it anymore by navigating with the feature map. 🎉 Just to be sure, I'll reserve final judgement until I do one of my longer sessions under WinDbg though.

---

Any ideas regarding the hang in https://github.com/Vector35/binaryninja-api/issues/3171#issuecomment-1165028833 (different binary)?

**Comment by psifertex** [comment] 2022-06-24 13:11
The hang looks like it's in BinaryNinjaCore::FlowGraph::PerformLayoutWorker so would be related to graph layout and is also, unfortunately, one of the more complicated functions in the core. 

Any chance you enabled graph layout for a very large function that was disabled by default due to the heuristic limits? Also, let's go ahead and file that separately so we can track it more easily if it's not due to enabling something past the limits.

**Closed** 2022-06-24 13:37 UTC
Labels: crash

**Comment by plafosse** [comment] 2022-06-24 13:43
Also I'm wondering if you have some special Windows heap thing turned on? We should have been able to reproduce that bug as it was reading off the end of a memory page. For some reason you were consistently getting crashes while we weren't.
