### ISSUE TITLE
The button to unlock the file for edit is hard to click on macOS

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#5330] opened 2024-04-26 05:21 UTC
When we wish to write to the file content, we need to first unlock the write lock by clikcing a small button at the lower-right corner. I find this hard to reach, especially since macOS introduced a new feature to create a new Note when you click the lower-right corner of the entire window. 

I recorded a video to show how often time I trigger the "New Note" functionality of the system, rather than being able to write to the file

https://github.com/Vector35/binaryninja-api/assets/94503187/2bc8fbe0-c9d8-4c11-bc77-60576a25cdc7

**Comment by fuzyll** [comment] 2024-04-29 16:07
Closing as duplicate of #5277.

**Closed by fuzyll** 2024-04-29 16:07 UTC
Labels: State: Duplicate
