### ISSUE TITLE
shell32.dll exports are not being labelled correctly

### ISSUE THREAD

**Issue by adrianherrera** [Vector35/binaryninja-api#716] opened 2017-06-20 09:42 UTC
Hi all,

I'm not sure if this is a problem with DLLs in general, or just this particular DLL (I haven't had the time to check). This problem occurs in both the latest release and dev channels (at the time of writing).

I wanted to look at the exported `CommandLineToArgvW` function. In graph view I see the following:

![binary-ninja](https://user-images.githubusercontent.com/8626578/27326708-87a74d7a-55ac-11e7-8168-9d92767112c3.png)

Which is clearly not correct. When I look at the DLL in a PE viewer, I can see that `CommandLineToArgvW` has an RVA of 0x00019EE8 and the DLL has a base address of 0x73800000. Therefore if I go to 0x73819EE8 I get a function labelled `SHIsFileAvailableOffline`. However this function contains the code that I expect for `CommandLineToArgvW`, see below:

![screen shot 2017-06-20 at 11 23 47 am](https://user-images.githubusercontent.com/8626578/27326879-0dd452c6-55ad-11e7-8980-a2bd109fdbb4.png)

![ida](https://user-images.githubusercontent.com/8626578/27326957-59585a76-55ad-11e7-8d6e-a5cbc8f511c8.png)

Any ideas on what's going on? Or am I just going crazy

Regards,
Adrian

**Comment by adrianherrera** [comment] 2017-06-20 10:23
Just a quick addendum.

I forgot to mention, the above issue is with a SysWOW64 DLL from Windows 7 (`C:\Windows\SysWOW64\shell32.dll`).

When I open the 64-bit version (`C:\Windows\System32\shell32.dll`) the `CommandLineToArgvW` function doesn't appear in the function list at all. When I go to its expected address the function is labelled `SHIsFileAvailableOffline` again.

I hope that gives some more useful information!

**Comment by psifertex** [comment] 2017-06-20 14:40
Thanks! we have one other known bug related to symbols by ordinal that might be the same, will double check and see if that's the case. I can't find the other bug in a quick search but will update once I find it.

**Comment by adrianherrera** [comment] 2017-06-20 21:17
Ok cool! I did a search for "dll" in the open issues and didn't find anything that seemed related. But feel free to close if this is a duplicate.

**Comment by plafosse** [comment] 2017-06-20 23:34
Unable to reproduce in Windows 10 SysWOW64/shell32.dll. Any chance of sharing the test case?

**Comment by 0xbc** [comment] 2017-06-21 06:59
@plafosse I could be mistaken, but it looks screwy to me on Windows 10 as well.

For SysWOW64/shell32.dll, I see Binary Ninja identifying `CommandLineToArgW` as the function at `0x699e7130` - is that what you're seeing? If you go to the same location in IDA, the function is actually (assuming IDA is correct) `PifMgr_OpenProperties`. If you browse to `PifMgr_OpenProperties` in Binja, you appear to end up in the middle of `PifMgr_GetProperties`.

Running 1.0.766-dev.

**Comment by D0ntPanic** [comment] 2017-06-22 03:21
Fixed in dev build 771

**Closed by D0ntPanic** 2017-06-22 03:21 UTC
Labels: question
