### ISSUE TITLE
Symbol renaming issue

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4320] opened 2023-05-19 12:14 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4286-dev, 58311b01
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

I want to rename `sub_363a8` in this disassembly to `exception_hook`.

```
000361d4  int32_t iwdg_hook_init()

000361d4  0248       ldr     r0, [pc, #8]  {data_361e0}  {sub_363a8}
000361d6  08b5       push    {r3, lr} {var_4} {__saved_r3}
000361d8  0ef024fc   bl      #set_exception_hook
000361dc  0020       movs    r0, #0
000361de  08bd       pop     {r3, pc} {__saved_r3} {var_4}
000361e0  void* data_361e0 = exception_hook
```

I pointed at `{sub_363a8}` below and renamed the symbol 

```
000361d4  0248       ldr     r0, [pc, #8]  {data_361e0}  {sub_363a8}
```

getting it to look like this 

```
000361d4  0248       ldr     r0, [pc, #8]  {data_361e0}  {exception_hook}
```

while the following still showed the old symbol name, i.e. 

```
000361e0  void* data_361e0 = sub_363a8
```

I cannot reproduce this anymore but will be on the lookout for it.

Anyone from V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by fuzyll** [comment] 2023-05-19 19:56
I was able to reproduce this on the database we were given:

1. Go to 0x361d4 in disassembly mode
2. `n` -> rename function on `sub_363a8`
3. Observe that 0x361e0 is not renamed
4. Switch to HLIL and observe that the old name is used

In both cases, hitting `o` on them immediately fixed the problem, and I now have:

```
0000361d4  int32_t iwdg_hook_init()
0000361d8      sub_44a24(exception_hook)
0000361de      return 0
0000361e0  void* data_361e0 = exception_hook
```

I agree this is surprising and a user should probably just expect this to work without needing to hit `o`. But, someone with more understanding of what's happening under-the-hood will need to weigh in on whether this is intended (and why) or a bug.

**Comment by fuzyll** [comment] 2023-06-08 17:55
To clarify the repro steps above, since they've tripped up multiple people:

The issue _isn't_ renaming the function at 0x363a8. The issue is that the pointer _to_ that function, which is at 0x361e0 (see step 3), is not recognized (possibly because of the thumb bit being set). So, when we rename that function and switch to HLIL, the raw value is shown because it's not being properly marked as an offset. Hitting `o` fixes this (as shown in the bottom of the comment).

The issue, as I see it, is that the user should not need to hit `o` and we should be able to do this automatically. But, if we can't for some technical reason I am unaware of, we should communicate that more clearly.

**Comment by plafosse** [comment] 2023-06-08 18:25
Ultimately this is just a duplicate of this
https://github.com/Vector35/binaryninja-api/issues/4399
and #1189

**Closed by plafosse** 2023-06-08 18:25 UTC
Labels: Component: Core
