### ISSUE TITLE
Binary ninja doesn't know the ANDN opcode on x86_64

### ISSUE THREAD

**Issue by human5** [Vector35/binaryninja-api#676] opened 2017-04-30 04:05 UTC
See address 0x4003e0 in attached file.

[a.out.zip](https://github.com/Vector35/binaryninja-api/files/966546/a.out.zip)

**Comment by psifertex** [comment] 2017-05-05 03:18
Dupe of #300

**Closed by psifertex** 2017-05-05 03:18 UTC
