### ISSUE TITLE
python console - binja closes when typing help() and then modules

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#388] opened 2016-08-19 18:58 UTC
OS: ubuntu 16.04 LTS

binja exits/crashes if you type in the python console:
help()
modules

**Comment by psifertex** [comment] 2016-08-19 19:01
Can you please clarify? I do something similar in this screenshot and it works fine: http://docs.binary.ninja/getting-started/index.html#script-python-console

**Comment by Manouchehri** [comment] 2016-08-19 19:17
What OS? `help()` works fine here on Windows 10.

**Comment by lucasduffey** [comment] 2016-08-19 20:22
it says "No handlers could be found for logger OpenGL.tk" right before the crash.

It's very brief so that string may not be exactly the same

**Comment by lucasduffey** [comment] 2016-08-19 20:23
it's ubuntu 16.04 LTS

**Comment by psifertex** [comment] 2016-08-19 20:31
Closing as it was not reproducible and is likely another root cause, feel free to re-open if you can figure out a reliable test case.

**Closed by psifertex** 2016-08-19 20:31 UTC
Labels: bug

**Comment by lucasduffey** [comment] 2016-08-19 20:54
not a binary ninja problem - ran in normal python shell and had the same problem.
