### ISSUE TITLE
Crash when renaming local variable

### ISSUE THREAD

**Issue by teknogeek** [Vector35/binaryninja-api#618] opened 2017-02-13 16:21 UTC
Crash Dump: http://pastebin.com/qQpkWxXd

**Comment by psifertex** [comment] 2017-02-17 20:31
Sorry for the delay on this -- is the crash reproducible? Is the binary one you can share? 

Unfortunately right now we don't have the ability to correlate stripped crash dumps with private builds with symbols which would help troubleshoot this.

**Comment by teknogeek** [comment] 2017-02-17 20:35
Sure, I believe that this was it

https://dl.dropboxusercontent.com/u/43457458/easypeasy

**Comment by psifertex** [comment] 2017-02-17 20:43
Thanks -- I tried changing a bunch of random variables there but couldn't reproduce it. Leaving open now in case anyone else can find it and get it more reproducible, or alternatively if we get our build system saving debug builds internally so we can match public crash dumps that would help too. 

Thanks for the report.

**Comment by teknogeek** [comment] 2017-03-05 02:58
Had the same kind of thing happen with a different binary. http://pastebin.com/yPa32sEH

**Comment by psifertex** [comment] 2017-03-05 03:06
Do you have a set of steps that reliably reproduce the crash? I suspect there is something relatively unique in your workflow that others tend not to do since we haven't had other reports and it's hard to say what that might be. Not to say we don't want to fix it, just that without either archived builds so we can align the crash dump with symbols or steps to reproduce it's unlikely we'll be able to root cause it.

**Comment by teknogeek** [comment] 2017-03-05 03:08
Well I typically do _a lot_ of variable renaming with `n`, to keep myself organized. I suspect that it might have to do with something regarding replacing all instances throughout the project when renaming?

**Comment by teknogeek** [comment] 2017-03-05 03:13
But no, so far I have not found a reliable way to reproduce the crash. As I encounter this more frequently, I presume I will find a reliable way to later on.

**Comment by psifertex** [comment] 2017-03-05 03:25
Hmm. I might try to script up something with the API to rename everything and see if that triggers anything. Otherwise we'll wait until we archive off debug builds. Thanks.

**Comment by psifertex** [comment] 2017-03-05 15:58
Any chance you regularly highlight either lines or blocks as well?

**Comment by teknogeek** [comment] 2017-04-01 18:22
Sorry I didn't see this. I do highlight blocks and lines a lot. I'm coming back to this issue because i just encountered this issue again https://pastebin.com/bk5NMH3E

**Comment by walterschell** [comment] 2017-05-13 20:18
The following steps crash binja for me every time I repeat them.
1. Open attached file Crack from rootme-org challenge "ELF - CrackPass"
2. Navigate to sub_80484f4
3. Press "i" to switch to il view
4. Click on "arg_4"
5. press "n"
6. enter a name and press enter

**Comment by teknogeek** [comment] 2017-05-13 21:04
Yes, at last! This is reproducible and I have tested it and the same is happening to me. I have attached a ZIP file with the apple crash log and the binary in it.
[Crash-Files.zip](https://github.com/Vector35/binaryninja-api/files/998933/Crash-Files.zip)


It should be noted that this only happens in the LLIL view, **not** in the assembly view.

**Comment by plafosse** [comment] 2017-07-18 03:53
I've tested this just now and was not able to reproduce the crash. Could someone else confirm that this issue is fixed?

**Comment by plafosse** [comment] 2017-08-06 23:46
Closing this since the bug seems to be fixed.

**Closed by plafosse** 2017-08-06 23:46 UTC
Labels: bug
