### ISSUE TITLE
Clicking on a string's xref doesn't take you to its location

### ISSUE THREAD

**Issue by adrianbn** [Vector35/binaryninja-api#484] opened 2016-09-19 17:32 UTC
Clicking on the xref for a string in the strings view does not take you to the linear/graph disassembly where the string is being referenced. Instead, the strings view is re-centered. 
How to reproduce:

1. Go to strings view and find a string with a xref
2. Select the string with the xref (left click)
3. Double click on the xref panel to go to its usage in the code

**Comment by psifertex** [comment] 2016-09-19 18:47
Dupe of #448

**Closed** 2016-09-19 18:47 UTC
