### ISSUE TITLE
Back-forward navigation support in types sidebar

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3936] opened 2023-02-23 10:56 UTC
Is it possible to navigate back and forwards in types view? I frequently navigate to inner structures in types sidebar and when I want to go back to where I am I can not do it by pressing ESC.

**Comment by wildex999** [comment] 2023-10-01 16:37
I second this one. It's extremely annoying when you're 3 layers deep into a type hierarchy, trying to figure out what goes where, and then suddenly losing where you were, since you can't go back to the previous type you were looking at.

In the main view I can just press the 4th mouse button to go back to the pervious location I was looking at, but it does nothing for the Types view. So much time lost to this.

**Comment by CouleeApps** [comment] 2024-02-17 21:17
Duplicate of #3452

**Closed by CouleeApps** 2024-02-17 21:17 UTC
Labels: Type: Enhancement, Component: UI, Effort: Low, Impact: Medium, UI: Types
