### ISSUE TITLE
Generated nested loop logic is hard to understand

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#5536] opened 2024-06-10 10:04 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5428-dev, 5597859f
- OS: macos
- OS Version: 14.5
- CPU Architecture: arm64

Internal binary `major dine favor`.

Consider the decompilation of `DjiAccessAdapter_IdentifyUart0InfoAndAircraftSeries`...

The IDA Pro decompilation uses easy to understand sequential for loops whereas BN generated a series of hard to understand nested loops. 

The first message to be sent should has the following header

```
  header.sender = 0xE5;
  header.receiver = 0x65;
```

BN generates a nested loops where the first message to be sent has a completely different header unless I take into account the various flags checked in the generated nested loops. 

IDA code

```
int64_t __fastcall DjiAccessAdapter_IdentifyUart0InfoAndAircraftSeries(
        int32_t *baud_rate,
        int32_t *protocol_id,
        int32_t *ca_ea_x,
        enum E_DjiAircraftSeries *series)
{
  enum E_DjiAircraftSeries v5; // w0
  Linker linker_1; // [xsp+10h] [xbp+10h] BYREF
  enum E_DjiAircraftSeries *series_1; // [xsp+B0h] [xbp+B0h]
  int32_t *ca_ea_x_1; // [xsp+B8h] [xbp+B8h]
  int32_t *protocol_id_1; // [xsp+C0h] [xbp+C0h]
  int32_t *baud_rate_1; // [xsp+C8h] [xbp+C8h]
  struct Link link; // [xsp+D0h] [xbp+D0h] BYREF
  __int64 v12; // [xsp+108h] [xbp+108h] BYREF
  __int64 v13; // [xsp+120h] [xbp+120h] BYREF
  char v14[8]; // [xsp+150h] [xbp+150h] BYREF
  MessageHeader cmd_header; // [xsp+158h] [xbp+158h] BYREF
  MessageHeader header; // [xsp+170h] [xbp+170h] BYREF
  char v17[1024]; // [xsp+188h] [xbp+188h] BYREF
  struct Linker linker; // [xsp+588h] [xbp+588h] BYREF
  int64_t err; // [xsp+628h] [xbp+628h]
  char v20; // [xsp+637h] [xbp+637h]
  T_DjiOsalHandler *osal; // [xsp+638h] [xbp+638h]
  int j; // [xsp+644h] [xbp+644h]
  unsigned int i; // [xsp+648h] [xbp+648h]
  char v24; // [xsp+64Fh] [xbp+64Fh]


  baud_rate_1 = baud_rate;
  protocol_id_1 = protocol_id;
  ca_ea_x_1 = ca_ea_x;
  series_1 = series;
  osal = DjiPlatform_GetOsalHandler();
  v24 = 0;
  memset(&linker, 0, sizeof(linker));
  memset(&header, 0, sizeof(header));
  memset(&cmd_header, 0, sizeof(cmd_header));
  v14[0] = 0;
  memset(&link, 0, sizeof(link));
  v20 = 0;
  err = DjiAccessAdapter_CheckUserUartBaudRateAndAircraftSeries(baud_rate_1, protocol_id_1, ca_ea_x_1, series_1);
  if ( !err )
    return 0LL;
  LOBYTE(link.protocol_id) = 2;
  header.is_reply = 0;
  header.ack_type = 2;
  header.type = 2;
  header.sender = 0xE5;
  header.receiver = 0x65;
  header.cmd_set = 3;
  header.cmd_id = 0xFD;
  header.payload_size = 0;
  for ( i = 0; i <= 4; ++i )
  {
    link.baud_rate = BAUD_RATES[i];
    err = DjiLinker_Init(&link, &linker);
    if ( err )
    {
      DjiLogger_Output(
        "adapter",
        0,
        "[%s:%d) DjiLinker_Init, stat:%lld",
        "DjiAccessAdapter_IdentifyUart0InfoAndAircraftSeries",
        591LL,
        err);
    }
    else
    {
      for ( j = 0; j <= 4; ++j )
      {
        LOWORD(header.seqnum) = j;
        memcpy(&linker_1, &linker, sizeof(linker_1));
        err = DjiLinker_SendMsg(&linker_1, &header, 0LL);
        if ( err )
          DjiLogger_Output(
            "adapter",
            0,
            "[%s:%d) DjiLinker_SendMsg, stat:%lld",
            "DjiAccessAdapter_IdentifyUart0InfoAndAircraftSeries",
            598LL,
            err);
...
```

and corresponding BN HLIL

```
000cf978  int64_t DjiAccessAdapter_IdentifyUart0InfoAndAircraftSeries(int32_t* baud_rate, int32_t* protocol_id, int32_t* ca_ea_x, enum E_DjiAircraftSeries* series)

000cf994      struct T_DjiOsalHandler* osal = DjiPlatform_GetOsalHandler()
000cf99c      char var_1 = 0
000cf9a4      struct Linker linker_1
000cf9a4      __builtin_memset(s: &linker_1, c: 0, n: 0xa0)
000cfa00      int64_t var_4f8
000cfa00      __builtin_memset(s: &var_4f8, c: 0, n: 0x30)
000cfa08      char payload = 0
000cfa0c      struct Link link
000cfa0c      __builtin_memset(s: &link, c: 0, n: 0x34)
000cfa1c      char var_19 = 0
000cfa40      int64_t err
000cf978      
000cfa40      if (DjiAccessAdapter_CheckUserUartBaudRateAndAircraftSeries(baud_rate, protocol_id, ca_ea_x, series) == 0)
000cfa44          err = 0
000cfa40      else
000cfa50          link.protocol_id.b = 2
000cfa54          struct MessageHeader header
000cfa54          header.is_reply = 0
000cfa5c          header.ack_type = 2
000cfa64          header.type = 2
000cfa6c          header.sender = 0xe5
000cfa74          header.receiver = 0x65
000cfa7c          header.cmd_set = 3
000cfa84          header.cmd_id = 0xfd
000cfa88          header.payload_size = 0
000cfa8c          int32_t var_8_1 = 0
000cfa50          
000cfd00          while (true)
000cfd00              struct Linker linker
000cfd00              uint8_t var_4f0[0x8]
000cfd00              char payload_1
000cfd00              
000cfd00              if (var_8_1 u> 4)
000cfd08                  link.protocol_id.b = 2
000cfd0c                  header.is_reply = 0
000cfd14                  header.ack_type = 2
000cfd1c                  header.type = 2
000cfd24                  header.sender = 0xca
000cfd2c                  header.receiver = 3
000cfd34                  header.cmd_set = 3
000cfd3c                  header.cmd_id = 0xfd
000cfd40                  header.payload_size = 0
000cfd44                  int32_t var_8_2 = 0
000cfd08                  
000cffb8                  while (true)
000cffb8                      if (var_8_2 u> 4)
000cffc0                          link.protocol_id.b = 2
000cffc4                          header.is_reply = 0
000cffcc                          header.ack_type = 2
000cffd4                          header.type = 2
000cffdc                          header.sender = 0xea
000cffe4                          header.receiver = 3
000cffec                          header.cmd_set = 3
000cfff4                          header.cmd_id = 0xfd
000cfff8                          header.payload_size = 0
000cfffc                          int32_t ix_1 = 0
000cffc0                          
000d02b0                          while (true)
000d02b0                              if (ix_1 u> 4)
000d02b8                                  link.protocol_id.b = 1
000d02bc                                  header.is_reply = 0
000d02c4                                  header.ack_type = 2
000d02cc                                  header.type = 1
000d02d4                                  header.sender = 0xa
000d02dc                                  header.receiver = 3
000d02e0                                  header.cmd_set = 0
000d02e4                                  header.cmd_id = 0
000d02ec                                  header.payload_size = 1
000d02f0                                  int32_t ix = 0
000d02b8                                  
000d0588                                  while (true)
000d0588                                      if (ix u> 4)
000d058c                                          err = 0x100
000d058c                                          break
000d0588                                      
000d0308                                      link.baud_rate = BAUD_RATES[sx.q(ix)]
000d0314                                      T_DjiReturnCode err_2 = DjiLinker_Init(&link, linker: &linker_1)
000d0588                                      
000d0324                                      if (err_2 != 0)
000d0354                                          DjiLogger_Output(tag: "adapter", level: 0, fmt: "[%s:%d) DjiLinker_Init, stat:%ll…", "DjiAccessAdapter_IdentifyUart0In…", 0x301, err_2)
000d0324                                      else
000d0504                                          int32_t i
000d035c                                          
000d0504                                          for (i = 0; i s<= 4; i += 1)
000d036c                                              header.seqnum.w = i.w
000d037c                                              memcpy(&linker, &linker_1, 0xa0)
000d038c                                              uint64_t x0_138 = DjiLinker_SendMsg(&linker, meta: &header, &payload)
000d0504                                              
000d039c                                              if (x0_138 != 0)
000d03cc                                                  DjiLogger_Output(tag: "adapter", level: 0, fmt: "[%s:%d) DjiLinker_SendMsg, stat:…", "DjiAccessAdapter_IdentifyUart0In…", 0x309, x0_138)
000d0504                                              
000d03dc                                              memcpy(&linker, &linker_1, 0xa0)
...
```

**Comment by xusheng6** [comment] 2024-06-11 05:29
Duplicate of https://github.com/Vector35/binaryninja-api/issues/5369

**Closed by xusheng6** 2024-06-11 05:29 UTC
