### ISSUE TITLE
Demangle issue thrown in log, plus crashes

### ISSUE THREAD

**Issue by thejtshow** [Vector35/binaryninja-api#2026] opened 2020-10-12 17:24 UTC
I am trying to analyze the RepetierServer binary provided in the 'Linux 64 bit intel' debian installer of Repetier Server [found here](https://www.repetier-server.com/download-repetier-server/), and am receiving `Unsupported demangle type: transaction clone` in the binja logs. 

Currently running dev build `2461` (personal) on Ubuntu. 

This analyze has also crashed a few times, but might be due to resource issues. dual core VM with 4 GB ram and no swap.

Binary will be uploaded shortly.

**Comment by thejtshow** [comment] 2020-10-12 17:30
crashes likely due to out of memory error. here is the binary for the demangle issue: 
[repetier.tar.gz](https://github.com/Vector35/binaryninja-api/files/5366625/repetier.tar.gz)

**Comment by plafosse** [comment] 2020-10-14 18:37
Duplicate of #1016

**Closed by plafosse** 2020-10-14 18:37 UTC
