### ISSUE TITLE
Default x86 and x86-64 architecture modules give wrong max_instr_size

### ISSUE THREAD

**Issue by sabastiaan** [Vector35/binaryninja-api#2225] opened 2021-01-08 15:58 UTC
![x86_64_max_size](https://user-images.githubusercontent.com/5167125/104034672-7c476300-51d1-11eb-9229-98fb70100868.png)

Both AMD and Intel explicitly state that all their CPU's will refuse to encode anything above 15 bytes. 
While it is possible to have a syntactically valid encoded instruction of more than 15, the size of these in bytes are theoretically infinite.

Sources:
[Intel: Volume 2:  2.2.1](https://software.intel.com/content/www/us/en/develop/download/intel-64-and-ia-32-architectures-sdm-combined-volumes-1-2a-2b-2c-2d-3a-3b-3c-3d-and-4.html)
[AMD: AMD64 Architecture Programmer’s Manual Volume 3: General Purpose and System Instructions section 1.1](https://developer.amd.com/resources/developer-guides-manuals/)

**Comment by psifertex** [comment] 2021-01-08 18:10
As I mentioned in the previous PR, this variable is poorly named. It's not /actually/ the max instruction length, it's just the largest size buffer the architecture module will accept and there's no reason it can't be larger than the actual maximum instruction length. Consider:

```
>>> Architecture['mips32'].max_instr_length
8
```

Does that mean MIPS 32 has 8 byte instructions? Nope, just that the MIPS architecture will read 8 bytes at a time (it does this for reasons of delay slots, but there may be other reasons an architecture chooses to consume more bytes)

Unfortunately it's a lot of work and would break existing architectures to rename this particular variable so we have no plans to change it (or the defined value of 16 for x86) at this time. I will definitely make a change to the documentation for that particular property though so that. I'm totally on board with your assertion that the maximum real-world instruction you can get is 15, but I think you'll find that even if we changed this value, none of our disassembly would change at all. Our disassembler will only ever produce 15 byte instructions, we're merely choosing this length because it's more convenient as a buffer read length that allows optimization. If you do indeed find any issues with correctness of disassembly caused by this, I'd be surprised, but that would definitely be a bug! Until then, I'm closing this as a "wont fix" since it's behaving as intended, just not quite as you might expect based on the name of the variable. 

So for not getting a more clear explanation of this previously, hopefully this helps clarify the purpose of this variable!

**Closed by psifertex** 2021-01-08 18:10 UTC
Labels: wontfix

**Comment by psifertex** [comment] 2021-01-08 18:21
Unfortunately that property doesn't have a dedicated setter/getter (which makes sense since it's a read only property of teh architecture) so I've documented it as a note on the Architecture class: 

https://github.com/Vector35/binaryninja-api/commit/b47c5a64e466d2322a7072a3fd1d11aff5cfab43

Let me know if you have any suggestions on how to make the explanation better!

**Comment by sabastiaan** [comment] 2021-01-09 00:43
Hey, so this extra explanation does now make sense to me.

So my major point of contention was not necessarily with fears of the assembly being incorrect (these should be handled in the disassembler anyway). But rather with that it would break user facing code that would naively try to check if there exists a possible preceding instruction, since these should be based on backtracking `max_instr_length` and having an extra byte here could change the output of that if you don't employ extra checks.

But as long as it's properly documented, like it is now, it should be fine I guess.
