### ISSUE TITLE
/bin/ls on LTS ubuntu 16.04 fails to identify main

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#401] opened 2016-08-22 04:56 UTC
Possible problems: 

1) dataflow fails to track argument, 
2) calling convention has changed, 
3) libc start prototype is different

**Comment by tylerni7** [comment] 2016-08-22 05:51
It looks like the issue is due to dataflow not terminating on a function, and maybe that is preventing all further analyses? One function seem to be causing issues with dataflow, I get a warning like
```
Data flow for function at 0x417020 did not terminate
Analysis update took 40.397 seconds
```

One of the times I opened `/bin/ls`, opened some other programs for analysis in binary ninja, and then closed the other programs, `/bin/ls` seemed to have finished processing. I cannot seem to reproduce that though (every time I open it and do other things, including leaving binary ninja opened for extended periods of time, it fails to identify main).

If I manually define the function at main, everything propagates and updates as expected.

Github is failing to let me upload files.. so I can't seem to attach my `/bin/ls`, but if there are issues reproducing this I can host it somewhere.

**Comment by psifertex** [comment] 2016-08-24 02:55
For those playing along at home, this is a race condition that we haven't quite identified, but it does have a simple fix -- simple edit any line of assembly in `start` (use the `e` key) and hit enter. This forces the analysis to re-run which properly identifies the prototype, finds main, and finishes analyzing the rest of the function.

**Comment by D0ntPanic** [comment] 2016-09-01 02:36
Fixed in dev

**Closed by D0ntPanic** 2016-09-01 02:36 UTC
Labels: bug
