### ISSUE TITLE
Feature Request : Add submenus for plugins

### ISSUE THREAD

**Issue by bkerler** [Vector35/binaryninja-api#1127] opened 2018-08-20 09:50 UTC
The current plugin system adds many menus, making it impossible to maintain multiple plugins.

Thus I'd recommend to add the following functionality :

1. Get main menu name from field "name" in **plugin.json** 

2. Add submenus for current plugin name in **__init.py__**
```
submenu=PluginCommand.CreateSubmenu("Session")
submenu.register_for_address('** attach **', '', s.attach)
submenu.register_for_address('** restore session **', '', s.attach)

submenu2=PluginCommand.CreateSubmenu("Emulate")
submenu2.register_for_address('** emulate to selected**', '', s.emulate, lambda x, y: s.current_function is not None and s.current_function_address != y))
submenu2.register_for_address('** emulate next**', '', s.emulate_next, lambda x, y: s.emulator is not None or s.current_function_address == y)
submenu2.register_for_address('** emulate selected **', '', s.emulate_instr, lambda x, y: s.current_function is not None and s.current_function_address != y)
```

**Example view in the plugin menu for binja-secret plugin:** 
```
"secRet.re" -> Session -> ** attach **
            |          |
            |          -> ** restore session **
            |
            -> Emulate -> ** emulate to selected**
                       |
                       -> ** emulate next **
                       |
                       -> ** emulate selected **
```

**Comment by bkerler** [comment] 2018-08-20 09:59
This is same request as #1107, but with a different approach

**Comment by plafosse** [comment] 2018-10-04 15:06
Closing as a duplicate of #1107 We can still use this ticket for reference even though its closed.

**Closed by plafosse** 2018-10-04 15:06 UTC
Labels: duplicate
