### ISSUE TITLE
Forced autocomplete in Re(n)ame Symbol dialog

### ISSUE THREAD

**Issue by amtal** [Vector35/binaryninja-api#2117] opened 2020-11-10 07:21 UTC
2.2.2518-dev / Windows

Manually defining new symbols that are prefixes of existing symbols auto-completes to the existing full-length symbol name. I hit enter thinking I'm done, but instead of trying to commit the symbol name it commits the auto-complete. Since symbol names are unique this is never what I want, cue mashing backspace and trying again...

This breaks flow and slows down manual markup.

The autocomplete makes sense as a hint when prefixing names with a compilation unit or object. It's unhelpful with suffix schemes (partial-application wrappers like `memcpy_0x26_bytes`, variations on assert or logging functions `log_to_uart?` / `log_debug_mode?` / `log_stub_3` / ...) or cases where you forgot you already had some related names under a different prefix.

A smart mid-word autocomplete feature that listed possible related names as hints and committed them only via dedicated completion hotkey (rather than the main-line "enter" hotkey) should result in cleaner manual markup.

**Comment by jonpalmisc** [comment] 2021-05-26 14:45
Duplicate of #2448.

**Closed by jonpalmisc** 2021-05-26 14:45 UTC
Labels: Effort: Low, Impact: Medium, duplicate, enhancement, ui

**Comment by psifertex** [comment] 2021-05-26 16:27
More accurately the duplication was the other way around but either way, they're both resolved. 😉
