### ISSUE TITLE
Type propogation into data variable

### ISSUE THREAD

**Issue by reversing-dev** [Vector35/binaryninja-api#4759] opened 2023-11-19 08:16 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4644-dev Personal, d289b1cc
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/e798f2d0-3a18-4cb5-9ce0-5fcf9022f1db)

![image](https://github.com/Vector35/binaryninja-api/assets/42991292/a39108a5-c70b-454a-8613-ab5e808e987b)

File: same as #4758

**Comment by xusheng6** [comment] 2023-11-21 05:35
The real problem is that we are not propagating type info into data variables. 

An alternative solution is to detect the type of the argument is a char* and then render it as a string, regardless of the actual data variable type. However, I am not sure that is a robust approach that fits into most cases. 

A workaround for now is to press 'A' at the data variable to define a string there, and the HLIL should be able to pick it up.

**Comment by xusheng6** [comment] 2023-11-21 05:46
I am pretty sure we have an issue that tracks "type propagation into data vars", but I cannot find it at the moment. Any idea? @fuzyll

**Comment by fuzyll** [comment] 2023-11-22 18:46
I'm not sure. I also don't explicitly see an issue that tracks that. #4692 is probably related?

**Comment by reversing-dev** [comment] 2023-11-22 19:45
It seems `%s` is not considered as a string. 
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/dd205a64-62f2-4f57-8702-40a203e6d3f4)

**Comment by plafosse** [comment] 2023-11-28 14:14
Duplicate of https://github.com/Vector35/binaryninja-api/issues/4400

**Closed by plafosse** 2023-11-28 14:14 UTC
Labels: Type: Enhancement, Component: Core, Effort: Medium, Impact: Medium
