### ISSUE TITLE
Varargs not recognized

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4255] opened 2023-04-21 08:34 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4248-dev, c26685e2
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

I'm working with a variant of a `sprintf` function, let's call it `log`. BN did not recognize it as having a variable number of arguments

```
00000523a  void* log(void* arg1, int32_t arg2, char* arg3, int32_t arg4))

00000523a  0cb4       push    {r2, r3} {var_4} {var_8}
00000523c  70b5       push    {r4, r5, r6, lr} {__saved_lr} {__saved_r6} {__saved_r5} {__saved_r4}
00000523e  9cb0       sub     sp, #0x70
000005240  0c46       mov     r4, r1
000005242  0646       mov     r6, r0
000005244  46f032f8   bl      #sub_4b2ac
000005248  002c       cmp     r4, #0
00000524a  0546       mov     r5, r0
00000524c  08da       bge     #0x5260

00000524e  8b23       movs    r3, #0x8b
000005250  0360       str     r3, [r0]  {0x8b}
000005252  4ff0ff30   mov     r0, #0xffffffff

000005256  1cb0       add     sp, #0x70
000005258  bde87040   pop     {r4, r5, r6, lr} {__saved_r4} {__saved_r5} {__saved_r6} {__saved_lr}
00000525c  02b0       add     sp, #8
00000525e  7047       bx      lr

000005260  4ff40273   mov     r3, #0x208
000005264  209a       ldr     r2, [sp, #0x80] {var_8}
000005266  adf81430   strh    r3, [sp, #0x14] {var_74_1}  {0x208}
00000526a  02a9       add     r1, sp, #8 {var_80}
00000526c  14bf       ite     ne
00000526e  04f1ff33   add     r3, r4, #0xffffffff
000005272  2346       mov     r3, r4
000005274  0493       str     r3, [sp, #0x10] {var_78_1}
000005276  0793       str     r3, [sp, #0x1c] {var_6c_1}
000005278  4ff6ff73   movw    r3, #0xffff
00000527c  adf81630   strh    r3, [sp, #0x16] {var_72_1}  {0xffff}
000005280  21ab       add     r3, sp, #0x84 {var_4}
000005282  0296       str     r6, [sp, #8] {var_80}
000005284  0193       str     r3, [sp, #4] {var_84_1} {var_4}
000005286  0696       str     r6, [sp, #0x18] {var_70_1}
000005288  fef79afc   bl      #sub_3bc0
00000528c  431c       adds    r3, r0, #1
00000528e  bcbf       itt     lt
000005290  8b23       movs    r3, #0x8b
000005292  2b60       str     r3, [r5]
000005294  002c       cmp     r4, #0
000005296  ded0       beq     #0x5256

000005298  029b       ldr     r3, [sp, #8] {var_80}
00000529a  0022       movs    r2, #0
00000529c  1a70       strb    r2, [r3]  {0x0}
00000529e  dae7       b       #0x5256
```

IDA does recognize it as a varargs function 

```
int log(int a1, int a2, const char *a3, ...)
{
  _DWORD *v5; // r0
  _DWORD *v6; // r5
  int result; // r0
  int v8; // r3
  int v9[3]; // [sp+8h] [bp-80h] BYREF
  __int16 v10; // [sp+14h] [bp-74h]
  __int16 v11; // [sp+16h] [bp-72h]
  int v12; // [sp+18h] [bp-70h]
  int v13; // [sp+1Ch] [bp-6Ch]
  unsigned __int8 *varg_r2; // [sp+80h] [bp-8h]
  va_list varg_r3; // [sp+84h] [bp-4h] BYREF

  va_start(varg_r3, a3);
  varg_r2 = (unsigned __int8 *)a3;
  v5 = (_DWORD *)sub_4B2AC();
  v6 = v5;
  if ( a2 >= 0 )
  {
    v10 = 0x208;
    if ( a2 )
      v8 = a2 - 1;
    else
      v8 = 0;
    v9[2] = v8;
    v13 = v8;
    v11 = -1;
    v9[0] = a1;
    v12 = a1;
    result = sub_3BC0(v5, (int)v9, varg_r2, (int *)varg_r3);
    if ( result < -1 )
      *v6 = 139;
    if ( a2 )
      *(_BYTE *)v9[0] = 0;
  }
  else
  {
    *v5 = 139;
    return -1;
  }
  return result;
}
```

but BN gives the following HLIL 

```
00000523a  {
00000523a      int32_t var_4 = arg4;
000005244      int32_t* r0 = sub_4b2ac();
00000524c      void* r0_1;
00000524c      if (arg2 < 0)
000005248      {
000005250          *(int32_t*)r0 = 0x8b;
000005252          r0_1 = &data_ffffffff;
000005252      }
000005260      else
000005260      {
000005260          int32_t r3 = 0x208;
000005266          int16_t var_74_1 = 0x208;
00000526e          if (arg2 != 0)
000005248          {
00000526e              r3 = (arg2 - 1);
00000526e          }
000005272          if (arg2 == 0)
000005248          {
000005272              r3 = arg2;
000005272          }
000005274          int32_t var_78_1 = r3;
000005276          int32_t var_6c_1 = r3;
00000527c          int16_t var_72_1 = 0xffff;
000005282          void* var_80 = arg1;
000005284          int32_t* var_84_1 = &var_4;
000005286          void* var_70_1 = arg1;
000005288          r0_1 = sub_3bc0(r0, &var_80, arg3, &var_4, arg1);
00000528c          void* r3_2 = ((char*)r0_1 + 1);
000005290          if (r0_1 < 0xffffffff)
00000528c          {
000005290              r3_2 = &*(int32_t*)((char*)data_88 + 3);
000005290          }
000005292          if (r0_1 < 0xffffffff)
00000528c          {
000005292              *(int32_t*)r0 = r3_2;
000005292          }
000005296          if (arg2 != 0)
000005294          {
00000529c              *(int8_t*)var_80 = 0;
00000529c          }
000005294      }
00000525e      return r0_1;
00000525e  }
```

I thought fixing the function signature would help so I changed it to 

```
00000523a  void* flight_log_523a(void* arg1, int32_t arg2, char* arg3, ...)
```

but that didn't change anything but the fist couple of lines 

```
00000523a  {
00000523a      int32_t r3;
00000523a      int32_t var_4 = r3;
000005244      int32_t* r0 = sub_4b2ac();
00000524c      void* r0_1;
00000524c      if (arg2 < 0)
000005248      {
000005250          *(int32_t*)r0 = 0x8b;
000005252          r0_1 = &data_ffffffff;
000005252      }
000005260      else
000005260      {
000005260          int32_t r3_1 = 0x208;
000005266          int16_t var_74_1 = 0x208;
00000526e          if (arg2 != 0)
000005248          {
00000526e              r3_1 = (arg2 - 1);
00000526e          }
000005272          if (arg2 == 0)
000005248          {
000005272              r3_1 = arg2;
000005272          }
000005274          int32_t var_78_1 = r3_1;
000005276          int32_t var_6c_1 = r3_1;
00000527c          int16_t var_72_1 = 0xffff;
000005282          void* var_80 = arg1;
000005284          int32_t* var_84_1 = &var_4;
000005286          void* var_70_1 = arg1;
000005288          r0_1 = sub_3bc0(r0, &var_80, arg3, &var_4, arg1);
00000528c          void* r3_3 = ((char*)r0_1 + 1);
000005290          if (r0_1 < 0xffffffff)
00000528c          {
000005290              r3_3 = &*(int32_t*)((char*)data_88 + 3);
000005290          }
000005292          if (r0_1 < 0xffffffff)
00000528c          {
000005292              *(int32_t*)r0 = r3_3;
000005292          }
000005296          if (arg2 != 0)
000005294          {
00000529c              *(int8_t*)var_80 = 0;
00000529c          }
000005294      }
00000525e      return r0_1;
00000525e  }
```

**Comment by plafosse** [comment] 2023-04-24 13:18
This is a duplicate of this issue: https://github.com/Vector35/binaryninja-api/issues/3916 
This plugin in the plugin manager fixes these up: https://github.com/nshp/binaryninja-printf

**Closed** 2023-04-24 13:18 UTC
Labels: State: Duplicate
