### ISSUE TITLE
Symbols not showing in symbols view

### ISSUE THREAD

**Issue by Kharos102** [Vector35/binaryninja-api#3063] opened 2022-04-09 12:55 UTC
Binary Ninja Version: 3.0.3337-dev Personal, 7daa28e8
Platform: Windows 11 Version 2009

PE64 binary compiled by rust for ARM64 with debug symbols will have the symbols shown in HLIL view, but not in Symbols view (meaning I can't search for the symbol).

I've attached a screenshot showing how in HLIL you can see the functions with actual symbolic names in HLIL view, but these names don't show in Symbol view (note that it does in the Stable branch of binja!).
![binja2](https://user-images.githubusercontent.com/16039802/162574983-22dc80a2-b716-48cf-a21b-f5255ce4a962.png)

**Comment by Kharos102** [comment] 2022-04-11 22:36
> If you right-click "Show Mangled Names" does it show up? ![image](https://user-images.githubusercontent.com/10556585/162795941-194fc0aa-c56d-40c4-bbf2-994d0701a90a.png)

No it does not.

If I right-click and press "Show Data Variables -> Local" it shows a **little** more, but not everything.

![mangled](https://user-images.githubusercontent.com/16039802/162844437-00442225-02b5-4a5d-9c73-30686779c325.png)

**Comment by psifertex** [comment] 2022-04-12 00:31
Can you share the binary?

**Comment by Kharos102** [comment] 2022-04-12 00:38
Here I've attached a built "kernel.exe" from this project: https://github.com/gamozolabs/chocolate_milk

It is a rust-based x64 PE32+ binary, symbols/functions like "_ZN6kernel5panic19attempt_soft_reboot17h0ef4bbe5067610eeE" don't show up in Symbols view, but they do in HLIL.

[kernel.zip](https://github.com/Vector35/binaryninja-api/files/8468609/kernel.zip)

**Comment by psifertex** [comment] 2022-04-12 00:48
Hah! I blame Falk! (Kidding, just funny to see it showing up from one of his projects). 

Thanks.

**Comment by psifertex** [comment] 2022-04-12 04:35
This actually looks like a much broader regression than anything related to rust caused by some of the recent performance improvements, thanks for pointing it out. If you want to go back to a prior version, dev builds before 3291 do not exhibit this issue (you may have to enable the `show all versions` setting to see it in your update list).

**Comment by D0ntPanic** [comment] 2022-04-12 17:13
Fixed in build 3344

**Closed by D0ntPanic** 2022-04-12 17:13 UTC
Labels: bug, Impact: High, regression
