### ISSUE TITLE
Component View does not properly sync with UI

### ISSUE THREAD

**Issue by malre0x21** [Vector35/binaryninja-api#4179] opened 2023-03-31 20:35 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4189-dev
- OS: Windows 10 Enterprise
- OS Version: 1607
- CPU Architecture: x64 

**Bug Description:**
if you rename a function in the UI the component view doesn't update to reflect the change
**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Settings ->  UI -> Components-> "Enable New Symbols UI".
2. Select a function in the UI
3. Rename function in the UI

**Expected Behavior:**
The component view should sync with the UI so that any changes in the UI are reflected back in the component view

**Screenshots:**
If applicable, please add screenshots here to help explain your problem.

**Additional Information:**
Please add any other context about the problem here.

**Comment by cxnder** [comment] 2023-03-31 20:49
Duplicate of #3962

**Closed by cxnder** 2023-03-31 20:49 UTC
