### ISSUE TITLE
Analysis not propogating the variable type from called function to stack variable

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#5549] opened 2024-06-11 08:34 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5458-dev,  6421303
- OS: macos
- OS Version: 14.5
- CPU Architecture: arm64

Internal binary `major dine favor`.

I may have filed this issue already and I apologize if so!

`DjiAircraftConnection_CheckExtensionPortConnectStatusBySdkProtocol` ...

IDA picks up the type of `var_20`, probably based on the signature of `DjiCommand_SendAsync`. 

BN doesn't.

```
000d1300  uint64_t DjiAircraftConnection_CheckExtensionPortConnectStatusBySdkProtocol(struct MessageReplyContext* ctx)

000d130c      int64_t var_20
000d130c      __builtin_memset(s: &var_20, c: 0, n: 0x18)
000d1328      void config
000d1328      uint64_t result
000d1300      
000d1328      if (DjiAircraftInfoParamConfig_Get(&config) != 0)
000d1354          DjiLogger_Output(tag: "infor", level: 2, fmt: "[%s:%d) Can't get aircraft info …", "DjiAircraftConnection_CheckExten…", 0x4e)
000d1358          result = 0xe3
000d1328      else
000d1364          var_20.d = 1
000d136c          int64_t var_18
000d136c          var_18:4.b = 0xa
000d1374          char var_27
000d1374          var_18:5.b = var_27
000d1384          int64_t var_10
000d1384          var_10.w = DjiCommand_GetSeqNum(cmd: DjiAccessAdapter_GetCmdHandle())
000d1388          var_20:4.d = 0
000d1390          var_18.d = 2
000d1394          var_18:6.b = 0
000d139c          var_18:7.b = 0xfc
000d13a4          var_10:4.d = 0xe
000d13e0          uint64_t result_1 = DjiCommand_SendAsync(mgr: DjiAccessAdapter_GetCmdHandle(), header: &var_20, payload: &heartBeatPack, callback: DjiAircraftInfo_CheckOSDKHeartBeatStatusAsyncCallback, info: ctx, size: 0x3e8, flag: 0)
000d1364          
000d13f0          if (result_1 != 0)
000d141c              DjiLogger_Output(tag: "infor", level: 0, fmt: "[%s:%d) check connect status asy…", "DjiAircraftConnection_CheckExten…", 0x60)
000d1424              ctx->sem.b = 0
000d1364          
000d1460          DjiLogger_Output(tag: "infor", level: 3, fmt: "[%s:%d) check connect status:%d", "DjiAircraftConnection_CheckExten…", 0x64, zx.q(ctx->sem.b))
000d1464          result = result_1
000d1300      
000d146c      return result
```

Properly typing `var_20` makes the code looks much nicer

```
000d1328      if (DjiAircraftInfoParamConfig_Get(&config) != 0)
000d1354          DjiLogger_Output(tag: "infor", level: 2, fmt: "[%s:%d) Can't get aircraft info …", "DjiAircraftConnection_CheckExten…", 0x4e)
000d1358          result = 0xe3
000d1328      else
000d1364          header.type = 1
000d136c          header.sender = 0xa
000d1374          char var_27
000d1374          header.receiver = var_27
000d1384          header.seqnum.w = DjiCommand_GetSeqNum(cmd: DjiAccessAdapter_GetCmdHandle())
000d1388          header.is_reply = 0
000d1390          header.ack_type = 2
000d1394          header.cmd_set = 0
000d139c          header.cmd_id = 0xfc
000d13a4          header.payload_size = 0xe
000d13e0          uint64_t result_1 = DjiCommand_SendAsync(mgr: DjiAccessAdapter_GetCmdHandle(), &header, payload: &heartBeatPack, callback: DjiAircraftInfo_CheckOSDKHeartBeatStatusAsyncCallback, info: ctx, size: 0x3e8, flag: 0)
```

**Comment by joelreymont** [comment] 2024-06-11 08:36
Same for `config` in 

```
000d1328      void config
000d1328      uint64_t result
000d1300      
000d1328      if (DjiAircraftInfoParamConfig_Get(&config) != 0)
```

**Comment by xusheng6** [comment] 2024-06-11 08:52
Related to https://github.com/Vector35/binaryninja-api/issues/772

**Comment by xusheng6** [comment] 2024-06-11 13:59
Duplicate of https://github.com/Vector35/binaryninja-api/issues/773

**Closed by xusheng6** 2024-06-11 13:59 UTC
