### ISSUE TITLE
setting string types in HLIL does not result in treating the argument as a string but uses heuristic CheckFor*Annotation instead

### ISSUE THREAD

**Issue by bluuuk** [Vector35/binaryninja-api#4079] opened 2023-03-08 13:09 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.3.3996 Personal (Build ID e34a955e)
- OS: MacOS Ventura 
- OS Version: 13.2.1
- CPU Architecture: M1

**Bug Description:**

I am reversing a binary that is linked to libc.

```
Type: ELF
Platform: linux-x86_64
Architecture: x86_64

Libraries: 
  libc.so.6
```

I got the the interesting part where a password comparision happens. On first sight, I thought the password is the one that is displayed within `strcmp`. But this is not the _full_ password.

<img width="404" alt="grafik" src="https://user-images.githubusercontent.com/24961549/223718592-b516649a-9a96-4533-9b26-b812e1a55ab2.png">

However, going deeper (assembly) gave me the same information.

<img width="628" alt="grafik" src="https://user-images.githubusercontent.com/24961549/223719609-6947cae8-7990-4135-b9d3-fe350e054e03.png">

After all, I looked at the memory location and was suprised that the string end is not awaited until a null byte.

<img width="549" alt="grafik" src="https://user-images.githubusercontent.com/24961549/223718710-4382d5be-cfa3-4fcb-813a-09b937013d80.png">

**Steps To Reproduce:**
I don't know if it is up to the binary, but the binary is currently part of an ongoing CTF which I am not allowed to share.

**Expected Behavior:**
The string should be displayed until there is a null byte.

**Comment by psifertex** [comment] 2023-03-08 14:52
The annotation not showing up in disassembly is correct and expected behavior. However, this does highlight another issue which I'm going to rename this issue to address. Specifically, even if you change the type of the argument to be a "char *" the "guess a string" annotator that's used in disassembly is used in HLIL which is incorrect. So the behavior you're observing here is mostly correct (except for the bug described in #4083), however the work-around I was going to suggest (setting the type of the argument -- indeed, depending on the type libraries for this binary the type might already be set) SHOULD result in correct rendering at the HLIL and that is indeed a bug.

**Comment by plafosse** [comment] 2023-06-20 14:40
The reason we don't display the full string is because we don't support line wrapping yet. I'm closing this ticket in favor of #2366

**Closed by plafosse** 2023-06-20 14:40 UTC
Labels: Type: Bug, Effort: Low, Impact: Medium
