### ISSUE TITLE
`test r13d, r13d` unimplemented (HLIL)

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4369] opened 2023-05-31 17:11 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4311-dev Personal (ff27871c)
- OS: Windows
- OS Version: 10.0.25375.1
- CPU Architecture: x64

**Bug Description:**
![image](https://github.com/Vector35/binaryninja-api/assets/44076/c60c2d60-1f84-44e7-92fd-773d8c517f82)
![image](https://github.com/Vector35/binaryninja-api/assets/44076/57d3967c-7814-46a7-ac35-9f0b628a89b3)

**Comment by xusheng6** [comment] 2023-06-07 05:25
@alexrp I cannot reproduce this, do you have a binary that I can test with?

Also this might be related to, or a duplicate of https://github.com/Vector35/binaryninja-api/issues/4041

**Comment by xusheng6** [comment] 2023-06-07 05:25
Well, it is unlikely to be a duplicate of #4041 since there is actually a `je` instruction after the test

**Comment by xusheng6** [comment] 2023-06-07 08:23
@alexrp Thanks, I will have a look at it!

**Comment by xusheng6** [comment] 2023-06-07 09:12
@D0ntPanic Could you please help triage this issue? I am not sure why it happens

**Comment by plafosse** [comment] 2024-01-17 20:15
The root cause here is that we're not implementing parity for a number of instruction in x86.  This is a duplicate of this issue: https://github.com/Vector35/binaryninja-api/issues/4044

**Closed by plafosse** 2024-01-17 20:15 UTC
Labels: Type: Bug, State: Duplicate, Component: Core
