### ISSUE TITLE
Multiple True/False BranchTypes from single instruction cause SEGV

### ISSUE THREAD

**Issue by mothran** [Vector35/binaryninja-api#1504] opened 2020-01-05 19:06 UTC
While implementing a DSP architecture I ran into an crash related to defining multiple True/False BranchType's for a single instruction.  The architecture I am implementing can have a single 'instruction' contain multiple sub instructions, and each sub instructions can be a conditional branch.

While implementing this logic in get_instruction_info() I defined a true / false branch for both of the sub instructions and caused the following python exception + crash:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/home/user/binaryninja/plugins/../python/binaryninja/architecture.py", line 527, in _get_instruction_info
    result[0].branchType[i] = info.branches[i].type
IndexError: invalid index
[1]    7426 segmentation fault (core dumped)  binaryninja -e
```

A simple reproduction step is to define an architecture that just returns something similar to:

```python
    result.add_branch(BranchType.TrueBranch, 0x1000)
    result.add_branch(BranchType.TrueBranch, 0x1004)
```

I am able to work around not being able to define multiple true or false branches by using UnresolvedBranch's and fixing it up in the LLIL but the crash is notable.

**Comment by KyleMiles** [comment] 2021-09-30 20:29
I can't reproduce this.  Here's what I tried:

1. Install the plugin below
2. Open a binary with options (I used /bin/cat)
3. Kill the ELF view, hit 'Open'
4. Right Click -> Make Function At This Address -> Test -> Test
5. Navigate around, cycle through ILs, etc

```
from binaryninja.architecture import Architecture, InstructionInfo, RegisterInfo
from binaryninja.enums import BranchType


class Test(Architecture):
  instructions = []
  name = 'Test'
  stack_pointer = 'sp'
  regs = {'sp': RegisterInfo('sp', 4)}

  def get_instruction_text(self, data, addr):
    return [[], 1]

  def get_instruction_info(self, data, addr):
    result = InstructionInfo()
    result.length = 1
    result.add_branch(BranchType.TrueBranch, 0x1000)
    result.add_branch(BranchType.TrueBranch, 0x1004)
    return result

  def get_instruction_low_level_il(self, data, addr, il):
    return 1


Test.register()
```

I'm going to close this as invalid for now, unless you can provide a repro.  It's quite possible it was inadvertently fixed since you filed this and no one noticed.

**Closed by KyleMiles** 2021-09-30 20:29 UTC
Labels: bug, core, API, crash, Impact: Low, Effort: Low, bugbash
