### ISSUE TITLE
editing types does not refresh dependent functions

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2313] opened 2021-03-12 00:00 UTC

**Comment by jeffli678** [comment] 2021-04-16 08:19
related to #2203. It seems we are not propagating type changes to its consumers

**Comment by jeffli678** [comment] 2021-04-20 04:04
potential duplicate of https://github.com/Vector35/binaryninja-api/issues/2060

**Comment by jeffli678** [comment] 2021-04-21 04:15
Followup on this: Jordan showed a case where it fails: the code references a data variable, and we first select 16 bytes, hit "1", and then hit "*". Then if we go back to the code that references the data, the HLIL is not updated. If you press "Y" to change type and specify "char var_name[0x10]", the HLIL is updated. 

This only happens on MacOS, I cannot reproduce it on Linux. (The HLIL is updated in all cases on Linux)

**Closed** 2021-04-23 06:20 UTC
Labels: Effort: Low, Impact: High, bug

**Comment by jeffli678** [comment] 2021-04-23 06:23
fixed in dev 2.3.2761
