### ISSUE TITLE
'Display as' in HLIL sometimes cause crashes 

### ISSUE THREAD

**Issue by grokeus** [Vector35/binaryninja-api#2119] opened 2020-11-10 09:37 UTC
Binary Ninja Version: 2.2.2520-dev Personal, 779b5105
Platform: Linux

Using 'Display as' menu while working with HLIL view sometimes lead to crashes.
![image](https://user-images.githubusercontent.com/20337200/98654637-9c80b000-234f-11eb-83d1-54806fbcfeea.png)
![image](https://user-images.githubusercontent.com/20337200/98655856-03529900-2351-11eb-9660-b6382440302c.png)

I tried to make some reproducible binary, but can't find out how stably trigger crash..
How to reproduce:
1) open 'crash' file in binary ninja.
2) goto 'prin' function.
3) start changing display type of constant 0x50447ba756c40 to some other representation.
4) repeat step3 until it crashed.

Crash can happened at first change of representation type (maybe size of function matters, but I can't say for sure)

[crash.zip](https://github.com/Vector35/binaryninja-api/files/5516187/crash.zip)

**Comment by jeffli678** [comment] 2020-11-10 09:55
This issue is reported several times. But I never manged to reproduce it. Will try again this time

**Comment by grokeus** [comment] 2020-11-11 17:42
small update - crash always happened(at least for me) if I do following steps:
1) open 'crash' binary
2) goto 'prin' function
3) press 'H' (hex view will be opened)
4) press 'ESC' (so we will be returnung to HLIL view)
5) press 'R' on constant - bn crashed

**Comment by psifertex** [comment] 2020-11-11 20:21
To be clear, tagging as "can't reproduce" doesn't mean we don't believe you, just that we're having a hard time getting a reproduction and anyone else who has a good set of repro steps we'd love to hear. :-) 

Can you please run BN under gdb and include the results of a stack dump? (`bt`)

**Comment by grokeus** [comment] 2020-11-11 20:57
attaching stack dump from gdb (it's a bit smaller than one from image since I able to reproduce it locally more reliably now :) )
same 5 steps from my previous comment also crashed windows version as well on my machine.

[stack_dump.txt](https://github.com/Vector35/binaryninja-api/files/5526710/stack_dump.txt)

**Comment by psifertex** [comment] 2020-11-11 22:20
Excellent, thanks! Still `2.2.2520`?

**Comment by psifertex** [comment] 2020-11-11 22:22
Also, is this a personal or commercial version? I'll try the exact build/version to see if I can reproduce it and make sure we align the stack trace.

**Comment by grokeus** [comment] 2020-11-11 22:29
2.2.2525-dev Personal, Build ID 47724854 on Windows

Linux stack trace also made at 2.2.2525-dev

**Comment by jeffli678** [comment] 2020-11-12 02:00
I will have a look at this again today

**Comment by jeffli678** [comment] 2020-11-12 06:51
I tested with the exact same version of binja on Linux, and still cannot reproduce it. Since you are the only one who gets a reliable reproduction (at least on your end), I would really like to follow up with the case. Do you have any plugins installed? Also, can you reproduce this with local settings disabled? (Just back up settings.json in the user folder and delete it)

Also, is it possible to make a video for it? I appreciate your repro steps very much, but there could be subtle differences in how we execute the steps, which affect whether we can reproduce it.

**Comment by grokeus** [comment] 2020-11-12 10:10
Try to remove settings.json - crash still exist.
I have installed 'snippets editor' plugins, but disabling/uninstalling didn't change anything...


it seems that pressing H is crucial here - so I guess for now I can just disable keybinding to avoid crashes (it seems that after years in IDA I press it automatically when want to change display type to 'hex')
[crash_video.zip](https://github.com/Vector35/binaryninja-api/files/5529742/crash_video.zip) - one with gdb attached and one without it

**Comment by jeffli678** [comment] 2020-11-12 10:15
I managed to reproduce! thx a lot!

the important thing is to press "ESC" to go back; I pressed 'H' again to go back. That is the difference

**Comment by jeffli678** [comment] 2020-11-12 10:26
I verified the reproduction step is as follows:

1. open 'crash' binary and goto 'prin' function
2. **goto HLIL in Linear view**
3. **set the display type of 0x50447ba756c40 to Character**
4. press 'H' (hex view will be opened)
5. **press 'ESC' (so we will be returnung to HLIL view)**
6. change the display type of the same constant

BN will crash

In step 2, it must be linear view, but it does not have to be HLIL. However, if another IL view is selected. It seems the display will not change according to the selection, but binja does not crash.

In step 3, it does not have to be Character. But it has to be something that has a different display as the default one

**Comment by jeffli678** [comment] 2020-11-16 15:16
fixed in dev 2.2.2539

**Closed by jeffli678** 2020-11-16 15:16 UTC
Labels: bug, crash

**Comment by psifertex** [comment] 2020-11-16 17:10
Please note that there may still be difficulty having "display as" work correctly in this particular workflow, but it will at least no longer crash. We recommend using graph view as a temporary work-around until then. We'll update this bug again when the main display-as functionality is working properly.

**Comment by negasora** [comment] 2020-11-16 20:42
Display-as is fixed in 2.2.2540-dev
