### ISSUE TITLE
odd font size after a period of binary ninja stay in background

### ISSUE THREAD

**Issue by codingsnippets** [Vector35/binaryninja-api#1242] opened 2019-01-12 04:39 UTC
Binary Ninja Version: 1.1.1462-dev Personal, 7fd03575
Platform: Ubuntu 18.04.1 LTS
NOTE: this may not be directly caused by Binary Ninja? Not sure, but following symptoms keeps happening.  (doing more investigation)

There seems to be some odd issues related to the font scaling.
I opened a large binary and waited for Binary Ninja to process it.
I kept the program running in the background for about an hour, 
when I comes back the font are scaling in correctly. (some function 
and graph font are scalled down quite a bit, I can still ctrl + scroll to 
make the graph font bigger but the graph will look huge, and font 
on the function list cannot be scaled back correctly)

Note the inconsistent font size in function list. 

![screenshot from 2019-01-11 23-29-35](https://user-images.githubusercontent.com/2884743/51069271-91e11c80-15f9-11e9-81de-671fa628639d.png)

**Comment by codingsnippets** [comment] 2019-01-12 04:42
this basically renders this program almost useless to me, as personal license user has no caching, I have restart the whole progress......

**Comment by plafosse** [comment] 2019-01-16 19:55
Any chance you unplugged a monitor, or your computer went to sleep, or maybe you moved it to a different monitor? This seems like a dpi scaling issue, and likely caused by QT rather than us.

**Comment by bpotchik** [comment] 2019-02-07 15:25
@codingsnippets can you still reproduce this issue on 1.1.1497-dev?

**Comment by plafosse** [comment] 2021-03-10 20:32
I believe this has been fixed by upgrading our Qt version

**Closed by plafosse** 2021-03-10 20:32 UTC
Labels: bug, ui
