### ISSUE TITLE
Keep C-style Comments in Types Defined with C Structure Editor

### ISSUE THREAD

**Issue by WhatTheFuzz** [Vector35/binaryninja-api#5822] opened 2024-08-04 15:51 UTC
**What is the feature you'd like to have?**
I'm working with a bunch of confusing Objective-C structures for the first time. I define the structures as Types within the C structure editor (via Create Types from C Source, hotkey `I`) or through importing header files. I find myself frequently revisiting my notes about the structures member objects.

It would find it helpful if I could add comments within the structure editor and have them persist within the Binary Ninja type. That way, I could add comments to the structure's members and reference them within Binary Ninja as opposed to referring to external documentation.

Currently, the parser accepts comments, but correctly ignores and discards them.

**Is your feature request related to a problem?**
No, just a feature request.

**Are any alternative solutions acceptable?**
I think just keeping the source text (including comments) would be the easiest option; I'm not sure what an alternative would look like.

**Comment by fuzyll** [comment] 2024-08-04 15:56
Hey, thanks for the feature request. :) We agree! But, I am going to close this as a duplicate of our original request for this feature, which is #1244. Please 👍🏼 and/or subscribe to that  issue when you get a chance.

**Closed by fuzyll** 2024-08-04 15:56 UTC
Labels: State: Duplicate

**Comment by WhatTheFuzz** [comment] 2024-08-04 16:00
Whoops, thanks fuzyll!
