### ISSUE TITLE
Provide Gnome Desktop File

### ISSUE THREAD

**Issue by FireFart** [Vector35/binaryninja-api#565] opened 2016-11-30 21:06 UTC
I created the following Gnome desktop file so binary ninja shows up in the application launcher and has an icon. It would be great if you can include it in the install package or mention it in the docs

```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=Binary Ninja
Comment=Binary Ninja
Exec=/opt/binaryninja/binaryninja
Icon=/opt/binaryninja/logo.png
Terminal=false
```

logo.png was fetched from here: https://docs.binary.ninja/images/logo.png

The file need to go in `~/.local/share/applications/binaryninja.desktop`. After adding restart Gnome with `ALT+F2` + `r`.

Tested on Fedora 25 with Gnome3

**Comment by lucasduffey** [comment] 2016-11-30 21:19
duplicate of https://github.com/Vector35/binaryninja-api/issues/361

**Comment by psifertex** [comment] 2016-12-01 00:13
Closing as a dupe -- thanks to both of you for coming up with this, the main issue has been deciding whether to do an installer, an after-the-fact script to run, as well as implementing this, file associations, and the url handler that the installers on the other two platforms used. 

It shouldn't be too much to implement something to do all of that though, I'll take a look at it again.

**Closed by psifertex** 2016-12-01 00:13 UTC
