### ISSUE TITLE
tabs in a comment can cause incorrect block size calculation

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#1505] opened 2020-01-07 04:11 UTC
<img width="495" alt="Screen Shot 2020-01-06 at 11 01 41 PM" src="https://user-images.githubusercontent.com/140215/71867538-858e8300-30d8-11ea-8e5b-2b4a49f23905.png">

For the comment:
```
the input must be in the format of:
8		4	4	4	12
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

Replacing tabs with four spaces causes the alignment to be correct.

**Comment by jeffli678** [comment] 2020-07-10 09:51
Duplicate of #1234.

**Closed by jeffli678** 2020-07-10 09:51 UTC
Labels: bug
