### ISSUE TITLE
decompiler sometimes fails to identify +offset as member acess

### ISSUE THREAD

**Issue by sum-catnip** [Vector35/binaryninja-api#2409] opened 2021-05-01 11:50 UTC
**Is your feature request related to a problem? Please describe.**
often times i see things like
> *(pstream->vtbl + 8)

because the decompiler sometimes doesn't see the +8 as a member access even tho i've declared  the types correctly.

**Describe the solution you'd like**
The type of pstream is build in a way that the above should actually be
> pstream->vtbl->addref

**Describe alternatives you've considered**
A way to manually turn an offset into a member access would be nice too.

**Additional context**
The places this isn't recognize always have a similar pattern:
```x86asm
mov     rax, qword [rdx {IStream::vtbl}]
mov     rcx, rbx
mov     rax, qword [rax+0x8]  // IStream::AddRef
call    qword [rel guardCFDispatchFunctionPointer]  {guardCFDispatchFunction}
```

First we put the base address into rax, then we do unrealted shit and then we deref the member access.
The whole thing looks like this in HLIL:
```
// IStream::AddRef
*(pstream->vtbl + 8)
guardCFDispatchFunction(pstream)
```
This is a very common pattern in windows binaries that are compiled with a [control flow guard](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=msvc-160).
the `guardCFDispatchFunction` is essentially a `jmp rax` so the code puts pstream->vtbl->addref into rax and pstream into rcx as the first `this` argument. Which is why the whole thing looks kinda funky in HLIL.

**Comment by sum-catnip** [comment] 2021-05-01 11:53
this somewhat relates to #1760 but i think an improved detection of the member access would be a good thing regardless of the cfg, i just happened to notice it in those situations.

**Comment by plafosse** [comment] 2021-05-05 18:28
Are you on the latest dev build? If not could you please try switching builds? If you are on dev could you possibly share a binary? We may be missing an edge case. We can't reproduce this.

**Comment by sum-catnip** [comment] 2021-05-09 18:45
yeah im on the latest dev build and. i reanalyzed the binary with the newest build but i didnt start the project with the newest version, hope that doesnt cause any problems.

I cant publicly upload the binary but i can share it privately if you want.

Ill try to give some more context.
this is a hlil of one of these situations:
```
struct IMFByteStream* bytestream_cpy = bytestream
// HRESULT GetCapabilities(
//   DWORD *pdwCapabilities
// );
// Retrieves the characteristics of the byte stream.
*(bytestream_cpy->vtbl + 0x18)
int32_t errcode = guardCFDispatchFunction(jmp_rax)(bytestream_cpy, &bytestream_capabilities)
```
The types are:
```
struct IMFByteStream __packed
{
    struct IMFByteStream_vtbl* vtbl;
};

struct IMFByteStream_vtbl
{
    struct IUnknown_vtbl iunknown;
    void* get_capabilities; // this is 0x18
```

this is the asm:
```
mov     rcx, qword [rsp+0x68 {bytestream}]
lea     rdx, [rsp+0x60 {bytestream_capabilities}]
mov     rax, qword [rcx {IMFByteStream::vtbl}]
// HRESULT GetCapabilities(
//   DWORD *pdwCapabilities
// );
// Retrieves the characteristics of the byte stream.
mov     rax, qword [rax+0x18]
call    qword [rel guardCFDispatchFunctionPointer]  {guardCFDispatchFunction(jmp_rax)}
```

I found out something interesting tho.
I may be completely stupid but in this context IMFByteStream* would be the same as IMFByteStream_vtbl** because the definition of IMFByteStream makes it just another pointer, right?
Im asking because i just noticed that:
```
struct IMFByteStream_vtbl** bytestream_cpy = bytestream
(*bytestream_cpy)->get_capabilities
int32_t errcode = guardCFDispatchFunction(jmp_rax)(bytestream_cpy, &bytestream_capabilities)
```
works.
I just set bytestream_cpy to IMFByteStream_vtbl** instead of IMFByteStream*

**Comment by plafosse** [comment] 2022-06-22 18:25
This is likely a duplicate of #2730

**Closed by plafosse** 2022-06-22 18:25 UTC
Labels: duplicate, enhancement, Impact: Medium
