### ISSUE TITLE
get_var_uses and get_var_definitions do not work on aliased variables

### ISSUE THREAD

**Issue by cetfor** [Vector35/binaryninja-api#2902] opened 2022-01-30 18:54 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3238-dev (also tried in release 3.0.3233)
- OS: Windows
- OS Version: 10

**Bug Description:**
When analyzing a MIPS big endian ELF, the  `get_var_uses` and `get_var_definitions` methods return empty lists when using HLIL, but return expected results on MLIL.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open binary in UI (or headless)
2. Get a variable reference (type binaryninja.variable.Variable) named var
3. Use `current_hlil.get_var_uses(var)` which produces an empty list.
4. Try again with current_mlil and it returns a populated list of expected results.

**Expected Behavior:**
The return values of `get_var_uses` and `get_var_definitions` should be correct when using an HLIL function.

**Screenshots:**
The following works as expected when using an MLIL function:
![mlil_vart_uses](https://user-images.githubusercontent.com/36994008/151713249-07e03852-42d9-43c8-8aa8-a2224bb3224a.PNG)

The following does not work as expected when using an HLIL function:
![hlil_vart_uses_def](https://user-images.githubusercontent.com/36994008/151713256-9d8e60db-48c0-4631-9ff3-e000e9babf5a.PNG)

**Additional Information:**
I can provide a mips big endian sample if you have issues reproducing.

**Comment by cetfor** [comment] 2022-01-30 19:11
I might be going crazy here - but this seems to work when targeting variables like `$v0_19` and `$s2`, but fails when targeting variables like `var_278` and `var_300`.

**Comment by plafosse** [comment] 2022-03-30 15:44
I've looked into this a bunch today and I don't have good answers but I do understand whats causing this to happen to _some_ variables but not others. The issue is that we determine variable def/use via SSA form, however if a MLIL variable is Aliased no SSAVariable is created and thus there are no entries in the list allowing us to calculate the def/use. I'll be discussing this issue with the team today at our meeting, and hopefully discover how to fix this.

**Comment by D0ntPanic** [comment] 2022-09-08 00:40
Fixed in build 3684

**Closed by D0ntPanic** 2022-09-08 00:40 UTC
Labels: bug, Impact: High
