### ISSUE TITLE
Poor performance on adding large number for types

### ISSUE THREAD

**Issue by riverar** [Vector35/binaryninja-api#834] opened 2017-10-10 18:40 UTC
Binary Ninja Version: 1.1.948-dev, 2aec65fb
Platform: Windows 10

1. Load twinui.dll from 17004 or earlier build of Windows
2. Load PDB
3. Note Binary Ninja eventually hangs the UI and you can't use it

I'm sure it's still working off the ~150MB PDB but it makes using the app impossible. Not much use in running a background task if it's going to hang the main UI thread.

Is code available for the Load PDB plugin?

**Comment by plafosse** [comment] 2018-01-12 02:48
The root cause of this issue is that our type system performs very poorly when adding a large number of types.

**Comment by bpotchik** [comment] 2021-04-06 17:24
This no longer seems to be an issue.

Fixed in 2.3.2731-dev.

**Closed by bpotchik** 2021-04-06 17:24 UTC
Labels: Effort: Medium, Impact: Low, bug, performance
