### ISSUE TITLE
No-return functions give no indication that they do not return

### ISSUE THREAD

**Issue by I-am-Batman** [Vector35/binaryninja-api#169] opened 2016-02-24 22:45 UTC
![bad_cfg](https://cloud.githubusercontent.com/assets/9060943/13303571/2bfe728c-db1e-11e5-9a8f-f962982a7029.png)
the CFG generation is incomplete in a non-obfuscated binary

![good_deadlist](https://cloud.githubusercontent.com/assets/9060943/13303586/33c6e468-db1e-11e5-9641-83dc50f9116a.png)
this is the correct disassembly from GDB

**Comment by plafosse** [comment] 2016-02-24 23:26
The only thing that would cause this is that the usage function is marked no-return.  Is it possible that the usage function unconditionally calls exit?  If not would you be able to provide the binary?

**Comment by I-am-Batman** [comment] 2016-02-25 01:56
[bufbomb.zip](https://github.com/Vector35/binaryninja-docs/files/145803/bufbomb.zip)
The screenshot I provided before is correct (usage leads to an unconditional exit), but parts of the CFG for main are definitely missing (mainly a switch statement). for instance, running `./bufbomb -u ChrMai -n` will execute the a `mov [esp+0x28], 0x5` at 0x080490d2 inside of main, which is not in my graph.

![screenshot from 2016-02-24 20-44-40](https://cloud.githubusercontent.com/assets/9060943/13307217/baa49e58-db37-11e5-9b15-c8700156820b.png)
Binary Ninja

![screenshot from 2016-02-24 20-45-21](https://cloud.githubusercontent.com/assets/9060943/13307222/bfa0bb62-db37-11e5-9355-50f51123ee31.png)
IDA 6.8

**Comment by plafosse** [comment] 2016-02-25 06:05
The jump table detection is a separate issue, see #39.  The issue is that indirect jumps such as `jmp eax` and jump tables used in switch cases such as `jmp [eax+ecx*4]` do not have an trivially calculable jump target.  A forthcoming beta release will help with the jump tables.  

But back to your first issue, I would say that the _real_ problem is that we didn't allow you to know that the analysis knows that the `usage` function does not return.  Rather than closing this issue I will change the title to reflect what we plan to do. Thanks for your submission.

**Comment by psifertex** [comment] 2016-07-20 07:02
Fixed in dev.

**Closed by psifertex** 2016-07-20 07:02 UTC
Labels: enhancement
