### ISSUE TITLE
Please Track Exported Symbols

### ISSUE THREAD

**Issue by clubbingbabyseals** [Vector35/binaryninja-api#1377] opened 2019-06-19 19:46 UTC
Binary Ninja Version: 1.1.1689, 856ac082
Platform: macOS Mojave (10.14)

Can you please track exported symbols and expose that information?

perhaps make it easier to access via an iterator (both imported and exported) functions

**Comment by joshwatson** [comment] 2019-06-19 20:54
They’re in the triage view. You can iterate over them based on the SymbolType

**Comment by plafosse** [comment] 2019-07-03 18:59
This is a duplicate of: #69

**Closed by plafosse** 2019-07-03 18:59 UTC
Labels: duplicate
