### ISSUE TITLE
MIPSEL32 HLIL conditional simplification.

### ISSUE THREAD

**Issue by dfraze** [Vector35/binaryninja-api#1688] opened 2020-05-20 19:05 UTC
This conditional could probably be simplified.

![image](https://user-images.githubusercontent.com/12348497/82486627-2770a400-9aab-11ea-924d-f979b52416bb.png)

[service.zip](https://github.com/Vector35/binaryninja-api/files/4658785/service.zip)
(Load as MIPSEL, base address 0xbfc00000.)

**Comment by plafosse** [comment] 2020-05-20 19:15
Duplicate of this #1642

**Closed by plafosse** 2020-05-20 19:15 UTC
Labels: duplicate
