### ISSUE TITLE
Disabling Tail Call Translation breaks Patch -> Edit Current Line for overlapping functions in linear view

### ISSUE THREAD

**Issue by sabastiaan** [Vector35/binaryninja-api#2214] opened 2021-01-04 00:57 UTC
**Disabling Tail Call Translation breaks Patch -> Edit Current Line **
When disabling the Tail Call Translation option, if you create an embedded function inside another function, then 
Patch -> Edit Current Line does not change the displayed instruction text into an input box anymore.
This functionally does remain working for the parent/root function. 

**To Reproduce**
1. Open any x64 binary with Tail Call Translation option disabled
2. Go to any identified function which has multiple instructions (__lib_c_init works), this will be referred to as the parent function
4. create a function inside the parent function, let this function be called the child function
5. Press E, or click Patch -> Edit Current Line for any of the instructions inside the child function

**Expected behavior**
The instruction text to change into an input box

**Desktop (please complete the following information):**
- OS: Ubuntu Linux
- Version 20.04
- Version 2.2.2587-dev, also happens in non-dev releases

**Comment by jeffli678** [comment] 2021-01-07 02:51
@sabastiaan Thanks for the report! However, I cannot reproduce it on my end. If you would like, please provide any binary that you can reproduce this with, or better, record a video for it. I believe some subtle differences in the way we follow the procedures lead to the result that I cannot reproduce it

**Comment by sabastiaan** [comment] 2021-01-09 01:04
I created a [little video](https://www.youtube.com/watch?v=lOnl1mibdgQ&feature=youtu.be) showcasing the bug. This works on any binary on my end. Let me know if you need more information

**Comment by jeffli678** [comment] 2021-01-10 06:29
Thanks, I am now able to reproduce it! I will try to fix it when available

**Comment by jeffli678** [comment] 2021-01-11 05:12
fixed in dev 2.2.2595

**Closed by jeffli678** 2021-01-11 05:12 UTC
Labels: bug, ui
