### ISSUE TITLE
binary ninja doesn't correctly identify glibc function call

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#460] opened 2016-09-08 22:05 UTC
binary: http://pwnable.kr/bin/bof

picture: https://goo.gl/photos/qBAU3vCUsomB5G8q7

if I click any of the unlabeled functions it just says "fc cld"

**Comment by psifertex** [comment] 2016-09-08 22:18
Dupe of #5

**Closed** 2016-09-08 22:18 UTC
