### ISSUE TITLE
Function comments may corrupt bndb

### ISSUE THREAD

**Issue by Tcc100** [Vector35/binaryninja-api#5271] opened 2024-04-12 14:32 UTC
**Version and Platform:**
- Binary Ninja Version: 4.1.5071
- OS: Linux
- CPU Architecture: amd64

**Bug Description:**
Function comments may corrupt the bndb, such that further saving is impossible.

The error message is not consistent, e.g.:
- `[Default] Error while saving database snapshot: IsString()`
- `[Default] Error while saving database snapshot: IsObject()`
- `[Default] Error while saving database snapshot: IsArray()`
- `[Default] Error while saving database snapshot: GetType() == kNumberType`
- sometimes even SEGFAULTs

**Steps To Reproduce:**
- create bndb
- open and set comments
- try to save
- see errors

```py
import binaryninja

elf = "wine"

with binaryninja.load(f"/bin/{elf}") as bv:
    bv.update_analysis_and_wait()
    print("Saving BNDB")
    bv.create_database(f"/tmp/{elf}.bndb")

with binaryninja.load(f"/tmp/{elf}.bndb") as bv:
    for f in bv.functions:
        f.comment = "comment"
        if not bv.save_auto_snapshot():
            break
```

**Additional Information:**
Other versions tested:
- 4.1.4920 ok
- 4.1.4942 ok
- 4.1.4963 ok
- 4.1.4986 error
- 4.1.5041 error
- 4.1.5071 error

Silently corrupted bndbs may also prevent saving in other versions.

**Comment by negasora** [comment] 2024-04-12 14:46
Duplicate of https://github.com/Vector35/binaryninja-api/issues/5267

**Closed by negasora** 2024-04-12 14:46 UTC
