### ISSUE TITLE
Analysis freeze

### ISSUE THREAD

**Issue by Metalnem** [Vector35/binaryninja-api#724] opened 2017-07-01 11:04 UTC
Binary Ninja Version: 1.0.776, 6573250f
Platform: OS X 10.12
Binary: [libBookshelf.so.zip](https://github.com/Vector35/binaryninja-api/files/1117009/libBookshelf.so.zip)

Analysis started to freeze each time for the attached file since the latest update on 2017-06-26. It was working fine in the previous version.

**Comment by psifertex** [comment] 2017-07-04 02:38
Thanks -- this is likely the result of a bug where we're making both thumb2 and armv8 functions at the same location and the wrong architecture is generating lots of spurious code blogs (some of which are blowing up our data flow). We've seen a few other test cases that caused it, but having another one is always helpful.

FWIW, you can always revert to the previous version with [version_switcher.py](https://github.com/Vector35/binaryninja-api/blob/dev/python/examples/version_switcher.py) though the root cause of the problem will still be there. The only difference is we had heuristics to stop dataflow analysis for extremely large broken blocks which prevented the bug from causing further failures.

**Comment by Metalnem** [comment] 2017-07-04 14:09
Thanks, I was going to ask if something like this exist. By the way, is there a way to abort the analysis process (like a function in the API or something like that)?

**Comment by bpotchik** [comment] 2017-12-06 08:32
Completed analysis on this binary in about 30 minutes. Fixed in build 1.1.1018-dev.

**Closed by bpotchik** 2017-12-06 08:32 UTC
Labels: core
