### ISSUE TITLE
Example plugins should be mentioned in plugins repo

### ISSUE THREAD

**Issue by sheadovas** [Vector35/binaryninja-api#1357] opened 2019-05-31 12:59 UTC
Vector35 have 2 repos for plugins:
- [community](https://github.com/Vector35/community-plugins)
- [official](https://github.com/Vector35/official-plugins)

Aaand special directory for example plugins `$BINJA_INSTALL_PATH/examples/python` - I didn't know about this directory, some of these plugins are much more than simple api examples, some should be actually enabled by default in binja (in my opinion) or at least moved to separate repo (one of above), because it is very easy to overlook them.

Additionally they should be also a bit better described, because description is often only saying what API functionality this plugin is showing or there is lack of description (example: `kaitai` plugin).

Short summary:

- plugins should be mirrored to separate repo or mentioned in *repo plugin list*
- description of example plugins should contain detailed info about functionality
- some of the plugins should be enabled by default
- I believe that we need some nice Plugin Manager (like this from Ghidra)  (I'm not sure which features will be introduced by #480 ) -> this possibly can be actually done by writing a plugin ;)

**Comment by psifertex** [comment] 2019-06-11 22:41
I've updated the documentation on the official repository that helps make the included ones more discoverable, but otherwise this is basically a duplicate of  #480 which you've already noted.

That's actually most of the way to complete and just needs some additional testing (it requires updating plugins to a slightly new format so we're trying to make sure we have sufficient documentation/examples to ease the transition). That should help tremendously with discoverability of all sources of plugins, both official and community-based.

**Closed by psifertex** 2019-06-11 22:41 UTC
