### ISSUE TITLE
Transform and Copy As->Hash->Sha256 submenus calculates broken data

### ISSUE THREAD

**Issue by johdcmlaker2000** [Vector35/binaryninja-api#2781] opened 2021-12-15 11:54 UTC
Transform and Copy As->Hash->Sha256 submenus calculates broken data

**To Reproduce**
1. Open new Hex view
2. Add new 0x33 byte
3. Select byte
4. Click on Transform or Copy As->Hash->Sha256 submenus

**Expected behavior**
Must return "4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce" hash, but got broken random data

**Screenshots**
![image](https://user-images.githubusercontent.com/95555363/146182023-9a3090b4-ccab-4433-9681-a73461e31960.png)

**Version and Platform (required):**
 - Binja Version 2.4.2846 (Build ID df7c027e)
 - OS: Windows 10 Pro x64
 - Version 10.0.19042.1165

**Comment by psifertex** [comment] 2021-12-15 15:30
Hmm, I can't reproduce this. 
```
>>> rawhex=Transform['RawHex']
>>> sha256=Transform['SHA256']
>>> rawhex.encode(sha256.encode("3"))
b'4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce'
```

And the same thing when I try from the UI. In fact, despite my comment in slack, the transform works for me too.

I've tested on MacOS and Windows on both latest dev and latest stable in the console and in the UI and all work for me. Can you maybe produce a short video showing the exact workflow? I've tried using the command-palette, the copy menu and the right-click menu and all work for me with the expected result.

**Comment by johdcmlaker2000** [comment] 2021-12-15 17:02
https://user-images.githubusercontent.com/95555363/146231251-6e8744fc-c3b1-402b-b263-f2ec4fe29878.mp4

**Comment by psifertex** [comment] 2021-12-15 17:43
Thanks! That's so strange. I can try _exactly_ that that and it works as expected with the correct value.

Please try the following troubleshooting steps:

1) Launch Binary Ninja with the `-p` command-line flag which will disable all plugins and settings
2) Re-install or switch to the development branch.

**Comment by johdcmlaker2000** [comment] 2021-12-15 21:03
launched bn without plugin - no changes
renamed settings file - no changes
updated bn to last dev Version 2.5.3129-dev (Build ID 9038e9f1) - no changes

BTW it's ok when hashing data with MD5 hash function (on 2.5.3129-dev too), 

it's ok when hashing data with SHA512 hash function

garbage generates when using sha256

BN craches trying to transform data with SHA1 hash function

**Comment by johdcmlaker2000** [comment] 2021-12-15 21:07
https://user-images.githubusercontent.com/95555363/146265056-1ccba211-71ef-4368-a3b9-e87f6de201cd.mp4

**Comment by johdcmlaker2000** [comment] 2021-12-20 22:00
After rebooting the system the bug still appears, and the hash result is the same, it is not random garbage.
Can I debug the process or in some other way help to reproduce the bug?

**Comment by johdcmlaker2000** [comment] 2021-12-21 02:09
crashdump RIP data

```
cryptoplugin:00007FFEDE314163 movaps  xmm6, xmmword ptr [rax-48h]
cryptoplugin:00007FFEDE314167 movaps  xmm7, xmmword ptr [rax-38h]
cryptoplugin:00007FFEDE31416B movaps  xmm8, xmmword ptr [rax-28h]
cryptoplugin:00007FFEDE314170 movaps  xmm9, xmmword ptr [rax-18h]
cryptoplugin:00007FFEDE314175 mov     rsp, rax
cryptoplugin:00007FFEDE314178 mov     rdi, [rsp+8]
cryptoplugin:00007FFEDE31417D mov     rsi, [rsp+10h]
cryptoplugin:00007FFEDE314182 rep retn
```

**Comment by jeffli678** [comment] 2021-12-21 02:17
Thanks for the detailed information. I will have a look at it later today. Hopefully I will be able to reproduce it.

**Comment by xusheng6** [comment] 2021-12-21 14:40
I also tried several combinations and cannot reproduce it.

**Comment by psifertex** [comment] 2022-02-09 20:43
Can you confirm that this issue still reproduces for you? We've been unable to reproduce it on our side which makes it unfortunately really hard to fix. I'm closing this as "can't reproduce" for now, but if you still continue to have issues, definitely feel free to re-open. I do recommend waiting a bit to try the latest QT update which will be on dev in a few weeks.

**Closed by psifertex** 2022-02-09 20:43 UTC
Labels: bug, Can't Reproduce
