### ISSUE TITLE
Making a pointer (O) doesn't always work on function arguments

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4338] opened 2023-05-23 15:11 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4286-dev, 58311b01
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

'O' doesn't work on the last argument here

```
0000f088                  r0_17, r2_10, r3_7 = sub_71b4c(9, 0x16, r2_9, 0x2005dccc)
```

but making the last argument of `sub_71b4c` a pointer does.

```
0000f088                  r0_17, r2_10, r3_7 = sub_71b4c(9, 0x16, r2_9, &data_2005dccc)
```

Trouble is, this is not consistent, e.g. 'O' works fine in similar situations, even though the argument is a regular int.

My hunch is this may have to do with the last argument to a function. I have not had to re-type function arguments in other positions. 

Anyone from V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by fuzyll** [comment] 2023-05-24 15:50
Duplicate of #4339.

**Closed by fuzyll** 2023-05-24 15:50 UTC
Labels: State: Duplicate
