### ISSUE TITLE
BinaryView links from html reports don't work for Fat Mach-O

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#1515] opened 2020-01-29 17:56 UTC
This has been reported but as of yet unverified.

**Comment by psifertex** [comment] 2020-01-29 19:41
This is not a bug but could use some improved documentation. The trick is that there are two show_html_report APIs and you have to call the one associated with the BinaryView to have the associated view linkable. 

The fix is to better document those two functions to be clear that linking only works when associated.

**Comment by bpotchik** [comment] 2020-08-03 04:18
Fixed in 2.1.2295-dev.

**Closed by bpotchik** 2020-08-03 04:18 UTC
Labels: bug
