### ISSUE TITLE
Support for multiple identical symbols at different addresses.

### ISSUE THREAD

**Issue by fluxchief** [Vector35/binaryninja-api#611] opened 2017-02-05 13:13 UTC
It seems that binja does not handles all PE imports correctly (see screenshot below).

![bin](https://cloud.githubusercontent.com/assets/2988703/22626414/1536605a-ebad-11e6-9cb5-5d0c6bac905b.png)

The file can be found in issue #561

**Comment by plafosse** [comment] 2017-02-09 20:27
The root cause of this is that the entries marked as `data_<hex>` are symbols that have already been imported, currently we only support a single symbol name per binary. Unfortunately the fix for this isn't straight forward, or else I would have already fixed it. I'm changing the name to reflect the true nature of the bug.

**Comment by bpotchik** [comment] 2021-04-06 17:23
Duplicate symbol support now exists.

Fixed in 2.3.2731-dev.

**Closed by bpotchik** 2021-04-06 17:23 UTC
Labels: Effort: Low, Impact: Medium, bug, enhancement
