### ISSUE TITLE
some instructions are not implemented in LLIL

### ISSUE THREAD

**Issue by nitrogar** [Vector35/binaryninja-api#3644] opened 2022-11-08 14:10 UTC
**Version and Platform (required):**
latest
- OS: linux
- CPU Architecture x64 

**Bug Description:**
![Screenshot 2022-11-08 170701](https://user-images.githubusercontent.com/53944555/200586546-4178af05-3dbf-4b27-ba19-a5ade26e3d05.png)
![Screenshot 2022-11-08 170713](https://user-images.githubusercontent.com/53944555/200586556-660414b5-5d95-4070-a645-df28ae26afca.png)

**Comment by plafosse** [comment] 2023-01-09 18:32
Thanks for the report. This is a duplicate of this issue: https://github.com/Vector35/arch-x86/issues/16

**Closed by plafosse** 2023-01-09 18:32 UTC
Labels: duplicate
