### ISSUE TITLE
Floating Sidebar widgets do not stay on top on Windows

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#6085] opened 2024-11-05 01:57 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6345-dev Ultimate (2f4145a2)
- OS: Windows
- OS Version: 11 23H2

**Bug Description:**
When sidebar widgets are put in "Floating" mode, they do not also remain on top, making them hard to refocus if the floating widget gets covered by any other window (including Binary Ninja and other widgets).

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Right click on any sidebar widget's icon, select "Floating"
2. Observe the sidebar widget pop out
3. Click on the main window
4. Observe the sidebar widget get covered and the only way to reactivate it is to uncover it, or click its icon twice to hide and show it.

**Expected Behavior:**
Sidebar widgets in Floating mode should be always-on-top (like they are on macOS)

**Comment by plafosse** [comment] 2024-11-07 13:07
Duplicate of https://github.com/Vector35/binaryninja-api/issues/5105

**Closed as completed by plafosse** 2024-11-07 13:07 UTC
Labels: State: Duplicate
