### ISSUE TITLE
Can't start search with certain characters in Strings View

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#1717] opened 2020-05-26 19:34 UTC
Searching for a string in the Strings View that starts with either `r`, `x` or `backtick` does not start searching and in some cases moves focus preventing the ability to search. 

* `r` will not start search but any keys after it will work
* `x` makes it so no proceeding keys will start search (i'm guessing focus is lost from strings view) 
* `backtick` will move focus to python console

**Comment by psifertex** [comment] 2020-05-26 19:46
Sadly, a dupe of #1533

**Closed by psifertex** 2020-05-26 19:46 UTC
