### ISSUE TITLE
Automatically make comment to WinAPI / functions arguments. 

### ISSUE THREAD

**Issue by 0xBinarySl3uth** [Vector35/binaryninja-api#5363] opened 2024-05-05 14:48 UTC
**What is the feature you'd like to have?**
Automatically make comment to WinAPI / functions arguments. 

![image](https://github.com/Vector35/binaryninja-api/assets/121362809/56538bd2-9fbd-41e4-8919-6ab60c08e629)

![image](https://github.com/Vector35/binaryninja-api/assets/121362809/65638363-d546-484f-9b87-0f7d8e5fc699)

**Comment by psifertex** [comment] 2024-05-05 14:52
I believe this is a duplicate of https://github.com/Vector35/binaryninja-api/issues/237

sorry I didn't get that url sooner. :-)

**Closed by psifertex** 2024-05-05 14:52 UTC
