### ISSUE TITLE
free version shows the changelog

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5122] opened 2024-02-27 21:12 UTC
It's hidden on initial load but pops back up later

**Comment by psifertex** [comment] 2024-02-27 21:14
To reproduce, open a new tab and close it.

**Comment by xusheng6** [comment] 2024-03-05 06:31
Also fixed by https://github.com/Vector35/binaryninja/commit/b48902b69b3c297c38430ab4566a4817775424c9. In fact, this has the same root cause as https://github.com/Vector35/binaryninja/issues/659

**Comment by plafosse** [comment] 2024-03-19 17:08
Fixed in 4.0.4958-stable

**Closed by plafosse** 2024-03-19 17:08 UTC
Labels: Type: Bug, UI: New Tab
