### ISSUE TITLE
multi-select in graph and linear view

### ISSUE THREAD

**Issue by CryptXor** [Vector35/binaryninja-api#91] opened 2016-01-21 07:35 UTC
I do not know if it is just me, or if it is something on the to-do list, but selection of anything seems impossible?

What I mean is similar to selecting lines out of notepad, dragging to highlight/etc

Is it an issue or something that has yet to be implemented?

**Comment by psifertex** [comment] 2016-01-21 08:17
This is currently by design. We do plan on having some selecting mechanisms, but haven't decided exactly how yet.

**Comment by psifertex** [comment] 2016-07-28 05:51
Changed the subject to better match what we're tracking with this report.

**Comment by psifertex** [comment] 2019-04-13 15:37
This is complete for graph views on builds 1594 and newer. Leaving open to track linear view.

**Comment by melomac** [comment] 2019-04-16 18:48
About merging #1325, please note that Ctrl + END key doesn't work in Graph view too.

**Comment by psifertex** [comment] 2019-04-19 00:53
@melomac Ctrl + END works in Graph view as of versions >=1611.

**Comment by psifertex** [comment] 2019-05-29 18:48
Closing this out -- there is one design limitation in that the selection only allows for single basic blocks for now. At some point we'll expand this, but this is the feature as we intend it to exist in 1.2.

**Closed by psifertex** 2019-05-29 18:48 UTC
Labels: enhancement, ui
