### ISSUE TITLE
Unable to create new structure in filtered Type View

### ISSUE THREAD

**Issue by inspier** [Vector35/binaryninja-api#2356] opened 2021-04-06 19:38 UTC
I am currently unable to create a new structure without specifying the size in the filtered types view set to only User Types. Doing so results in the application crashing.

Build: v2.3.2731-dev
Build ID: ee7f8d75

**Comment by negasora** [comment] 2021-04-09 22:12
I can't reproduce this on 2.3.2738-dev

**Comment by negasora** [comment] 2021-04-12 19:47
Fixed in 2.3.2741-dev

**Closed by negasora** 2021-04-12 19:47 UTC
Labels: bug, crash
