### ISSUE TITLE
int128_t data is not rendered correctly

### ISSUE THREAD

**Issue by nitrogar** [Vector35/binaryninja-api#4706] opened 2023-10-25 21:03 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4596-dev
- OS: Manjaro
- CPU Architecture: x64 
- 
**Bug Description:**
the values of int128_t variables in the data section is not rendered and left blank

**Screenshots:**
 the values as int128_t
![image](https://github.com/Vector35/binaryninja-api/assets/53944555/6b52401f-db8f-477e-9a5f-5e43407a7127)

after changing it to int64_t 
![image](https://github.com/Vector35/binaryninja-api/assets/53944555/d17e2b68-e460-4995-882a-e097ed290f94)

the executable is flareon third challenge.

**Comment by fuzyll** [comment] 2023-10-25 21:31
Closing as duplicate of #4059. But, thanks for the extra test case!

**Closed by fuzyll** 2023-10-25 21:31 UTC
Labels: State: Duplicate
