### ISSUE TITLE
Selected token not persisted after rename

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4416] opened 2023-06-14 18:09 UTC
When renaming a function, variable, etc., the selected token is not persisted after the name change completes. For example:

1. Select a variable, function, or anything with a name
2. Hit 'N' and rename it, choosing a name that differs from the original
3. (Pretend you made a typo and want to fix the name)
4. Hit 'N' again (as if to rename the same thing a second time)
5. Notice nothing happens because the selection was cleared when the rename occurred

I would expect that the selection persists so that hitting 'N' in step 4 works as expected.

**Comment by jonpalmisc** [comment] 2023-06-15 18:32
Another bit to add: this also affects creating struct fields with the 'S' hotkey—you can't immediately hit 'N' after to name the field without re-selecting it.

**Comment by plafosse** [comment] 2023-06-20 01:23
Duplicate of #1086

**Closed** 2023-06-20 01:24 UTC
Labels: Type: Bug, State: Duplicate, Component: UI, Impact: Low, Effort: Trivial
