### ISSUE TITLE
Assembly to HLIL address mapping is incorrect

### ISSUE THREAD

**Issue by mahaloz** [Vector35/binaryninja-api#2898] opened 2022-01-29 04:02 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3234-dev
- OS: MacOS
- OS Version: 12.1

**Bug Description:**
When trying to understand what instruction address mapps to what HLIL instructions, the API and mapping provided by Binary Ninja returns incorrect results. 

**Steps To Reproduce:**
Attached is the binary `objdump_2`, which is the objdump from Ubuntu 20.04. When loading the binary into Binary Ninja and using the lines below, you will get incorrect HLIL lines returned:
```python
addr = 0x933b
func = bv.get_functions_containing(addr)[0]
decomp_lines = func.get_low_level_il_at(addr).hlils
print(decomp_lines) # this is incorrect, correct line is <HLIL_CALL: setlocale(0, &data_46ea3)>
```

Usually after using those lines, you are left with something you can lookup in `func.hlil.instructions`, but the returned objects in the list is not something that exists in `func.hlil.instructions`

To make things more concise, the above thinks mapping:
```
xor     edi, edi  {0x0}
lea     rsi, [rel data_46ea3]
call    setlocale
```
To
```
setlocale(category: 0, locale: &data_46ea3)
```
Is incorrect. 

**Expected Behavior:**
When running the python snippet above, one of the returned objects in the list should be `<HLIL_CALL: setlocale(0, &data_46ea3)>`. 

[objdump_2.zip](https://github.com/Vector35/binaryninja-api/files/7962925/objdump_2.zip)

**Comment by psifertex** [comment] 2022-01-29 04:16
```
>>> addr = 0x933b
... func = bv.get_functions_containing(addr)[0]
... h = func.get_low_level_il_at(addr).hlils[0]
... print(h.instr)
... 
setlocale(0, &data_46ea3)
```
I believe this is "as intended". Remember, HLIL has lots of code folding going on and in this case the parameter is part of a different higher level expression.

In this case, you can either grab `expr_index` or grab `.instr` from the `hlil` to get back the higher level instruction as i showed above.

**Comment by mahaloz** [comment] 2022-01-29 06:49
@psifertex I see. I suppose this should turn into an enhancement request then, since it is proving to be a little less than trivial to get the mapping from an instruction address to a HLIL line. I'll play around with the `.instr`

**Comment by psifertex** [comment] 2022-01-29 15:15
I think accessing `.instr` is pretty trivial!  Closing for now, but feel free to re-open if it doesn't work for you.

**Closed by psifertex** 2022-01-29 15:15 UTC
