### ISSUE TITLE
Comments added in the disassembly does not always show up in HLIL

### ISSUE THREAD

**Issue by BlasterXiao** [Vector35/binaryninja-api#5947] opened 2024-09-24 07:56 UTC
binary ninja 4.2.6096-dev presonal(a79d2bf7)
windows 11 x64

You can check the comment issue yourselves, the latest version of dev
![image](https://github.com/user-attachments/assets/9a6dbf44-8a1b-4940-87a7-236b5135e104)

**Comment by plafosse** [comment] 2024-09-24 15:00
can you share the binary that this is occurring in?

**Comment by BlasterXiao** [comment] 2024-09-25 01:25
> can you share the binary that this is occurring in?

You can experiment yourself, write multiple nested switches or if-else statements, then compare the disassembly and hil, and you'll see

**Comment by BlasterXiao** [comment] 2024-09-25 01:39
@xusheng6 Are you trying to find an excuse to solve the problem? This is clearly an issue with your software, yet you're saying that the disassembly comments are not always displayed in HLIL. If the comments aren't shown, what's the point of having them? If there's a problem, just solve it. Why do you keep making so many excuses and reasons? Instead of spending time making excuses, why not improve the product? (Besides, I'm just a customer who purchased the software, not your bug-finding personnel. Please solve the problems yourselves instead of always letting customers discover and report issues, and then you don't even bother to fix them, okay?)

**Comment by xusheng6** [comment] 2024-09-25 01:48
> @xusheng6 Are you trying to find an excuse to solve the problem? This is clearly an issue with your software, yet you're saying that the disassembly comments are not always displayed in HLIL. If the comments aren't shown, what's the point of having them? If there's a problem, just solve it. Why do you keep making so many excuses and reasons? Instead of spending time making excuses, why not improve the product? (Besides, I'm just a customer who purchased the software, not your bug-finding personnel. Please solve the problems yourselves instead of always letting customers discover and report issues, and then you don't even bother to fix them, okay?)

I set that as the issue title, which gives more information and better describes the bug. The bug itself is the comment should always show up, but yet it does not do so

**Comment by CouleeApps** [comment] 2024-09-25 01:52
Similar: #2728

**Comment by xusheng6** [comment] 2024-09-25 01:53
As a workaround, if you add the comment in the HLIL, it should show up in the disassembly. This is related to the internal mapping of the different layers of the ILs, and unfortunately it is not a trivial problem to fix

**Comment by plafosse** [comment] 2024-10-10 18:01
Ultimately this is a duplicate of #2728 which is slated for the current release

**Closed as completed** 2024-10-10 18:01 UTC
Labels: State: Duplicate, Effort: Medium, Impact: Medium, UI: Linear
