### ISSUE TITLE
Save prompt on exit

### ISSUE THREAD

**Issue by tykind** [Vector35/binaryninja-api#3366] opened 2022-08-08 04:26 UTC
Binary Ninja Version: 3.1.3610-dev Personal, c644592d
Platform: Windows 11 Version 2009

Because losing everything is so easy, it would be helpful to have a save prompt before quitting the program. 
(Also an option to disable this for the people who don't like it)

**Comment by psifertex** [comment] 2022-08-08 05:05
It already does -- if you've made any changes to either the file or analysis you are be prompted. Are you not seeing that happen?

**Comment by tykind** [comment] 2022-08-08 14:49
That's strange, I never got it. After adding types, editing names, and args I get no prompt asking me to save. It just exit's the program instantly without any prompt/warning asking to save at all.

**Comment by fuzyll** [comment] 2022-08-08 14:58
Just tried the following on Windows 11 with 3.1.3608-dev Commercial and could not reproduce the issue - what am I doing differently?

1. Open new file
2. Change 3 function names
3. Change 3 function prototypes to have new types
4. Add a new type

Both hitting the X in the top-right and doing File -> Quit produced a dialog box for me:

![image](https://user-images.githubusercontent.com/607452/183448519-fb31944b-01b8-4916-a9de-276919404092.png)

**Comment by tykind** [comment] 2022-08-08 15:59
That's strange, the prompt show's now. But before it didn't, I'm not sure what causes it not to save, this happened multiple times apart from yesterday.  Added types, function names and renamed args as stated.

**Comment by psifertex** [comment] 2022-08-08 16:16
Very strange -- we haven't seen that before. I'm closing this for now as "can't reproduce" but definitely keep an eye out and if you're able to reproduce it again let us know as that is a potentially very serious bug.

**Closed by psifertex** 2022-08-08 16:16 UTC
Labels: enhancement
