### ISSUE TITLE
Show function prototype for imported functions on hovering

### ISSUE THREAD

**Issue by kevre91** [Vector35/binaryninja-api#3295] opened 2022-07-19 18:39 UTC
BN shows function preview when hovering on function names. But when hovering on a function that is imported from another library, BN shows hex dump of the import table, I guess. 

Wouldn't be better if BN preview function prototype in this example?

![hover](https://user-images.githubusercontent.com/109617473/179824087-37f9ee9f-e942-4b61-a0ca-d1236df96007.png)

**Comment by plafosse** [comment] 2022-08-01 17:55
Duplicate of: #1175

**Closed by plafosse** 2022-08-01 17:55 UTC
Labels: duplicate, enhancement
