### ISSUE TITLE
New semantics not registered by calling update_analysis_and_wait a second time.

### ISSUE THREAD

**Issue by quend** [Vector35/binaryninja-api#1293] opened 2019-03-07 03:29 UTC
After recovering a function address and marked its segment as ReadOnlySemantics, “update_analysis_and_wait” used to find the function and all sub-functions would auto-populate.

Calling update_analysis_and_wait does not ‘recover’ the main function even though it is marked appropriately. 

Worked in 1.1.1344 
Fails in 1.1.656-test

**Comment by plafosse** [comment] 2019-03-07 04:57
The root cause of this should be fixed in v1.1.1540

**Closed by plafosse** 2019-03-07 04:57 UTC
