### ISSUE TITLE
Python console autocompletition overlays over other programs if switching to another program during selection

### ISSUE THREAD

**Issue by fuomag9** [Vector35/binaryninja-api#2061] opened 2020-10-24 16:51 UTC
As per title, if you try to use autocompletition and "leave it there" and switch to another program in the meantime it will overlay over the other program (for a bit, then the overlaying will disappear unless interacted with it again)
![image](https://user-images.githubusercontent.com/1580624/97087340-9be6da80-1629-11eb-909a-cc65201d486f.png)

This is happening in `Version 2.2.2487 Personal`

**Comment by psifertex** [comment] 2020-10-24 17:06
What platform are you using? I can't reproduce this on MacOS on the latest stable. These bugs have cropped up in the past and were usually QT bugs fixed by newer QT versions. How are you switching? Just Alt-Tab/Cmd-Tab?

**Comment by fuomag9** [comment] 2020-10-24 17:08
> What platform are you using? I can't reproduce this on MacOS on the latest stable. These bugs have cropped up in the past and were usually QT bugs fixed by newer QT versions. How are you switching? Just Alt-Tab/Cmd-Tab?

I'm on windows 10, I'm switching just by changing programs via the task bar

**Comment by psifertex** [comment] 2020-10-26 18:46
Thanks -- we were able to reproduce it with that info and have a fix in latest dev. Builds  >=2494 should resolve this.

**Closed by psifertex** 2020-10-26 18:46 UTC
Labels: bug, ui
