### ISSUE TITLE
UI Crash when scrolling settings with app font = 15

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#3078] opened 2022-04-20 19:56 UTC
It looks like that for builds using Qt 6.2.4 or 6.3.0, if you set the app font size to 15 and scroll in the settings view, you can crash the whole app.

It may be possible to crash at other font sizes, but it appears fairly consistent at 14, 15. More investigation is needed to figure out where

**Comment by D0ntPanic** [comment] 2022-04-20 20:37
The root cause of this is `settingsview.cpp:1331`. The hover action is used to update the selection, which *must not* be called from a paint routine in Qt 6.2 onwards. The hover handling must be moved out of the paint handler to fix this.

**Comment by bpotchik** [comment] 2022-04-20 21:18
Fixed in `3.0.3358-dev`.

**Closed by bpotchik** 2022-04-20 21:18 UTC
Labels: bug, ui, crash
