### ISSUE TITLE
Opening a .bndb after upgrading causes binja to consistently crash during re-analysis

### ISSUE THREAD

**Issue by riskydissonance** [Vector35/binaryninja-api#5636] opened 2024-06-19 21:45 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.15546-dev
- OS: Windows
- OS Version: 11 23H2
- CPU Architecture: x64

**Bug Description:**

I have a .bndb from `4.0.4958` that causes binja to hang and then (eventually, after 5-10 mins) crash when I try to load it on `4.15546-dev` after it starts re-analysing. 

Attaching a debugger is incosistent, first time I tried it it states it's a an access violation at `binaryninjacore.dll:$11DC947` because the value of `rax` is not a valid memory address.

Second time was because it was trying to execute instructions on a RW page.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
- Open the .bndb and wait.

**Expected Behavior:**
- Analysis to complete successfully.

**Screenshots/Video Recording:**

First crash:
![image](https://github.com/Vector35/binaryninja-api/assets/20513519/e0a4918d-f5c1-4677-b5d6-9ea3d73c2d0b)
![image](https://github.com/Vector35/binaryninja-api/assets/20513519/f87d48c7-7454-4e0b-b653-81d283a6f8cd)

Second crash:
![image](https://github.com/Vector35/binaryninja-api/assets/20513519/8801f446-5065-4652-a385-76e9180200e0)
![image](https://github.com/Vector35/binaryninja-api/assets/20513519/51053db6-3962-419a-b589-9fd1352f77b8)
![image](https://github.com/Vector35/binaryninja-api/assets/20513519/5396f889-78bc-42ea-9e49-1e8d5012ce7c)

...etc.

**Binary:**
I've provided the .bndb to glenns on slack (from RiskyDissonance, 2024-06-19 @ 21:14 UTC)

**Additional Information:**

**Comment by emesare** [comment] 2024-06-20 14:18
Fixed in `4.1.5553-dev`, thank you for the detailed crash report!

**Comment by emesare** [comment] 2024-06-20 14:41
Unfortunately your crash was unrelated to the one I fixed, sorry for the confusion

**Comment by CouleeApps** [comment] 2024-06-21 02:10
User reported being on an Intel 14900K CPU, and the crashes are looking very similar to #5449. Indeed, when they tried switching the worker thread count to 4 (as was the workaround in https://github.com/Vector35/binaryninja-api/issues/5449#issuecomment-2136587290 ) it sounds like the crashes stopped. Closing this for now as a duplicate of #5449 for now and we shall eagerly await Intel fixing this with a microcode patch or something.

**Closed by CouleeApps** 2024-06-21 02:10 UTC
