### ISSUE TITLE
Binary Ninja loses track of the stack due to 64-byte stack alignment 

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#5230] opened 2024-04-02 16:45 UTC
### Discussed in https://github.com/Vector35/binaryninja-api/discussions/5102

<div type='discussions-op-text'>

<sup>Originally posted by **itewqq** February 23, 2024</sup>
I'm new to binja, but I'm finding that both the pseudo-C code and the High level IR have a large number of stack pointer offset based results that are very difficult to sort out in the code:
![image](https://github.com/Vector35/binaryninja-api/assets/30570177/b4dd0978-d7f1-4583-8230-115459cbc0bc)

Is there a good way to rename them or make them local variables? In IDA we can change the function property to BP-Based Frame and it will automatically gives a label to each stack variable. How to make it happen in Binja?
![image](https://github.com/Vector35/binaryninja-api/assets/30570177/0651d696-aa55-4103-9a2c-c1303ec66494)
</div>

**Comment by xusheng6** [comment] 2024-04-03 07:45
Duplicate of https://github.com/Vector35/binaryninja-api/issues/3033. I am keeping this newer issue open because it has better info (triage & binary)

**Comment by xusheng6** [comment] 2024-04-03 07:51
It seems we do not always fail for such cases -- attached is the helloworld binary from our debugger unit test. It is Linux-x86, and we can see the stack pointer offset after the alignment is reported as 0x0:

[helloworld.zip](https://github.com/Vector35/binaryninja-api/files/14848684/helloworld.zip)

![Screenshot 2024-04-03 at 3 51 26 PM](https://github.com/Vector35/binaryninja-api/assets/94503187/a2c5efb4-231b-41ad-ae75-f8d7d15b99d0)

**Comment by xusheng6** [comment] 2024-04-03 08:05
The `and rsp, 0xffffffffffffffc0` instruction aligns the stack to 64 bytes boundary. Meanwhile, the code in the main function uses some AVX-512 instructions. I searched a bit and it seems sometimes these instructions cause the compiler to align the data to 64 bytes boundaries.

**Closed** 2024-04-04 04:29 UTC
Labels: Type: Bug, Component: Core, Impact: Medium, Effort: Trivial
