### ISSUE TITLE
Restore Previous Session After An Update

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#624] opened 2017-02-17 19:05 UTC
if you apply an update and have to restart, binja should
* reopen files you were previously using 
* go the address/view you were previously viewing

**Comment by psifertex** [comment] 2017-02-17 20:20
Duplicate of #226 though admittedly the name isn't as good. I'll add text there.

**Comment by psifertex** [comment] 2017-02-17 20:21
Actually, peter pointed out they're really separate things. Re-opening.

**Closed** 2022-08-11 15:33 UTC
Labels: enhancement, ui, Impact: High, Effort: Medium
