### ISSUE TITLE
Label not used + missing array access

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4310] opened 2023-05-19 06:58 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4286-dev, 58311b01
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

Anyone from V35 should search for "Encourage Salesman Prompt Delay" to find the database.

Consider the following BN disassembly where `SYS_TASKS` Is an array of structures `20056A40`. 

```
00049344  int32_t* const sys_task_by_index(int32_t arg1)

00049344  0928       cmp     r0, #9
00049346  0ad8       bhi     #0x4935e

00049348  064b       ldr     r3, [pc, #0x18]  {data_49364}
0004934a  0c22       movs    r2, #0xc
0004934c  02fb0030   mla     r0, r2, r0, r3
00049350  8368       ldr     r3, [r0, #8]
00049352  23b1       cbz     r3, #0x4935e

00049354  4368       ldr     r3, [r0, #4]
00049356  002b       cmp     r3, #0
00049358  08bf       it      eq
0004935a  0020       movs    r0, #0  {0x0}
0004935c  7047       bx      lr

0004935e  0020       movs    r0, #0
00049360  7047       bx      lr

00049362        00 bf                                                                                        ..

00049364  void* data_49364 = SYS_TASKS
```

IDA creates the following C code 

```
sys_task_t *__fastcall sys_task_by_index(unsigned int ix)
{
  sys_task_t *task; // r0

  if ( ix > 9 )
    return 0;
  task = &SYS_TASKS[ix];
  if ( !task->ctx )
    return 0;
  if ( !task->proc )
    return 0;
  return task;
}
```

BN has the reference in LLIL 

```
00049344  int32_t* const sys_task_by_index(int32_t arg1)

   0 @ 00049346  if (r0 u> 9) then 1 @ 0x4935e else 3 @ 0x49348

   1 @ 0004935e  r0 = 0
   2 @ 00049360  <return> jump(lr)

   3 @ 00049348  r3 = [&data_49364].d
   4 @ 0004934a  r2 = 0xc
   5 @ 0004934c  r0 = r3 + r2 * r0
   6 @ 00049350  r3 = [r0 + 8].d
   7 @ 00049352  if (r3 == 0) then 1 @ 0x4935e else 8 @ 0x49354

   8 @ 00049354  r3 = [r0 + 4].d
   9 @ 0004935a  if (r3 == 0) then 10 else 12 @ 0x4935c

  10 @ 0004935a  r0 = 0
  11 @ 0004935a  goto 12 @ 0x4935c

  12 @ 0004935c  <return> jump(lr)
```

but eliminates it starting with MLIL and outputs the following HLIL 

```
00049344  int32_t* const sys_task_by_index(int32_t arg1)

00049346      if (arg1 u<= 9)
0004934c          int32_t* const r0 = 0x20056a40 + 0xc * arg1
00049352          if (r0[2] != 0)
0004935a              if (r0[1] == 0)
0004935a                  r0 = nullptr
0004935c              return r0
00049360      return 0
```

The above misses both the label and a chance to show array access. 

The array is there 

```
20056a40  struct sys_task_t SYS_TASKS[0xa] = 
20056a40  {
20056a40      [0x0] = 
20056a40      {
20056a40          char* name = nullptr
20056a44          void* proc = nullptr
20056a48          void* ctx = nullptr
20056a4c      }
...
```

**Comment by fuzyll** [comment] 2023-05-19 19:00
The copy of the database we have from you doesn't have this type, but I recreated it as close as I could and can confirm our output. You can improve it by hitting the `o` hotkey on 0x20056a40 to tell us that this value is a pointer, though:

```
000049344  struct sys_task_t* sub_49344(uint32_t arg1)

000049346      if (arg1 u<= 9)
00004934c          struct sys_task_t* r0 = &SYS_TASKS[0].proc + 0xc * arg1
000049352          if (r0->ctx != 0)
00004935a              if (r0->proc == 0)
00004935a                  r0 = nullptr
00004935c              return r0
000049360      return 0
```

It would be nice if we did that automatically for you, though. And, of course, the array access is still not fixed.

**Comment by fuzyll** [comment] 2023-05-24 16:35
Closing this as a duplicate of #4251.

**Closed by fuzyll** 2023-05-24 16:35 UTC
Labels: Type: Bug, State: Duplicate
