### ISSUE TITLE
Better user docs on offset pointers

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#5236] opened 2024-04-04 13:42 UTC
We've had offset pointers since 3.2 but it doesn't look like have very good documentation on them:

https://binary.ninja/2022/10/28/3.2-released.html#offset-pointers

**Comment by CouleeApps** [comment] 2024-05-23 06:16
Duplicate of #3834

**Closed by CouleeApps** 2024-05-23 06:16 UTC
Labels: Component: Documentation, Impact: Medium, Effort: Trivial
