### ISSUE TITLE
HLIL simplifies array access incorrectly

### ISSUE THREAD

**Issue by gitbubaa** [Vector35/binaryninja-api#2446] opened 2021-05-09 07:47 UTC
**Describe the bug**
HLIL simplifies array access incorrectly.

**To Reproduce**
1. Open attached the binary `command` from the ctf chall: [stolen_backdoor_0e0064acfb07b8c644c57e07c4c7d6c711fda3186c77d20b96e30b9a71b8f4e1.tar.gz](https://github.com/Vector35/binaryninja-api/files/6447103/stolen_backdoor_0e0064acfb07b8c644c57e07c4c7d6c711fda3186c77d20b96e30b9a71b8f4e1.tar.gz)
2. Go to `main`
3. View HLIL

**Expected behavior**
The data array for input should be accessed at `var_70`-1

**Screenshots**
Before simplification:
![image](https://user-images.githubusercontent.com/83194823/117564102-255a7900-b05f-11eb-8578-5c6b128549f3.png)
After:
![image](https://user-images.githubusercontent.com/83194823/117564114-3e632a00-b05f-11eb-8111-a3c163767fea.png)

HLIL:
![image](https://user-images.githubusercontent.com/83194823/117564125-55098100-b05f-11eb-91f4-6fdb1f2c63d0.png)

Disassembly:
![image](https://user-images.githubusercontent.com/83194823/117564140-6d799b80-b05f-11eb-9989-2818014e1f1d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Binary Ninja version: 2.3.2796-dev

**Additional context**
hexrays can handle this. Maybe just some compiler heuristics.
![image](https://user-images.githubusercontent.com/83194823/117564170-9a2db300-b05f-11eb-99bb-00982d39d8fb.png)
ghidra also makes the same mistake
![image](https://user-images.githubusercontent.com/83194823/117564175-a6197500-b05f-11eb-900a-498d61eeb333.png)

**Comment by plafosse** [comment] 2024-02-19 13:53
I know this is rather old but do you happen to have the binary associated with this? The provided binary doesn't look to have the binary in question.

**Comment by fuzyll** [comment] 2024-03-26 14:27
Closing this because we still don't have a reproducible binary. Please feel free to reopen if anyone has one.

**Closed by fuzyll** 2024-03-26 14:27 UTC
Labels: Type: Bug, Component: Core, Core: HLIL, Effort: High, Impact: Medium, State: Blocked (Customer)
