### ISSUE TITLE
Custom Architecture Documentation

### ISSUE THREAD

**Issue by plafosse** [Vector35/binaryninja-api#3402] opened 2022-08-16 14:37 UTC
**Is this a general concept that needs to be documented or a specific API?**
General Concept

**What concept or API needs more documentation?**
The act of building a custom Architecture needs to be documented.

There exist plenty of examples and there are blog posts about doing it but this information needs to be distilled and added to the user documentation.

- https://binary.ninja/2020/01/08/guide-to-architecture-plugins-part1.html
- https://binary.ninja/2021/12/09/guide-to-architecture-plugins-part2.html

**Comment by psifertex** [comment] 2024-02-22 04:27
Duplicate of #2613

**Closed by psifertex** 2024-02-22 04:27 UTC
Labels: Type: Enhancement, Component: Documentation, Effort: Low, Impact: Medium
