### ISSUE TITLE
`HMODULE` propagates as `struct HINSTANCE__*`

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4898] opened 2024-01-15 11:27 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4767-dev, 6c169ddb
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

**Steps To Reproduce:**
1. Find a similar situation
2. Change second variable type to `HMODULE`
3. See the wrong propagation

**Expected Behavior:**
I expect it to propagate it as `HMODULE`.

**Screenshots:**
![Recording 2024-01-15 at 13 22 37](https://github.com/Vector35/binaryninja-api/assets/109607896/b72fabfa-0410-4f69-b576-5980228f19f2)

**Comment by alexrp** [comment] 2024-01-15 17:15
Possible dup of #4552 ?

**Comment by fuzyll** [comment] 2024-01-16 14:50
`HMODULE` is defined as `typedef HINSTANCE HMODULE;` in our Windows platform types. So, I agree with @alexrp and believe this is a duplicate of #4552. I'm closing this as a result, but this is definitely an issue and the original ticket is remaining open until we address that.

Thanks for the report, having other examples of this is always a good thing.

**Closed by fuzyll** 2024-01-16 14:50 UTC
Labels: State: Duplicate
