### ISSUE TITLE
Copy sometimes fails when under heavy load

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#1973] opened 2020-09-13 08:46 UTC
My assumption is that any text binja displays to me should be selectable and I should be able to copy/paste my selection using the same copy/paste logic that applies to every other desktop application I use.

1) Copy/pasting does not consistently work, especially if binja is busy doing analysis
![image](https://user-images.githubusercontent.com/8716677/93013852-e40dda00-f560-11ea-9a1b-bc9d499861cd.png)

2) #2019 You cannot select text inside of a given token, e.g. if I have `data_140c57ec0` and I want to copy the substring `c57ec0` this is impossible. 

3) #2439 You cannot select text on any log entries, meaning you cannot copy/paste parts of log lines

4) #2440 You cannot select text on graph view function signatures, meaning you cannot copy/paste function signatures without switching to linear view and scrolling to the top of your function.

**Comment by psifertex** [comment] 2020-09-16 18:57
1. Are you saying that behavior only occurs during analysis? I'm trying to reproduce it with various similar selections and can't do it currently as they all copy correctly. 

2-3 Honestly, this is probably a "won't fix" for now for us. Partly because it would require a major refactor with relatively small benefit and partly because this is an intentional design choice. I /prefer/ being able to single click a token/line and have it grab the appropriate size. Adding a cursor would make keyboard navigation worse as well as opposed to the token-based navigation we have now. We could presumably do it with some click-drag-with-modifier for example, but again, large refactor. For 2, at least that particular use case -- if it were me, I'd implement a snippet and bind to a hotkey that would pull out the relative offset of tokens and copy it into the clipboard. (See: https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-clipboard-py)

4. Yeah, this is definitely something I'd like to see fixed. Just for ease of tracking, I'm going to file a new bug for that in #1989 

Given that I'm going to rename this bug to describe the bug status and get it prioritized once we can repro it.

**Comment by yrp604** [comment] 2020-09-16 19:30
re 1: I can repro this with relative consistency right now (3/4 times) on the latest dev -- I open ntoskrnl.exe, while its analyzing I put it into linear view and select/copy/paste. I can repro this in both linear and graph view, though linear seems to display the bug more reliably.

**Comment by psifertex** [comment] 2020-09-16 20:56
Current theory is this is related to: https://bugreports.qt.io/browse/QTBUG-27097?focusedCommentId=370522&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

And that the fix is just sufficient for high-load, though I'm unable to totally replicate it on my windows vm under similar load conditions.

**Comment by CouleeApps** [comment] 2021-05-05 19:30
Looks like 2 on this was done but none of the others. Going to open separate issues for each and keep this issue for 1

**Comment by psifertex** [comment] 2021-06-29 02:54
Just curious whether the Qt6 change has had any impact on this bug -- does it still repro for you?

**Comment by fuzyll** [comment] 2024-03-26 14:26
I'm going to close this. This has been dormant for a few years now and we have some internal issues to track places where we do things we shouldn't on the main thread (which is, I believe, the ultimate culprit here). If anyone has any specific repro steps for a specific situation in which this occurs, let us know either in this issue or a new one and we'll look into those.

**Closed by fuzyll** 2024-03-26 14:26 UTC
Labels: Type: Bug, Component: UI, Effort: Low, Impact: Medium, UI: Linear, State: Blocked (Customer)
