### ISSUE TITLE
Thumb2: Floats not recognized (this time for real!)

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4390] opened 2023-06-07 09:50 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4317-dev, a5d64740
- OS: macos
- OS Version: 13.4
- CPU Architecture: arm64

It should be 

```
00043416                                                                    00 bf                                                ..
00043418  float data_43418 = 0.244140625
```

but is 

```
00043416                                                                    00 bf 00 00                                          ....
0004341a  int32_t data_4341a = -0x4af7c186
```

in the code below.

Probably because Thumb2 doesn't have proper float support at the moment.

```
000433bc  int32_t sub_433bc(int32_t arg1, int16_t* arg2, int32_t arg3, int32_t arg4)

000433bc      int32_t var_10 = arg3
000433bc      int16_t* var_14 = arg2
000433bc      int32_t var_18 = arg1
000433c2      int128_t q1
000433c2      q1:0xc.d = fconvert.s(-5.07548634e-07f)
000433c6      var_18.w = *arg2
000433ce      var_18:2.w = arg2[1]
000433d2      int32_t r0_2 = 0
000433d4      var_14.w = arg2[2]
0004340e      do
000433f2          int128_t q2
000433f2          q2.d = (zx.d(*((zx.d(*(arg4 + (r0_2 << 1))) & 0xfe) + &var_10 - 8)) - 0x8000) * sx.d(*(arg4 + 1 + (r0_2 << 1)))
🚫000433f6          unimplemented  {vcvt.f32.F32.S32 s15, s15}
000433fa          q2.d = &data_433fe f* q1:0xc.d
🚫000433fe          unimplemented  {vcvt.s32.f32 s15, s15}
00043406          *(arg3 + (r0_2 << 1)) = 0x3406
0004340a          r0_2 = r0_2 + 1
0004340a      while (r0_2 != 3)
00043414      return 0

00043416                                                                    00 bf 00 00                                          ....

0004341a  int32_t data_4341a = -0x4af7c186
```

**Comment by joelreymont** [comment] 2023-06-07 09:51
Anyone from V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by plafosse** [comment] 2023-06-09 15:37
I created this issue because of some of the issues you posted. Marking this as a duplicate of https://github.com/Vector35/binaryninja-api/issues/4400

**Closed by plafosse** 2023-06-09 15:37 UTC
Labels: State: Duplicate
