### ISSUE TITLE
The contents of the structures are no longer displayed

### ISSUE THREAD

**Issue by UnidentifiedCitizen** [Vector35/binaryninja-api#5059] opened 2024-02-15 00:23 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4883-dev Personal, 811e395d
- OS: windows
- OS Version: 10
- CPU Architecture: x86_64

**Bug Description:**
Sometimes the ability to see the contents of the structure disappears, when you click on/select the structure, its contents are not displayed in the desired window

**Steps To Reproduce:**
It stops working on its own

**Screenshots:**
![изображение](https://github.com/Vector35/binaryninja-api/assets/43756332/6047228a-164c-422e-92d6-3a697e106c48)

**Comment by CouleeApps** [comment] 2024-02-15 01:49
Does this happen in all cases or only for specific binaries / structures / after a specific time / after performing specific actions? I can't reproduce this when simply opening a file and browsing around.

**Comment by UnidentifiedCitizen** [comment] 2024-02-15 03:07
> Does this happen in all cases or only for specific binaries / structures / after a specific time / after performing specific actions? I can't reproduce this when simply opening a file and browsing around.

Im using BN with large binary (around 60MB), so my DB is around 2GB after saving, i can send binary here you want

**Comment by UnidentifiedCitizen** [comment] 2024-02-15 03:14
Also, structure window is hidden by default to the right side here

![изображение](https://github.com/Vector35/binaryninja-api/assets/43756332/2fc24f24-7206-48cc-bba3-00af6b718107)

**Comment by CouleeApps** [comment] 2024-02-15 04:37
If you could upload the binary that triggers the bug that would be appreciated. I spent some time poking around ntoskrnl which is admittedly only 8MB, and didn't see anything like what you described.

In the second picture it looks like the splitter widget has shrunk. You should be able to expand it by dragging on the ... dots (there are two, you want the left one).

**Comment by UnidentifiedCitizen** [comment] 2024-02-15 04:46
> If you could upload the binary that triggers the bug that would be appreciated. I spent some time poking around ntoskrnl which is admittedly only 8MB, and didn't see anything like what you described.
> 
> In the second picture it looks like the splitter widget has shrunk. You should be able to expand it by dragging on the ... dots (there are two, you want the left one).

I also have added PDB file: https://file.io/aIz367GMNklA

**Comment by UnidentifiedCitizen** [comment] 2024-02-15 16:43
Also, sometimes it's stops showing xrefs on structure fields

**Comment by UnidentifiedCitizen** [comment] 2024-02-15 16:58
Also, Binary Ninja does not close after closing the window, although it has been at least 2 minutes

**Comment by fuzyll** [comment] 2024-02-15 18:01
Thanks for the test case. Vector 35 employees can search for `silenced tapioca serpent puppet` to find it and the provided PDB.

**Comment by fuzyll** [comment] 2024-03-25 22:40
We have been unable to reproduce this, so I'm going to close it. If we've missed a step or if there's more information/test cases you can give, please let us know and we can reopen it.

I suspect that at least one of the issues described here is a performance problem, but it's difficult for us to troubleshoot it in this specific instance without more information about hardware and settings.

**Comment by CouleeApps** [comment] 2024-06-06 18:52
Reopening this because I found a way to reproduce it which I think is accurate to the issue:

1. Add binary to project
2. Open binary
3. Open types view
4. Save binary
5. Now types view is broken

It tooks to be the action of saving the binary that is causing this.

**Comment by CouleeApps** [comment] 2024-06-06 19:30
Fix for this is going out in >= 4.1.5431-dev

**Closed** 2024-06-06 19:30 UTC
Labels: Type: Bug, Component: UI, Impact: Medium, UI: Types
