### ISSUE TITLE
Back/Forward Mouse Button on Windows 10

### ISSUE THREAD

**Issue by pjlhjr** [Vector35/binaryninja-api#828] opened 2017-10-07 21:53 UTC
When using the special back/forward buttons on a USB mouse with Windows 10, the button press registers twice: once on the button press and once on the button release. This causes the Disassembly View to skip back/forward two functions, rather than just one. This does not occur in other applications (such as web browsers), but I have not tested this issue on other machines.

Looking at #405, switching the back/forward button logic from mousePressEvent to mouseClickEvent might do the trick.

Obviously, this is a rather minor issue, because _Esc_ does the job just fine, but having a forward button in addition can be very convenient.

**Comment by plafosse** [comment] 2018-01-12 02:41
This is a duplicate of #337 and is actually fixed as of >=1.1.1041

**Closed by plafosse** 2018-01-12 02:41 UTC
