### ISSUE TITLE
Pinned cross references do not close on file close

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#2978] opened 2022-02-20 18:03 UTC
Repro steps:
1. Open a binary
2. Open a pinned cross references pane
3. Close the binary with the ⌘W shortcut
4. Notice the pinned cross references pane remains open

This doesn't seem to happen if the binary is closed by clicking the 'x' on the tab.

Discovered on 3.0.3253-dev.

**Comment by fuzyll** [comment] 2022-02-21 18:17
From Slack conversation about this issue:

```
Rusty Wagner  15:11
That’s not actually what you think. Cmd+W is close pane now, because that’s more commonly wanted. Shift+Cmd+W is close tab. If you close the non-xrefs pane with the “X” on the pane it gets in the same state.
15:11
Obviously if you prefer something different keybinding wise users can change it.
15:12
There is no system in place to disallow it.
15:12
It’s a pane. It’s still there
15:12
It doesn’t know it’s not important to keep open.
15:12
There is no “this isn’t important, close it automatically” flag
15:13
Especially since you can have another window where you DEFINITELY want only the xrefs pane.
15:13
I wouldn’t close the issue because it feels weird to have that as the only pane open anywhere though.
```

**Comment by plafosse** [comment] 2024-03-19 20:37
CMD+W is no longer 'Close Pane' making this just a duplicate of #3345

**Closed by plafosse** 2024-03-19 20:37 UTC
Labels: Type: Bug, State: Duplicate, Component: UI, Impact: Low, Effort: Low, UI: Panes
