### ISSUE TITLE
Show warning when renaming variable to same name

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3582] opened 2022-10-21 12:38 UTC
Currently we can rename multiple variable to same name. Especially in big functions I often  create multiple variable to same name and it might be annoying sometimes. It would be useful if we have an option for showing warning in this situation.

**Comment by CouleeApps** [comment] 2022-10-21 13:43
Duplicate of #3455

**Closed by CouleeApps** 2022-10-21 13:43 UTC
Labels: enhancement
