### ISSUE TITLE
ARM disassembly wrong for mov reg, reg

### ISSUE THREAD

**Issue by Matir** [Vector35/binaryninja-api#236] opened 2016-04-22 18:23 UTC
Here's the output from objdump:
```
   16e44:	e1a01000 	mov	r1, r0
   16e48:	e28d0098 	add	r0, sp, #152	; 0x98
   16e4c:	ebfffb96 	bl	15cac <_init+0x770>
   16e50:	e3a02000 	mov	r2, #0
   16e54:	e28d1098 	add	r1, sp, #152	; 0x98
   16e58:	e3a00002 	mov	r0, #2
   16e5c:	e1a04002 	mov	r4, r2
   16e60:	ebfffb73 	bl	15c34 <_init+0x6f8>
   16e64:	e28d0010 	add	r0, sp, #16
   16e68:	e5cd400c 	strb	r4, [sp, #12]
   16e6c:	ebfffe28 	bl	16714 <_init+0x11d8>
   16e70:	e59f3798 	ldr	r3, [pc, #1944]	; 17610 <_init+0x20d4>
   16e74:	e28d100c 	add	r1, sp, #12
   16e78:	e7953003 	ldr	r3, [r5, r3]
   16e7c:	e1a02004 	mov	r2, r4
   16e80:	e3a0000b 	mov	r0, #11
   16e84:	e58d300c 	str	r3, [sp, #12]
   16e88:	e58d8090 	str	r8, [sp, #144]	; 0x90
   16e8c:	ebfffd12 	bl	162dc <_init+0xda0>
   16e90:	e28d100c 	add	r1, sp, #12
   16e94:	e1a02004 	mov	r2, r4
   16e98:	e1a00008 	mov	r0, r8
   16e9c:	ebfffd0e 	bl	162dc <_init+0xda0>
   16ea0:	e28d100c 	add	r1, sp, #12
   16ea4:	e1a02004 	mov	r2, r4
   16ea8:	e3a0000d 	mov	r0, #13
   16eac:	ebfffd0a 	bl	162dc <_init+0xda0>
   16eb0:	e28d100c 	add	r1, sp, #12
   16eb4:	e1a02004 	mov	r2, r4
   16eb8:	e3a00002 	mov	r0, #2
   16ebc:	ebfffd06 	bl	162dc <_init+0xda0>
   16ec0:	e28d100c 	add	r1, sp, #12
   16ec4:	e1a02004 	mov	r2, r4
   16ec8:	e3a0000f 	mov	r0, #15
   16ecc:	ebfffd02 	bl	162dc <_init+0xda0>
   16ed0:	e1a02004 	mov	r2, r4
   16ed4:	e28d100c 	add	r1, sp, #12
   16ed8:	e3a0002c 	mov	r0, #44	; 0x2c
   16edc:	ebfffcfe 	bl	162dc <_init+0xda0>
```

Here's what binaryninja comes up with:
![arm_disassembly_wrong](https://cloud.githubusercontent.com/assets/808960/14750932/310193e6-087c-11e6-88b4-79f8a2180b06.png)

Not the lack of operands on the mov and the strange {0x175e4} value.

Sorry, I can't provide the full binary, but hopefully this is enough to debug the issue.

**Comment by plafosse** [comment] 2016-04-22 20:52
I'm having problems reproducing this issue.  Could you show the IL view? Also could you show any instructions prior to this issue starting? My little test didn't show this issue: 
<img width="29" alt="screen shot 2016-02-21 at 12 00 11 pm" src="https://cloud.githubusercontent.com/assets/10556585/14754638/9a07c7d8-08aa-11e6-8874-291b00d01a1f.png">

**Comment by Matir** [comment] 2016-04-22 21:35
Your image seems to be empty.

Here's the IL of that section.  How much before it do you need?  (Mostly because I want to provide enough to debug without disclosing too much about the product I'm reviewing.)  This is on 1.0.290 beta, which seems to be the latest from the beta channel.

![disassembly_il](https://cloud.githubusercontent.com/assets/808960/14755177/4f755d80-0895-11e6-83ed-5ec619dc7746.png)

I've found another binary from the same project with almost the same issue (it doesn't display the curly-braced value, it's just a "mov" without operands) that is significantly less sensitive.  Is there an email address I could send that?

**Comment by plafosse** [comment] 2016-04-26 15:30
You can send it to info@vector35.com Thanks!

**Comment by psifertex** [comment] 2016-04-26 22:49
Thanks for sending that. 

Looks like a compiler bug/difference -- the OS X build doesn't have that problem, just the Linux version. Appreciate it, we should be able to track it down now.

**Comment by Matir** [comment] 2016-04-26 22:52
Glad you were able to repro with it.  If you can share what the root cause turns out to be, I'd be very curious (as would several other engineers here).  Our current speculation (without knowing anything about the implementation of binaryninja) is that there's some arithmetic/bitwise operation that ends up being "undefined behavior" by the C++ spec and so wanders into "implementation-defined behavior".  But  of course, that's just guessing. :)

**Comment by plafosse** [comment] 2016-04-27 20:10
Well I've root caused the issue, it is indeed a compiler bug. 

I create a 4x2 lookup table of structs, each struct has 2 32-bit elements in it.  Gcc allocates space on the stack for the lookup table but then only assigns one of the 32-bit elements. When we then do our lookup we get an uninitialized value for our instruction type causing the issue. The fix for now is just to make the lookup table static so it goes in the data segment.

Fixed in dev

**Closed by plafosse** 2016-04-27 20:10 UTC
