### ISSUE TITLE
Value set analysis loses track of stack offset value

### ISSUE THREAD

**Issue by ZetaTwo** [Vector35/binaryninja-api#4832] opened 2023-12-14 13:50 UTC
**Version and Platform (required):**
- Binary Ninja Version: latest dev (will update this with exact number when I get home)
- OS: Linux Ubuntu 
- OS Version: 22.04 LTS
- CPU Architecture: x64

**Bug Description:**
I have a snippet of code like this:
```
0x1446f95f1: mov qword [rsp], rbp
0x1446f95f5: sub rsp, 0x40
```

![image](https://github.com/Vector35/binaryninja-api/assets/870392/362d6d99-1a52-41fd-a47b-54669dee35b6)

When the first instruction is executing, rbp contains a certain offset in the current frame:
```
(f is the function containing this)
>>> f.get_reg_value_at(0x1446f95f1, 'rbp')
<stack frame offset -0x210> # <- this value is important
>>> f.get_reg_value_at(0x1446f95f1, 'rsp')
<stack frame offset -0x250> # <- current stack offset
>>> f.get_stack_contents_at(0x1446f95f1, -0x250, 8)
<undetermined> # <- makes sense, we haven't assigned the value yet
```
So far, so good, however immediately after the instruction has executed, Binja does not know what is on top of the stack:
```
>>> f.get_stack_contents_at(0x1446f95f5, -0x250, 8)
<undetermined> # <- this should be "<stack frame offset -0x210>", not "<undetermined>"
```

This is an issue because later in the function the code restores the rbp and uses it as a base, something like:
```
mov rbp, [rsp + xxx] # pointing to the same location as above
mov rax, [rbp + 0x30] # Can not resolve where on the stack this points to
jmp rax # destination of this jump unknown even though it's a constant value in reality
```

**Expected Behavior:**
I expect the value set analysis to keep track of the register value when pushed on the stack.

**Comment by plafosse** [comment] 2023-12-16 12:22
Any chance you can share the binary or what the MLILSSA looks like?

**Comment by ZetaTwo** [comment] 2023-12-16 15:02
MLILSSA looks like this:
![image](https://github.com/Vector35/binaryninja-api/assets/870392/e2c4b75e-a3a8-4af7-b636-99458e277521)

I can not share the binary publicly but @fuzyll already have it and I can send it to you on Slack as well.

**Comment by fuzyll** [comment] 2024-01-03 05:08
Apparently I forgot to put it in this issue, but the magic words for finding the binary are "playful brisk dairy sauna".

**Comment by plafosse** [comment] 2024-09-06 18:26
So I tried this but I can't reproduce the issue. Though I'm getting different values for the stack at location: 
```
>>> f.get_reg_value_at(0x1446f95f1, 'rbp')
<entry rbp>
>>> f.get_reg_value_at(0x1446f95f1, 'rsp')
<stack frame offset -0x10>
>>> f.get_stack_contents_at(0x1446f95f1, -0x10, 8)
<undetermined>
>>> f.get_stack_contents_after(0x1446f95f1, -0x10, 8)
<entry rbp>
```
<img width="604" alt="image" src="https://github.com/user-attachments/assets/06f68784-8a7a-44a3-9bb9-375d346d9231">

**Comment by ZetaTwo** [comment] 2024-09-17 21:32
I will take a look with the latest binja version and see what results I get. I will get back on this.

**Comment by plafosse** [comment] 2024-10-09 17:04
Closing this issue as it seems to be resolved

**Closed by plafosse** 2024-10-09 17:04 UTC
Labels: State: Unreproducible
