### ISSUE TITLE
Multiple if condition optimization

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3527] opened 2022-10-12 10:48 UTC
I've a code block in decompiler output which is like this:

```
if (manager != 0)
    initialized = manager->initialized
    if (initialized != 0)
        datalist = manager->datalist
        if (datalist != 0)
            if (initialized == 0 || (initialized != 0 && datalist == 0))
                manager = nullptr
```
Optimizing this into this would be very useful:

```
 if ( manager && manager->initialized && manager->datalist )
```

I've seen a lot of examples like this in if blocks that have multiple conditions. So I don't know if I need to attach binary. I think this is something general. There could be an issue for this already, but I couldn't be able to find it, *sorry if duplicate*.

**Comment by op2786** [comment] 2022-10-12 10:56
Here is another example from same binary:

```
if (manager == 0 || (manager != 0 && initialized == 0) || (manager != 0 && initialized != 0 && datalist == 0))
    result = 4
```

Which can be optimized into:

```
 if ( !manager || !manager->initialized || !manager->datalist )
    result = 4
```

**Comment by op2786** [comment] 2023-03-09 11:49
```
0804c122        int32_t eax_19 = strcasecmp(&bin_type, "EX")
0804c12c        if (eax_19 != 0) {
0804c13b          eax_19 = strcasecmp(&bin_type, "DEX")
0804c145          if (eax_19 != 0) {
0804c154            eax_19 = strcasecmp(&bin_type, "NEX")
0804c14a          }
0804c12a        }
0804c15e        if (eax_19 == 0 || eax_19 == 0 || eax_19 == 0) {
0804c160          data[0] = 0x156677
```

can be optimized into:

```
if ( !strcasecmp(&bin_type, "EX") || !strcasecmp(&bin_type, "DEX") || !strcasecmp(&bin_type, "NEX") )
  data[0] = 0x156677;
```

**Comment by op2786** [comment] 2024-01-22 13:09
```
163dc703      if (ps->CreateToolhelp32Snapshot == 0) {
163dc728        not_valid:
163dc728        ps->valid = 0
163dc728      } else {
163dc70a        if (ps->Process32First == 0) {
163dc70a          goto not_valid
163dc70a        }
163dc711        
163dc711        if (ps->Process32Next == 0) {
163dc711          goto not_valid
163dc711        }
163dc718        
163dc718        if (ps->Module32First == 0) {
163dc718          goto not_valid
163dc718        }
163dc71d        
163dc71d        if (Module32Next == 0) {
163dc71d          goto not_valid
163dc71d        }
163dc721        
163dc721        ps->valid = 1
163dc721      }
```

can be optimized into:

```c
    ps->valid = ps->CreateToolhelp32Snapshot
             && ps->Process32First
             && ps->Process32Next
             && ps->Module32First
             && Module32Next;
```

**Comment by Zerotistic** [comment] 2024-01-22 13:12
I've encountered similar situation.

This code:
![image](https://github.com/Vector35/binaryninja-api/assets/54184933/1a82e3bd-0f7e-441f-ac38-280c338d7fa8)
 

Could be optimized into this:
```c
if ( !lstrcmpiW(rax_3[1], "-service") )
    {
      StartServiceCtrlDispatcherW(&ServiceStartTable);
      return 0;
}
if ( !lstrcmpiW(rax_3[1], "-install") )
      return func1();
if ( !lstrcmpiW(rax_3[1], "-uninstall") )
      return func2();
if ( !lstrcmpiW(rax_3[1], "-start") )
      return func3();
if ( !lstrcmpiW(rax_3[1], "-testservice") )
{
      // stuff
}
```

**Comment by plafosse** [comment] 2024-06-07 17:38
This is being actively worked on and is slated to be in 4.1

**Comment by D0ntPanic** [comment] 2024-07-02 21:53
Control flow recovery is using an entirely new algorithm for 4.1, and there are no binaries provided for any of the examples provided in this ticket. It is not possible to know if the new algorithm has improved any of these cases, so the issue is being closed as control flow recovery is now a very different implementation.

**Closed by D0ntPanic** 2024-07-02 21:53 UTC
Labels: Type: Enhancement, Component: Core, Core: HLIL, IL Optimization, Impact: High
