### ISSUE TITLE
support for raw byte string search

### ISSUE THREAD

**Issue by mgmoshes** [Vector35/binaryninja-api#585] opened 2016-12-21 21:53 UTC
Currently in the "Find" menu there are only the "Raw String" and "Escaped String" options. However there's no way to search for a raw byte string like '\xB5\x04'.

**Comment by lucasduffey** [comment] 2016-12-21 21:55
possible duplicate of https://github.com/Vector35/binaryninja-api/issues/41

**Comment by psifertex** [comment] 2016-12-21 23:03
Escaped string should allow for searching of binary bytes exactly as you describe. Did it not work?

**Comment by plafosse** [comment] 2017-07-15 23:08
This feature is supported just search for "\xB5\x04" with Escaped String selected.

**Closed by plafosse** 2017-07-15 23:08 UTC
