### ISSUE TITLE
Global Names are Stored as Bytes

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#6034] opened 2024-10-23 16:15 UTC
**Is this a general concept that needs to be documented or a specific API?**
This is specifc to the globals API

**What concept or API needs more documentation?**
The key for a global is stored as a bytes string rather than a plain string. No problem with this except that when using a variable for the string name, the user has to `.encode()` if using `bv.file.database.globals` and `bv.file.database.global_keys`. Otherwise, it may appear that the global you just set has disappeared.

Unexpected:

```python
globalname = 'foo'
bv.file.database.write_global(globalname, 'bar')
bv.file.database.globals.get(globalname)
```

Correct:

```python
globalname = 'foo'
bv.file.database.write_global(globalname, 'bar')
bv.file.database.globals.get(globalname.encode())
```

**Is this documentation related to a specific API?**
Python

Please add a note about this here:
https://api.binary.ninja/binaryninja.database-module.html#binaryninja.database.Database.global_keys

and here:
https://api.binary.ninja/binaryninja.database-module.html#binaryninja.database.Database.globals

**Comment by utkonos** [comment] 2024-10-23 16:39
Just to head off "Use `read_global`"

If you use `read_global` with a non-existant key, it raises an exception. It is cleaner to be able to do `get` and then provide a default if the key is missing.

It would be nice if `read_global` allowed for a default if the key were missing and then only throw an exception if the default is not provided in the first place.

**Comment by CouleeApps** [comment] 2024-10-23 18:23
Yep, looks like a missing call to convert bytes to string. Looks like string was intended, based on the function return signature. Pretty simple fix though

**Comment by CouleeApps** [comment] 2024-10-23 18:24
Fixed via https://github.com/Vector35/binaryninja-api/commit/7939567080840779182536303645940324674813

**Closed as completed by CouleeApps** 2024-10-23 18:24 UTC

**Comment by utkonos** [comment] 2024-10-23 18:56
@CouleeApps This is what I was thinking, but I saw that all the globals in there are bytes string key names. I hope this change doesn't break a zillion things.

**Comment by CouleeApps** [comment] 2024-10-23 18:57
Unlikely this breaks much, as those apis are rarely used from what I've seen. Easy fix anywhere they are, though
