### ISSUE TITLE
Wrong variable in `movsb`

### ISSUE THREAD

**Issue by reversing-dev** [Vector35/binaryninja-api#5241] opened 2024-04-06 04:08 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5071-dev Personal, 41729337
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/1b06db97-4def-4a30-ae67-4d6c77792818)
`var_82` is neither source nor destination. This messes up the decompilation.
![image](https://github.com/Vector35/binaryninja-api/assets/42991292/93885c77-5fb5-46fa-a7fb-231522ddb3d8)

File: #4760

**Comment by xusheng6** [comment] 2024-04-09 13:48
This is probably caused by: https://github.com/Vector35/binaryninja-api/blob/b1d4d336ad66273982ddd2fd8e9e1e950dd4c89a/arch/x86/il.cpp#L2513-L2541. The two true/false branches are identical, which is unexpected.

**Comment by bpotchik** [comment] 2024-04-09 13:50
Fixed in `4.1.5075-dev`.

**Closed by bpotchik** 2024-04-09 13:50 UTC
Labels: Type: Bug, Component: Architecture, Arch: x86, Impact: Low, Effort: Low
