### ISSUE TITLE
Documentation: update binaryninja.interaction.get_save_filename_input documentation to reflect binaryninja.interaction.get_open_filename_input

### ISSUE THREAD

**Issue by fuomag9** [Vector35/binaryninja-api#2062] opened 2020-10-24 18:42 UTC
In [binaryninja.interaction.get_save_filename_input](https://api.binary.ninja/binaryninja.interaction.get_save_filename_input.html?highlight=get_save_filename_input) there's missing documentation for (supported, I tested that myself!) sample syntax of multiple file types like in [binaryninja.interaction.get_open_filename_input
](https://api.binary.ninja/binaryninja.interaction.get_open_filename_input.html)

What I mean is the difference below:
![image](https://user-images.githubusercontent.com/1580624/97091060-3bf83000-1639-11eb-8af9-342abcfb1a83.png)
![image](https://user-images.githubusercontent.com/1580624/97091065-41ee1100-1639-11eb-955c-f93d0ef860df.png)

**Comment by psifertex** [comment] 2020-10-24 19:17
While you're correct that it's missing, the right fix is actually removing the extension entirely as a parameter. That parameter is actually not even used at all in the save prompt since it's up to the user to select/type a filename and the extension they return is all that matters. 

A save dialog box doesn't actually require a specific extension, it would be up to any code that uses the extension to decide whether to accept the value or not. I'm not sure why the API was designed that way in the first place, except for symmetry but that argument isn't used at all in the native code that implements that API. 

Given that I'm just going to close it as "wontfix" for now since I think the proper fix is to actually remove that parameter entirely, but that would have some compatibility issues with other plugins so I want to think about how we do that first.

**Closed by psifertex** 2020-10-24 19:17 UTC
