### ISSUE TITLE
HiDPI scale factor applied on non-HiDPI external monitor

### ISSUE THREAD

**Issue by obilodeau** [Vector35/binaryninja-api#291] opened 2016-06-07 18:35 UTC
Screenshot shows it all: 
![selection_017](https://cloud.githubusercontent.com/assets/546325/15869887/4aa08dfc-2cbc-11e6-82cd-e5fdd2d131bd.png)

On the left, a normally behaving application. On the right binaryninja.

On the terminal when I start `./binaryninja`:
```
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use: 
    QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors. 
    QT_SCREEN_SCALE_FACTORS to set per-screen factors. 
    QT_SCALE_FACTOR to set the application global scale factor.
```

**Comment by psifertex** [comment] 2016-06-07 19:07
Dupe of #86, already got the fix planned. Thanks for the report.

**Closed by psifertex** 2016-06-07 19:07 UTC
Labels: duplicate

**Comment by obilodeau** [comment] 2016-06-07 19:19
From the video I didn't think it was the same issue since I couldn't reproduce the video's behavior (hex editor lines jumping around). Plus scale factor was correct in the video.

Sorry for the double post. I'll wait until #86 is marked as fixed and I'll retest then.

**Comment by psifertex** [comment] 2016-06-08 05:03
Could be wrong, but I think it's the same underlying, but we'll see when we fix it! Thanks.
