### ISSUE TITLE
Crash from QSortFilterProxyModelPrivate::_q_sourceDataChanged

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#4094] opened 2023-03-11 02:44 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4084-dev (Build ID 6b32dfcc)
- OS: macOS
- OS Version: 13.1 (22C65)
- CPU Architecture: M1

**Bug Description:**
Binary Ninja crashed (and made me lose some work) while I was trying to set the type of a variable while analysis was also ongoing.  I can't reproduce this, so all I have is the crash log:
https://gist.github.com/comex/7d661588a91c501b173da7a7be0fa748

**Comment by comex** [comment] 2023-03-11 02:47
Famous last words.  When I tried to redo my work, it happened again:
https://gist.github.com/comex/467cebcb9f0dce3ab2185f3e87c04027

Just updated to 3.4.4137-dev; I'll see if it happens again.

**Comment by psifertex** [comment] 2023-03-11 03:24
We've two or three known crashing bugs in that window of dev builds so 🤞 that it's already fixed. Very sorry for the lost data -- hopefully the latest update has no issue. I'll symbolicate the stack traces and double check if they align with anything we know to be fixed or not as well.

**Comment by psifertex** [comment] 2023-03-11 03:28
Yeah, it's almost certainly a duplicate of #3912 from the crash log. Very sorry about that, but the good news is the update should fix it!

**Closed by psifertex** 2023-03-11 03:28 UTC
Labels: duplicate
