### ISSUE TITLE
Tag hover preview (or something else?) can deselects multiple tags

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2620] opened 2021-09-10 03:04 UTC
2974-dev

**Describe the bug**
When selecting multiple tags from the tag list, the pop-up preview can cause the tags to deselect without clcking

**To Reproduce**
1. Select multiple tags (click, hold shift, click again)
2. Move the mouse
3. Wait a bit

**Expected behavior**
The tags I select stay selected unless I deselect them somehow.

**Screenshots**
![tag-select](https://user-images.githubusercontent.com/8716677/132792696-577778d5-f7ce-4c81-80c8-2556436c15f7.gif)

**Version and Platform (required):**
 - Binary Ninja:  2974-dev
 - OS: Windows
 - Version: 11

**Additional context**

**Comment by plafosse** [comment] 2021-09-22 15:55
Seems like maybe is the code preview window pop up thats doing it?

**Comment by yrp604** [comment] 2021-09-22 16:06
It’s not the preview window directly as it doesn’t repro consistently, but it does seem like the preview window is related. 

My best guess was preview window for a function that wasn’t lifted (or some other computation that the result of gets cached). Preview window on first preview triggers lifting, and that lifting causes the tags to deselects. Subsequent previews the lift doesn’t happen and so the tags stay selected.

Just a guess based on trouble capturing a gif.

**Comment by bpotchik** [comment] 2021-09-22 16:41
One cause of this is trying to select while analysis is ongoing. This is a bug and needs fixed. Unsure if this is the cause of yrp's issue.

**Comment by CouleeApps** [comment] 2021-11-05 23:00
Fixed in 2.4.3102

**Closed by CouleeApps** 2021-11-05 23:00 UTC
Labels: bug, ui, Impact: Medium, Effort: Trivial
