### ISSUE TITLE
Result of `Display as` -> `Enum Member` gets 'stuck' after renaming enum members

### ISSUE THREAD

**Issue by alexrp** [Vector35/binaryninja-api#4486] opened 2023-07-13 17:37 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4387-dev Personal (71942341)
- OS: Windows
- OS Version: 10.0.25375.1
- CPU Architecture: x64

**Bug Description:**
When using `Display as` -> `Enum Member` on some lines and later renaming the enum members, the lines that had their display changed get 'stuck' - they continue to use the old names, and BN just completely refuses to change their display to anything else, too.

**Steps To Reproduce:**
1. Grab [this BNDB](https://drive.google.com/file/d/1mLCLJDAw_iA4oyaZi6dnCFAuo1iDC4Ol/view?usp=sharing).
2. Navigate to `0x7ff69bb40c08`.

**Expected Behavior:**
The enum member references should update with renames, and also not get 'stuck'.

**Screenshots:**
![image](https://github.com/Vector35/binaryninja-api/assets/44076/b653663e-bf89-41cf-9adb-e6731593e9d3)
![image](https://github.com/Vector35/binaryninja-api/assets/44076/34cdeb46-7600-4970-9af4-32c3febeeaec)

**Comment by plafosse** [comment] 2023-07-13 17:39
Yes this is an annoying bug you have to re-analyze the function an that should fix it I believe. I think this is a duplicate of https://github.com/Vector35/binaryninja-api/issues/4341

**Closed as completed by plafosse** 2023-07-13 17:39 UTC
Labels: State: Duplicate

**Comment by alexrp** [comment] 2023-07-13 17:41
Reanalyzing the function unfortunately does not seem to resolve it.
