### ISSUE TITLE
Navigation enchancements in disassembly, graph and types view

### ISSUE THREAD

**Issue by 3331** [Vector35/binaryninja-api#1310] opened 2019-03-26 16:57 UTC
### Graph views
- [x] Up/down: Highlight above/below line instead of scrolling
- [x] Left: Inner highlight previous item on same line, and if carret is at first item then go to line above and inner highlight last item instead of scrolling
- [x] Right: Inner highlight next item on same line, and if carret is at last item then go to line below and inner highlight first item instead of scrolling
- [x] Enter: `*` Already exists to follow pointer, but it feels a lot more intuitive to use enter instead imo.
- [ ] Backspace: Should probably have same behaviour as `Esc` in this view
- [ ] Middle mouse: Click anywhere even on graph blocks to drag the view around, instead of highlighting a line in a graph block.

I am not sure about what is more sensible when it comes to up/down/left/right and following the next block in a graph, maybe some intermediate state where the 2 graph lines are highlighted as you reach the end of a block while navigating with arrows and then you press left/right to choose which one to follow.

### Disassembly view
- [x] Up/down: It would make more sense if these buttons changed highlight carret like suggested in graph views, instead of scrolling
- [x] Left/right: Same as up/down except they should control the inner highlight carret like suggested in graph views, instead of doing nothing
- [x] Enter: Same as above
- [ ] Backspace: Should probably have same behaviour as `Esc` in this view

### Types view
- [x] Up/down: works as expected
- [ ] Left/right: same as above, should move inner highlight carret
- [ ] Enter: Open `Edit Field Type...`
- [ ] Double click on type: Open `Edit Field Type...`

Side note: strings view already has a `Enter` and `Double click` to follow string so it would be nice to carry this over to the other view types as well.

**Comment by psifertex** [comment] 2019-03-27 18:40
Many of these are coming in the next few weeks as a part of the 1.2 UI refactor so I'm converting this into a checklist so that we can mark individual features as we implement them. Lots of good ideas here.

**Comment by 3331** [comment] 2019-03-27 21:46
Another general thing in all views should be selecting an area of text (mouse click and drag to mark text, or ctrl/shift click/arrows to select text areas)

- [ ] CTRL/SHIFT + Click/arrows selecting behaviour (like in any normal text editor)

Im not sure how this will conflict with the inner highlight when clicking single items but I think it should be possible to make it work in a seamless and intuitive way.

**Comment by psifertex** [comment] 2019-03-27 21:48
That last one is a duplicate of #91 and is one of our top priorities right now and should be done within a few weeks at most.

**Comment by psifertex** [comment] 2019-03-27 21:48
Accordingly, I'm just going to check it here as a duplicate of the original and you can follow that bug for status updates to it.

**Comment by plafosse** [comment] 2019-07-17 18:44
Most of these are done, the ones that aren't done can be added through the keybindings ui

**Closed by plafosse** 2019-07-17 18:44 UTC
Labels: enhancement, ui
