### ISSUE TITLE
Crash when searching for single byte hex string

### ISSUE THREAD

**Issue by JesseAusten** [Vector35/binaryninja-api#2656] opened 2021-09-25 04:34 UTC
**Binary Ninja Version**
2.4.3008-dev

**Describe the bug**
Searching an entire binary for a single byte hex string crashes the program (it was a typo, I'm not actually trying to index a gazillion instructions). Below is a screenshot of the search settings.

**To Reproduce**
See screenshot for search settings to reproduce.

**Expected behavior**
Program hangs for a second and then silently crashes.

**Screenshots**
http://puu.sh/IdNM8/5a540c10a7.png

**Version and Platform (required):**
 - Binary Ninja: 2.4.3008-dev
 - OS: Windows 10
 - Version 10.0.19043 Build 19043

**Additional context**
Binary being reversed is windows x86

**Comment by psifertex** [comment] 2021-09-27 17:16
Also, can you share what `bv.segments` looks like for that particular file?

**Comment by JesseAusten** [comment] 2021-09-27 22:05
File size is 643 KB.
Segment mapping is
`[<segment: 0x10000000-0x10000400, r-->, <segment: 0x10001000-0x1006e9d4, r-x>, <segment: 0x1006f000-0x1008b448, r-->, <segment: 0x1008c000-0x10097f18, rw->, <segment: 0x10098000-0x100981e0, r-->, <segment: 0x10099000-0x100a3628, r-->]`

This is actually the PwnAdventure3 GameLogic.dll binary for win32.
As a side note, Binary Ninja repeatedly crashed upon loading the associated pdb file on dev branch. I had to switch back to stable to get it to load.

**Comment by psifertex** [comment] 2021-09-27 22:52
Thanks -- I can reproduce the PDB bug, I'll file a new issue to track that one, appreciate you catching that.

I still can't reproduce the problem searching for `12` though -- I opened the `gamelogic.dll` file, do a search:
<img width="432" alt="Screen Shot 2021-09-27 at 6 50 03 PM" src="https://user-images.githubusercontent.com/140215/134995722-219ff534-d3df-4289-9ace-feae8fbd82c1.png">

And get the results:

<img width="1868" alt="Screen Shot 2021-09-27 at 6 50 20 PM" src="https://user-images.githubusercontent.com/140215/134995758-3480efcf-9e39-433e-bad6-dfe98dfc1b8b.png">

Are you by chance running BN in a VM with a very small amount of RAM? Even

**Comment by JesseAusten** [comment] 2021-09-28 00:18
The search oddly seems to work for me now. It was not in a VM, and 32GB of RAM. If I can reproduce it I'll let you know.

**Comment by psifertex** [comment] 2021-09-28 00:32
Sounds good. Closing for now but definitely reopen if you reproduce it.

**Closed by psifertex** 2021-09-28 00:32 UTC
Labels: question, Can't Reproduce
