### ISSUE TITLE
Comments Hidden Based on Proximity of Another Comment

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#6140] opened 2024-11-15 19:55 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5902
- OS: macOS
- OS Version: 15.1 (24B83)
- CPU Architecture: x64

**Bug Description:**
When setting comments in a data section, if there is a comment immediately below it, it will be hidden.

**Steps To Reproduce:**
1. Navigate to a data section of a PE.
2. Click on a location in a struct
3. Right click and add a comment
4. Add the same comment to the address right above that one.
5. Notice that the first comment is now hidden.

**Expected Behavior:**
All comments visible regardless of presence of neighboring comments.

**Screenshots/Video Recording:**

https://github.com/user-attachments/assets/c53ff032-fbb6-4e8d-9878-061a68a2d041

**Comment by psifertex** [comment] 2024-11-15 20:19
This is already resolved on the latest dev, new stable should be out next week with this fix. Duplicate of https://github.com/Vector35/binaryninja-api/issues/5550

**Closed as not planned by psifertex** 2024-11-15 20:19 UTC
Labels: State: Duplicate

**Comment by utkonos** [comment] 2024-11-15 20:38
Issue search would be a legit use case for an LLM.

I tried, but not hard enough:

<img width="842" alt="image" src="https://github.com/user-attachments/assets/addb8f6b-3562-4654-abb5-e0019c189347">

**Comment by psifertex** [comment] 2024-11-15 20:41
"is:open" is the main issue there. Well, also "not showing" is too specific since "hidden" is a synonym. It was actually recent enough that just "comment" would have been better. 

I agree GH search could definitely be better. I often can't find issues I _know_ exist.

**Comment by fuzyll** [comment] 2024-11-15 20:41
It still doesn't show with "closed". You'd have also needed "visible" instead of "showing". We really do need a fuzzy search with synonyms for some of these.

**Comment by utkonos** [comment] 2024-11-15 20:45
Could Sidekick do this? I would defintiely ask Sidekick before opening a bug issue.

**Comment by psifertex** [comment] 2024-11-15 20:51
Not currently but that's a great suggestion. We could probably feed it the list of all software issues and let users search that via sidekick in the UI.
