### ISSUE TITLE
Highlight register _and_ sub-registers

### ISSUE THREAD

**Issue by sizzop** [Vector35/binaryninja-api#841] opened 2017-10-13 18:25 UTC
Can we have the option to highlight sub-registers when I click on registers in the main graph view?

When trying to track changes to a register within a function my first move is typically to click on the register to highlight it and take a quick look around to see what instructions might be referencing it. In BN (1.1.922 Build ID 4d40ebb7) when I click a register, it does not highlight sub-registers. This makes it so that I can't as easily follow changes to a register if only the sub-register is modified.

e.g. I click on r14, scroll up and see that no other instructions have touched it since it was pushed in the prologue. Except that doesn't make sense, so I look further and find that r14d was modified but it wasn't highlighted.

Thanks!

**Comment by plafosse** [comment] 2018-01-12 03:02
This is a dupe of #321

**Closed by plafosse** 2018-01-12 03:02 UTC
Labels: duplicate
