### ISSUE TITLE
Segmentation fault in `PyType_Ready`

### ISSUE THREAD

**Issue by g0ldminer** [Vector35/binaryninja-api#5394] opened 2024-05-10 11:55 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4958
- OS: Fedora Linux
- OS Version: 40
- CPU Architecture: x64

**Bug Description:**
I have recently updated my Fedora packages, including python updates, which have now lead to segfaulting binary ninja when opening. I have Python 3.12.3 and I'm using the latest stable release. I have attached screenshots from GDB with binary ninja as the target program.

**Steps To Reproduce:**
> Disclaimer: I'm not sure if this is an environment issue or this affects all Fedora distributions with the latest python packages installed.
1. gdb binaryninja
2. run
3. wait for segfault

**Expected Behavior:**
Not segfault.

**Screenshots:**
![Screenshot from 2024-05-10 13-45-37](https://github.com/Vector35/binaryninja-api/assets/154477347/ad5072a4-0b76-4897-8acb-21178dad2fc3)
![Screenshot from 2024-05-10 13-45-50](https://github.com/Vector35/binaryninja-api/assets/154477347/ac928364-e604-4e34-ae9d-584ee1638372)

**Additional Information:**
Additionally, I can also provide a core dump (probably via email because the file (31MB) exceeds github's maximum file size limit).

**Comment by negasora** [comment] 2024-05-10 12:41
Duplicate of #5392 
Until the upstream bug is fixed using a virtual environment with an older python might prevent the crash

**Closed by negasora** 2024-05-10 12:41 UTC

**Comment by psifertex** [comment] 2024-05-10 17:03
Another work-around is to downgrade your local Python to 3.12.2 or use a pipenv, Docker, etc.
