### ISSUE TITLE
Search ignores the "search range"

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#6071] opened 2024-11-01 07:21 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6330-dev Personal (ce297927)
- OS: manjaro Linux
- OS Version: Linux version 6.10.13-3-MANJARO (builduser@fv-az1246-770) (gcc (GCC) 14.2.1 20240910, GNU ld (GNU Binutils) 2.43.0) #1 SMP PREEMPT_DYNAMIC Tue Oct  8 03:24:49 UTC 2024
- CPU Architecture: x64

**Bug Description:**
![image](https://github.com/user-attachments/assets/dbd5d81d-3643-4163-a1d9-5fd10e5a6260)
when we check the option of Find All, is the Search range of Current function still usefull?
Because in this case, we will find many other positions out of the scope of current function.

![image](https://github.com/user-attachments/assets/5c453a65-56e8-4b33-bb0c-839240f1f00b)

**Comment by xusheng6** [comment] 2024-11-05 08:56
It seems that we are somehow ignoring the search range no mater either "Current Function" or "Custom Range" is selected

**Comment by bb33bb** [comment] 2024-11-05 11:43
> It seems that we are somehow ignoring the search range no mater either "Current Function" or "Custom Range" is selected

是的。😄

**Comment by xusheng6** [comment] 2024-11-06 03:44
This is a regression since the last stable

**Comment by xusheng6** [comment] 2024-11-06 05:40
This is broken in 4.2.5824-dev

**Comment by xusheng6** [comment] 2024-11-07 07:47
This is more complicated than it seems. We will need someone else to look at it. Here is a simple repro:

1. Open [helloworld.zip](https://github.com/user-attachments/files/17657851/helloworld.zip) 
2. Navigate to `main` as the current function, ensure you are in HLIL
3. Press CMD+F
4. Type in "a"
5. Select "Current Function" as the search range
6. Search
7. Observe there are many matches whose address is beyond the end of function

![Screenshot 2024-11-07 at 3 48 33 PM](https://github.com/user-attachments/assets/a4ad5b7c-dc9e-4adf-91f1-d5bea827aaae)

**Comment by bpotchik** [comment] 2024-11-07 14:54
Fixed in `4.2.6386-dev`.

**Closed as completed by bpotchik** 2024-11-07 14:54 UTC
Labels: Component: Core, Effort: Low, Impact: Critical
