### ISSUE TITLE
Theme switching based on system theme

### ISSUE THREAD

**Issue by fabianfreyer** [Vector35/binaryninja-api#2505] opened 2021-06-13 12:10 UTC
On systems that allow a global dark/light mode switch, please allow specifying a default dark and light theme that automatically switch based on the system theme.

**Comment by jonpalmisc** [comment] 2021-06-13 14:16
This looks to be a duplicate of https://github.com/Vector35/binaryninja-api/issues/2505. I'm going to close this issue in favor of that one, but feel free to add a thumbs up reaction there to "vote" for the issue.

**Closed by jonpalmisc** 2021-06-13 14:16 UTC
Labels: duplicate, enhancement
