### ISSUE TITLE
Right-click -> Copy in Symbols view does not work as expected

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#2516] opened 2021-06-18 11:15 UTC
Selecting a symbol in the symbols list then right-clicking and choosing copy does not copy the symbols name. It should.

Additionally, it should copy whichever form of the symbol name is currently shown - demangled or mangled.

Running 2.4.2871 on macOS at time of reporting.

**Comment by galenbwill** [comment] 2021-06-18 12:42
In lieu of select-all & copy, i have wanted a "copy all" action, that would copy all the currently visible symbols (in their current form)

**Comment by plafosse** [comment] 2021-10-01 18:09
Duplicate of #1918

**Closed by plafosse** 2021-10-01 18:09 UTC
Labels: bug, duplicate, ui, Impact: Medium, bugbash, Effort:Trivial
