### ISSUE TITLE
Improved Mappings Between Disassembly and HLIL

### ISSUE THREAD

**Issue by Thiefyface** [Vector35/binaryninja-api#2705] opened 2021-10-14 20:55 UTC
Binary Ninja Version 2.4.3068
OS: Ubuntu 20.04.2

When toggling between the HLIL and disassembly modes, in either graph or linear mode, if you go from HLIL to disassembly, then you're fine, you land in the same location that you'd expect. The issue lies when navigating from disassembly to HLIL. If you switch views on certain instructions, your graph/linear disassembly ends up in a completely different spot. To elaborate, for the following disassembly basic block:

`lw      $v0, -0x7840($gp)  {0x834570}  {g_board_version}`
`nop`     
`lw      $v1, ($v0)  {g_board_version}`
`addiu   $v0, $zero, 2`
`bne     $v1, $v0, 0x57c178`
`nop`     

Who's corresponding HLIL basic block looks like so: `if (g_board_version != 2)`, if I have any disassembly line besides the `bne     $v1, $v0, 0x57c178` highlighted, my view winds up in the middle of fuck nowhere and I gotta find my way back.  

A similar issue also seems to occur when navigating to certain xrefs (via the Cross References side-window) in that either the view change works, doesn't change at all, or is placed in a random spot, which is making navigating in HLIL a massive pain in the ass.

**Comment by KyleMiles** [comment] 2021-10-14 21:11
Possible duplicate of #2371

**Comment by psifertex** [comment] 2022-01-24 20:10
I think there were two related issues. The first was #2371 but with that complete, we're still seeing the other one. Specifically for graph <-> linear transitions using the menu versus using <SPACE> to toggle. I'm renaming this issue accordingly and scheduling it for 3.1 because it does break workflows and is kinda annoying even if there is a work-around for now (use space).

**Comment by bpotchik** [comment] 2022-05-04 21:30
This is a duplicate of #2731. However the specific mapping pointed out by OP works just fine now and has for a while.

```
>>> current_hlil[10]
<HLIL_IF: if ((($t3 - 0x3ff00000) | arg5) == 0)>
>>> current_hlil[10].llil
<llil: if (temp1#3.d != 0) then 71 @ 0x4003ac else 76 @ 0x400398>
>>> bv.get_disassembly(current_hlil[10].address)
'bne     $v0, $zero, 0x4003ac'
```

**Closed by bpotchik** 2022-05-04 21:30 UTC
Labels: bug, HLIL, Effort: Low, Impact: Medium
