### ISSUE TITLE
hlil.dest.value returns <unavailable>

### ISSUE THREAD

**Issue by CunningLogic** [Vector35/binaryninja-api#1670] opened 2020-05-15 16:05 UTC
mlil.dest.value returns the address of a call, but hlil.dest.value returns <unavailable>

Work around here for me was to use hlil.dest.constant.

Version 2.0.2144-dev (Build ID f704503e)

**Comment by D0ntPanic** [comment] 2020-05-18 22:18
Caused by #1683

**Comment by D0ntPanic** [comment] 2020-06-24 04:26
Fixed in build 2242

**Closed by D0ntPanic** 2020-06-24 04:26 UTC
Labels: HLIL, bug
