### ISSUE TITLE
More fine grained copy and paste

### ISSUE THREAD

**Issue by gsingh93** [Vector35/binaryninja-api#457] opened 2016-09-07 17:24 UTC
Sorry if there's already an issue about this.

I'd really like more fine grained copy and paste options. I believe the best way to do this is to let the user select any text in the graph/linear view and making ctrl-c/cmd-c copy that text. This way, the user can copy an address, opcodes, the instruction, the instruction operands, multiple lines of instructions, etc.

I'm fine with adding some more copy commands to the context menu (copy address, copy instruction, copy line, etc.), but I think having freeform selection is much more important and powerful.

**Comment by plafosse** [comment] 2016-09-09 15:18
Dupe of #91

**Closed by plafosse** 2016-09-09 15:18 UTC
