### ISSUE TITLE
Add break statement in switch statement of HLIL window

### ISSUE THREAD

**Issue by pr0xy-t** [Vector35/binaryninja-api#3743] opened 2022-12-16 05:44 UTC
**Add break statement in switch statement of HLIL window**

[fuga.zip](https://github.com/Vector35/binaryninja-api/files/10242921/fuga.zip)
When I analyze this binary (fuga.o) , the break statement is not displayed in the switch statement of the HLIL window as shown in below picture. 
I want the break statement to be displayed in the HLIL window because I mainly look at the HLIL window to analyze.
If I only look at the HLIL window, I cannot tell whether the break statement exists or not in terms of the semantics of the program.

That is ,  I would like the break statement to be added to the switch statement in the HLIL window, just as it is displayed in the pseudo c window.

![Screenshot from 2022-12-16 14-28-54](https://user-images.githubusercontent.com/42575435/208028927-dfd0b053-bd97-44fe-81f9-9fca25aae1dd.png)

**Comment by ccarpenter04** [comment] 2022-12-16 10:57
Wow, I never noticed that but you're right, the HLIL isn't clear about where breaks are happening at all.

**Comment by pr0xy-t** [comment] 2022-12-16 23:53
One reason this is difficult to notice is that binaryninja often displays switch statements as if statements, even if they are switch statements.

**Comment by D0ntPanic** [comment] 2023-01-09 19:21
HLIL is not C. Switch statements in HLIL do not have fallthrough, so break statements will not appear at the end of cases. This is intentional and not a bug. If you want C, use the Pseudo-C view.

**Comment by ccarpenter04** [comment] 2023-01-09 22:34
> HLIL is not C. Switch statements in HLIL do not have fallthrough, so break statements will not appear at the end of cases. This is intentional and not a bug. If you want C, use the Pseudo-C view.

Where are the syntax guidelines for HLIL documented?

**Comment by psifertex** [comment] 2023-01-09 22:37
From an API perspective, everything should be documented via: 
https://api.binary.ninja/_modules/binaryninja/highlevelil.html#HighLevelILInstruction

which has all instructions and their possible operands. 

From just a reading perspective:

https://docs.binary.ninja/dev/bnil-overview.html#reading-il

**Comment by psifertex** [comment] 2023-01-09 22:38
And yes, I did just point to source as documentation as if this were some open source project. 😉 

We do plan on expanding the documentation of HLIL to match those for [LLIL](https://docs.binary.ninja/dev/bnil-llil.html) and [MLIL](https://docs.binary.ninja/dev/bnil-mlil.html) but for now the previous links are the best (and you'll notice much of the content is duplicated there anyway).

**Comment by pr0xy-t** [comment] 2023-01-11 08:25
> HLIL is not C. Switch statements in HLIL do not have fallthrough, so break statements will not appear at the end of cases. This is intentional and not a bug. If you want C, use the Pseudo-C view.

OK. I understood about HLIL not having a fallthrough syntax.

Then, when I analyze the attached program, the "case 4" is not correct, is it?

![Screenshot from 2023-01-11 17-23-41](https://user-images.githubusercontent.com/42575435/211754920-66be555d-ccb7-4bc6-b04e-b2f0e7db404e.png)

[switch4.zip](https://github.com/Vector35/binaryninja-api/files/10390133/switch4.zip)

**Comment by pr0xy-t** [comment] 2023-01-11 08:28
By the way, I think the "psedo c" window is wrong when analyzing that program.
![Screenshot from 2023-01-11 17-28-05](https://user-images.githubusercontent.com/42575435/211755800-2319681e-2e70-44d6-9e55-b12803d5e3f2.png)

**Comment by psifertex** [comment] 2023-01-11 19:48
Good catch -- that is 100% a bug and we need to fix it. Re-opening.

**Comment by D0ntPanic** [comment] 2023-04-06 19:09
The HLIL control flow recovery system was not validating that default cases cover all values not covered by other cases and do not overlap with other cases. This is fixed in 3.4.4198.

There is currently no support for representing a fall through into a default case directly, so the decompiler now emits an if statement to cover it below the switch.

**Closed by D0ntPanic** 2023-04-06 19:09 UTC
Labels: bug, enhancement, HLIL, IL Optimization

**Comment by pr0xy-t** [comment] 2023-04-08 02:02
@D0ntPanic 
Thanks for fixing the bug :) 

What do you think about a idea to use HLIL_GOTO when doing HLIL control flow recovery?
In this case, I think the output looks a little cleaner since no if statements are generated.
