### ISSUE TITLE
Binary Ninja - Update subsystem: Windows - Cannot Update; cannot locate Python

### ISSUE THREAD

**Issue by nathaniel-gray** [Vector35/binaryninja-api#1139] opened 2018-08-30 06:06 UTC
Binary Ninja Version: 1.1.1259 Personal, f51163e8
Platform: Windows 10 (10.0)

**When:** Brand new install @ 20180830.
**What:** 
- Errors identified in the log:
-- Unable to initialize Python API
-- Error fetching channel list: Download provider: DefaultDownloadProvider not available!

- Warning identified in the log:
-- Falling back to bundled Python; system failed to load ''

Prior to this issue, I also experienced the DownloadProvider issue with the 1.1.30... release-personal-dev update channel.

Impact from error:
- Python not available within Binary Ninja
- Binary Ninja unable to locate correct settings to populate the Update Channel and Select Version fields in the Updates section of the Preferences dialog.

Note: Have not attempted to recreate in Linux.

[Edit @ 20180830 :: 0212 EST] Additional reproduction steps:
- Reverted to installer for 1.1.922 Personal, Build ID 4d40ebb7 (clean install)
- Restarted application, the auto-upgrade feature downloaded successfully.
- Installation update verifier runs.
- Result: update to: 1.1.1259 Personal, Build ID f5116e8
-- Python API still won't initialize
-- DefaultDownloadProvider no longer available (original reported error)

**Comment by psifertex** [comment] 2018-08-30 12:30
The warning about falling back to buit in isn't a problem, it was fixed in recent dev builds. That said, the error and lack of updates is a problem. 

Can you verify the hash of the installer via https://binary.ninja/js/hashes.js to make sure it wasn't corrupted? 

Do you have anything in your settings.json? (See: https://docs.binary.ninja/getting-started/index.html).

**Comment by rssor** [comment] 2018-08-30 22:14
As a quick additional check: do you have a version of Python installed system-wide, and if so, is `PYTHONPATH` set in your environment?

If so, I'd try both starting Binary Ninja with no Python environment variables set, seeing if that lets our bundled Python initialize successfully, or alternatively manually pointing the Python interpreter in `settings.json` to the `python27.dll` from your system/user installation.

**Comment by nathaniel-gray** [comment] 2018-09-01 04:04
Sorry for the wall of text (and delay getting you answers):

Quick question: what's the settings.json config string to point to a specific python interepreter? I didn't see that in the getting-started table of settings, and the preferences modal doesn't allow you to specify there.

---
C:\Users\usera>echo %PYTHONPATH%
C:\Python27\Lib;C:\Python27\DLLs

Installers:
BinaryNinja-personal-windows.exe                            | 

$ md5sum BinaryNinja-personal-windows_1.1.922_4d40ebb7.exe
2f8ccf9b4aaaabd3352d8f62dc8a7e07 *BinaryNinja-personal-windows.exe

usera@lalala /cygdrive/f/tools/BinaryNinja
$ sha256sum BinaryNinja-personal-windows_1.1.922_4d40ebb7.exe
82582985bdaf5e03bc95e86c9fc7240143e8c5c6d95c4972c4ab4e95ba946f05 *BinaryNinja-personal-windows.exe


BinaryNinja-personal-windows_20180830_1.1.1259_f51163e8.exe | 

$ md5sum BinaryNinja-personal-windows_20180830_1.1.1259_f51163e8.exe
2bef8e453450b2b7bb7f19c6e83cf9d6 *BinaryNinja-personal-windows_20180830_1.1.1259_f51163e8.exe

usera@lalala /cygdrive/f/tools/BinaryNinja
$ sha256sum BinaryNinja-personal-windows_20180830_1.1.1259_f51163e8.exe
fa517214a0f7464a5579cd17bc00a628c6a6febbf38e390fe72afe53e16217bc *BinaryNinja-personal-windows_20180830_1.1.1259_f51163e8.exe

----
[Fresh Install]
1.1.922 Personal, Build ID 4d40ebb7
C:\Users\usera\AppData\Roaming\Binary Ninja\settings.json
pre-install:    N/A
post-install:   N/A
running:        
{
	"ui" : 
	{
		"colorblind" : false
	}
}

update/ba42f444c143ece14f00d93076b91b5a9fcee30b17ef9cec2f7bf5bdf60acc50/manifest
{"auto":true,"channel":"release-personal","last_check":0,"pending":false}

Auto-update ran automatically; successfully

Restart:
1.1.1259 Personal, Build ID f51163e8

Result: Auto-update cannot find DefaultDownload Provider

[Interrupt auto-update by specifying settings in the manifest file]
- Default Update channel: "latest Binary Ninja Personal release"
- Switch to "Binary Ninja Personal development build 1.1.1313-dev Personal" via manifest (or modal)

manually updating manifest: {"auto":false,"channel":"dev-personal","last_check":0,"pending":false}

- Help - Check for Updates - <Downloading...> - 975 files
- Update path: C:\Users\usera\AppData\Roaming\Binary Ninja\update\ba42f444c143ece14f00d93076b91b5a9fcee30b17ef9cec2f7bf5bdf60acc50
- manifest file: {"auto":false,"channel":"dev-personal","last_check":0,"pending":false}
- application restart: version reflected: 1.1.1313-dev Personal, Build ID 3f8fa19e
- mainfest file updates: shows the hash of all files
- update directory updated, 964 / 975 files deleted
- BinaryNinja main path: C:\Program Files\Vector35\BinaryNinja
-- uninstall.exe does not exist after update
-- python path: C:\Program Files\Vector35\BinaryNinja\python\binaryninja | python scripts exist

----

[Fresh Install]
1.1.1259 Personal, Build ID f51163e8
C:\Users\usera\AppData\Roaming\Binary Ninja\settings.json
pre-install:    N/A
post-install:   N/A
running:   
{
	"ui" : 
	{
		"colorblind" : false
	}
}

manually updating manifest: {"auto":false,"channel":"release-personal","last_check":0,"pending":false}


Result: Auto-update cannot find DefaultDownload Provider

Specifying the manifest directly: {"auto":false,"channel":"release-personal","last_check":0,"pending":false}
Select version dropdown box is empty

**Comment by psifertex** [comment] 2018-09-03 18:26
Yup, definitely looks like the problem is the existing python install conflicting. You have two options: either remove the pythonpath so that our existing python doesn't try to load libraries from a different install, or point BN to be using that python directly instead (with something like: https://gist.github.com/psifertex/a1cd72f2a4ecafb309fe64ce0c5e6612)

**Comment by psifertex** [comment] 2018-09-10 17:12
Haven't heard back yet, but we're pretty confident the above solution will work so I'm going to close this issue out. If you still have problems after following the above troubleshooting, feel free to re-open.

**Closed by psifertex** 2018-09-10 17:12 UTC
