### ISSUE TITLE
Unresolved indirect control flow: Jump to unhandled / unknown possible value set

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4332] opened 2023-05-22 13:08 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4286-dev, 58311b01
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

There's nothing wrong with the following BN disassembly but...

```
00036784  void sub_36784()

00036784  10b5       push    {r4, lr} {var_4} {__saved_r4}
00036786  064c       ldr     r4, [pc, #0x18]  {data_367a0}
00036788  2268       ldr     r2, [r4]  {data_20053a44}
0003678a  12b1       cbz     r2, #0x36792

0003678c  4ff4fa60   mov     r0, #0x7d0
00036790  9047       blx     r2

00036792  6368       ldr     r3, [r4, #4]  {data_20053a48}
00036794  13b1       cbz     r3, #0x3679c

00036796  bde81040   pop     {r4, lr} {var_4} {__saved_r4}
❓0003679a  1847       bx      r3

0003679c  10bd       pop     {r4, pc} {__saved_r4}
```

Why the warning and the strange HLIL and Pseudo-C?

```
00036784  void sub_36784()

00036784      int32_t lr
00036784      int32_t var_4 = lr
00036788      int32_t r2 = data_20053a44
0003678a      if (r2 != 0)
00036790          r2(0x7d0)
00036792      int32_t r3 = data_20053a48
00036794      if (r3 == 0)
0003679c          return 
❓0003679a      jump(r3)
```

IDA shows

```
int sub_36784()
{
  int result; // r0

  if ( dword_20053A44 )
    result = dword_20053A44(2000);
  if ( dword_20053A48 )
    return dword_20053A48();
  return result;
}
```

Anyone from V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by negasora** [comment] 2023-05-22 14:09
Setting the return type to `int` makes the hlil match up with what you'd expect that function to look like.

As far as the tag, that's not a warning, just a notice that there's a jump to some unresolved location. I'm not sure why the `r2` call isn't marked with it though.

**Comment by joelreymont** [comment] 2023-05-22 14:17
No change after setting the return type

```
00036784  int32_t sub_36784()

00036784      int32_t lr
00036784      int32_t var_4 = lr
00036788      int32_t r2 = data_20053a44
0003678a      int32_t r0
0003678a      if (r2 != 0)
00036790          r0 = r2(0x7d0)
00036792      int32_t r3 = data_20053a48
00036794      if (r3 == 0)
0003679c          return r0
❓0003679a      jump(r3)
```

**Comment by plafosse** [comment] 2023-06-08 19:20
Ultimately this is a duplicate of https://github.com/Vector35/binaryninja-api/issues/4247

**Closed by plafosse** 2023-06-08 19:20 UTC
Labels: State: Duplicate, Type: Question, UI: Tags
