### ISSUE TITLE
Exceeds 'analysis.limits.maxFunctionUpdateCount'

### ISSUE THREAD

**Issue by mdaniel** [Vector35/binaryninja-api#4273] opened 2023-04-29 17:55 UTC
Binary Ninja Version: 3.3.3996 Personal, e34a955e
Platform: macOS Monterey (12.6)

> Skipping analysis for function at 0x1005f2380 : Exceeds 'analysis.limits.maxFunctionUpdateCount'. If possible, please report this issue.

There are 18 such lines, with differing function addresses. I can get you the binary it used if that's helpful, or send the analysis database

I do see #3036 but it is reported as fixed so I'm guessing it is a regression?

**Comment by plafosse** [comment] 2023-06-08 15:02
There are many possibilities which can cause this issue. If you can share the binary we can potentially look into the cause of this. If you can't there is unfortunately nothing we can do about this.

**Comment by fuzyll** [comment] 2023-08-15 14:25
Closing this since it's been a few months and we haven't received information we need to replicate and fix the issue. Feel free to reopen if we're able to get a binary or database that we can reproduce this on.

**Closed by fuzyll** 2023-08-15 14:25 UTC
Labels: Type: Enhancement, Component: Core, State: Unreproducible, State: Blocked (Customer)
