### ISSUE TITLE
Better ADRP handling in ARM

### ISSUE THREAD

**Issue by mmaekr** [Vector35/binaryninja-api#5790] opened 2024-07-25 16:42 UTC
**What is the feature you'd like to have?**
Better ADRP handling (similar to #4650). 

**Is your feature request related to a problem?**
Binary Ninja creates a data variable at every ADRP base address. Besides generating a bunch of useless cross references to page boundaries, it can shorten a jump tables if they overlap with a page boundary. This leads to incorrect jump tables and bad further analysis. In the past, I have written a workflow that converted any ADRP/ADD combinations to just a single constant pointer, but it would be better if this was handled in Binary Ninja.

**Additional Information:**
You can see in the screenshot that the jumptable should continue, but the data variable at 0x187ec8000 (because of ADRP's) interrupts it.
![Clipboard - July 25, 2024 12_00 PM](https://github.com/user-attachments/assets/e87a1970-138b-4a7d-8de3-736c36707b0b)

**Comment by xusheng6** [comment] 2024-07-30 03:17
Duplicate of https://github.com/Vector35/binaryninja-api/issues/4528. I believe the real fix for the issue is to relax the jump table size detection code to allow it to overwrite some data variables, for example, when the data variable is void or otherwise does not provide much value

**Closed by xusheng6** 2024-07-30 03:17 UTC
