### ISSUE TITLE
`ExternalSymbol`s defined twice

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#4417] opened 2023-06-14 21:17 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4332-dev

**Bug Description:**
Symbols for externs are defined twice in some binaries and returned twice from relevant APIs (`get_symbols`, `get_symbols_of_type`, etc)

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open [program.txt](https://github.com/Vector35/binaryninja-api/files/11750617/program.txt)
2. Do `bv.get_symbols_of_type(SymbolType.ExternalSymbol)`
3. Notice symbols are returned twice

**Expected Behavior:**
Symbols are only defined once at a location via analysis

**Additional Information:**
As far as I can tell the symbols returned are identical

**Comment by plafosse** [comment] 2023-06-20 00:50
Duplicate of #4109

**Closed** 2023-06-20 00:53 UTC
Labels: Type: Bug, State: Duplicate, Component: Core, Impact: Low
