### ISSUE TITLE
Issues with union selection inside a struct

### ISSUE THREAD

**Issue by 0xFDFDFDFD** [Vector35/binaryninja-api#4218] opened 2023-04-14 00:47 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4224-dev Personal
- OS: Manjaro Linux
- CPU Architecture: x86_64

**Bug Description:**
When reversing a windows driver module I cannot select which union inside a struct is displayed. But it just displays it as an offset instead of CurrentStackLocation or PacketType.
Additionally the IL views are not consistent in displaying unions. High IL doesnt show any union while medium and low IL detects the Overlay struct but the sub types cannot be defined. 
**Steps To Reproduce:**
1. Load a windows kernel driver module
2. Define the IRP struct (Import it from wdm.h)
3. Try to select the union type inside Tail

**Expected Behavior:**
It is possible to select the union type and is not just written as an offset. In this case it should be currentstacklocation
**Screenshots:**

![high_level_il](https://user-images.githubusercontent.com/129995235/231912927-5f33e556-7286-405a-a9cc-0c7c617f922b.png)

![low_level_il](https://user-images.githubusercontent.com/129995235/231912970-41600ece-eba3-461c-805b-1c019a9d3799.png)

![part_ of_IRP_struct](https://user-images.githubusercontent.com/129995235/231913005-48ccc8fb-d056-4305-82b5-d3cd00e3b867.png)

**Comment by op2786** [comment] 2023-04-14 08:28
Could be related to #1013. Better union support is an urgent thing in my opinion.

**Comment by plafosse** [comment] 2023-05-30 13:19
Duplicate of https://github.com/Vector35/binaryninja-api/issues/1013

**Closed by plafosse** 2023-05-30 13:19 UTC
Labels: State: Duplicate
