### ISSUE TITLE
Structure growth doesn't always update fields

### ISSUE THREAD

**Issue by yrp604** [Vector35/binaryninja-api#2060] opened 2020-10-24 09:58 UTC
I have a structure:
```
struct VmState __packed
{
    uint16_t RA;
    uint16_t RB;
    uint16_t RC;
    uint16_t RD;
    uint16_t BP;
    uint16_t SP;
    uint16_t PC;
    uint16_t CondPC;
    uint16_t Flags;
}
```

It works like I expect (woo!):
```
00400f5d  struct VmState* vm = arg1->vm
00400f73  fprintf(stream: *stderr, format: "RA: %04x\n", zx.q(vm->RA))
00400f8b  fprintf(stream: *stderr, format: "RB: %04x\n", zx.q(vm->RB))
00400fa3  fprintf(stream: *stderr, format: "RC: %04x\n", zx.q(vm->RC))
```

I find some more fields, and add them, growing the structure:
```
struct VmState __packed
{
    uint16_t RA;
    uint16_t RB;
    uint16_t RC;
    uint16_t RD;
    uint16_t BP;
    uint16_t SP;
    uint16_t PC;
    uint16_t CondPC;
    uint16_t Flags;
    uint16_t Scratch0;
    uint16_t AddTmp;
    uint16_t SubTmp;
    uint16_t CmpTmp;
    uint16_t MemValue;
    uint16_t MemReg;
    uint16_t ConstantOne;
};
```

However, in that same function, the previous undef results aren't updated:
```
0040111c  fprintf(stream: *stderr, format: "Scratch0: %04x\n", zx.q(vm->__offset(0x12).w))
00401134  fprintf(stream: *stderr, format: "AddTmp: %04x\n", zx.q(vm->__offset(0x14).w))
0040114c  fprintf(stream: *stderr, format: "SubTmp: %04x\n", zx.q(vm->__offset(0x16).w))
```

Changing graph/linear and cycling through all the ILs doesn't cause this to update automatically. If I re-set the type on `vm` however, this _will_ update. This definitely does work sometime, so I'm not sure what the issue here is. Relevant function is `DumpMemory`.

[rootkit.txt](https://github.com/Vector35/binaryninja-api/files/5432681/rootkit.txt)

**Comment by plafosse** [comment] 2020-10-24 10:27
Does updating analysis for the function fix the IL?

**Comment by jeffli678** [comment] 2020-10-24 10:31
I have encountered similar issues. Sometimes creating new fields in a
structure also fail to trigger an update. In my case, updating the analysis
does fix the issue

**Comment by yrp604** [comment] 2020-10-24 20:11
No it does not, presuming that I'm updating analysis correctly (right click -> reanalyze current function).

**Comment by jeffli678** [comment] 2021-04-20 04:28
I cannot reproduce this. Given this issue has been there for a while, it might have been fixed earlier. If one can still reproduce it, please quote me with some details and I can start checking it out again.

**Comment by jeffli678** [comment] 2021-04-20 05:41
Nope, this is not fixed. The HLIL appears to be correct thanks to the periodic update of the display, though the type changes are not propagated in the system

**Comment by jeffli678** [comment] 2021-04-21 03:06
This should have been fixed when I merged the PR on type xref. Now when a type (in the type view) changes, all functions that references it gets updated. I am closing this, but if anyone has more information on this, please free feel to reopen it.

**Comment by yrp604** [comment] 2021-05-01 09:19
@jeffli678 I was just able to reproduce this again -- you can see the definition for hash_entry is out of sync.

![image](https://user-images.githubusercontent.com/8716677/116777745-df7c3000-aa22-11eb-97b5-0c8308390034.png)
![image](https://user-images.githubusercontent.com/8716677/116777751-e5721100-aa22-11eb-9cf7-68b9518237df.png)

One thing I realized I do which might be relevant: I will frequently split a bndb to two tabs tab, and one tab be disas while the other stays on the types view. Could this be the pattern that causes this desync?

Attached bndb also demonstrates the problem -- if i re-declare the variable at hlil addr 000015ba it will be resolved.
[mooosl - Copy.bndb.txt](https://github.com/Vector35/binaryninja-api/files/6409278/mooosl.-.Copy.bndb.txt)

**Comment by yrp604** [comment] 2021-05-01 09:20
Sorry, this was on 2780-dev

**Comment by jeffli678** [comment] 2021-05-04 05:03
yrp reported another way to trigger this, though in a slightly more complex way

**Comment by jeffli678** [comment] 2021-05-04 05:34
moved the report to a dedicated issue: https://github.com/Vector35/binaryninja-api/issues/2428

**Closed by jeffli678** 2021-05-04 05:34 UTC
Labels: bug
