### ISSUE TITLE
Wrapping of really long lines

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#5552] opened 2024-06-11 11:09 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5458-dev,  6421303
- OS: macos
- OS Version: 14.5
- CPU Architecture: arm64

Internal binary `major dine favor`.

`DjiCore_Init`...

This would be much more readable if each condition was on a separate line

```
00066558                                                          if ((baseInfo.aircraftType != DJI_AIRCRAFT_TYPE_M300_RTK && baseInfo.aircraftType != DJI_AIRCRAFT_TYPE_M350_RTK) || ((baseInfo.aircraftType == DJI_AIRCRAFT_TYPE_M300_RTK || baseInfo.aircraftType == DJI_AIRCRAFT_TYPE_M350_RTK) && baseInfo.djiAdapterType != DJI_SDK_ADAPTER_TYPE_SKYPORT_V2 && baseInfo.djiAdapterType != DJI_SDK_ADAPTER_TYPE_XPORT) || ((baseInfo.aircraftType == DJI_AIRCRAFT_TYPE_M300_RTK || baseInfo.aircraftType == DJI_AIRCRAFT_TYPE_M350_RTK) && (baseInfo.djiAdapterType == DJI_SDK_ADAPTER_TYPE_SKYPORT_V2 || baseInfo.djiAdapterType == DJI_SDK_ADAPTER_TYPE_XPORT) && err_10 == 0))
00066614                                                              int64_t err_11
```

**Comment by xusheng6** [comment] 2024-06-11 11:12
Duplicate of https://github.com/Vector35/binaryninja-api/issues/3289

**Closed by xusheng6** 2024-06-11 11:12 UTC
