### ISSUE TITLE
Cannot change the type of a struct or type using the "Change Type..." option from the context menu

### ISSUE THREAD

**Issue by masl123** [Vector35/binaryninja-api#1634] opened 2020-05-01 12:59 UTC
**Description of the Problem:**
You cannot change the type of a struct or type using the "Change Type..." option from the context menu.

**Example:**
1. Open some executable using File-->Open
2. wait for the autoanalysis to complete
3. Open the Types View
4. create a new struct using e.g. the "Create New Types..." option.
The struct added may look like this.
```
struct notempty
{
   int i;
};
```
5. select the name of the newly created struct.
6. open the context menu and select the option "Change Type..." or use the shortcut 'Y'
7. a dialog should open. 
8. click on the "Create" Button
9. Error Message

**Info:**
Binary Ninja Version: 2.0.2111-dev Personal, 5466385d
Platform: Windows 10 Version 1803

**Comment by jeffli678** [comment] 2020-09-03 07:26
closing since it is duplicate of https://github.com/Vector35/binaryninja-api/issues/1665

**Closed by jeffli678** 2020-09-03 07:26 UTC
Labels: bug
