### ISSUE TITLE
Add 'Find Previous' (e.g. Ctrl+shift+G)

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#4855] opened 2023-12-30 10:12 UTC
![image](https://github.com/Vector35/binaryninja-api/assets/5463104/4cd5dfe3-cb4a-4862-a204-81c968ad7066)

**What is the feature you'd like to have?**
Please provide a clear and concise description of what you want.
when search for something , somtimes we use Ctrl+G
becasue the confusing time of searching the whole image, may be Ctrl+G is a better methord.
But when using Ctrl+G, we easily missed our destination
So is there a Ctrl+shift+G to go back?
**Is your feature request related to a problem?**
no
**Are any alternative solutions acceptable?**

**Additional Information:**

**Comment by xusheng6** [comment] 2024-01-03 05:50
Duplicate of https://github.com/Vector35/binaryninja-api/issues/3679

**Closed by xusheng6** 2024-01-03 05:50 UTC
