### ISSUE TITLE
Weird structure field offsets

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4394] opened 2023-06-07 15:44 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4317-dev, a5d64740
- OS: macos
- OS Version: 13.4
- CPU Architecture: arm64

Note the proper offsets into structure fields that IDA creates.

```
int __fastcall icc_map_addr_47EE8(int a1)
{
  char *v2; // r7
  int v3; // r1
  int v4; // r2
  int v5; // r1
  __int64 v6; // r2
  int v7; // r1
  __int64 v8; // r2
  int v9; // r1
  __int64 v10; // r2
  unsigned __int8 *v11; // r0
  int v12; // r6
  int v14; // r3
  int v15; // r1
  int v16; // r2
  int v17; // r1
  __int64 v18; // r2
  int v19; // r1
  __int64 v20; // r2
  __int64 v21; // r0
  __int64 v22; // r2
  __int64 v23[13]; // [sp+0h] [bp-68h] BYREF

  memset(&v23[1], 0, 0x40u);
  v2 = &unk_20055E4C + 204 * a1;
  *(v2 + 8) = off_E3940[2 * a1 + 1];
  LOBYTE(v23[1]) = 1;
  HIDWORD(v23[2]) = dword_5FFD0000;
  LODWORD(v23[3]) = dword_5FFD0000;
  HIDWORD(v23[3]) = 126976;
  v3 = HIDWORD(v23[1]);
  v4 = v23[2];
  *(v2 + 10) = v23[1];
  *(v2 + 11) = v3;
  *(v2 + 12) = v4;
  *(v2 + 13) = dword_5FFD0000;
  v5 = HIDWORD(v23[3]);
  v6 = v23[4];
  *(v2 + 14) = v23[3];
  *(v2 + 15) = v5;
  *(v2 + 8) = v6;
  v7 = HIDWORD(v23[5]);
  v8 = v23[6];
  v23[0] = 0i64;
  *(v2 + 18) = v23[5];
  *(v2 + 19) = v7;
  *(v2 + 10) = v8;
  v9 = HIDWORD(v23[7]);
  v10 = v23[8];
  *(v2 + 22) = v23[7];
  *(v2 + 23) = v9;
  *(v2 + 12) = v10;
  v11 = sub_C6C16(dword_5FFD0000);
  icc_47E98(v11, 768, v23, v23 + 1);
  if ( !v23[0] )
    return -1;
  v12 = sub_477AC(0, v23[0], 3, v23);
  if ( v12 )
  {
    log_special(4, "CRITICAL:icc_err:map addr fail, addr: %x!\n", LODWORD(v23[0]));
  }
  else if ( HIDWORD(v23[0]) < (a1 + 1) << 14 )
  {
    return -2;
  }
  else
  {
    LOBYTE(v23[1]) = 0;
    v14 = ((a1 + 1) << 14) - 0x4000 + LODWORD(v23[0]);
    *(v2 + 27) = off_E3940[2 * a1];
    HIDWORD(v23[2]) = v14;
    v23[3] = v14 | 0x400000000000i64;
    v15 = HIDWORD(v23[1]);
    v16 = v23[2];
    *(v2 + 29) = v23[1];
    *(v2 + 30) = v15;
    *(v2 + 31) = v16;
    *(v2 + 32) = v14;
    v17 = HIDWORD(v23[3]);
    v18 = v23[4];
    *(v2 + 33) = v23[3];
    *(v2 + 34) = v17;
    *(v2 + 140) = v18;
    v19 = HIDWORD(v23[5]);
    v20 = v23[6];
    *(v2 + 37) = v23[5];
    *(v2 + 38) = v19;
    *(v2 + 156) = v20;
    v21 = v23[7];
    v22 = v23[8];
    *(v2 + 56) = 0;
    *(v2 + 164) = v21;
    *(v2 + 172) = v22;
  }
  return v12;
}
```

Compare to those of BN

```
00047ee8  int32_t icc_map_addr_47ee8(int32_t* arg1)

00047ef8      char var_60
00047ef8      memset(&var_60, 0, 0x40)
00047f18      *(0xcc * arg1 + &data_20055e6c) = *((arg1 << 3) + 0xe3944)
00047f1c      var_60 = 1
00047f2c      *(0xcc * arg1 + 0x20055e74) = var_60.d
00047f2c      int32_t var_5c
00047f2c      *(0xcc * arg1 + &data_20055e78) = var_5c
00047f2c      int32_t var_58
00047f2c      *(0xcc * arg1 + &data_20055e7c) = var_58
00047f2c      *(0xcc * arg1 + &data_20055e80) = 0x5ffd0000
00047f30      *(0xcc * arg1 + 0x20055e84) = 0x5ffd0000
00047f30      *(0xcc * arg1 + &data_20055e88) = 0x1f000
00047f30      int32_t var_48
00047f30      *(0xcc * arg1 + &data_20055e8c) = var_48
00047f30      int32_t var_44
00047f30      *(0xcc * arg1 + &data_20055e90) = var_44
00047f34      int32_t var_68 = 0
00047f34      int32_t var_64 = 0
00047f38      int32_t var_40
00047f38      *(0xcc * arg1 + 0x20055e94) = var_40
00047f38      int32_t var_3c
00047f38      *(0xcc * arg1 + &data_20055e98) = var_3c
00047f38      int32_t var_38
00047f38      *(0xcc * arg1 + &data_20055e9c) = var_38
00047f38      int32_t var_34
00047f38      *(0xcc * arg1 + &data_20055ea0) = var_34
00047f3e      int32_t var_30
00047f3e      *(0xcc * arg1 + 0x20055ea4) = var_30
00047f3e      int32_t var_2c
00047f3e      *(0xcc * arg1 + &data_20055ea8) = var_2c
00047f3e      int32_t var_28
00047f3e      *(0xcc * arg1 + &data_20055eac) = var_28
00047f3e      int32_t var_24
00047f3e      *(0xcc * arg1 + &data_20055eb0) = var_24
00047f50      icc_47e98(sub_c6c16(0x5ffd0000), 0x300, &var_68, &var_64)
00047f54      int32_t r1_3 = var_68
00047f5a      int32_t r6
00047f5a      if ((var_64 | r1_3) == 0)
00047fca          r6 = 0xffffffff
00047f62      else
00047f62          int32_t r0_5 = sub_477ac(0, r1_3, 3, &var_68)
00047f66          r6 = r0_5
00047f68          if (r0_5 != 0)
00047f74              log_30e20(4, "CRITICAL:icc_err:map addr fail, …", var_68, log_30e20)
00047f8c          else if (var_64 u< (arg1 + 1) << 0xe)
00047fd0              r6 = 0xfffffffe
00047f8e          else
00047f8e              int32_t r2_7 = var_68
00047f96              var_60 = r0_5.b
00047f9a              int32_t r3_11 = ((arg1 + 1) << 0xe) - 0x4000 + r2_7
00047fa4              *(0xcc * arg1 + &data_20055eb8) = *(0xe3940 + (arg1 << 3))
00047fb2              *(0xcc * arg1 + 0x20055ec0) = var_60.d
00047fb2              *(0xcc * arg1 + &data_20055ec4) = var_5c
00047fb2              *(0xcc * arg1 + &data_20055ec8) = var_58
00047fb2              *(0xcc * arg1 + &data_20055ecc) = r3_11
00047fb6              *(0xcc * arg1 + 0x20055ed0) = r3_11
00047fb6              *(0xcc * arg1 + &data_20055ed4) = 0x4000
00047fb6              *(0xcc * arg1 + &data_20055ed8) = var_48
00047fb6              *(0xcc * arg1 + &data_20055edc) = var_44
00047fba              *(0xcc * arg1 + 0x20055ee0) = var_40
00047fba              *(0xcc * arg1 + &data_20055ee4) = var_3c
00047fba              *(0xcc * arg1 + &data_20055ee8) = var_38
00047fba              *(0xcc * arg1 + &data_20055eec) = var_34
00047fc0              *(0xcc * arg1 + &data_20055ebc) = r6.w
00047fc4              *(0xcc * arg1 + 0x20055ef0) = var_30
00047fc4              *(0xcc * arg1 + &data_20055ef4) = var_2c
00047fc4              *(0xcc * arg1 + &data_20055ef8) = var_28
00047fc4              *(0xcc * arg1 + &data_20055efc) = var_24
00047f7a      return r6
```

Anyone from V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by plafosse** [comment] 2023-06-09 19:34
Duplicate of #1888

**Closed by plafosse** 2023-06-09 19:35 UTC
