### ISSUE TITLE
Horizontal scrolling in Strings view

### ISSUE THREAD

**Issue by HackingThings** [Vector35/binaryninja-api#5732] opened 2024-07-12 18:25 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.0.5336, b4281362
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
The strings view does not have a horizontal scrolling bar, making it frustrating when I need to read a very long string

**Steps To Reproduce:**
Open any file with strings longer than what the strings view can display

**Expected Behavior:**
a horizontal scroll bar appears when strings are displayed that are wider than the view can display.

**Screenshots:**
![image](https://github.com/user-attachments/assets/9796f577-1bb3-442a-a3ae-62e9aa2cd50c)

**Additional Information:**

included in issue #3051, but it has been a while...

**Comment by psifertex** [comment] 2024-07-12 18:37
Yeah, this is fair -- sorry for the other taking so long. I'm going to close this in favor of that, but explicitly mark the priority higher and assign it to the next release so it's less likely to get missed. Thanks for the ping. 

Duplicate of #3051

**Closed by psifertex** 2024-07-12 18:37 UTC
