### ISSUE TITLE
Code created over float data

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4330] opened 2023-05-22 12:17 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4286-dev, 58311b01
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

This disassembly 

```
00030614  int32_t* data_30614 = data_200777fc

00030618  float* sub_30618(void** arg1, int16_t* arg2, int32_t* arg3, int32_t arg4, int32_t arg5 @ r4, int32_t* arg6 @ r5, int16_t* arg7 @ r6, int32_t arg8 @ r7, 
00030618      int32_t arg9, int32_t arg10, int32_t arg11, int32_t arg12, int32_t arg13, int32_t arg14, int32_t arg15, int32_t arg16, int32_t arg17)

00030618  8fc2       stm     r2!, {r0, r1, r2, r3, r7}
0003061a  f53c       subs    r4, #0xf5
0003061c  ec51       str     r4, [r5, r7]
0003061e  783f       subs    r7, #0x78
00030620  0ad7       bvc     #0x30638

00030622  233c       subs    r4, #0x23
00030624  0ad7       bvc     #0x3063c

00030626  a33c       subs    r4, #0xa3
00030628  a470       strb    r4, [r4, #2]
0003062a  7d3f       subs    r7, #0x7d
0003062c  9a99       ldr     r1, [sp, #0x268] {arg17}
0003062e  193f       subs    r7, #0x19
00030630  cdcc       ldm     r4!, {r0, r2, r3, r6, r7}
00030632  cc3d       subs    r5, #0xcc  {sub_30634}
{ Falls through into sub_30634 }
```

should really be at least this 

```
00030614  int32_t* data_30614 = data_200777fc

00030618                                                                          8f c2                                            ..

0003061a  int32_t data_3061a = 0x51ec3cf5

0003061e                                                                                            78 3f                                x?

00030620  int32_t data_30620 = 0x3c23d70a

00030624              0a d7                                                                                    ..

00030626  int32_t data_30626 = 0x70a43ca3
0003062a  int32_t data_3062a = -0x6665c083
0003062e  int32_t data_3062e = -0x3332c0e7

00030632                                                        cc 3d                                                        .=

00030634  int32_t* sub_30634(void** arg1, int16_t* arg2, int16_t* arg3)

00030634  2de9f04f   push    {r4, r5, r6, r7, r8, r9, r10, r11, lr} {var_4} {__saved_r11} {__saved_r10} {__saved_r9} {__saved_r8} {__saved_r7} {__saved_r6} {__saved_r5} {__saved_r4}
00030638  1646       mov     r6, r2
0003063a  aa4a       ldr     r2, [pc, #0x2a8]  {data_308e4}  {data_200777fc}
0003063c  dfedaa7a   vldr    s15, [pc, #0x2a8]  {data_308e8}
00030640  0d46       mov     r5, r1
00030642  1368       ldr     r3, [r2]  {data_200777fc}
00030644  9146       mov     r9, r2  {data_200777fc}
00030646  0027       movs    r7, #0
00030648  a84a       ldr     r2, [pc, #0x2a0]  {data_308ec}  {data_200771b0}
0003064a  03f6b863   addw    r3, r3, #0xeb8
...
```

Ideally, it should be this instead, i.e. floats recognized 

```
00030614  int32_t* data_30614 = data_200777fc
00030618  float data_30618 = 0.0299999993
0003061c  float data_3061c = 0.970000029
00030620  float data_30620 = 0.00999999978
00030624  float data_30624 = 0.0199999996
00030628  float data_30628 = 0.99000001
0003062c  float data_3062c = 0.600000024
00030630  float data_30630 = 0.100000001

00030634  int32_t* sub_30634(void** arg1, int16_t* arg2, int16_t* arg3)

00030634  2de9f04f   push    {r4, r5, r6, r7, r8, r9, r10, r11, lr} {var_4} {__saved_r11} {__saved_r10} {__saved_r9} {__saved_r8} {__saved_r7} {__saved_r6} {__saved_r5} {__saved_r4}
00030638  1646       mov     r6, r2
0003063a  aa4a       ldr     r2, [pc, #0x2a8]  {data_308e4}  {data_200777fc}
0003063c  dfedaa7a   vldr    s15, [pc, #0x2a8]  {data_308e8}
00030640  0d46       mov     r5, r1
00030642  1368       ldr     r3, [r2]  {data_200777fc}
00030644  9146       mov     r9, r2  {data_200777fc}
00030646  0027       movs    r7, #0
00030648  a84a       ldr     r2, [pc, #0x2a0]  {data_308ec}  {data_200771b0}
0003064a  03f6b863   addw    r3, r3, #0xeb8
🚫0003064e  2ded028b   vpush   {d8}
00030652  abb0       sub     sp, #0xac
00030654  b0ee678a   vmov.f32.F32 s16, s15  {data_30658}
00030658  c3ed007a   vstr    s15, [r3]  {data_3065c}
0003065c  02ac       add     r4, sp, #8 {var_c8}
...
```

Note that undefining the first function at the top _does_ give me the second listing, albeit with floats unrecognized.

Anyone from V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by joelreymont** [comment] 2023-05-23 15:26
Another good example at `0x13328`.

**Comment by fuzyll** [comment] 2023-05-23 18:28
Yeah, wow, I have no idea what happened here. I thought maybe this had something to do with how the analysis was originally run on this file, so I actually exported the original and created an entirely new database. Both of these functions are created, even with the platform set, and the one at 0x13328 doesn't have any cross-references.

**Comment by joelreymont** [comment] 2023-05-23 18:32
Cross-references are likely missing because the pointer to this function is
stored in some structure, within another function. And because BN is
treating that function pointer as an int.

This is why I’m going through the code and changing all the literals to
pointers. Cross-references won’t be there if I don’t!

**Comment by plafosse** [comment] 2023-06-08 19:10
Ultimately there is a confluence of things going on here. 

1. Linearsweep making bad functions. Which is essentially a duplicate of: https://github.com/Vector35/binaryninja-api/issues/4245
2. We don't have a way to coerce those constants to their inferred type because this would involve taking into account all functions which reference that particular DataVariable and then coercing it.  https://github.com/Vector35/binaryninja-api/issues/4400
Closing this as a duplicate of the two above.

**Closed by plafosse** 2023-06-08 19:10 UTC
Labels: State: Duplicate
