### ISSUE TITLE
ARM64 Unimplemented Instructions

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#661] opened 2017-04-22 14:31 UTC
In a single function for the Nintendo Switch, the following instructions are unimplemented: `movk`, `shmulh`, `ldaxr`, `stlxr`, `madd`, `ccmp`, `cinc`

`movk` is used quite a bit across the library.

**Comment by plafosse** [comment] 2017-04-22 22:33
`shmulh` isn't an instruction, typo?

**Comment by withzombies** [comment] 2017-04-22 22:41
Yeah I don't know. I can't find the example function again.

**Comment by plafosse** [comment] 2017-04-26 22:57
Duplicate of #210

**Closed by plafosse** 2017-04-26 22:57 UTC
