### ISSUE TITLE
Crash when loading an ELF file

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#6004] opened 2024-10-17 23:35 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6223-dev Personal (15658718)
- OS: Debian
- OS Version: testing
- CPU Architecture: amd64

**Bug Description:**
Binary Ninja crashes when opening an ELF file.

**Steps To Reproduce:**
1. Download [2024-10-18-binja-crash.zip](https://github.com/user-attachments/files/17424754/2024-10-18-binja-crash.zip)
2. Open `a.elf`
3. Crash!
4. Please do not ask why the file is like that.

**Expected Behavior:**
No crash.

**Additional Information:**
Crashes with SIGFPE in `libview_elf.so+0xab249`, so it's probably some field in an ELF that's set to zero that should not be set to zero.

```
(gdb) bt
#0  0x00007fffcb6ab249 in ?? () from .../binaryninja/plugins/libview_elf.so
#1  0x00007fffcb6e2032 in ?? () from .../binaryninja/plugins/libview_elf.so
```
```
7fffcb600000-7fffcb642000 r--p 00000000 fd:01 6204500                    .../binaryninja/plugins/libview_elf.so
7fffcb642000-7fffcb81c000 r-xp 00042000 fd:01 6204500                    .../binaryninja/plugins/libview_elf.so
7fffcb81c000-7fffcb89c000 r--p 0021c000 fd:01 6204500                    .../binaryninja/plugins/libview_elf.so
7fffcb89c000-7fffcb8a0000 r--p 0029b000 fd:01 6204500                    .../binaryninja/plugins/libview_elf.so
7fffcb8a0000-7fffcb8a5000 rw-p 0029f000 fd:01 6204500                    .../binaryninja/plugins/libview_elf.so
```

**Comment by whitequark** [comment] 2024-10-17 23:38
By the way, the decompile for `libview_elf.so` after running a linear sweep is kind of atrocious, not sure why:

![Screenshot_20241017_233759](https://github.com/user-attachments/assets/849f69ec-85cf-47e6-8511-b3ad55f6296a)

**Comment by psifertex** [comment] 2024-10-17 23:44
I can't reproduce the crash on the same version on macos anyway -- mind double checking it without any plugins/settings using https://docs.binary.ninja/guide/troubleshooting.html#troubleshooting-plugins to see if it still crashes?

**Comment by whitequark** [comment] 2024-10-17 23:51
Still crashes when launched as:

```
$ BN_DISABLE_USER_PLUGINS= BN_DISABLE_USER_SETTINGS= ./binaryninja
Floating point exception
```

Could this be Linux-specific somehow?

**Comment by psifertex** [comment] 2024-10-17 23:54
Could be, will check there.

**Comment by psifertex** [comment] 2024-10-18 00:02
Yup, confirmed that did it. Thanks for the report.

**Comment by whitequark** [comment] 2024-10-18 00:03
If you fix it quickly enough you might end up helping me figure out what I'm doing wrong :D

**Comment by psifertex** [comment] 2024-10-18 00:42
I'm slower than the rest of the team but I happened to be up so might as well. :-) 

It was indeed a div0: https://github.com/Vector35/binaryninja-api/commit/f5bf35d44a1a01d5edb476ddb7f4194344975890

New build is going now, will be in builds >= 4.2.6224

**Closed as completed by psifertex** 2024-10-18 00:42 UTC
Labels: Impact: High

**Comment by whitequark** [comment] 2024-10-18 00:44
Thanks!

**Comment by whitequark** [comment] 2024-10-18 03:26
I think there's something wrong with the fix. I verified it with `readelf` and the entry size is not zero:

```
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [10] .rela.dyn         RELA             0000000000006260  00006260
       00000000000000d8  0000000000000018   A       8     0     24
```

Also, I can't seem to get `.rela.dyn` or `.rela.plt` displayed even for `/bin/ls` or other obviously correctly linked binaries.

**Comment by whitequark** [comment] 2024-10-18 03:32
Nevermind, I just realized that you're taking entry size from `DT_REL(A)ENT`, not the section properties. This is the right thing to do. Sorry for the bother!
