### ISSUE TITLE
Installing and uninstalling the demo version disables the PDB parser plugin

### ISSUE THREAD

**Issue by bytefactory73** [Vector35/binaryninja-api#4824] opened 2023-12-12 16:24 UTC
**Windows x64:**
- Binary Ninja Version: 3.5.4526, ec37d737
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

[Default] File does not contain debug info

with the purchased version of binary ninja i cannot load pdb files. i always get: "[Default] File does not contain debug info"

The demo versin before worked as expected.

**Comment by bytefactory73** [comment] 2023-12-16 12:11
i found the culprit: after uninstalling the demop and installing the commercial license the pdb loader plugin was disabled. enabling it fixed the problem.

**Comment by xusheng6** [comment] 2023-12-16 17:17
We might still wish to see if this can be fixed. Since it is quite common for users to try the demo first and then become a paid user

**Comment by xusheng6** [comment] 2024-01-03 06:20
@bytefactory73 I cannot reproduce this. Can you still reproduce this? I tried installing and uninstalling demo, but the PDB plugin is not disabled

**Comment by xusheng6** [comment] 2024-01-19 08:36
I am closing this since we cannot reproduce it and this is no reason why installing and uninstalling demo will disable the plugin. Please feel free to re-open this if there is new input or reports of similar issues

**Closed by xusheng6** 2024-01-19 08:36 UTC
Labels: State: Unreproducible, Impact: Low, Effort: Medium
