### ISSUE TITLE
Feature request: Make imports/exports lists in Triage copiable

### ISSUE THREAD

**Issue by jankais3r** [Vector35/binaryninja-api#3118] opened 2022-05-10 11:27 UTC
**What is the feature you'd like to have?**
It would be great if we could select more than one import/export in the Triage view and copy them out as a plaintext list.

**Is your feature request related to a problem?**
I would like to compare imports/exports of different binaries and having a way to easily get these lists out from BN would be helpful.

**Are any alternative solutions acceptable?**
I am not aware of any solution besides running a custom Python script. I would consider this a QoL improvement.

**Comment by xusheng6** [comment] 2022-08-25 03:45
This is a duplicate of https://github.com/Vector35/binaryninja-api/issues/2820

**Closed by xusheng6** 2022-08-25 03:45 UTC
Labels: enhancement, Impact: Low, Effort: Low
