### ISSUE TITLE
HLIL Global Substring References seems broken

### ISSUE THREAD

**Issue by dfraze** [Vector35/binaryninja-api#2421] opened 2021-05-03 15:30 UTC
Recent Binary Ninja versions (I feel like this may be related to the new array code) seem to have a creative way of representing references to substrings of global strings in HLIL views in certain cases.

Sample binary from DEF CON CTF Quals provided. Offset 0x7b14 shows the issue.

**Expected behavior**
HLIL should only display the substring.
[libBBSFiles.zip](https://github.com/Vector35/binaryninja-api/files/6415830/libBBSFiles.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/12348497/116896434-4146c080-ac02-11eb-8e5b-e8bca14f1e64.png)

**Comment by nshp** [comment] 2021-05-03 15:41
Dupe of #2402 :+1:

**Closed** 2021-05-05 18:33 UTC
Labels: duplicate
