### ISSUE TITLE
Script console SHIFT+INSERT hotkey

### ISSUE THREAD

**Issue by captincook** [Vector35/binaryninja-api#750] opened 2017-07-26 21:20 UTC
I frequently rely on Shift-Insert for Paste. Pressing Shift-Insert in the python console does not work but something confusing is happening with disassembly... I have no idea whats going on but its very very odd shortcut.

Could you change Shift-Insert for Paste ?

**Comment by plafosse** [comment] 2017-08-06 21:26
The weird thing happening with the graph is Shift-insert is pasting those bytes at the currently selected address in the graph.  Obviously this isn't something that should be happening. The root cause is a focusing bug rather than a lack of support for shift+insert.  Marking this a duplicate of #324

**Closed by plafosse** 2017-08-06 21:26 UTC
Labels: duplicate
