### ISSUE TITLE
Inconsistent Architecture.assemble() error cases

### ISSUE THREAD

**Issue by gynophage** [Vector35/binaryninja-api#310] opened 2016-06-17 20:51 UTC
There are 3 ways the python API reports assembler errors for the builtin architectures:

>>> binaryninja.Architecture["x86"].assemble("thisisnotaninstruction")
('', '')
>>> binaryninja.Architecture["x86_64"].assemble("thisisnotaninstruction")
('', '')
>>> binaryninja.Architecture["powerpc"].assemble("thisisnotaninstruction")
(None, '')
>>> binaryninja.Architecture["mips32"].assemble("thisisnotaninstruction")
(None, 'Not supported for this architecture.')
>>> binaryninja.Architecture["armv7"].assemble("thisisnotaninstruction")
(None, 'Not supported for this architecture.')
>>>

None of these 3 ways are python exceptions. I'd love some exception being thrown. I'd settle for a standard way to report failure that wasn't a python exception, but was the same.

**Comment by lwerdna** [comment] 2016-09-05 20:33
Sorry Dustin, no exceptions yet. Docs currently say it should return a tuple of None and error string when a problem occurs.

**before:**
* result was return status of ExecuteWorkerProcess() so success of assembly was improperly tied only to success of YASM execution
* unrecognized mnemonics were considered labels (google yasm orphan label)
* no clue as to the cause of the error

**after:**
* success if ExecuteWorkerProcess() succeeds AND resulting binary is non-empty AND the nasm reported no errors or warnings
* warn on orphan labels (-Worphan-labels) and put this on stdout (-s)
* output of yasm is the error string

**testing**
```
>>> Architecture["x86"].assemble("thisisnotaninstruction")
(None, 'input:1: warning: label alone on a line without a colon might be in error\n')
>>> Architecture["x86_64"].assemble("thisisnotaninstruction")
(None, 'input:1: warning: label alone on a line without a colon might be in error\n')
>>> Architecture["mips32"].assemble("thisisnotaninstruction")
(None, 'Not supported for this architecture.')
>>> Architecture["armv7"].assemble("thisisnotaninstruction")
(None, 'Not supported for this architecture.')
```

**lldb notes:**
```
b libarch_x86.dylib`X86CommonArchitecture::Assemble
b libarch_mips.dylib`MipsArchitecture::Assemble
```

**Comment by lwerdna** [comment] 2016-09-05 20:44
fixed in dev

**Closed by lwerdna** 2016-09-05 20:44 UTC
Labels: bug
