### ISSUE TITLE
UI freezing when highlighting a symbol with a large amount of xrefs

### ISSUE THREAD

**Issue by whitequark** [Vector35/binaryninja-api#5899] opened 2024-09-03 09:51 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6028-dev
- OS: Debian Linux
- OS Version: stable
- CPU Architecture: x64

**Bug Description:**
Highlighting a symbol with a large amount (1000+) xrefs hangs the interface for a minute or so. This happens even if the xref view is completely hidden.

**Steps To Reproduce:**
1. Open `libgowin.so`
2. Look up `MsgInfo_` (I think there's one in `.data` and one in `.got`, either works. the `.got` one is at `0x42f6d10`)
3. Make some coffee or tea while it's spinning

**Expected Behavior:**
The UI should not hang for a minute.

**Binary:**
[This 80 MB monstrosity](https://mega.nz/file/gtAHjKrQ#Qa3cHo0-k88sRrWGmchteZAhYydBBWPNnAByrO3JFiI)

**Additional Information:**
It looks like Qt is spinning in `_pcre2_valid_utf_16`, so I speculate that something goes wrong while applying a filter to xrefs. I don't have any filter enabled at all, so this could be entirely off base.

**Comment by plafosse** [comment] 2024-09-03 14:44
Hmm I'm unable to reproduce this hang on macOS must be a Linux specific bug. Oh what UI elements do you have up? Is Cross references a tableview or a treeview ?

**Comment by bpotchik** [comment] 2024-09-03 15:04
I was able to repro on macOS. Looking into it.

**Comment by whitequark** [comment] 2024-09-04 07:28
> Oh what UI elements do you have up? Is Cross references a tableview or a treeview ?

Xrefs could be one of the two view types? I must be missing something...

**Comment by plafosse** [comment] 2024-09-04 10:42
Right click -> view as Table

**Comment by bpotchik** [comment] 2024-09-05 17:23
Fixed in `4.2.6034-dev`.

**Closed as completed by bpotchik** 2024-09-05 17:23 UTC
Labels: Component: UI, Impact: High, Effort: Low

**Comment by whitequark** [comment] 2024-09-05 17:25
Thanks!

**Comment by whitequark** [comment] 2024-09-05 17:26
What went wrong?

**Comment by plafosse** [comment] 2024-09-05 17:27
Threads are hard 😛

**Comment by bpotchik** [comment] 2024-09-05 17:29
Excessive model invalidation when a symbols filter was active. This new approach should preserve consistency but greatly improve UI performance when a symbols view filter is active.

Actually, nothing to do with threads.

**Comment by plafosse** [comment] 2024-09-05 17:30
That doesn't invalidate my assertion 😆

**Comment by bpotchik** [comment] 2024-09-05 17:41
Oh, for brevity I was able to repro this simply by opening the file above and putting an "a" in the symbols view filter...
