### ISSUE TITLE
Thumb2 disassembler can't decode NEON instruction

### ISSUE THREAD

**Issue by Metalnem** [Vector35/binaryninja-api#744] opened 2017-07-20 14:47 UTC
At the address 0x003dbfe8 In the [attached file](https://github.com/Vector35/binaryninja-api/files/1162655/folio.zip) is the instruction 0x04f9ef8a. Both Hopper and [Online HEX To ARM Converter](http://armconverter.com/hextoarm/) can successfully decode it as `vst1.64 {d8, d9}, [r4, #0x80]`. Binary Ninja can't decode it, and it will also skip decoding the rest of the function.

**Comment by plafosse** [comment] 2017-07-20 16:34
Updated the issue a bit.  This is a Thumb2 instruction, and it is expected behavior to halt disassembly when an invalid instruction is encountered.

**Comment by tchebb** [comment] 2017-09-27 06:15
I'm encountering the same issue with the `vpush` Thumb instruction. The instruction that fails to decode is `2ded088b` (`vpush   {d8-d11}`). The file I'm working with uses `vpush` at the beginning of a lot of functions, and since the failed decode prevents further parsing, they show up as having only one or two instructions in total.

**Comment by bpotchik** [comment] 2017-12-15 00:52
Fixed by Andrew. Verified in latest build 1.1.1127-dev but the fix showed up several builds earlier.

**Closed by bpotchik** 2017-12-15 00:52 UTC
Labels: bug
