### ISSUE TITLE
Crash parsing DWARF debug information

### ISSUE THREAD

**Issue by trumank** [Vector35/binaryninja-api#4881] opened 2024-01-11 17:51 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4738-dev Personal (8ff0a04d)
- OS: Arch Linux
- OS Version: -
- CPU Architecture: x64

**Bug Description:**
Crashes upon opening Factorio headless server with default options during the DWARF symbol parsing stage. With "Import Debug Information" unchecked the binary opens and fully analyzes fine.

The binary can be obtained from https://factorio.com/get-download/1.1.101/headless/linux64. I tested a few other versions including the full game and they seem to have the same issue.

```console
$ sha256sum factorio_headless_x64_1.1.101.tar.xz
0688a6f615a87bf73d3f46b53dc423ee37cad3fc4412723f3d7450aed1638392  factorio_headless_x64_1.1.101.tar.xz
```

**Comment by KyleMiles** [comment] 2024-01-19 21:34
Sorry for the delay on this. Thank you for the bug report! This should be fixed in builds >=3.6.4779-dev. The cause is what I believe to be a malformed infinite reference cycle in the DWARF information, specifically the DIE:

```
0x0342d309:     DW_TAG_label
                  DW_AT_abstract_origin	(0x0342d309)
```

**Closed by KyleMiles** 2024-01-19 21:34 UTC
Labels: Type: Crash, Impact: Low, Effort: Trivial, DebugInfo: DWARF, Component: DebugInfo
