### ISSUE TITLE
document resolving unresolved stack usage

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4876] opened 2024-01-09 16:04 UTC
There's a particular workflow for resolving unresolved stack usage that's currently undocumented. 

There's a short thread here: https://github.com/Vector35/binaryninja-api/discussions/1644

But we need a much better explanation in the actual docs.

**Comment by xusheng6** [comment] 2024-01-10 04:41
I think the document should involve these parts:

1. How to set it for a function in the edit function property dialog
2. How to set it for a particular callsite by right-click, and the select "Set stack adjustment"

Optionally, it can involve:

3. Accessing and setting the stack adjustment for a function using https://api.binary.ninja/binaryninja.function-module.html#binaryninja.function.Function.stack_adjustment
4. Accessing and setting the stack adjustment for a callsite by https://api.binary.ninja/binaryninja.function-module.html#binaryninja.function.Function.set_call_stack_adjustment

Relevant: https://binary.ninja/2023/11/13/obfuscation-flare-on.html#fixing-up-the-stack

**Comment by xusheng6** [comment] 2024-01-10 05:58
Lol, this is duplicate of https://github.com/Vector35/binaryninja-api/issues/4063

**Closed** 2024-01-10 14:13 UTC
Labels: Component: Documentation
