### ISSUE TITLE
Mach-O Platform support

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#247] opened 2016-05-09 13:19 UTC
<img width="499" alt="screen shot 2016-05-09 at 9 10 34 am" src="https://cloud.githubusercontent.com/assets/4872355/15114266/190d9cd2-15c7-11e6-8e61-6722bb99672f.png">
<img width="416" alt="screen shot 2016-05-09 at 9 11 39 am" src="https://cloud.githubusercontent.com/assets/4872355/15114270/1d1b9018-15c7-11e6-8947-79e6d06c53d0.png">

[ls.zip](https://github.com/Vector35/binaryninja-api/files/255040/ls.zip)

**Comment by psifertex** [comment] 2016-05-10 14:07
Looks like the problem is we fail to mark `_err` as noreturn. The data afterward is not code but rather the base for a jump table. It's marked as no return after where it should because it encounters an invalid instruction. So the disassembly is pretty much right if you ignore everything after the call to `_err`.

**Comment by plafosse** [comment] 2016-05-29 14:37
Fixed in dev

**Closed by plafosse** 2016-05-29 14:37 UTC
