### ISSUE TITLE
Was scrolling thru analyzed [malware] code and the software crashed.  Scary...

### ISSUE THREAD

**Issue by themrrobert** [Vector35/binaryninja-api#3011] opened 2022-03-12 06:06 UTC
If it happens again I'll try to get more info, lmk if there's some way i can get debug info.

Obv I don't want to upload the malware here. It was a discord token grabber bundled in a nodejs runtime exe.

Really scary to have software analysis software crash when you're working on exe files, you REALLY don't want that code being accidentally executed/overflowed.

Here is the virus total hash just in case [bd97a360eb69ed2b7701e50d5538ff164c92f44b4573d9db0a7be43388e93944](https://www.virustotal.com/gui/file/bd97a360eb69ed2b7701e50d5538ff164c92f44b4573d9db0a7be43388e93944/detection)

Binary Ninja Version: 3.0.3282-dev Personal, 49064472
Platform: Windows 10 Version 2009

**Comment by fuzyll** [comment] 2022-03-14 19:06
Could you please share the sample either here on GitHub (in a `.zip`) or via email at binaryninja@vector35.com? If the crash doesn't occur on open, you could share the `.bndb` instead of the actual malware sample.

Also, do you have any more information about when this crash occurs? Is there a specific function or section of the binary that this crash occurs on? We'll want to reproduce it ourselves and more information will help us do that.

Thanks!

**Comment by HackingThings** [comment] 2022-03-16 21:00
I hope you don't mind me jumping in the thread like this, but if it helps here is the sample (pass: infected) 😄 
[6078100372357120.zip](https://github.com/Vector35/binaryninja-api/files/8273937/6078100372357120.zip)

**Comment by fuzyll** [comment] 2022-03-21 23:01
Thanks, @HackingThings!

Unfortunately, I've been unable to reproduce this on 3.0.3282-dev on either Windows 11 or macOS. I'm going to close this out since we don't have a way to reproduce the issue.

If either of you are able to give some more detailed instructions on how to reproduce this, I'm more than happy to re-open the issue and look into it further. I'm just not sure what to do with just the information we have here right now in the ticket.

**Closed by fuzyll** 2022-03-21 23:01 UTC
