### ISSUE TITLE
analyze static binary with library signatures.

### ISSUE THREAD

**Issue by junorouse** [Vector35/binaryninja-api#601] opened 2017-01-21 19:21 UTC
Auto matching function name from libc signatures

like ida pro feature.

**Comment by lucasduffey** [comment] 2017-01-21 19:26
might be a duplicate of https://github.com/Vector35/binaryninja-api/issues/431

**Comment by junorouse** [comment] 2017-01-21 19:44
@lucasduffey thx. since I searched Signaturs with "s" issue didn't come out.

**Closed** 2017-01-21 19:43 UTC
