### ISSUE TITLE
Ability to rebase different parts of the binary

### ISSUE THREAD

**Issue by nitrogar** [Vector35/binaryninja-api#3700] opened 2022-11-28 08:11 UTC
**What is the feature you'd like to have?**
While doing bare-metal arm firmware reversing I could not rebase the data section(global variables) to the SRAM offset.

I can rebase the whole binary but I want to assign different bases for an arbitrary binary offsets.

In my case I want to rebase the offset 0x80001320 to 0x20000000 . 

Yes i can create a new segment using the memory map UI but for some reasone i cant repopulate the content mybe because it is not supported with binary file size ??  But even if I can modify the new segment i still need to copy the global variables which is inconvenient.

**Comment by plafosse** [comment] 2023-01-11 12:55
Yes this is a needed feature. This is a duplicate of #2882 which requires a bit of internal rework to get done.

**Closed by plafosse** 2023-01-11 12:55 UTC
Labels: duplicate, enhancement
