### ISSUE TITLE
MLIL fails to optimize out push/pop for saved register in this case

### ISSUE THREAD

**Issue by amatus** [Vector35/binaryninja-api#1010] opened 2018-04-05 15:12 UTC
Analyzing this function:
```
push rbx
test rdi, rdi
jz L1
xor ebx, ebx
L1:
pop rbx
ret
```
Results with an MLIL function starting with `int64_t var_8 = rbx` and ending with `int64_t rbx_2 = var_8` where usually these assignments are optimized out.

**Comment by joshwatson** [comment] 2018-04-05 15:29
rbx is a preserved register so this is probably correct behavior

**Comment by joshwatson** [comment] 2018-04-05 15:38
thinking more on it, this looks like there would be several issues with optimizing that out, so I definitely think this is working as intended

**Comment by amatus** [comment] 2018-04-05 16:06
Same behavior with other regs like r12. It also gets optimized out if the test+jz or the xor are removed.

**Comment by amatus** [comment] 2018-04-05 16:28
Consider:
```
push r14
push r13
push r12
xor r14, r14
test rdi, rdi
jz L1
xor r13, r13
L1:
xor r12, r12
pop r12
pop r13
pop r14
ret
```
![screenshot from 2018-04-05 11-25-25](https://user-images.githubusercontent.com/282880/38378689-17aecdee-38c4-11e8-929d-3978c2b1f402.png)
The push/pop for r12 and r14 get optimized out but not r13. I don't see the issue with removing line 0 and line 4 from that MLIL.

**Comment by D0ntPanic** [comment] 2018-04-11 21:05
Fixed in build 1167

**Closed by D0ntPanic** 2018-04-11 21:05 UTC
