### ISSUE TITLE
Disconnected HLIL basic blocks

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#2823] opened 2022-01-06 00:46 UTC
**Version and Platform (required):**
- Binary Ninja Version: 2.5.3157-dev
- OS: macOS
- OS Version: 12.0.1

**Bug Description:**
If you analyze the arm64e slice of macOS 12.0.1 /bin/ls, you will find a floating HLIL block in _start that has no parents but is not the entry point.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open this binary: [ls_arm.zip](https://github.com/Vector35/binaryninja-api/files/7818612/ls_arm.zip)
2. Go to _start, HLIL flow graph
3. Observe the block at `335 @ 100003ea8` (it should be to the right of the entry block

**Expected Behavior:**
I expected all HLIL basic blocks to have control flow into them from the entry block

**Screenshots:**
Notice how there are two blocks with no parents
![image](https://user-images.githubusercontent.com/711973/148310225-fda1e74e-402d-414a-8914-ccd2d6bcf051.png)

**Comment by psifertex** [comment] 2022-01-12 17:45
This might actually be a duplicate of https://github.com/Vector35/binaryninja-api/issues/2809 after looking at that bug in graph view as well.
![Screen Shot 2022-01-12 at 12 45 23 PM](https://user-images.githubusercontent.com/140215/149193825-2977c5d6-d4ba-4ed9-bfb4-12145f2d7bc5.png)

We'll wait for triage to confirm.

**Comment by D0ntPanic** [comment] 2022-02-04 01:46
This appears to be caused by switch statements with no default case (which means that a case that is not covered will do nothing). There is no edge generated in the graph for this fall through case. In this particular binary the two defined cases both jump to the start of the loop, so the missing fall through case is the only route to the rest of the loop code. The linear view of the decompilation is correct.

**Comment by D0ntPanic** [comment] 2022-06-22 23:45
Fixed in build 3528

**Closed by D0ntPanic** 2022-06-22 23:45 UTC
Labels: bug, HLIL, Effort: Low, Impact: Medium
