### ISSUE TITLE
Show function arguments in disassembly graph

### ISSUE THREAD

**Issue by bmuessig** [Vector35/binaryninja-api#1353] opened 2019-05-22 21:06 UTC
Binary Ninja Version: 1.1.1555 Personal, 1d59e7dc
Platform: Ubuntu 18.04.2 LTS

The other big reverse engineering platform has a very nice feature, where the names of the function arguments are shown in a comment next to their stack pushes before the function branch. I find this feature very useful as it allows you to quickly grasp which pushes will result in which arguments. It would also be great, if the arguments passed to the currently displayed function would be presented in a similar way next to lines loading them in the disassembly graph.

**Comment by plafosse** [comment] 2019-05-22 21:07
Duplicate of https://github.com/Vector35/binaryninja-api/issues/237

**Closed by plafosse** 2019-05-22 21:07 UTC
Labels: duplicate

**Comment by psifertex** [comment] 2019-05-22 21:33
D'oh, my fault -- I should have remembered that other issue and I directed @bmuessig to file this. Sorry about that.
