### ISSUE TITLE
Using registered_name of created type returns broken Type object

### ISSUE THREAD

**Issue by kristopax** [Vector35/binaryninja-api#4085] opened 2023-03-08 17:02 UTC
**Version and Platform (required):**
- Binary Ninja Version: latest
- OS: MacOS
- OS Version: Ventura
- CPU Architecture: M1

**Bug Description:**
Creating a PointerType from a struct type using registered_name returns a broken type.

**Steps To Reproduce:**

1. Run the following code in the Python console:
```
current_function.parameter_vars[0].type = PointerType.create(bv.arch, bv.types["struct_1"].registered_name)
with Type.builder(bv, 'struct_1') as modified:
  modified.add_member_at_offset("top", Type.int(8), 0, overwrite_existing=True)
```
2. The structure won't get updated

**Expected Behavior:**
The structure should get updated.

The binary for this issue has been provided separately.

**Comment by plafosse** [comment] 2023-03-08 17:50
Duplicate of #4084

**Closed by plafosse** 2023-03-08 17:50 UTC
Labels: bug, duplicate, API, Effort: Low, Impact: Medium
