### ISSUE TITLE
Assembler errors not formatted correctly. 

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3695] opened 2022-11-24 18:23 UTC
**Version and Platform (required):**

**Bug Description:**
Assembler errors appear to be running python's `str()` on a bytes object, instead of decoding it. 

**Steps To Reproduce:**
1. Write some bad assembly (see me for help I am an expert at this.) 

**Screenshots:**

![image](https://user-images.githubusercontent.com/55725881/203841153-817bf177-bccf-427a-b11a-e0a14b01209c.png)

**Comment by fuzyll** [comment] 2023-07-19 15:23
Are you able to reproduce this? It seems like it might've been fixed at some point, because this is what my test case gave me:

<img width="479" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/607452/8361dba5-96ec-4c4b-a4f3-9a9c56cfcb0d">

The output is also different depending on the assembler. Which assembler were you testing with? The image above is with `arm64` (which is what I'm assuming you were testing with, but maybe not).

**Comment by fuzyll** [comment] 2023-07-28 18:08
Closing this since I can't reproduce it. Hoping that means it's fixed! 🤞

**Closed by fuzyll** 2023-07-28 18:08 UTC
Labels: Type: Bug, Component: UI, State: Unreproducible, Impact: Low, Effort: Trivial, UI: Dialogs
