### ISSUE TITLE
Binja should have an RVA type for use in PE headers and elsewhere

### ISSUE THREAD

**Issue by LunNova** [Vector35/binaryninja-api#3762] opened 2023-01-01 06:50 UTC
Relative virtual addresses are declared as uint32_t and don't show up as xrefs.

PE header with uint32 pointing at .reloc: 
![PE header with uint32 pointing at .reloc](https://user-images.githubusercontent.com/782440/210163030-58124b3d-69d7-477b-9418-7797b3856790.png)

Start of .reloc section at 0x14... + that RVA: 
![Start of .reloc section at 0x14... + that RVA](https://user-images.githubusercontent.com/782440/210163054-cac2b0ce-87c0-4373-8bef-969c4cd775d6.png)

x-refs empty: 
![x-refs empty](https://user-images.githubusercontent.com/782440/210163066-be8303d0-cec6-4264-ab5b-51dd82fd70b0.png)

Having 32 and 64 bit RVA types relative to image base would be useful to allow x-refs to work for the PE header, references in the pdata section, and so on.

I tried to work out how to define a type for RVAs myself but if it's possible I can't work out how.

**Comment by jonpalmisc** [comment] 2023-01-01 11:21
Seems to be a duplicate of #2785.

**Closed** 2023-01-01 11:21 UTC
