### ISSUE TITLE
apply_auto_discovered_type

### ISSUE THREAD

**Issue by ea** [Vector35/binaryninja-api#3222] opened 2022-06-27 19:27 UTC
**Version and Platform (required):**
- Version: 3.1.3523-dev
- OS: macOS
- OS Version: 12
- CPU Architecture x64

**Bug Description:**

Seems like `apply_auto_discovered_type` easily crashes whole Binary Ninja when trying to apply a type with unknown (or empty) struct. It seems to me like it crashes after the type is applied.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to any function
2. make sure `struct in_addr` is NOT defined.
3. execute `current_function.apply_auto_discovered_type("char *a (const struct in_addr *arg1, char *s);")`
4. Binja should crash

**Expected Behavior:**
Expecting an error of some sort? 

**Additional Information:**
This can obviously be worked around and it's my fault for not defining the struct first, but I thought i should report it.
Cheers!

**Comment by negasora** [comment] 2022-06-29 19:34
I can't reproduce with 3.1.3539-dev

**Comment by ea** [comment] 2022-06-29 21:07
Weird , here's how i reproduce it:
![Screen Shot 2022-06-29 at 4 03 06 PM](https://user-images.githubusercontent.com/65802/176544465-05436e0d-facf-4d10-aa99-1f5db7b51242.png)

As soon as i hit return , crashes. 
Attaching a crashdump as well in case that might be helpful, but i don't really see anything outright useful in it.

[struct_crash_report.txt](https://github.com/Vector35/binaryninja-api/files/9014529/struct_crash_report.txt)

**Comment by ea** [comment] 2022-06-29 21:08
Should add, the above binary is just `/bin/cat` on macOS

**Comment by negasora** [comment] 2022-06-29 21:10
Tried on a different binary and it repro'd, ty!

**Comment by negasora** [comment] 2022-06-29 23:28
Fixed in 3.1.3542-dev

**Closed by negasora** 2022-06-29 23:28 UTC
Labels: bug, crash
