### ISSUE TITLE
Need better handling of compiler optimizations for `%` operator

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3302] opened 2022-07-20 14:15 UTC
I have a piece of code like this (x64, msvc):

```c
int test_function()
{
    TestStructure* s1 = malloc(sizeof(TestStructure));
    s1->e1 = rand() % 1000;
    s1->e2 = rand() % 2000;
    s1->e3 = rand() % 3000;
    s1->e4 = rand() % 4000;
    s1->e5 = rand() % 5000;

    return 0;
}
```

In HLIL view, BN gives me an output like below after creating the `TestStructure` by hand:

```
180001ae0  int64_t test_function()

180001aeb      struct TestStructure* rax = j_sub_18000a48c(0x20)
180001af3      int32_t rax_1 = sub_1800092f8()
180001b00      int32_t temp0
180001b00      int32_t temp1
180001b00      temp0:temp1 = muls.dp.d(0x10624dd3, rax_1)
180001b03      int32_t rdx_1 = temp0 s>> 6
180001b16      rax->e1 = rax_1 - (rdx_1 + (rdx_1 u>> 0x1f)) * 0x3e8
180001b19      int32_t rax_3 = sub_1800092f8()
180001b26      int32_t temp2
180001b26      int32_t temp3
180001b26      temp2:temp3 = muls.dp.d(0x10624dd3, rax_3)
180001b29      int32_t rdx_4 = temp2 s>> 7
180001b3f      rax->e2 = sx.q(rax_3 - (rdx_4 + (rdx_4 u>> 0x1f)) * 0x7d0)
180001b43      int32_t rax_5 = sub_1800092f8()
180001b50      int32_t temp4
180001b50      int32_t temp5
180001b50      temp4:temp5 = muls.dp.d(0x57619f1, rax_5)
180001b53      int32_t rdx_7 = temp4 s>> 6
180001b69      rax->e3 = sx.q(rax_5 - (rdx_7 + (rdx_7 u>> 0x1f)) * 0xbb8)
180001b6d      int32_t rax_7 = sub_1800092f8()
180001b7a      int32_t temp6
180001b7a      int32_t temp7
180001b7a      temp6:temp7 = muls.dp.d(0x10624dd3, rax_7)
180001b7d      int32_t rdx_10 = temp6 s>> 8
180001b93      rax->e4 = sx.q(rax_7 - (rdx_10 + (rdx_10 u>> 0x1f)) * 0xfa0)
180001b97      int32_t rax_9 = sub_1800092f8()
180001ba4      int32_t temp8
180001ba4      int32_t temp9
180001ba4      temp8:temp9 = muls.dp.d(0x68db8bad, rax_9)
180001ba7      int32_t rdx_13 = temp8 s>> 0xb
180001bba      rax->e5 = rax_9 - (rdx_13 + (rdx_13 u>> 0x1f)) * 0x1388
180001bc5      return 0
```

I see three things in this output those should be improved in order to improve BN's decompiler:

* BN does not recognize `malloc` and `rand` function
* BN handles compiler optimization (I guess that is an optimization) in a way that makes understanding what is happening harder
* BN makes assignments in different lines for structure elements. Maybe, it could be resolved if optimization is handled more gracefully?

Is the first one is related to recognizing standard library functions which is already mentioned in #3268?

**Comment by psifertex** [comment] 2022-07-20 15:11
Duplicate of #2043

**Closed as completed by psifertex** 2022-07-20 15:11 UTC
