### ISSUE TITLE
BN crashes upon analyzing a file

### ISSUE THREAD

**Issue by fluxchief** [Vector35/binaryninja-api#717] opened 2017-06-21 19:14 UTC
```(15f8.26b8): Access violation - code c0000005 (!!! second chance !!!)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Program Files\Vector35\BinaryNinja\binaryninjacore.dll - 
binaryninjacore!BNToVariableIdentifier+0x1093:
00007ffc`28fc5513 488b5310        mov     rdx,qword ptr [rbx+10h] ds:00000246`2e6d7a10=????????????????
```

[sample.zip](https://github.com/Vector35/binaryninja-api/files/1092620/sample.zip)
BN Version 1.0.766-dev 59284be2

**Comment by psifertex** [comment] 2017-06-21 19:16
Just to confirm, you're running on Windows? What version of the OS? The crash doesn't reproduce for me on windows, want to get the same setup to test.

**Comment by fluxchief** [comment] 2017-06-21 19:19
Stacktrace (from a separate run, so addresses might vary):

```
0000002b`ef9fe620 00007ffc`28fc464e : 0000002b`ef9feb78 0000002b`ef9ff0b0 00000000`00000000 0000012c`ec848478 : binaryninjacore!BNToVariableIdentifier+0x1093
0000002b`ef9feb40 00007ffc`28f9baa3 : 0000002b`ef9ff0b0 0000012c`00000000 0000012c`ee632fe0 0000012c`ee632fe0 : binaryninjacore!BNToVariableIdentifier+0x1ce
0000002b`ef9feb70 00007ffc`28dc6ee4 : 0000002b`ef9ff2a0 00000000`ffffffff 00000000`00000001 0000012c`ea0c5d80 : binaryninjacore!BNNewTemporaryFileReference+0x9673
0000002b`ef9ff250 00007ffc`28dbb3c1 : 0000012c`eb3192b0 0000012c`eb03b830 00000000`00000001 0000012c`eb03b830 : binaryninjacore!BNSetDisassemblyWidth+0x20464
0000002b`ef9ff3a0 00007ffc`28e16b6e : 0000012c`eb03b701 0000012c`ed81f140 0000012c`ed821e40 00007ffc`3c93886f : binaryninjacore!BNSetDisassemblyWidth+0x14941
0000002b`ef9ff5a0 00007ffc`28d97267 : 0000012c`e9f47270 0000012c`e9f47270 00000000`00000000 0000012c`ed81f740 : binaryninjacore!BNUpdateAnalysis+0x7fe
0000002b`ef9ff620 00007ffc`28d97ba7 : 0000002b`eeaf91d8 00000000`00000000 0000012c`e7682620 00000000`00000000 : binaryninjacore!BNSetBinaryViewTypeArchitectureConstant+0x1487
0000002b`ef9ff6e0 00007ffc`28d6c969 : 0000012c`e7a4f060 00000000`00000000 00000000`00000000 00000000`00000000 : binaryninjacore!BNSetBinaryViewTypeArchitectureConstant+0x1dc7
0000002b`ef9ff720 00007ffc`5b5d0369 : 00000000`d91d0000 0000012c`e7a4f060 00000000`00000000 00000000`00000000 : binaryninjacore!BNRegisterUndoActionType+0x3be9
0000002b`ef9ff750 00007ffc`5dd82774 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ucrtbase!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x39
0000002b`ef9ff780 00007ffc`5f100d61 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
0000002b`ef9ff7b0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21
```

Windows 10 EDU x64

**Comment by psifertex** [comment] 2017-06-22 01:16
Thanks. I can repro it on Win10. Will let you know when we've got a fix.

**Comment by robert-yates** [comment] 2017-06-22 13:47
This looks like the same crash that im also having

**Comment by D0ntPanic** [comment] 2017-06-22 23:26
Fixed in dev build 772

**Closed by D0ntPanic** 2017-06-22 23:26 UTC
Labels: bug, core
