### ISSUE TITLE
Copy address only works on symbols

### ISSUE THREAD

**Issue by evanpjensen** [Vector35/binaryninja-api#1255] opened 2019-01-24 17:33 UTC
Video of the behavior 
https://youtu.be/qMP6U5dZ21g

**Comment by psifertex** [comment] 2019-01-24 18:56
I think copy address is behaving as intended here -- the issue is you have to first select the thing you want to copy the address of. 

I suppose we could modify it such that if the right click itself occurs on an address it would use that address as well? I dunno, need to think this one through because sometimes it's nice to have something selected and be able to right-click and select copy address without worrying what's under your cursor.

**Comment by evanpjensen** [comment] 2019-01-24 20:44
Either grey it out when selecting things for which the operation is invalid or copy the address. I'd prefer that the address be copyable, an example of when you might want this is when selecting into the middle of an array.  When making an array of structs, getting the address of the second element either results in 0 if you execute "copy address" on the address or the element number if you select the element number instead. 

Also, copy address from the edit menu appears to be broken. At minimum it's not the same operation as copy address from the right button menu.

It's possible I'm doing everything wrong because ctrl+c does what I want in almost every case.

**Comment by psifertex** [comment] 2019-01-25 00:17
The address /is/ copyable if you left click it first (it moves the cursor to the first byte on that line which has the right address). My point is that the way the "copy address" function always works is you first select something, then copy it's address. If we changed it so you didn't have to actually select something first it would be a different workflow. Maybe better? I'm not totally sure though. 

I just tested the hotkey and menu for copy address and they both worked for me. Can you give me specific repro instructions for the copy address edit menu not working?

**Comment by psifertex** [comment] 2019-02-13 19:49
Looks like we missed closing this one when it was resolved.

**Closed by psifertex** 2019-02-13 19:49 UTC
Labels: bug
