### ISSUE TITLE
Right clicking in report collection causes crash

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1485] opened 2019-11-20 04:18 UTC
Version: 1.2.1956-dev
```
Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libbinaryninjaui.dylib        	0x000000010c564b9a 0x10c357000 + 2153370
1   libbinaryninjaui.dylib        	0x000000010c51f679 0x10c357000 + 1869433
2   libbinaryninjaui.dylib        	0x000000010c3a8baa MenuInstance::layoutMenu(std::__1::map<QString, QString, std::__1::less<QString>, std::__1::allocator<std::__1::pair<QString const, QString> > > const&, QString const&, bool) + 1546
3   libbinaryninjaui.dylib        	0x000000010c3a6ff7 MenuInstance::update(UIActionHandler*, UIActionContext const&, bool) + 215
4   libbinaryninjaui.dylib        	0x000000010c3a6d9d MenuInstance::update(UIActionHandler*, bool) + 317
5   libbinaryninjaui.dylib        	0x000000010c3a6b57 Menu::create(QWidget*, UIActionHandler*, bool) + 263
6   libbinaryninjaui.dylib        	0x000000010c45e915 ContextMenuManager::show(Menu*, UIActionHandler*) + 101
7   libbinaryninjaui.dylib        	0x000000010c505a03 FlowGraphWidget::mousePressEvent(QMouseEvent*) + 1955
8   org.qt-project.QtWidgets      	0x000000010e5335f8 QWidget::event(QEvent*) + 424
9   org.qt-project.QtWidgets      	0x000000010e5db21d QFrame::event(QEvent*) + 45
10  org.qt-project.QtCore         	0x000000010f816a74 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 148
11  org.qt-project.QtWidgets      	0x000000010e4f7758 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 248
12  org.qt-project.QtWidgets      	0x000000010e4fa5c8 QApplication::notify(QObject*, QEvent*) + 7336
13  org.qt-project.QtCore         	0x000000010f8167c4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
14  org.qt-project.QtWidgets      	0x000000010e4f8090 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 896
```

**Comment by psifertex** [comment] 2019-11-20 19:35
This is almost certainly a duplicate of #1484 and isn't reproducible on example report collections we test. 

There's something unique about your use case that we'll need to minimize to reproduce. Marking as duplicate, will re-open if it turns out to be unique.

**Closed by psifertex** 2019-11-20 19:35 UTC
Labels: crash, duplicate
