### ISSUE TITLE
Incorrect disassembly of pushq

### ISSUE THREAD

**Issue by amatus** [Vector35/binaryninja-api#860] opened 2017-11-07 20:54 UTC
objdump:
```
  4006e7:	ff 75 f8             	pushq  -0x8(%rbp)
```
rasm2:
```
push qword [rbp - 8]
```
binja:
```
004006e7  ff75f8                  push     dword [rbp-0x8]
```
One of these things is not like the other...

**Comment by joshwatson** [comment] 2017-11-07 21:01
Duplicate of #732

**Comment by plafosse** [comment] 2017-11-08 00:32
Fixed in dev 1.1.991

**Closed by plafosse** 2017-11-08 00:32 UTC
