### ISSUE TITLE
Set contents of __mod_init_func and __mod_term_func as function pointers

### ISSUE THREAD

**Issue by shellcromancer** [Vector35/binaryninja-api#3913] opened 2023-02-19 00:40 UTC
**What is the feature you'd like to have?**
To improve analyzing Mach-O's that have C++ classes, it would be great to have the function pointers typed in the  `__DATA/__mod_init_func` and `__DATA/__mod_term_func` like shown.  For mod_init_func's they are typed as `void (*)(int, char **, char **, char **)` in [dyld](https://github.com/opensource-apple/dyld/blob/master/src/ImageLoaderMachO.cpp#L1839) and it seems like mod_term_func's have no parameters/return in [dyld](https://github.com/opensource-apple/dyld/blob/master/src/ImageLoaderMachO.cpp#L1935).

![image](https://user-images.githubusercontent.com/21696437/219905572-e3ae0a48-776f-4608-a76c-df981e502333.png)

**Is your feature request related to a problem?**
Today this section is parsed and displayed as standard data, which isn't wrong but types could be a better default. 
![image](https://user-images.githubusercontent.com/21696437/219905570-46eb771b-3d32-4e41-a1b2-74c32368973e.png)

**Are any alternative solutions acceptable?**
Leaving this as is? 🤷‍♂️

**Additional Information:**
Discussion in [slack](https://binaryninja.slack.com/archives/C04ATNJ2U9J/p1674832231932809) on this.

**Comment by cxnder** [comment] 2023-02-21 15:26
Duplicate of #3334

**Closed by cxnder** 2023-02-21 15:26 UTC
Labels: enhancement, Impact: Low, Effort: Trivial
