### ISSUE TITLE
Disassembling NtUserDestroyWindow() Will Result in Extra Arguments

### ISSUE THREAD

**Issue by gwillcox-r7** [Vector35/binaryninja-api#1671] opened 2020-05-15 19:56 UTC
Attempting to disassemble NtUserDestroyWindow() from win32kfull.sys will result in extra arguments being shown in Binary Ninja. Somehow it thought it was a bright idea to assign every other zmm register as an argument to the function? I really have no idea how this happened:

![Screen Shot 2020-05-15 at 2 56 02 PM](https://user-images.githubusercontent.com/63261883/82090985-34148700-96bc-11ea-907a-47efd0b159af.png)

Looks like the disassembler might need to be readjusted. For reference NtUserDestroyWindow() should only take in one argument, a HWND argument named hWnd.

This was tested using Binary Ninja 2.0.2147-dev on MacOSX

**Comment by gwillcox-r7** [comment] 2020-05-15 20:01
Oh also funnily enough this also propagates through to other calls and affects HLIL as well:

![Screen Shot 2020-05-15 at 3 01 19 PM](https://user-images.githubusercontent.com/63261883/82091423-f06e4d00-96bc-11ea-8af7-c2f49786d27d.png)

![Screen Shot 2020-05-15 at 3 01 43 PM](https://user-images.githubusercontent.com/63261883/82091452-ff54ff80-96bc-11ea-8721-a2baf6dfa024.png)

**Comment by bpotchik** [comment] 2020-05-15 20:02
She issue as Function Parameter Propagation Issues #1456

**Comment by gwillcox-r7** [comment] 2020-05-15 20:06
@bpotchik I'm not so sure as there are no cross references to NtUserDestroyWindow, so not sure how the function parameter propagation would affect this? Or is that title misleading?

**Comment by bpotchik** [comment] 2020-05-15 20:11
What are the signatures of the Validate and UserSession functions that get called?

**Comment by gwillcox-r7** [comment] 2020-05-15 20:57
Hmm xxxDestroyWindow() calls about 14 other functions, so kind of hard to tell. Given that I have seen SSE/AVX used as optimizations before though I'd say this is a plausible argument. Initial quick inspection didn't turn up anything using SSE but again probably would need to look deeper but don't have the time to dig through 40+ functions to check this right now.

**Comment by plafosse** [comment] 2020-05-27 18:52
Duplicate of #1456

**Closed by plafosse** 2020-05-27 18:52 UTC
