### ISSUE TITLE
Closing search results causes crash

### ISSUE THREAD

**Issue by malre0x21** [Vector35/binaryninja-api#3064] opened 2022-04-09 12:57 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3337-dev (2022-04-08 19:33:12)  
- OS: MacOS
- OS Version: Monterey 12.3.1

**Bug Description:**
Binaryninja crashes whenever closing the search results box window.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Go to Edit -> Find (or CMD-F)
2. Perform a search 
3. Close the result window after the search displays the results

**Expected Behavior:**
Should be able to close the search results and still remain in the same view in the UI before the search window was opened

**Comment by psifertex** [comment] 2022-04-09 16:35
I'm not able to replicate this using the exact same BN on the exact same MacOS.

Can you try with:
1) Another file
2) Disabling [user settings](https://dev-docs.binary.ninja/guide/troubleshooting.html#disabling-user-settings)
3) [Disabling plugins](https://docs.binary.ninja/guide/troubleshooting.html#disabling-plugins)

To clarify, you're using the "find all" checkbox?

**Comment by malre0x21** [comment] 2022-04-09 17:02
ah.. yes I forgot to add that this happens with the "find all" option checked. I've tested multiple files with user settings and plugins disabled and as long as the "find all option" is checked binja crashes on my installation.

**Comment by psifertex** [comment] 2022-04-09 19:37
Thanks. It looks like this bug is happening only on x64 builds on MacOS,  not M1. We've reproduced it and are testing a fix.

**Comment by D0ntPanic** [comment] 2022-04-10 00:57
Fixed in build 3338

**Closed by D0ntPanic** 2022-04-10 00:57 UTC

**Comment by malre0x21** [comment] 2022-04-10 08:45
This is why ya'll can have all my money!
