### ISSUE TITLE
Function args are not propagated when __cdecl convention is used

### ISSUE THREAD

**Issue by peperunas** [Vector35/binaryninja-api#928] opened 2018-02-04 06:34 UTC
The function arguments aren't displayed in the disassembly view.

![image](https://user-images.githubusercontent.com/6033387/35774922-37857652-0932-11e8-864e-c5c6ecd3a4df.png)

**Comment by plafosse** [comment] 2019-02-27 20:22
I believe this is a dupe of #237

**Closed by plafosse** 2019-02-27 20:22 UTC
Labels: duplicate
