### ISSUE TITLE
No indication of string type with inlined strings

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#4271] opened 2023-04-29 00:00 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4265
- OS: macOS
- OS Version: 13.3.1
- CPU Architecture: M1

**Bug Description:**

When strings are inlined in any way, there is no indication about the character width, which can lead to confusion:

For example:
```rax_15 = sub_140076334(rcx_9, 0x110, "\logs\", 6)```
Is defined in the data section as:
```wchar16 data_1400d10a0[0x7] = "\\logs\\", 0```

This can especially be confusing with outlined memcpy, as the data types are often not defined and the data itself is the only source of information about it:

```__builtin_memcpy(dest: var_58, src: "SystemRoot", n: 0x16)```

In this case, the string is a `wchar16` string, but there is no indication other than by doing the math manually or looking at the assembly to determine this.

**Comment by op2786** [comment] 2023-05-02 07:16
Could be duplicate of #3301.

**Closed** 2023-05-04 00:40 UTC
