### ISSUE TITLE
BN fails showing `'` in stack string initialization

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4154] opened 2023-03-27 11:39 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4170-dev
- OS: Windows 11, x64

**Bug Description:**

HLIL:
```
08049d68        char s[0x24]
08049d68        __builtin_strncpy(s[0], "I HAVE THE CONCH DON", 0x14)
08049df9        s[0x14] = 0x5
08049dfc        __builtin_strncpy(s[0x15], "T INTERRUPT ME", 0xf)
```

Assembly:
```assembly
08049d68  c6856cffffff49     mov     byte [ebp-0x94 {s[0]}], 0x49
08049d6f  c6856dffffff20     mov     byte [ebp-0x93 {s[1]}], 0x20
08049d76  c6856effffff48     mov     byte [ebp-0x92 {s[2]}], 0x48
08049d7d  c6856fffffff41     mov     byte [ebp-0x91 {s[3]}], 0x41
08049d84  c68570ffffff56     mov     byte [ebp-0x90 {s[4]}], 0x56
08049d8b  c68571ffffff45     mov     byte [ebp-0x8f {s[5]}], 0x45
08049d92  c68572ffffff20     mov     byte [ebp-0x8e {s[6]}], 0x20
08049d99  c68573ffffff54     mov     byte [ebp-0x8d {s[7]}], 0x54
08049da0  c68574ffffff48     mov     byte [ebp-0x8c {s[8]}], 0x48
08049da7  c68575ffffff45     mov     byte [ebp-0x8b {s[9]}], 0x45
08049dae  c68576ffffff20     mov     byte [ebp-0x8a {s[0xa]}], 0x20
08049db5  c68577ffffff43     mov     byte [ebp-0x89 {s[0xb]}], 0x43
08049dbc  c68578ffffff4f     mov     byte [ebp-0x88 {s[0xc]}], 0x4f
08049dc3  c68579ffffff4e     mov     byte [ebp-0x87 {s[0xd]}], 0x4e
08049dca  c6857affffff43     mov     byte [ebp-0x86 {s[0xe]}], 0x43
08049dd1  c6857bffffff48     mov     byte [ebp-0x85 {s[0xf]}], 0x48
08049dd8  c6857cffffff20     mov     byte [ebp-0x84 {s[0x10]}], 0x20
08049ddf  c6857dffffff44     mov     byte [ebp-0x83 {s[0x11]}], 0x44
08049de6  c6857effffff4f     mov     byte [ebp-0x82 {s[0x12]}], 0x4f
08049ded  c6857fffffff4e     mov     byte [ebp-0x81 {s[0x13]}], 0x4e
08049df4  b805650508         mov     eax, data_8056505
08049df9  884580             mov     byte [ebp-0x80 {s[0x14]}], al  {0x5}
08049dfc  c6458154           mov     byte [ebp-0x7f {s[0x15]}], 0x54
08049e00  c6458220           mov     byte [ebp-0x7e {s[0x16]}], 0x20
08049e04  c6458349           mov     byte [ebp-0x7d {s[0x17]}], 0x49
08049e08  c645844e           mov     byte [ebp-0x7c {s[0x18]}], 0x4e
08049e0c  c6458554           mov     byte [ebp-0x7b {s[0x19]}], 0x54
08049e10  c6458645           mov     byte [ebp-0x7a {s[0x1a]}], 0x45
08049e14  c6458752           mov     byte [ebp-0x79 {s[0x1b]}], 0x52
08049e18  c6458852           mov     byte [ebp-0x78 {s[0x1c]}], 0x52
08049e1c  c6458955           mov     byte [ebp-0x77 {s[0x1d]}], 0x55
08049e20  c6458a50           mov     byte [ebp-0x76 {s[0x1e]}], 0x50
08049e24  c6458b54           mov     byte [ebp-0x75 {s[0x1f]}], 0x54
08049e28  c6458c20           mov     byte [ebp-0x74 {s[0x20]}], 0x20
08049e2c  c6458d4d           mov     byte [ebp-0x73 {s[0x21]}], 0x4d
08049e30  c6458e45           mov     byte [ebp-0x72 {s[0x22]}], 0x45
08049e34  c6458f00           mov     byte [ebp-0x71 {s[0x23]}], 0x0
```

As you can see disassembly shows that it uses some data from `data_8056505` which is `0x27` defined as `int16_t`. Even if I retype it as `char data_8056505[2]` it does not uses `'` at `08049df9`.

**Steps To Reproduce:**
* Download the attached binary and open it
* Go to address 08049df4 
* Set `var_98` type as `char s[0x24]`
* See the bug

**Expected Behavior:**
I expect it to show it correctly as `'`.  It would be even better if BN would do this in a single strncpy.

**Additional Information:**

[break.zip](https://github.com/Vector35/binaryninja-api/files/11078103/break.zip)

**Comment by plafosse** [comment] 2023-04-04 00:20
Thats because the code doesn't do what its supposed to do. The instruction moves the address of the `'` into the register not the `'` itself:
![image](https://user-images.githubusercontent.com/10556585/229654338-fedd1958-b4d7-4a35-9245-511146ea2901.png)

If you modify the code to instead move the value at the address into the eax register everything seems to work just fine

![image](https://user-images.githubusercontent.com/10556585/229654193-7b40304c-38de-4684-a996-ae3650899d85.png)

Thanks for the report but I'm going to mark this as won't fix as it seems to be working as intended.

**Closed by plafosse** 2023-04-04 00:20 UTC
Labels: wontfix
