### ISSUE TITLE
Database Corruption on dev build - Version 1.3.2050-dev

### ISSUE THREAD

**Issue by Knight-Ops** [Vector35/binaryninja-api#1550] opened 2020-03-11 18:02 UTC
Binary Ninja Version 1.3.2050-dev (Build ID 7d40bc24)

While using `1.3.2050-dev` and a custom View, it seems that save files are corrupted without any notification there might be an issue until you try to reopen them. This corruption means you don't get most (maybe any) of user analysis, specifically including any user types are not loaded from the database and no snapshot can be loaded so analysis happens again.

Specific Error : `Error while reading snapshot from database: Exception while parsing json.`

**Comment by negasora** [comment] 2020-03-11 19:40
Are you able to share the bndb? That would help track down the root cause.

**Comment by psifertex** [comment] 2020-03-11 21:12
Also, do you mean that the problem first showed up on 2050 and wasn't there in previous builds or just that you noticed it there?

**Comment by Knight-Ops** [comment] 2020-03-12 02:27
I noticed it there, and it is reproducible I don't have reason to believe
it happened on any other build because the time frame for corruption
spanned about 3 days (based on my version control of the database being
corrupted for these days). I can't share the database currently, but I am
working on it, if there is other information I can provide to help
troubleshoot, please let me know.

**Comment by bpotchik** [comment] 2020-03-29 17:05
@Knight-Ops I found the issue causing this. No data has been lost. The next dev build should be able to load your custom view correctly.

**Comment by bpotchik** [comment] 2020-03-29 17:06
Fixed in 1.3.2075-dev.

**Closed by bpotchik** 2020-03-29 17:06 UTC
Labels: bug
