### ISSUE TITLE
zero sized data variable arrays break linear view

### ISSUE THREAD

**Issue by Maykeye** [Vector35/binaryninja-api#782] opened 2017-09-02 02:23 UTC
It should do something other than spamming the same address

http://i.imgur.com/0fNRcCq.jpg

Like print once/print an error/assume whole section of length N is actually char[N] instead of char [0], assume

**Comment by plafosse** [comment] 2018-01-12 01:16
This is actually a display bug in linear view. Changing the title to reflect this.

**Comment by plafosse** [comment] 2018-01-16 23:34
The root cause is this code in `core/lineardisassembly.cpp`
```
if (IsDataVariableDisplayedAsValue(pos.address, var))
{
    endDataAddr = pos.address + var.type->GetWidth();
```
I haven't looked into this code enough to know how this needs to be fixed.

**Comment by D0ntPanic** [comment] 2018-03-20 02:24
Fixed in build 1123

**Closed by D0ntPanic** 2018-03-20 02:24 UTC
Labels: bug
