### ISSUE TITLE
Feature request: Comments on struct fields

### ISSUE THREAD

**Issue by comex** [Vector35/binaryninja-api#4069] opened 2023-03-04 21:28 UTC
**What is the feature you'd like to have?**
I'd like to add a comment next to a struct field to document how the field is used.  This should show up in the types view, as well as in the main view when the field is referenced.

**Are any alternative solutions acceptable?**
There might be other UI designs that can accomplish similar goals, but I can't think of anything in particular.

**Additional Information:**
IDA and Ghidra both support adding comments to fields, though I don't know if Ghidra does the "show in main view when field is referenced" bit.

**Comment by ccarpenter04** [comment] 2023-03-05 18:14
I think this would be a good addition to the types view, hover I don't think the comments should be displayed in the linear view unless the field is hovered.

**Comment by plafosse** [comment] 2023-03-06 18:06
Yeah I agree this is a duplicate of this issue: https://github.com/Vector35/binaryninja-api/issues/1244

**Closed by plafosse** 2023-03-06 18:06 UTC
Labels: duplicate, enhancement
