### ISSUE TITLE
hide base/offset features in "create Structure" dialog by default

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#5259] opened 2024-04-10 14:34 UTC
Advanced options such as working with offset/base types and propagating data variable references are shown by default in the "create structure" dialog but they are advanced options many users may not use and it would improve the experience to fold those into a drawer/drop-down.

**Comment by alexrp** [comment] 2024-04-10 14:50
FWIW, I*m not exaggerating when I say that 95%+ of the types I define make use of these features while reversing large C++ binaries. So if you do this, please be sure to make the dialog remember the opened/closed state of the drawer. :eyes:

**Comment by psifertex** [comment] 2024-04-10 16:57
That's a great point -- it should absolutely remember the state.

**Comment by xusheng6** [comment] 2024-05-31 04:18
Duplicate of https://github.com/Vector35/binaryninja-api/issues/4268

**Closed by xusheng6** 2024-05-31 04:18 UTC
Labels: Type: Enhancement, Component: UI, Impact: Low, Effort: Trivial, UI: Dialogs
