### ISSUE TITLE
Allowed to create types with '::' in name, but cannot apply types named that way

### ISSUE THREAD

**Issue by Douggem** [Vector35/binaryninja-api#2298] opened 2021-03-04 22:10 UTC
I'm auto generating types with RTTI, so I end up generating structs with namespaces in their names.  It lets me name the types like that, but I can't assign a var to that type with the change type dialog, I'm assuming because of the colons

![image](https://user-images.githubusercontent.com/4275220/110037501-7d49cc00-7d0c-11eb-97e5-4abee6c26927.png)

![image](https://user-images.githubusercontent.com/4275220/110037517-833fad00-7d0c-11eb-98ae-1f86c71cb6c3.png)

**Comment by ccarpenter04** [comment] 2021-03-05 00:36
I can confirm this bug exists.

**Comment by yrp604** [comment] 2021-03-05 04:54
This is a dupe of #1658 and is potentially related to #2285.

**Comment by CouleeApps** [comment] 2022-02-16 21:31
Type names with :: are now allowed via string escaping. See https://github.com/Vector35/binaryninja-api/issues/2427#issuecomment-1042327994 for details.

**Closed by CouleeApps** 2022-02-16 21:31 UTC
Labels: bug, Effort: Medium, Impact: Medium
