### ISSUE TITLE
Need to clamp maximum segment length to avoid performance issues

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#4850] opened 2023-12-29 08:55 UTC
Binary Ninja freezes if you leave the data length & offset fields blank when adding a segment ~~while initial analysis is held~~.

To reproduce, make the dialog look like this (or similar) ~~while initial analysis has been held~~, then click "Ok".

<img width="338" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/41548458/cf977f14-28cc-4ce1-b8cd-2cbbe82c1e97">

Binary Ninja 3.6.4738-dev, 8ff0a04d, macOS 14.2 (arm64)

**Comment by jonpalmisc** [comment] 2023-12-29 08:58
Update: Seems it doesn't matter if analysis is held, just happened again without an analysis hold.

**Comment by negasora** [comment] 2024-01-02 17:31
I can't repro this, but if I had to guess it's because you're in linear view and displaying that range at the time you add the segment. We should clamp the end to the max size of the address space instead of resolving it to `0x31ff` in this case

**Comment by xusheng6** [comment] 2024-01-03 04:58
I can reproduce it with this file (just a random ELF helloworld)

[helloworld.zip](https://github.com/Vector35/binaryninja-api/files/13815804/helloworld.zip)

Note the end of the segment is 0xfffffffffffff, which contains 13 'f's. Might just be a cursed address (no way!)

**Comment by xusheng6** [comment] 2024-01-03 05:05
This has nothing to do with the fields being empty -- you are simply creating a segment that is too large and it will create all sorts of issues (OOM being one of them, but the hang is caused by a different problem). We might wish to warn the user when they are creating very large segments? Maybe 4GB is a good size. 

Now I see this is related to #920. We are talking about how we should create an efficient storage to avoid the OOM when the user creates giant segments, and now we have a different problem to deal with

**Comment by jonpalmisc** [comment] 2024-01-06 14:38
FWIW, I was expecting IDA-like behavior when I typed in `0xffff....`. I was trying to create a segment backed by the file starting at 0x3200, spanning until the end of the file. I could have sworn this worked once, but maybe that was a section.

**Comment by bpotchik** [comment] 2024-05-16 15:38
@jonpalmisc if you want the length to be truncated with spanning until the end of the file, you need to also provide 0xffff......in the 'Data Length' field.

**Comment by bpotchik** [comment] 2024-05-16 15:39
Fixed in `4.1.5295-dev`.

**Closed by bpotchik** 2024-05-16 15:39 UTC
Labels: Type: Bug, Component: Core, Impact: Low, Effort: Trivial
