### ISSUE TITLE
Global pointer value not updated during re-analysis

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/binaryninja-api#1221] opened 2018-12-14 03:34 UTC
# Steps to duplicate

Paste the following hex into binja's hex view and make an x86 function at 0:

```
31c985db7e01c3c3
```

Now patch the first instruction to be `xor ebx, ebx`, causing `ebx` to be evaluated by dataflow to be `ConstantValue: 0`.

Now, you can undo that, patch in another one, nop it out, whatever, but binja will now think that `ebx` is `ConstantPointerValue: 0` (not even `ConstantValue: 0`). You can even undefine/recreate the function at 0 and it will still happen.

------

I first saw this issue pop up in an x68 PE (it manifested without any patching), but the end result of the above example is the same.

**Comment by plafosse** [comment] 2019-01-14 17:13
I've confirmed the issue, thanks for the report.

**Comment by chinmaydd** [comment] 2020-07-29 15:44
On the reanalysis which triggers after the undo/patching, `ebx` is identified as a constant (global) pointer value due to our heuristic. Unfortunately, we dont have an immediate fix for this yet.

**Comment by DanielAdolfsson** [comment] 2023-10-14 09:20
"Immediate" fix, surely not. I just ran into this problem. What's the workaround here?

**Comment by xusheng6** [comment] 2023-10-14 09:34
> "Immediate" fix, surely not. I just ran into this problem. What's the workaround here?

Try to re-analyze the offending function and it should fix it. You can right click and find the action to update the analysis (cannot remember its name)

**Comment by xusheng6** [comment] 2024-05-31 05:06
I just realized the even re-analyzing the function would not fix the issue -- the analysis result from dataflow are stuck and not going away even when the function bytes are restored to its origin. 

This might even be related to https://github.com/Vector35/binaryninja-api/issues/4288

**Comment by xusheng6** [comment] 2024-05-31 10:30
@toolCHAINZ @DanielAdolfsson Sorry for the long wait and I have been looking into this issue lately. I have identified the root cause of the issue and a fix is on its way! However, I noticed this issue is likely to be triggered on binaries with a very small number of functions, e.g., in the original complaint, there is literally just 1 function. If you have seen this issue happen on a larger and realistic binary, please let me know so I can evaluate the case more thoroughly

**Comment by toolCHAINZ** [comment] 2024-05-31 10:36
Hi @xusheng6, glad to hear this is getting resolved! It's been long enough, I don't have any idea what the original binary was, but I think it was an x86 PE from a CTF challenge or something. When I originally ran into this, it happened without any of the patching behavior in my reproduction instructions.

However, in the 6 years that have passed, I've never run into this again, so agreed it's probably pretty rare haha

**Comment by xusheng6** [comment] 2024-06-01 04:28
> Hi @xusheng6, glad to hear this is getting resolved! It's been long enough, I don't have any idea what the original binary was, but I think it was an x86 PE from a CTF challenge or something. When I originally ran into this, it happened without any of the patching behavior in my reproduction instructions.
> 
> However, in the 6 years that have passed, I've never run into this again, so agreed it's probably pretty rare haha

Thanks for letting me know it can also happen without the patching! I will think more thoroughly about the dynamics of this issue!

**Comment by xusheng6** [comment] 2024-06-03 03:10
I am bumping this to the next release since this does not look that important -- it can only be triggered in rare cases

**Closed** 2024-06-21 04:30 UTC
Labels: Type: Bug, Component: Core, Effort: High, Impact: Medium
