### ISSUE TITLE
FR: Fold branches in HLIL

### ISSUE THREAD

**Issue by WZ-Tong** [Vector35/binaryninja-api#4349] opened 2023-05-26 15:37 UTC
**What is the feature you'd like to have?**
Provide an option to collapse blocks (e.g. long "if" block).
If a large block (that I don't care) is between two blocks I care, it's hard to switch HLIL view (I must to find a suitable variable and use cross reference)

**Is your feature request related to a problem?**
No

**Are any alternative solutions acceptable?**
Provide a shortcut to jump to a bottom of the block

**Comment by psifertex** [comment] 2023-05-26 17:09
I believe this is a duplicate of #510 which is currently scheduled for two stable releases from now, recommend upvoting that issue.

**Comment by psifertex** [comment] 2023-05-26 17:10
And if you mean in graph view instead, that's a duplicate of #1142 so I'm gonna go ahead and close this for now as a duplicate. Feel free to correct me if I've misunderstood.

**Closed by psifertex** 2023-05-26 17:10 UTC
Labels: State: Duplicate
