### ISSUE TITLE
Ability to mark a range as "padding bytes"

### ISSUE THREAD

**Issue by rickmark** [Vector35/binaryninja-api#3812] opened 2023-01-19 23:37 UTC
**What is the feature you'd like to have?**
The ability to inform a binary view that a range are "padding bytes" to prevent them from being shown in the linear view.

**Is your feature request related to a problem?**
The only problem is that the liner view could be cleaner if you were able to mark pad bytes between aligned values.  The linear view could then collapse those bytes from the view to improve readability.

**Are any alternative solutions acceptable?**
Please provide a clear and concise description of any alternative solutions or features you've considered.

**Additional Information:**
Please add any other context or screenshots that would help us understand your feature request here.

Examples of areas of padding that could be collapsed from linear view

<img width="1066" alt="Screenshot 2023-01-19 at 3 35 34 PM" src="https://user-images.githubusercontent.com/125403/213585766-abcce55d-7528-4b18-a150-1daf0643cfbd.png">

<img width="1043" alt="Screenshot 2023-01-19 at 3 36 46 PM" src="https://user-images.githubusercontent.com/125403/213585831-d10509e6-7968-47c1-af2f-68918bd37802.png">

**Comment by rickmark** [comment] 2023-01-19 23:39
Additionally the string display could collapse the following into their string, plus N null terminators to show strings in a more useful form (fixed width strings with null pads on the right are common)

<img width="579" alt="Screenshot 2023-01-19 at 3 37 53 PM" src="https://user-images.githubusercontent.com/125403/213586058-45a00a16-ef3c-4585-b1b3-ff068ddf0d4d.png">

**Comment by plafosse** [comment] 2023-02-20 18:39
Yes I agree padding bytes would be great marking as a duplicate of #412

**Closed by plafosse** 2023-02-20 18:39 UTC
Labels: enhancement
