### ISSUE TITLE
"Create Function Here" has weird ARM vs Thumb behavior

### ISSUE THREAD

**Issue by percontation** [Vector35/binaryninja-api#1177] opened 2018-10-21 07:37 UTC
Setup:

1. I have a small raw binary, it's mostly thumb instructions
2. I mark some functions as thumb, so Binary Ninja now shows the default architecture as thumb.
3. There are additional chunks of data I would like to mark as thumb functions. 

Behavior:

In the Linear Disassembly view, pressing "P" to mark new functions (on data that hasn't been identified as code) creates non-thumb ARM functions. In the right-click context menu, the "Create Function Here      P" option does not have a submenu that would allow creating a thumb function.

In the Hex Editor view, things are different. The default "P" action does create thumb functions, and the right-click context menu has a submenu that would allow me to pick ARM, Thumb, or whatever else I wanted.

Issue:

The default behavior of the "P" hotkey in Linear Disassembly view isn't what I wanted here. I'm not sure if it's incorrectly using ARM when it should be using thumb, or some heuristics about when to switch between ARM/thumb are just off in this case. Either way, I should have the option to override the default.

Hex Editor view behaves as desired (but obviously, is not convenient to access).

**Comment by percontation** [comment] 2018-10-21 07:45
Quick illustration of the behavior difference, in case I described it poorly: https://gfycat.com/SpottedNegligibleBlacklemur

Also, noticed this comment: https://github.com/Vector35/binaryninja-api/issues/883#issuecomment-348392365 , but as described above this seems to only be true in Hex Editor view and not Linear Disassembly view.

**Comment by bpotchik** [comment] 2018-10-21 10:01
To create a Thumb function you can hit "P" on an odd address.

**Comment by psifertex** [comment] 2018-10-21 12:57
The P behavior is as designed. As Brian mentioned, the arch is determined based on the address in the case of arm/thumb since that's how the hardware works. But once a default is set, we don't ask again since it's generally the right user experience. 

The hex view not accounting for the odd/even doesn't surprise me since we don't have a binary view available there to use to check the address mapping (even if with a flat file the mapping is the same). 

The issue about the right click create function being missing in linear view though is not something I can reproduce and would be a problem. Do you have a screen cap of that?

**Comment by percontation** [comment] 2018-10-22 19:55
Ah. Odd address is very easy to remember :)

The issue about right-click create wasn't that it was missing; just that it was different from Hex View and does not give a submenu to select architectures (which made me think I had no way to create a thumb function from linear view, which was my main issue).

Linear view, no submenu to select arch:

<img width="762" alt="Linear view, no submenu to select arch" src="https://user-images.githubusercontent.com/563506/47315388-4ff79a00-d5f9-11e8-9282-2fec82e5c0df.png">

Hex view has the submenu:

<img width="1323" alt="Hex view has the submenu" src="https://user-images.githubusercontent.com/563506/47315378-479f5f00-d5f9-11e8-89f3-0e2ca846b65c.png">

**Comment by percontation** [comment] 2018-10-22 19:58
(I retract my suggestion that the linear view _needs_ that arch-choosing submenu, now that I know how to make a thumb function there. Maybe it'd be good for consistency, though? idk.)

**Comment by psifertex** [comment] 2023-06-07 18:41
We are re-opening this as we believe the current behavior is indeed a bug and we wish to fix it. Here's what we believe should be done:

- Hitting "p" should _always_ create a function of the default platform.
- We also believe that the associated platforms (arm/thumb in this case) should be sorted in the "Make Function at this Address" up top

**Comment by joelreymont** [comment] 2023-06-08 05:01
In my experience with #4244 I was able to create the right Thumb code even not positioning myself on the +1 address. So long as I used the Thumb2 item which was present for me in the create function context menu.

**Comment by psifertex** [comment] 2023-06-08 13:14
Did pressing `p` also work for you though? That's the behavior we believe was broken.

**Comment by joelreymont** [comment] 2023-06-08 16:46
No, it doesn't work, even though the label says _P (thumb2)_, or something like that. What works is drilling down the context menu and selecting thumb2 from there.

**Comment by lwerdna** [comment] 2023-08-24 04:54
The final solution isn't fully decided, but one decision we're leaning towards is 'P' always creating a function with the binaryview's default architecture. That's only useful if the user can easily set the default architecture, so branch `set-default-arch-menu` has this menu option. Once the setting sticks after saves/loads of bndbs, it will be merged in.

**Comment by gsingh93** [comment] 2024-03-13 17:36
I just got bit by this issue. I'm fine with whatever behavior gets chosen, but in any case the `Default (<arch>)` message should show the architecture it's actually going to make instructions with. With the current behavior, that would mean showing something like "Default (armv7)" when right clicking on even addresses and "Default (thumb2)" when clicking on odd addresses. Currently, it always shows "Default (thumb2)" for me, which leads to a lot of confusion when I don't get thumb2 instructions.

If this issue is close to being fixed, where the behavior will not change based on the odd and even addresses, then the UI issue gets "fixed" automatically. But if this issue will take some more time, then at least addressing the UI issue would make things less confusing.

**Closed** 2024-07-24 17:13 UTC
Labels: Type: Bug, Component: UI, Impact: Medium, Effort: Trivial, UI: Linear, UI: Graph
