### ISSUE TITLE
Add Cross References for Lookup Tables

### ISSUE THREAD

**Issue by gkprow** [Vector35/binaryninja-api#1856] opened 2020-07-29 21:45 UTC
The jump table seems suspect because:
1) It has no xrefs
2) It's a array of uint8_t elements not 32-bit addresses
3) It exists in the middle or .rodata and is surrounded by a bunch of seemingly random bytes that look similar

I've only seen this issue on PPC. I have not attempted to look for it in other architectures.

![before-jump-table](https://user-images.githubusercontent.com/10360156/88856841-d374f080-d1ba-11ea-9b1c-3f40694b6c2c.png)

![top-of-jump-table](https://user-images.githubusercontent.com/10360156/88856728-9ad51700-d1ba-11ea-9519-399f301a79ca.png)

![after-jump-table](https://user-images.githubusercontent.com/10360156/88856863-dc65c200-d1ba-11ea-829c-0f7ff3d8f35d.png)

**Comment by plafosse** [comment] 2020-08-06 15:35
Did you happen to create and then remove a function? We do have a know issue where data variables aren't reference counted, and thus if a function is created and then removed, any data variables that are created by the function aren't automatically removed. This a potential duplicate of... a ticket that I can't find right now.

**Comment by gkprow** [comment] 2020-08-06 15:47
No, I have not modified the binary or its analysis in any way. I opened up Binary Ninja GUI, opened the binary then let the analysis complete, moved the UI to address 0x100d9507 and observed that the jump table is present and without xrefs.

I reproduced the same issue this morning using:
Version 2.1.2321-dev (Build ID f57c0c7d)

**Comment by bpotchik** [comment] 2020-08-09 01:34
As of build 2.1.324-dev the data variable is automatically named `lookup_table_100d9507` The table is actually used in the dispatch at location 0x10024e64. Normally there would be a cross reference automatically created at the load address for this table, however the base of this table is obscured by multiple operations which does not leave a constant base for us to generate a cross reference from. I'm tempted to close this as won't fix as I don't see us resolving this anytime soon.

**Comment by gkprow** [comment] 2020-10-21 18:33
Thank you for the information. It has been a little while since this issue's status has been updated. Have you all decided the fate of this issue, either addressing the issue or closing as won't fix?

**Comment by bpotchik** [comment] 2020-12-12 15:58
I think we should leave it open for now. I would like to add xrefs for these lookup tables at some point.

**Comment by bpotchik** [comment] 2022-03-14 21:28
Fixed in `3.0.3295-dev`.

**Closed by bpotchik** 2022-03-14 21:28 UTC
Labels: bug, Impact: Low, Effort: Medium
