### ISSUE TITLE
MIPS indirect jumps not resolved as functions

### ISSUE THREAD

**Issue by aschmitz** [Vector35/binaryninja-api#260] opened 2016-05-29 21:35 UTC
It appears common in MIPS to load a `$gp` value at the start of a function (functions are called via `jalr $t9`, then `$gp` is set as an offset from `$t9`, which allows position-independent binaries), and then call functions as an offset from `$gp`.

For example, one such call is here:
![sample jalr](https://cloud.githubusercontent.com/assets/29508/15636141/2bab9e62-25bb-11e6-9a42-100dd6677562.png)

It would be handy if binja could resolve these as references to functions: it has already resolved the functions themselves (they appear in the sidebar), but it seems difficult to actually get it to note the link in the call site.

**Comment by gynophage** [comment] 2016-06-03 03:33
Duplicate of #264?

**Comment by aschmitz** [comment] 2016-06-03 03:39
Most likely, yes. (If I'm reading #264 correctly.) I'm not sure how binja
would best handle this, as it appears to be simply calling convention which
may vary between compilers, but it seems plausible that following the data
flow would allow you to resolve the actual address that was called,
resolving the issue without special cases.
On Jun 2, 2016 10:34 PM, "gynophage" <notifications@github.com> wrote:

Duplicate of #264 <https://github.com/Vector35/binaryninja-api/issues/264>?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Vector35/binaryninja-api/issues/260#issuecomment-223482949>,
or mute the thread
<https://github.com/notifications/unsubscribe/AABzRD3Fl4Q4ZyNciaIW4HWMgUFvdXedks5qH6CogaJpZM4IpYrt>
.

**Comment by D0ntPanic** [comment] 2017-08-15 23:25
T9 is now supported in dev build 864, but some usage of the GP register is not handled. Also, the MIPS-specific ELF headers used for imports are not handled.

**Comment by D0ntPanic** [comment] 2017-08-24 04:17
Calls through global pointers are now supported in all architectures by defining the global pointer register in the calling convention. This has been put into place for both x86 PIC and MIPS code, which now both resolve function calls through their respective global pointer. Fixed in dev build 876.

**Closed by D0ntPanic** 2017-08-24 04:17 UTC
Labels: enhancement
