### ISSUE TITLE
Add support for parenthesis matching in Pseudo C view.

### ISSUE THREAD

**Issue by st1064870** [Vector35/binaryninja-api#3124] opened 2022-05-13 18:40 UTC
**What is the feature you'd like to have?**
Add support for parenthesis matching in Pseudo C view. First of all the parenthesis will need to become selectable and when it is selected the matching parenthesis is highlighted. This is implemented in every famous editor. I'm not asking Pseudo C to become a text editor, just to add some small improvements for better readability with complex C expressions.

P.S. Curly braces "{" matching can also be implemented as well but I think it is not so useful as parenthesis matching.

**Comment by galenbwill** [comment] 2022-05-13 19:58
Duplicate of #1730

**Closed by galenbwill** 2022-05-13 19:58 UTC
Labels: enhancement
