### ISSUE TITLE
Changing pane type when multiple pane open corrupts pane views

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3588] opened 2022-10-21 14:36 UTC
* Binary Ninja Version: 3.2.3782-dev
* OS: Windows 10 x64

See the GIF please. I found that this reproduces with Triage, Strings etc.

![Recording 2022-10-21 at 16 27 43](https://user-images.githubusercontent.com/109607896/197221161-318ba202-be6e-4fc6-8bc8-510b62767a70.gif)

**Comment by bpotchik** [comment] 2022-10-21 16:03
Possible duplicate of #3588. Leaving open to track.

**Comment by bpotchik** [comment] 2022-11-01 18:05
Fixed in `3.2.3819-dev`.

**Closed by bpotchik** 2022-11-01 18:05 UTC
Labels: bug, Effort: Low, Impact: Medium
