### ISSUE TITLE
Setting integer display types at all levels is very inconsistant, and often mappings do not work, or it fails to set the type for the current IL level.

### ISSUE THREAD

**Issue by cxnder** [Vector35/binaryninja-api#3726] opened 2022-12-09 16:06 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3875

**Steps To Reproduce:**
Open the attached bndb. 

**Failed mapping between disassembly and ILs**
Navigate to 0x8
Swap to HLIL
Set the type for 0x2a1 to display as Signed Decimal.
Swap to disassembly. It will display as hex again. You can also set it in disassembly however it will not map to the ILs.

**Failure to render the display type properly in the context menu**
Navigate to 0xa0 in disassembly
Set the display type for 0xFFFF to any of the signed ones, and note that it renders entirely differently in the right-click dialog (-1) vs in disassembly (0x65535). The latter is correct as the register is 32 bits wide. 

**Failure to set the display type** 
Swap to HLIL view. 
Set the display type for the same 0xFFFF to Unsigned Octal
Setting the display type in any of the IL levels for this constant is entirely inconsistent and may only work in disasm/HLIL, or other arbitrary ones. 

[Stage2.bndb.zip](https://github.com/Vector35/binaryninja-api/files/10196145/Stage2.bndb.zip)

**Comment by xusheng6** [comment] 2022-12-22 03:16
Duplicate of #3490

**Closed by xusheng6** 2022-12-22 03:16 UTC
