### ISSUE TITLE
Inferior IL for array access that involves zero-sized array

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/binaryninja-api#6084] opened 2024-11-05 01:35 UTC
# Repro

Download the binary: [libjpak.dylib.txt](https://github.com/user-attachments/files/17625710/libjpak.dylib.txt)

Define the following types:

```c
typedef struct {
    uint32_t offset;
    int32_t size;
    int8_t name[24];
} JpakItem;

typedef struct {
    uint32_t magic;
    uint32_t version;
    int32_t num_items;
    uint32_t reserved;

    JpakItem _items_internal[0];
} Jpak;
```

Then apply the following signature to `jpak_index`:

```c
int32_t jpak_index(Jpak const *jpak, char const *name);
```

# Problem

The resulting Pseudo-C in Binary Ninja on 4.2.6337-dev is:

```
int32_t jpak_index(Jpak* jpak, char const* name)
{
    int32_t i = 0;
    
    while (true) {
        if (i >= jpak->num_items)
            return 0xffffffff;
        
        if (!_strncmp(&jpak[1 + (int64_t)i * 2].num_items, name, 0x18))
            break;
        
        i += 1;
    }
    
    return i;
}
```

This does not clearly represent the index into the zero-length array at the end of the structure.

However, IDA renders this more clearly:

```c
int32_t jpak_index(const Jpak *jpak, const char *name)
{
    int32_t i; // [xsp+14h] [xbp-1Ch]

    for ( i = 0; i < jpak->num_items; ++i )
    {
        if ( !strncmp(jpak->_items_internal[i].name, name, 0x18uLL) )
            return i;
    }

    return -1;
}
```

It would be nice if Binja could do this too.

**Comment by xusheng6** [comment] 2024-11-05 09:20
I feel like the real issue is we are unable to simplify the several additions correctly since the +0x8 (which accounts for the offset of the `name` field in `_JpakItem`. It might work if that is added first (before `18 @ 00003e84  x8_5 = x8_4 + (x9_3 << 5)`):

![Screenshot 2024-11-05 at 5 17 59 PM](https://github.com/user-attachments/assets/4d70a333-cacb-4a0a-9ef2-75027f000a98)

However, regardless of whether my guess is correct, there is an issue and we need to look into it. We will need to have someone else look at it

**Comment by plafosse** [comment] 2024-11-05 14:41
Thanks for the report. Marking this as a duplicate of https://github.com/Vector35/binaryninja-api/issues/3530

**Closed as completed by plafosse** 2024-11-05 14:41 UTC
Labels: State: Duplicate
