### ISSUE TITLE
Some PDB symbols have short_name and raw_name swapped

### ISSUE THREAD

**Issue by 0x1F9F1** [Vector35/binaryninja-api#1663] opened 2020-05-13 21:19 UTC
Binary Ninja Version: 2.0.2145-dev, 1e232a6e
Platform: Windows 10 Version 1903

Some PDB symbols have short_name/full_name and raw_name the wrong way round.
```
>>> sym
<SymbolType.DataSymbol: "??_7format_error@v6@fmt@@6B@" @ 0x14001e410>
>>> sym.name
"fmt::v6::format_error::`vftable'"
>>> sym.short_name
'??_7format_error@v6@fmt@@6B@'
>>> sym.full_name
'??_7format_error@v6@fmt@@6B@'
>>> sym.raw_name
"fmt::v6::format_error::`vftable'"
```

**Comment by psifertex** [comment] 2020-06-19 18:02
Do you happen to have a sample PDB you can share that exhibits this?

**Comment by fuzyll** [comment] 2022-03-24 16:57
Closing this issue because we aren't able to reproduce it. If anyone has a test case we can use for this, please feel free to re-open and provide the file and we'll get it fixed.

**Closed by fuzyll** 2022-03-24 16:57 UTC
Labels: bug, PDB, good first issue, Impact: Low, Effort: Medium
