### ISSUE TITLE
iPython cannot start kernel

### ISSUE THREAD

**Issue by Manouchehri** [Vector35/binaryninja-api#393] opened 2016-08-20 05:13 UTC
Seems to be related to how the python shell is set up (#32).

```python
>>> import IPython
>>> IPython.embed_kernel()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\python27-64\lib\site-packages\IPython\__init__.py", line 83, in embed_kernel
    (caller_module, caller_locals) = extract_module_locals(1)
  File "C:\python27-64\lib\site-packages\IPython\utils\frame.py", line 96, in extract_module_locals
    module = sys.modules[global_ns['__name__']]
KeyError: '__console__'
>>> IPython.embed()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\python27-64\lib\site-packages\IPython\terminal\embed.py", line 315, in embed
    shell = InteractiveShellEmbed.instance(_call_location_id='%s:%s' % (frame.f_code.co_filename, frame.f_lineno), **kwargs)
  File "C:\python27-64\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\python27-64\lib\site-packages\IPython\terminal\embed.py", line 100, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "C:\python27-64\lib\site-packages\IPython\terminal\interactiveshell.py", line 396, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "C:\python27-64\lib\site-packages\IPython\core\interactiveshell.py", line 499, in __init__
    self.init_io()
  File "C:\python27-64\lib\site-packages\IPython\terminal\interactiveshell.py", line 363, in init_io
    self.enable_win_unicode_console()
  File "C:\python27-64\lib\site-packages\IPython\terminal\interactiveshell.py", line 357, in enable_win_unicode_console
    stderr=stderr_text_str)
  File "C:\python27-64\lib\site-packages\win_unicode_console\__init__.py", line 31, in enable
    readline_hook.enable(use_pyreadline=use_pyreadline)
  File "C:\python27-64\lib\site-packages\win_unicode_console\readline_hook.py", line 134, in enable
    check_encodings()
  File "C:\python27-64\lib\site-packages\win_unicode_console\readline_hook.py", line 50, in check_encodings
    if sys.stdin.encoding != sys.stdout.encoding:
AttributeError: '_PythonScriptingInstanceInput' object has no attribute 'encoding'

```

Would be nice to have this fixed so iPython's Qt console can be used instead.

**Comment by psifertex** [comment] 2016-08-20 12:45
Dupe of #392

**Closed by psifertex** 2016-08-20 12:45 UTC

**Comment by Manouchehri** [comment] 2016-08-20 12:57
I'm blind. Thanks.
