### ISSUE TITLE
Data Flow Quirks Cause False Parameters

### ISSUE THREAD

**Issue by resrever** [Vector35/binaryninja-api#893] opened 2017-12-20 03:05 UTC
This is likely several issues together.  I first noticed a call to sub_7220 returning into register rdx_1#1 (x86_64 in MLIL SSA form), but sub_7220 never touches the edx/rdx register.  It thinks this register is used as a parameter to sub_2b40.

![not_a_return_value](https://user-images.githubusercontent.com/29237040/34188755-f546d600-e505-11e7-9de8-3fb1690830cb.png)

Diving in to sub_2b40, it appears something happened with instruction 24 mulu.dp.d writing output to mixed registers, then instruction 25 thinking it takes arg3 (edx/rdx) and zeroes the high 32 bits.  But since it read the low part of the 64-bit register, it thinks it read the 64 bit register, thus creating a false argument arg3.

![false_arg](https://user-images.githubusercontent.com/29237040/34188753-f4ffb36a-e505-11e7-8b3a-978d273210d8.png)

Some thoughts:
1. Does the two-32-bit-register multiply output implicitly zero the high 32 bits of those registers?
2. 32-bit moves should probably not implicitly reference the contents of the high 32 bits in a way that forces a data dependency on those high 32 bits.
3. MLIL lifting might be better if it tracked information about called functions.  For example, a program that did actually use edx in a later call should probably walk back the dependency to a function that actually assigns edx, and skip sub_7220 in this example.

**Comment by rssor** [comment] 2018-03-08 21:49
The root cause here looks to be an SSA translation issue related to LLIL_SET_REG_SPLIT, which was fixed in build 1085.

When converting lifted IL to low level IL, partial registers used as the destination are replaced with temporary registers. After LLIL_SET_REG_SPLIT, the results are moved into the partial register.

**Closed by rssor** 2018-03-08 21:49 UTC
