### ISSUE TITLE
Cannot select monospaced font

### ISSUE THREAD

**Issue by cblichmann** [Vector35/binaryninja-api#1586] opened 2020-04-20 10:16 UTC
Binary Ninja Version: 2.0.2097-dev, 451aae39
Platform: Debian GNU/Linux bullseye/sid

Hey there,

See the title, I'm trying to set the "[Fira Code](https://github.com/tonsky/FiraCode)" font, which is a monospaced font that works well in my terminal and basically anywhere else (see screenshot).

Still, it does not appear in the list of fonts.

Same issue on 1.3.2015.

![Screenshot from 2020-04-20 12-10-05](https://user-images.githubusercontent.com/213059/79740635-4d662580-8300-11ea-895f-1bd9cd476cbf.png)

**Comment by psifertex** [comment] 2020-04-22 02:40
Hmm, yeah, I suspect this is a QT bug as I can reproduce this on Linux but not MacOS or Windows and our font handling isn't really OS-specific. 

Here's a minimal test case while we're investigating it: 

```
from PySide2.QtGui import QFont
from PySide2.QtWidgets import QFontDialog
(ok, font) = QFontDialog.getFont(QFont("Helvetica [Cronyx]", 10), None, options=QFontDialog.DontUseNativeDialog | QFontDialog.MonospacedFonts)
```

Apparently on Linux, either QT or whatever they're using natively doesn't match MonospacedFonts properly.

**Comment by psifertex** [comment] 2020-04-22 02:42
Also, from a quick test, I /think/ if you just select any non-default font, then edit your `~/.binaryninja/settings.json` to have `"Fira Code"` instead, it looks like it works.

**Comment by psifertex** [comment] 2020-04-22 03:02
Depends on https://bugreports.qt.io/browse/QTBUG-83699

**Comment by cblichmann** [comment] 2020-04-26 20:18
Thanks, the workaround, well worked :)

**Comment by psifertex** [comment] 2021-05-06 15:51
We have a reasonable work-around and unfortunately the bug is pretty far outside our control, so closing this for now.

**Closed by psifertex** 2021-05-06 15:51 UTC
Labels: Effort: Low, Impact: Low, ui

**Comment by jonpalmisc** [comment] 2021-05-06 15:57
@cblichmann I think this actually might be specific to the Fira Code font itself. I'm able to select other monospace fonts in the dialog, and more importantly, I'm able to select the Fira Mono font, which is the font Fira Code is based off of.

I'm no OpenType expert, but I think something about there might be an error in Fira Code's build process causing certain flags to be set/unset, resulting in the font not being recognized as a mono font.

If you aren't using Fira Code's ligatures, then Fira Mono will look exactly the same IIRC, and you should be able to select that in the font chooser dialog.
