### ISSUE TITLE
Strange HLIL with a messed up stack and use of undefined variables

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#5413] opened 2024-05-14 12:48 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5272-dev, 3a057a87
- OS: macos
- OS Version: 14.4
- CPU Architecture: arm64

Internal binary `major dine favor`.

IDA Pro

```
MD5_CTX *__fastcall DjiMd5_Transform(MD5_CTX *ctx_1, MD5_CTX *ctx_2)
{
  unsigned __int64 v2; // t2
  int data[20]; // [xsp+18h] [xbp-58h]
  int j; // [xsp+68h] [xbp-8h]
  unsigned int i; // [xsp+6Ch] [xbp-4h]

  i = 0;
  j = 0;
  while ( i <= 0xF )
  {
    data[i++] = ctx_2->data[j] + (ctx_2->data[j + 1] << 8) + (ctx_2->data[j + 2] << 16) + (ctx_2->data[j + 3] << 24);
    j += 4;
  }
  data[19] = ctx_1->state[0];
  data[18] = ctx_1->state[1];
  data[17] = ctx_1->state[2];
  data[16] = ctx_1->state[3];
```

But what is `arg_0` in the HLIL below and why does it want to refer to `__elf_program_headers` all of a sudden?

Also, where's the assignment to `data[16]` and how do I create `uint32_t data[20]` on the stack here? 

I can rename `arg_0` to `data` and type it as `int[20]` but that doesn't change the assignments to `x0_34`, etc. at the end and doesn't add the missing one. 

```
0008575c  struct MD5_CTX* DjiMd5_Transform(struct MD5_CTX* ctx_1, struct MD5_CTX* ctx_2)

00085768      int32_t i = 0
0008576c      int32_t j = 0
00085824      while (i u<= 0xf)
000857e4          uint32_t x0_21 = zx.d(ctx_2->data[zx.q(j)]) + (zx.d(ctx_2->data[zx.q(j + 1)]) << 8) + (zx.d(ctx_2->data[zx.q(j + 2)]) << 0x10) + (zx.d(ctx_2->data[zx.q(j + 3)]) << 0x18)
00085800          *(&arg_0 + (zx.q(i) << 2) - &__elf_program_headers[0].physical_address) = x0_21
0008580c          i += 1
00085818          j += 4
00085838      unsigned int x0_34 = ctx_1->state[1]
00085844      unsigned int x0_36 = ctx_1->state[2]
00085850      unsigned int x0_38 = ctx_1->state[3]
000858a4      int32_t var_58
000858a4      int32_t x0_48 = ror.d(((x0_34 & x0_36) | (not.d(x0_34) & x0_38)) + var_58 + ctx_1->state[0] - 0x28955b88, 0x19) + x0_34
```

**Comment by joelreymont** [comment] 2024-05-14 12:57
The stack according to IDA Pro

```
.text:000000000008575C var_70          = -0x70
.text:000000000008575C var_68          = -0x68
.text:000000000008575C data            = -0x58
.text:000000000008575C j               = -8
.text:000000000008575C i               = -4
.text:000000000008575C arg_0           =  0
```

**Comment by emesare** [comment] 2024-05-14 13:53
> Also, where's the assignment to data[16] and how do I create uint32_t data[20] on the stack here?

Right now this has to be done manually (see https://github.com/Vector35/binaryninja-api/issues/2570). To do so you really should utilize the stack view, it makes validation easier. First you want to go to the stack view, identify the place you want to create it, in your case it is `-0x58` (or var_58) and retype it as an array, you will get the following output:

```
00085830      int32_t var_58[0x14]
00085830      var_58[0x13] = *(arg1 + 0x50)
0008583c      var_58[0x12] = *(arg1 + 0x54)
00085848      var_58[0x11] = *(arg1 + 0x58)
00085854      var_58[0x10] = *(arg1 + 0x5c)
00085894      var_58[0x13] = ((var_58[0x12] & var_58[0x11]) | (not.d(var_58[0x12]) & var_58[0x10])) + var_58[0] + var_58[0x13] - 0x28955b88
```

**Comment by joelreymont** [comment] 2024-05-14 14:14
I don't have a stack view for some reason so I assumed that BN didn't have this functionality. 

Will go figure out how to enable it...

<img width="729" alt="Screenshot 2024-05-14 at 5 13 30 PM" src="https://github.com/Vector35/binaryninja-api/assets/18791/e605bb68-31da-4b0b-99af-b040bbc6ca35">

**Comment by emesare** [comment] 2024-05-14 14:21
> I don't have a stack view for some reason so I assumed that BN didn't have this functionality.

https://docs.binary.ninja/guide/index.html#stack

**Comment by joelreymont** [comment] 2024-05-14 14:53
It's doing the right thing now, thanks! 

How do I get rid of `- &__elf_program_headers[0].physical_address)` in the assignment?

Also, note that `data` is defined _after_ the loop that uses it. I think it ought to be before, just like `i` and `j`.

```
0008575c  struct MD5_CTX* DjiMd5_Transform(struct MD5_CTX* ctx_1, struct MD5_CTX* ctx_2)
00085768      int32_t i = 0
0008576c      int32_t j = 0
00085824      while (i u<= 0xf)
000857e4          uint32_t x0_21 = zx.d(ctx_2->data[zx.q(j)]) + (zx.d(ctx_2->data[zx.q(j + 1)]) << 8) + (zx.d(ctx_2->data[zx.q(j + 2)]) << 0x10) + (zx.d(ctx_2->data[zx.q(j + 3)]) << 0x18)
00085800          *(&data[zx.q(i)] - &__elf_program_headers[0].physical_address) = x0_21
0008580c          i += 1
00085818          j += 4
00085830      int32_t data[0x14]
```

**Comment by plafosse** [comment] 2024-05-14 14:59
either mark it as not a pointer or rebase your binary.

**Comment by joelreymont** [comment] 2024-05-14 15:06
I may be missing something but ... 

This is a proper ELF binary so I do have ELF

```
00000040  struct Elf64_ProgramHeader __elf_program_headers[0x9] = 
00000040  {
00000040      [0x0] = 
00000040      {
00000040          enum p_type type = PT_PHDR
00000044          enum p_flags flags = PF_R
00000048          uint64_t offset = 0x40
00000050          uint64_t virtual_address = 0x40
00000058          uint64_t physical_address = 0x40
00000060          uint64_t file_size = 0x1f8
00000068          uint64_t memory_size = 0x1f8
00000070          uint64_t align = 0x8
00000078      }
```

`data` is just an array of ints so no pointers. 

`&__elf_program_headers[0].physical_address` resolves to `0x58`. 

IDA shows 

```
    data[i++] = ctx_2->data[j] + (ctx_2->data[j + 1] << 8) + (ctx_2->data[j + 2] << 16) + (ctx_2->data[j + 3] << 24);
```

but BN shows 

```
*(&data[zx.q(i)] - 0x58) =  ...
```

What am I missing?

**Comment by plafosse** [comment] 2024-05-21 14:45
This is a duplicate of this:  https://github.com/Vector35/binaryninja-api/issues/5406 
If we fix 5406 we'd not have this issue.

**Closed by plafosse** 2024-05-21 14:45 UTC
