### ISSUE TITLE
Ctrl+c from the Python console does not always behave as expected

### ISSUE THREAD

**Issue by Manouchehri** [Vector35/binaryninja-api#389] opened 2016-08-19 19:13 UTC
When there's a `current_address` and output text is selected from the Python console, ctrl+c _always_ copies from the graph.

I think the expected behavior would be to copy whichever was selected last?
#373 is a related issue.

(Let me know if you need a video, it's hard to explain in words.)

**Comment by snare** [comment] 2016-08-31 05:45
Reproducing is easy and will make it make more sense if this is not understood.

1. Click any instruction in the assembly view so it's selected
2. Open the Python console and select some text in it
3. Hit Ctrl-C/Cmd-C
4. Hit Ctrl-V/Cmd-V

The data in the paste buffer will be the selected instruction, not the data selected in the Python console.

**Comment by snare** [comment] 2016-08-31 05:48
Note: you can successfully copy what's in the console by selecting text, right clicking and selecting "copy"

**Comment by Manouchehri** [comment] 2016-08-31 16:44
Thanks snare. I also made a video that should help make it clear.

https://www.youtube.com/watch?v=8Fls6F7Kl1w

**Comment by plafosse** [comment] 2017-05-06 18:56
dupe of #324

**Closed by plafosse** 2017-05-06 18:56 UTC
