### ISSUE TITLE
ARM64: unable to assemble bl instruction

### ISSUE THREAD

**Issue by 1337-42** [Vector35/binaryninja-api#6042] opened 2024-10-25 08:55 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6298-dev, 3fb67302
- OS: macos
- OS Version: 14.7
- CPU Architecture: arm64

**Bug Description:**
Binary Ninja is unable to reassemble its assembly output.

**Steps To Reproduce:**

- Disassemble an ARM64-mac binary
- Find a branch instruction
- Run this Python snippet

```
>>> bv.get_disassembly(current_address, bv.arch)
'bl      0x1000700a0'
>>> disasm = bv.get_disassembly(current_address, bv.arch)
>>> print(disasm)
bl      0x1000700a0
>>> bv.arch.assemble(disasm, current_address)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/architecture.py", line 2510, in assemble
    raise ValueError(f"Could not assemble: {error_str}")
ValueError: Could not assemble: b'line 37: expected label or encodable integer pc offset\n'
```

**Expected Behavior:**
The output should be the assembled bytes.

**Screenshots:**

<img width="2196" alt="image" src="https://github.com/user-attachments/assets/1054f758-41c6-4612-b592-38ed127585d8">

**Additional Information:**
Other instructions seem to assemble just fine. It's only when offsets are used in, for example, branch instructions.

**Comment by xusheng6** [comment] 2024-10-29 07:19
I am pretty sure this a known issue and we have a duplicate issue for it. Just cannot find it at the moment. Is it https://github.com/Vector35/binaryninja-api/issues/71?

**Comment by 1337-42** [comment] 2024-10-29 14:41
Not sure what has changed since 2015. It could be related to that issue.

**Comment by plafosse** [comment] 2024-10-29 14:46
Closing this as a duplicate of #71  Back in 2015 this was very difficult because llvm didn't support the nasm-style .org directive. Modern llvm probably supports this now and we might be able to do this without much difficulty.

**Comment by plafosse** [comment] 2024-10-29 14:47
A work around is that you need to subtract your current offset from the offset provided to the assembler

**Closed as completed** 2024-10-29 14:47 UTC
Labels: State: Duplicate
