### ISSUE TITLE
Exception handler gets eliminated

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#4716] opened 2023-10-27 19:56 UTC
Created this issue from [this discussion](https://github.com/Vector35/binaryninja-api/discussions/4693).

See code below. When we decompile this, we actually lose the entire `catch` branch somehow and don't decompile it. Part of the problem is that we mark the `mightThrow()` function as `noreturn`, but even if you mark the function as able to return, it still skips over the exception handler. I haven't looked closely enough to figure out why.

The compiled executable I made is attached:

[exception_test.zip](https://github.com/Vector35/binaryninja-api/files/13192811/exception_test.zip)

<div type='discussions-op-text'>

<sup>Originally posted by **oskarwirga** October 19, 2023</sup>
Exceptions are hard I know but analyzing the try catch in main this isn't quite supported in any decompiler that I've seen.
```
#include <iostream>
#include <stdexcept>

int mightThrow(){
    std::cout << "Throwing an exception...\n";
    throw std::runtime_error("This is a runtime error exception!");
}

int main(int argc, char** argv) {
    if (argc > 2){
        try {
            mightThrow();
        } catch (const std::exception& e) {
            std::cout << "Caught an exception: " << e.what() << "\n";
        }
    }
    return 0;
}
```
</div>

**Comment by plafosse** [comment] 2023-11-07 15:25
Closing as duplicate of #9

**Closed by plafosse** 2023-11-07 15:25 UTC
Labels: Type: Bug, State: Duplicate, Component: Core, Effort: Low, Impact: Medium
