### ISSUE TITLE
`QtWebEngineProcess` not executable

### ISSUE THREAD

**Issue by arty-hlr** [Vector35/binaryninja-api#2145] opened 2020-11-24 17:07 UTC
Hi,

I just bought binary ninja and opened it, but this wasn't possible due to `QtWebEngineProcess` not being executable out of the box as it says by launching `binaryninja`:
```
LaunchProcess: failed to execvp:
/home/florian/Documents/Hacking/binaryninja/QtWebEngineProcess
```

Obviously this is a quick fix, but it would be nice if that binary could be made executable so that it works out of the box!

**Comment by plafosse** [comment] 2020-11-24 17:29
We have discovered the caused of this and have a fix. The issue will be fixed in the next stable release. version 2.3.

**Closed by plafosse** 2020-11-24 17:29 UTC
Labels: bug, installation

**Comment by psifertex** [comment] 2020-11-24 18:46
It's also fixed if you use the "dev" download from https://binary.ninja/recover/ if you don't want to wait for 2.3
