### ISSUE TITLE
NULL-deref in `Platform.register_calling_convention`

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#670] opened 2017-04-27 00:38 UTC
Steps to reproduce:
1. Open any binary
2. At console, type `bv.platform.register_calling_convention(CallingConvention(bv.arch))`
3. crash

**Comment by plafosse** [comment] 2017-07-16 02:25
Duplicate of #539 Which was fixed in build 812

**Closed by plafosse** 2017-07-16 02:25 UTC
