### ISSUE TITLE
Crash when searching for Hex "c3" in notepad.exe on Windows

### ISSUE THREAD

**Issue by D0ntPanic** [Vector35/binaryninja-api#5104] opened 2024-02-23 19:05 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4903
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

**Bug Description:**
Opening `c:\windows\notepad.exe` and searching for Hex of `c3` in the find sidebar widget crashes.

**Comment by plafosse** [comment] 2024-02-23 19:42
Duplicate of #4854

**Closed by plafosse** 2024-02-23 19:42 UTC
Labels: Component: UI, Type: Crash, Impact: Critical
