### ISSUE TITLE
Freezing when closing a tab

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4180] opened 2023-03-31 21:58 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.4.4189-dev 
- OS: Windows 11, x64

**Bug Description:**
I've reproduced this in several files. I've attached two of them. I couldn't be able to reproduce it with nc.exe in virtual machine, but t8.exe still freeze even if in Windows VM. I've also tried those binaries in Mac, couldn't be able to reproduce freeze.

**Steps To Reproduce:**
1. Open one of attached binary in BN (Especially, t8.exe)
2. Wait for analysis finish
3. Try to close current tab
4. See the freeze

**Expected Behavior:**
I expect it to close tab without freezing.

**Additional Information:**
[hang_bins.zip](https://github.com/Vector35/binaryninja-api/files/11127186/hang_bins.zip)

**Comment by op2786** [comment] 2023-03-31 22:10
I guess it could be related to components. Because when I disable components it does not freezee.

**Comment by bpotchik** [comment] 2023-04-05 04:50
Pushed a possible fix in build `3.4.4194-dev`. Leaving open until we have broad confirmation that the issue is resolved.

**Comment by bpotchik** [comment] 2023-04-05 20:40
Fix is in build `3.4.4194-dev`. If issue persists please reopen.

**Closed by bpotchik** 2023-04-05 20:40 UTC
Labels: bug, ui, Impact: High, Effort: Low
