### ISSUE TITLE
Branch Instruction in Conditional Block (IT{TTT}) leads to incorrect Graph Dependencies

### ISSUE THREAD

**Issue by pr0me** [Vector35/binaryninja-api#3976] opened 2022-05-10 16:07 UTC
If a branch instruction is made conditional by a previous IT instruction, the disassembler still treats the branch as unconditional.
This leads to disconnected graphs/functions: 
![Selection_082](https://user-images.githubusercontent.com/5177161/167672242-fa8c6573-e762-4b7f-a7b1-56cdd92bbb1e.png)

Instead, the branch should be treated as conditional, connecting the following basic block as a fall-through edge.
This bug not only leads to disconnected basic block graphs but also to missed instructions:
![Selection_083](https://user-images.githubusercontent.com/5177161/167673233-0ee9091f-f39f-4552-851f-57c92f6dda32.png)

[Example binary (the behavior is observable in the `Reset_Handler`)](https://github.com/ucsb-seclab/hal-fuzz/blob/master/tests/nxp_lwip_http/nxp_lwip_http.elf)

**Comment by fuzyll** [comment] 2023-05-22 21:57
Closing this as a duplicate of #1720.

**Closed by fuzyll** 2023-05-22 21:57 UTC
Labels: State: Duplicate, Component: Architecture, Arch: ARM/Thumb
