### ISSUE TITLE
crash binja by putting folder as filename argument for parse_types_from_source_file

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#575] opened 2016-12-07 04:44 UTC
**OS:** Ubuntu 16.04 LTS

# reproduction
```
Architecture.parse_types_from_source_file(bv.arch, "/tmp")
```

**Comment by psifertex** [comment] 2016-12-08 02:51
I can't reproduce this -- might be from the other fix just put onto dev. Can you confirm?

**Comment by lucasduffey** [comment] 2016-12-09 05:47
not binja issue

**Comment by psifertex** [comment] 2016-12-09 23:19
Fixed in dev.

**Closed by psifertex** 2016-12-09 23:19 UTC

**Comment by psifertex** [comment] 2016-12-10 03:35
I lied four hours ago. ;-) My first fix broke windows so it never passed the CI. Current version building now should be deployed soon and includes the fix.
