### ISSUE TITLE
Undefined variables in HLIL

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4395] opened 2023-06-07 16:00 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4317-dev, a5d64740
- OS: macos
- OS Version: 13.4
- CPU Architecture: arm64

BN creates undefined variables and proceeds to assign them locations in memory, e.g. HLIL

```
00048640              int32_t var_48
00048640              data_20056298 = var_48
00048640              int32_t var_44
00048640              data_2005629c = var_44
00048644              int32_t var_40
00048644              data_200562a0 = var_40
00048644              int32_t var_3c
00048644              data_200562a4 = var_3c
00048644              int32_t var_38
00048644              data_200562a8 = var_38
00048644              int32_t var_34
00048644              data_200562ac = var_34
0004864a              int32_t var_30
0004864a              data_200562b0 = var_30
```

IDA does this right 

```
int sub_48574()
{
  int v0; // r7
  int *v1; // r5
  int v2; // r4
  int v3; // r0
  int v4; // t1
  char v6; // [sp+Eh] [bp-62h] BYREF
  char v7[97]; // [sp+Fh] [bp-61h] BYREF

  v6 = 0;
  link_monitor_4DAA0(&unk_2001D510);
  v0 = add_icc_handlers_48054(0, &v6);
  if ( !v0 )
  {
    unk_20055E60 = 0;
    sub_48558(&unk_20055E4C);
    unk_20055F2C = 1;
    sub_48558(&unk_20055F18);
    unk_20055FF8 = 2;
    sub_48558(&unk_20055FE4);
    unk_200560C4 = 3;
    sub_48558(&unk_200560B0);
    unk_20056190 = 4;
    sub_48558(&unk_2005617C);
    if ( v6 )
    {
      icc_secure_482AC(0);
      dword_20056248 = 1;
    }
    v7[0] = 0;
    v0 = add_icc_handlers_48054(1, v7);
    if ( !v0 )
    {
      unk_2005626C = 5;
      memset(&v7[1], 0, 0x40u);
      unk_20056278 = "ap3-mcu0-0.0";
      v7[1] = 1;
      *&v7[5] = 0;
      *&v7[9] = 0;
      unk_20056280 = *&v7[1];
      unk_20056284 = 0;
      unk_20056288 = 0;
      unk_2005628C = dword_5FFC0000;
      unk_20056290 = dword_5FFC0000;
      unk_20056294 = 0x8000;
      unk_20056298 = *&v7[25];
      unk_2005629C = *&v7[29];
      unk_200562A0 = *&v7[33];
      unk_200562A4 = *&v7[37];
      unk_200562A8 = *&v7[41];
      unk_200562AC = *&v7[45];
      unk_200562B0 = *&v7[49];
      unk_200562B4 = *&v7[53];
      unk_200562B8 = *&v7[57];
      unk_200562BC = *&v7[61];
      v7[1] = 0;
      unk_200562C4 = "mcu0-ap3-0.0";
      *&v7[13] = &unk_5FFC5D20;
      *&v7[17] = &unk_5FFC5D20;
      *&v7[21] = 9216;
      unk_200562CC = *&v7[1];
      unk_200562D0 = 0;
      unk_200562D4 = 0;
      unk_200562D8 = &unk_5FFC5D20;
      unk_200562DC = &unk_5FFC5D20;
      unk_200562E0 = 9216;
      unk_200562E4 = *&v7[25];
      unk_200562E8 = *&v7[29];
      unk_200562EC = *&v7[33];
      unk_200562F0 = *&v7[37];
      unk_200562F4 = *&v7[41];
      unk_200562F8 = *&v7[45];
      unk_200562FC = *&v7[49];
      unk_20056300 = *&v7[53];
      unk_20056304 = *&v7[57];
      unk_20056308 = *&v7[61];
      unk_200562C8 = 128;
      sub_48558(&unk_20056258);
      if ( v7[0] )
      {
        icc_secure_482AC(1);
        dword_20056248 = 1;
      }
      v1 = &dword_2001D4FC;
      v2 = 4;
      while ( 1 )
      {
        v4 = *v1++;
        v3 = v4;
        if ( v4 == -1 )
        {
LABEL_11:
          link_monitor_4DAA0(&unk_2001D4EC);
          return v0;
        }
        if ( sub_424F0(v3, &off_4818C + 1, 0) )
          return -14;
        sub_C842C(*(v1 - 1));
        if ( !--v2 )
          goto LABEL_11;
      }
    }
  }
  return v0;
}
```

BN shows something else entirely

```
00048574  int32_t sub_48574()

0004857e      char var_62 = 0
00048582      link_monitor_4daa0(&data_2001d510)
0004858c      int32_t r0 = add_icc_handlers_48054(0, &var_62)
00048590      int32_t r7 = r0
00048594      if (r0 == 0)
0004859c          data_20055e60 = r0
000485a0          sub_48558(&data_20055e4c)
000485a8          data_20055f2c = 1
000485ac          sub_48558(&data_20055f18)
000485b6          data_20055ff8 = 2
000485ba          sub_48558(&data_20055fe4)
000485c4          data_200560c4 = 3
000485c8          sub_48558(&data_200560b0)
000485d2          data_20056190 = 4
000485d6          sub_48558(&data_2005617c)
000485de          if (zx.d(var_62) != 0)
000485e2              icc_chnl_482ac(r7)
000485e8              data_20056248 = 1
000485f2          char var_61 = 0
000485f6          int32_t r0_2 = add_icc_handlers_48054(1, &var_61)
000485fa          r7 = r0_2
000485fe          if (r0_2 == 0)
0004860a              data_2005626c = 5
00048610              char var_60
00048610              memset(&var_60, r0_2, 0x40)
0004861c              data_20056278 = "ap3-mcu0-0.0"
00048628              var_60 = 1
0004863c              data_20056280 = var_60.d
0004863c              data_20056284 = r7
0004863c              data_20056288 = r7
0004863c              data_2005628c = 0x5ffc0000
00048640              data_20056290 = 0x5ffc0000
00048640              data_20056294 = 0x8000
00048640              int32_t var_48
00048640              data_20056298 = var_48
00048640              int32_t var_44
00048640              data_2005629c = var_44
00048644              int32_t var_40
00048644              data_200562a0 = var_40
00048644              int32_t var_3c
00048644              data_200562a4 = var_3c
00048644              int32_t var_38
00048644              data_200562a8 = var_38
00048644              int32_t var_34
00048644              data_200562ac = var_34
0004864a              int32_t var_30
0004864a              data_200562b0 = var_30
0004864a              int32_t var_2c
0004864a              data_200562b4 = var_2c
0004864a              int32_t var_28
0004864a              data_200562b8 = var_28
0004864a              int32_t var_24
0004864a              data_200562bc = var_24
00048654              var_60 = r7.b
00048658              data_200562c4 = "mcu0-ap3-0.0"
0004866a              data_200562cc = var_60.d
0004866a              data_200562d0 = r7
0004866a              data_200562d4 = r7
0004866a              data_200562d8 = 0x5ffc5d20
0004866e              data_200562dc = 0x5ffc5d20
0004866e              data_200562e0 = 0x2400
0004866e              data_200562e4 = var_48
0004866e              data_200562e8 = var_44
00048672              data_200562ec = var_40
00048672              data_200562f0 = var_3c
00048672              data_200562f4 = var_38
00048672              data_200562f8 = var_34
00048678              data_200562fc = var_30
00048678              data_20056300 = var_2c
00048678              data_20056304 = var_28
00048678              data_20056308 = var_24
00048680              data_200562c8 = 0x80
00048684              sub_48558(&data_20056258)
0004868c              if (zx.d(var_61) != 0)
00048690                  icc_chnl_482ac(1)
00048696                  data_20056248 = 1
0004869a              int32_t* r5_1 = &data_2001d4fc
0004869c              int32_t r4_1 = 4
000486a4              while (true)
000486a4                  int32_t r0_10 = *r5_1
000486a4                  r5_1 = &r5_1[1]
000486aa                  if (r0_10 != 0xffffffff)
000486b0                      int32_t var_70_1 = 0
000486b8                      if (sub_424f0(r0_10, 0x4818d, 0) != 0)
000486ce                          r7 = 0xfffffff2
000486ce                          break
000486be                      sub_c842c(*(r5_1 - 4))
000486c2                      int32_t temp1_1 = r4_1
000486c2                      r4_1 = r4_1 - 1
000486c4                      if (temp1_1 != 1)
000486c4                          continue
000486c8                  link_monitor_4daa0(0x2001d4ec)
000486cc                  break
000486d6      return r7
```

**Comment by plafosse** [comment] 2023-06-09 19:33
This is a duplicate of #1888

**Closed by plafosse** 2023-06-09 19:33 UTC
Labels: State: Duplicate
