### ISSUE TITLE
address labels

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-api#205] opened 2016-03-23 04:50 UTC
can't add "name" or "flag" to addresses (`n` in ida or `f` in r2)

**Comment by psifertex** [comment] 2016-03-25 18:01
Yup, this is a known missing feature for now. Thanks for filing it, thought we already had it listed somewhere. I'm going to edit the title since we'll refer to them as names and it will make it easier to find.

**Comment by psifertex** [comment] 2019-08-07 18:47
We've renamed #185 to describe our planned implementation that makes this a duplicate of that feature as we will see it implemented.

**Closed by psifertex** 2019-08-07 18:47 UTC
Labels: enhancement, ui
