### ISSUE TITLE
Disable Copying as big/little Endian when a token is selected 

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#5189] opened 2024-03-16 17:08 UTC
Version and Platform (required):

Binary Ninja Version: 4.1.4963-dev Personal (a066b74f)
OS: manjaro
OS Version: Linux version 6.6.19-1-MANJARO (builduser@fv-az1021-257) (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.42.0) https://github.com/Vector35/binaryninja-api/issues/1 SMP PREEMPT_DYNAMIC Fri Mar 1 18:16:16 UTC 2024
CPU Architecture: x64

**Bug Description:**
no difference between copying big Endian or Little Endian 

**Steps To Reproduce:**
just check the video:

https://github.com/Vector35/binaryninja-api/assets/5463104/4fede0ad-832c-4d38-b2fd-7038b951f103

**Expected Behavior:**
 big Endian is different from Little Endian

**Comment by xusheng6** [comment] 2024-03-19 14:25
I cannot reproduce it in a general sense. Is it possible to share the binary with us?

**Comment by plafosse** [comment] 2024-03-19 14:31
**Work around**: Select the line rather than the token on the line and that should work as expected.
Whats happening here is that you're copying the token instead of the bytes.  Our fix for this will be to disable copy as big/little endian when a token is selected rather than a byte range.

**Closed** 2024-03-20 05:27 UTC
Labels: Type: Bug, Component: UI, Impact: Low, Effort: Trivial

**Comment by xusheng6** [comment] 2024-03-20 05:28
I actually did not disable the "Copy As" action on an opcode token. And it should now work as expected with the above fix

**Comment by xusheng6** [comment] 2024-03-20 05:29
Fixed in dev 4.1.4972
