### ISSUE TITLE
libtriage error at every script run

### ISSUE THREAD

**Issue by melomac** [Vector35/binaryninja-api#1618] opened 2020-04-28 18:31 UTC
Everytime I am calling binaryninja from scripts, I get the following annoyance:

```
Plugin module '/Users/REDACTED/Applications/Binary Ninja.app/Contents/Resources/python/binaryninja/../../../MacOS/plugins/libtriage.dylib' failed to load
dlerror() reports: dlopen(/Users/REDACTED/Applications/Binary Ninja.app/Contents/Resources/python/binaryninja/../../../MacOS/plugins/libtriage.dylib, 5): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Users/REDACTED/Applications/Binary Ninja.app/Contents/MacOS/plugins/libtriage.dylib
  Reason: image not found
```

Indeed, `libtriage.dylib` is looking for Qt libraries at the wrong place and, while it breaks the code signature, the following command fix the problem until next update:

```
install_name_tool -add_rpath @loader_path/../../Frameworks "/Users/REDACTED/Applications/Binary Ninja.app/Contents/MacOS/plugins/libtriage.dylib"
```

**Comment by D0ntPanic** [comment] 2020-04-28 21:33
Duplicate of #1556

**Closed by D0ntPanic** 2020-04-28 21:33 UTC
Labels: duplicate
