### ISSUE TITLE
Improve for loops recovery

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4326] opened 2023-05-19 14:05 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4286-dev, 58311b01
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

Here's the pseudo-C generated by BN. 

See the double-cast at `0x3906c`.

Also, why is `i` multiplied by 2 and the whole thing cast to `int32_t` when everything is `int32_t` already?

```
00039030  int32_t pm_init_pbd_table(uint32_t len)

00039030  {
00039034      int32_t r0;
00039034      int32_t p;
00039034      if (len != 0)
00039034      {
0003903e          int32_t r2_1;
0003903e          p = kmem_zalloc((len << 2), 7);
00039044          PM_PBD_TAB = p;
00039046          if (p != 0)
00039046          {
00039070              int32_t i = 0;
0003906c              while (((uint32_t)((int8_t)i)) < len)
0003906a              {
00039062                  *(int32_t*)(p + (i << 2)) = 0;
00039066                  i = (i + 1);
00039066              }
00039066          }
00039050          else
00039050          {
00039050              log_30e20(6, "INFO:PM:init_pbd_table: kmem_zal…", r2_1, log_30e20);
00039054              void* log = PM_CFG_0.log;
00039056              if (log != 0)
00039056              {
0003905c                  log(4, "PM:init_pbd_table: kmem_zalloc f…");
00039058              }
0003905e              r0 = 2;
0003905e          }
0003905e      }
00039046      if ((len == 0 || (len != 0 && p != 0)))
00039046      {
00039036          r0 = 0;
00039036      }
00039038      return r0;
00039038  }
```

compare to IDA 

```
int __fastcall pm_init_pbd_table(unsigned int len)
{
  void *p; // r0
  int i; // r3

  if ( !len )
    return 0;
  p = kmem_zalloc(4 * len, 7);
  PM_PBD_TAB = p;
  if ( p )
  {
    for ( i = 0; i < len; ++i )
      *(p + i) = 0;
    return 0;
  }
  log_special(6, "INFO:PM:init_pbd_table: kmem_zalloc failed!\r\n");
  if ( PM_CFG.log )
    PM_CFG.log(4, "PM:init_pbd_table: kmem_zalloc failed!\r\n");
  return 2;
}
```

**Comment by fuzyll** [comment] 2023-05-19 18:07
One major difference in the example from your first message is that IDA types `p` as a pointer, while we have it typed as an integer. I'm not entirely sure why that is, but if you make a single type change, you wind up with much nicer output:

```
000039030  int32_t sub_39030(int32_t len)
000039030  {
000039034      int32_t r0;
000039034      int32_t* p;
000039034      if (len != 0)
000039034      {
00003903e          int32_t r2_1;
00003903e          p = sub_39020((len << 2), 7);
000039044          data_20053edc = p;
000039046          if (p != 0)
000039046          {
000039070              int32_t i = 0;
00003906c              while (((uint32_t)((int8_t)i)) < len)
00003906a              {
000039062                  p[i] = 0;
000039066                  i = (i + 1);
000039066              }
000039066          }
000039050          else
000039050          {
000039050              log_30e20(6, "INFO:PM:init_pbd_table: kmem_zal…", r2_1, log_30e20);
000039054              int32_t r3_1 = data_20053ed8;
000039056              if (r3_1 != 0)
000039056              {
00003905c                  r3_1(4, "PM:init_pbd_table: kmem_zalloc f…");
000039058              }
00003905e              r0 = 2;
00003905e          }
00003905e      }
000039046      if ((len == 0 || (len != 0 && p != 0)))
000039046      {
000039036          r0 = 0;
000039036      }
000039038      return r0;
000039038  }
```

The casts at 0x3906c are, I believe, being emitted because it's showing the explicit chain of type promotions. In my opinion, this is pretty useful because it shows:

1. The value of `i` can't ever be larger than 255 here
2. The value is being treated as an unsigned value, despite `i` being typed as signed

The underlying instruction here is a `uxtb`:

```
000039068  dab2       uxtb    r2, r3
00003906a  a242       cmp     r2, r4
00003906c  f9d3       bcc     #0x39062
```

...which extends a byte into a word with zeroes, so this should be the only correct interpretation. This looks a lot nicer in HLIL because we lift it as `while (zx.d(i.b) u< len)` using nomenclature that doesn't exist in C to disambiguate what's happening.

If you don't really care about the specifics of what's happening, you can make this look even simpler (after the change above to make it a pointer) by going to the hamburger menu in the top-right of the pane and turning off "Show Type Casts":

```
00003906c              while (i < len)
00003906a              {
000039062                  p[i] = 0;
000039066                  i = (i + 1);
000039066              }
```

It still shows as a `while` loop instead of a `for` loop, though.

I think the actionable parts of this issue are:

1. Why don't we recognize this as a `for` loop?
2. Why don't we recognize `r0` as being a pointer instead of an integer?

The type casts are a preference for explicit information that is a feature, rather than a bug, and has a supported workaround for users that have a preference otherwise.

Does all of the above make sense and do you agree? Or, is there some other nuance or viewpoint I've missed?

**Comment by joelreymont** [comment] 2023-05-22 06:25
I agree with the above, thank you!

**Comment by xusheng6** [comment] 2024-06-11 05:28
The loop-recovery part of this issue is a duplicate of https://github.com/Vector35/binaryninja-api/issues/5369. The other part of the issue is also discussed and resolved in it. Closing this

**Closed by xusheng6** 2024-06-11 05:28 UTC
Labels: Type: Enhancement, Component: Core, Core: HLIL, IL Optimization, Impact: High, Effort: High
