### ISSUE TITLE
Type libraries missing for Mach-O binaries

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#4926] opened 2024-01-22 10:05 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.6.4783-dev, 6fc13294
- OS: macos
- OS Version: 14.2
- CPU Architecture: arm64

**Steps To Reproduce:**
Load any mach-o binary to BN and look at the imports.

**Screenshots:**
<img width="621" src="https://github.com/Vector35/binaryninja-api/assets/109607896/9736543b-d4ab-4f27-bce3-068fd14cee41">

**Additional Information:**
Screenshot is from `ls`. 

Could be related to (or duplicate of) #3106.

**Comment by fuzyll** [comment] 2024-01-22 15:37
Closing this as a duplicate of #2735.

**Closed by fuzyll** 2024-01-22 15:37 UTC
Labels: State: Duplicate
