### ISSUE TITLE
Jump labels in assembly

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#4331] opened 2023-05-22 12:44 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4286-dev, 58311b01
- OS: macos
- OS Version: 13.3
- CPU Architecture: arm64

It would be much better to have the the jump to a label below 

```
ROM:000331DA                 B               loc_33208
...
ROM:00033208 loc_33208                               ; CODE XREF: sub_32A94+746↑j
ROM:00033208                 LDR             R0, [SP,#0x90+var_88]
```

than a regular jump to an address since the address is within the same function

```
000331da  15e0       b       #0x33208
...
00033208  0298       ldr     r0, [sp, #8] {var_88}
```

Anyone from V35 should search for "Encourage Salesman Prompt Delay" to find the database.

**Comment by negasora** [comment] 2023-05-22 13:55
Dupe of https://github.com/Vector35/binaryninja-api/issues/185

**Closed by negasora** 2023-05-22 13:55 UTC
