### ISSUE TITLE
Simplify compound conditionals involving `cmp`

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#3411] opened 2022-08-17 22:15 UTC
(Issue for @cookiemon)
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3618-dev

**Bug Description:**
Transcript from public slack ([from `@null_ptr`](https://binaryninja.slack.com/archives/C0CVALTLN/p1660390659549479))

> When I have a function like this in hlil, is there a way to have the conditional simplified by substituting `rbx` with `rbx_1`? The conditional comes out of a `sub` followed by a `cmp` and it seems binja uses the operand of the `sub` instead of the result.
![image](https://user-images.githubusercontent.com/12259536/185214246-43ad2adc-c469-4a9b-87c9-4dbc50500030.png)
> For reference the disassembly
![image](https://user-images.githubusercontent.com/12259536/185214310-21648fab-1c81-4c27-8c47-0516b9539af1.png)

> Merging doesn't really solve the issue and just introduces a temporary.
![image](https://user-images.githubusercontent.com/12259536/185214380-df843594-a6fb-4725-9dc7-f12dd9744a1a.png)

**Expected Behavior:**
> What I'm looking for is more like how other decompilers decompile it.
![image](https://user-images.githubusercontent.com/12259536/185214445-3dfe15ce-d424-4bb9-9da0-de82f063ff2d.png)

**Additional Information:**
> I can share a test binary I used to check the different compiler outputs in dogbolt that shows the behavior.
[main.zip](https://github.com/Vector35/binaryninja-api/files/9365252/main.zip)
> The function at `0x140001000` is the one with the condition.

**Comment by xusheng6** [comment] 2023-08-15 14:51
Related to, or duplicate of https://github.com/Vector35/binaryninja-api/issues/3527

**Comment by negasora** [comment] 2024-05-24 06:40
This was fixed, new output:
![image](https://github.com/Vector35/binaryninja-api/assets/3020965/00209155-1640-4de6-8d29-415d0c9884c4)

**Closed by negasora** 2024-05-24 06:40 UTC
Labels: Type: Enhancement, Component: Core, Core: HLIL, IL Optimization, Impact: Low
