### ISSUE TITLE
Improved parsing of C types

### ISSUE THREAD

**Issue by zznop** [Vector35/binaryninja-api#2398] opened 2021-04-26 13:14 UTC
Binary Ninja is unable to parse many different type declarations that are valid C. Some examples:

1. Forward declarations in the following syntax:

```cpp
typedef struct EFI_TIME EFI_TIME, *PEFI_TIME;
```

2. Structures containing multi-dimensional arrays

```cpp
struct foo {
    int x;
    int y[2][2];
};
```

3. Bitfields (related issue #2154)

Creating type libraries for larger projects can be a pain for this reason. An example of a difficult project to create a BN type library for is EDK-II: https://github.com/tianocore/edk2

**Comment by plafosse** [comment] 2021-04-28 19:01
1 is a duplicate of #2088 
2 does parse in `dev` branch 2.3
3 is a duplicate of #2154

**Closed by plafosse** 2021-04-28 19:01 UTC
Labels: duplicate, enhancement
