### ISSUE TITLE
Tail call failed

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3934] opened 2023-02-23 09:12 UTC
Binary Ninja Version: 3.4.4090-dev
Platform: Windows 11 Version 22H2

Prototype of the function that made tail call:
```
int64_t sub_163D3D00(int64_t arg1, int64_t arg2, int64_t arg3)
```

Disassembly of the function that made tail call:
```
163d3d00  mov     rax, qword [rel callui]
163d3d07  mov     ecx, 1099
163d3d0c  jmp     qword [rax]
```

HLIL:

```
163d3d0c  jump(*callui)
```

IDA:

```
return callui(1099, a2, a3);
```

Interestingly, that function call is problematic in other places too.

Example:

```
163d3ebf  (*callui)(0x18, 2, format, &arg_10)
```

Prototype of `callui`:

```
int64_t callui(enum ui_notification_t, ...)
```

I can share the binary in slack.

**Comment by plafosse** [comment] 2023-10-20 16:08
Duplicate of https://github.com/Vector35/binaryninja-api/issues/1060

**Closed by plafosse** 2023-10-20 16:08 UTC
Labels: Type: Bug, State: Duplicate, Component: Core
