### ISSUE TITLE
High RAM usage when running for a long time

### ISSUE THREAD

**Issue by toomanybananas** [Vector35/binaryninja-api#343] opened 2016-07-21 19:47 UTC
After running binja for about 2 weeks on my (Debian Linux 8 64-bit) the process uses about 14GB of RAM, even when no files are open.

**Comment by toomanybananas** [comment] 2016-07-23 17:56
Further information: opening a moderately sized (600kb) statically-linked ELF file causes binja to allocate roughly 1GB of RAM, which is not freed when the file is closed.

I can't share this specific sample unfortunately but I will attempt to reproduce it.

**Comment by plafosse** [comment] 2017-06-20 23:08
Can you validate this on the current dev build?

**Comment by plafosse** [comment] 2017-12-01 04:23
Closing this since the question has been outstanding for a while and I can't seem to replicate it. Please reopen this bug if the issue is still present.

**Closed by plafosse** 2017-12-01 04:23 UTC
Labels: question
