### ISSUE TITLE
segmentation fault in binaryninjaui on MacOS

### ISSUE THREAD

**Issue by ATorNinja** [Vector35/binaryninja-api#1397] opened 2019-07-17 08:55 UTC
# MacOS Version 1.1.1779-dev 
> stop reason = EXC_BAD_ACCESS (code=1, address=0x1637865647e)  
> frame #0: 0x00000001006cf0ac  
> libbinaryninjaui.dylib`___lldb_unnamed_symbol1772$$libbinaryninjaui.dylib + 60  
> Open two windows to open the binary will not give the error   

[multiple-styles.zip](https://github.com/Vector35/binaryninja-api/files/3400938/multiple-styles.zip)

**Comment by psifertex** [comment] 2019-07-17 12:41
Do you have any plugins enabled? I can't reproduce the crash.

**Comment by plafosse** [comment] 2019-07-17 13:20
I was able to repro

**Comment by ATorNinja** [comment] 2019-07-17 15:00
> Do you have any plugins enabled? I can't reproduce the crash.

I've removed all my plugins, it still crashed.

**Comment by plafosse** [comment] 2019-07-18 18:33
Fixed in 1.1.1780 Thanks for the report.

**Closed by plafosse** 2019-07-18 18:33 UTC
Labels: bug, crash
