### ISSUE TITLE
Perform cleanup post auto-analysis in support of orphaned function discovery

### ISSUE THREAD

**Issue by xusheng6** [Vector35/binaryninja-api#6200] opened 2024-11-26 06:11 UTC
While analyzing
[al-khaser_x64.exe_.zip](https://github.com/user-attachments/files/17913696/al-khaser_x64.exe_.zip), the function at 0x14004b4f0 is first created, and then removed, for unknown reason. This is causing https://github.com/mandiant/capa/issues/2507

**Comment by xusheng6** [comment] 2024-11-26 09:20
![image](https://github.com/user-attachments/assets/14e84e63-ef5b-48cd-bf6a-03cd95f74bf0)

**Comment by xusheng6** [comment] 2024-11-27 08:27
The regression was introduced in build 4.2.6295-dev. Unfortunately this builds includes some 20+ commits in it, and it is not trivial to narrow it down to a specific commit. However, it includes `ce53ad98ce13715e4259daec0fe7ad75aa635c31` (Initial implementation of the module-level analysis workflow), which I suspect is when it starts to happen

**Comment by bpotchik** [comment] 2024-11-27 22:41
This is not a regression and also not due to the commit above.

What likely happened is that there were some updates to some type libraries. RaiseException is tagged as __no_return.
![Screenshot 2024-11-27 at 5 29 03 PM](https://github.com/user-attachments/assets/ed000292-12cd-4b33-a067-84e322dcf567)

Because of that, this function gets terminated early:
![Screenshot 2024-11-27 at 5 27 41 PM](https://github.com/user-attachments/assets/5eada3d1-5309-4526-85bd-fff3d1bbb3df)

The reason the functions are removed is because there are no references left to them once the tail of the function above is removed due to the _no_return call.

The LibrarySymbol is added by SignatureMatcher. That has no bearing on whether or not auto code regions get cleaned up when there are no references to them. So in this case everything is working as designed.

If you change the `DebuggerProbe` function signature to no longer be __no_return, all of the functions referenced in the tail are recreated again.

**Comment by bpotchik** [comment] 2024-11-28 13:26
After some more discussion, the issue appears to be slightly more nuanced. While the above is true, it is also true that we updated when our garbage collection process was called. This change resulted in linear sweep not being able to create the orphaned functions (because they already existed). After analysis was complete, the situation above would occur.

I can push a fix which allows linear sweep to find and create these orphaned functions, rather than auto-analysis removing them at the end.

**Comment by bpotchik** [comment] 2024-12-03 06:08
Fixed in `4.3.6518-dev`.

**Closed as completed by bpotchik** 2024-12-03 06:08 UTC
Labels: Component: Core, Impact: Low, Effort: Trivial
