### ISSUE TITLE
Double-clicking in Xrefs list and function list is not working properly when the Strings view is shown

### ISSUE THREAD

**Issue by buildandcrash** [Vector35/binaryninja-api#518] opened 2016-10-17 22:41 UTC
When **Strings** is checked:
- Double-clicking in **Xrefs** view that is shown in the lower-left it will randomly select an item from **Strings** view instead of switching the view where it is referenced from.
- The same thing when you double-click on a function in the upper-left (**Functions view**).

**Comment by psifertex** [comment] 2016-10-17 23:50
Duplicate of #448.

This is one of the more annoying UI bugs we have right now, I realized it wasn't marked for 1.1 so just added it for that release.

**Closed by psifertex** 2016-10-17 23:50 UTC
