### ISSUE TITLE
Function type is invalid by default

### ISSUE THREAD

**Issue by Kharos102** [Vector35/binaryninja-api#3062] opened 2022-04-09 12:44 UTC
Binary Ninja Version: 3.0.3337-dev Personal, 7daa28e8
Platform: Windows 11 Version 2009
Example File: C:\windows\system32\wevtsvc.dll

When disassembling this file with symbols, Binja will create the function prototypes.

However, these prototypes can be invalid when attempting to edit them.

The screenshot I've attached is the function prototype as created by binary ninja when parsing the file with symbols, if I go to edit it, its already invalid before I can change it (so if i wanted to change arg2 to another type, it wouldn't work because something with the pre-filled prototype defined by binja prevents parsing).
![binja1](https://user-images.githubusercontent.com/16039802/162574629-9edb57f4-c779-441e-a0af-a92e7dd36cad.png)

**Comment by plafosse** [comment] 2022-04-11 17:29
This is likely due to us not parsing the `__ptr64`  We should be hiding those when we emit the string.

**Comment by plafosse** [comment] 2022-04-11 17:30
This output comes from the output of the msvc++ name demangler.

**Comment by Kharos102** [comment] 2022-04-11 22:34
> This is likely due to us not parsing the `__ptr64` We should be hiding those when we emit the string.

Yes, fixing up this line does fix this issue.

**Comment by CouleeApps** [comment] 2022-05-25 20:04
Clang says: `'__ptr64' attribute only applies to pointer arguments`. This is a bug in whatever generated that type, since __ptr64 does not apply to references. It should be easily worked around by changing the parameter type to a pointer. Will leave this open for future as this is likely a bug with the PDB parser.

**Comment by Kharos102** [comment] 2022-05-30 07:16
[sample.zip](https://github.com/Vector35/binaryninja-api/files/8796334/sample.zip)
Adding another example here which may be the same issue?

It affects a rust binary compiled for Arm64 rust (no PDBs) -- trying to change the type of a function symbol generated during analysis is also invalid by default.

Attached the screenshot and binary.

<img width="849" alt="Screen Shot 2022-05-30 at 12 13 27 AM" src="https://user-images.githubusercontent.com/16039802/170937508-8cf1b510-4839-4406-a0ef-9c3253060ef1.png">

**Comment by CouleeApps** [comment] 2022-06-08 19:08
`int128_t` is not supported on the default type parser-- try switching to Clang in the Settings (analysis -> type parser) or use a different type.

**Comment by fuzyll** [comment] 2022-06-20 20:39
We're closing this as fixed because it should work with the Clang parser. Please let us know if this isn't actually fixed and we'll look into it further.

**Closed by fuzyll** 2022-06-20 20:39 UTC
Labels: bug, PDB

**Comment by Kharos102** [comment] 2022-06-22 00:38
Hi,

This still is broken, even with the latest dev binja.

This time the error is different, see the screenshot of the result of analysing "c:\windows\system32\wevtsvc.dll" and attempting to change the function type (but not changing it, just immediately hitting ok)
![image](https://user-images.githubusercontent.com/16039802/174918932-4c9c2263-4f98-4f73-ad83-5ef86e6f7d4d.png)

**Comment by CouleeApps** [comment] 2022-06-22 00:49
Looks like the PDB did not define the class `wmi::AutoRef<class Log>` and so Clang creates an empty struct when it sees `class wmi::AutoRef<class Log>` and returns that instead of the function. I'm not quite sure what the expected behavior is here, considering that the "change type" dialog is now trying to define a type, but the PDB loader bugs are still leading to type parsing bugs down the line.
