### ISSUE TITLE
put the pointer of array out of the for loop

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#6264] opened 2024-12-20 00:44 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.3.6594-dev Personal (c7f7c5e4)
- OS: manjaro
- OS Version: Linux version 6.11.10-2-MANJARO (linux611@manjaro) (gcc (GCC) 14.2.1 20240910, GNU ld (GNU Binutils) 2.43.0) #1 SMP PREEMPT_DYNAMIC Mon, 25 Nov 2024 05:29:44 +0000

- CPU Architecture: x64

**Bug Description:**
in a for loop, lets check the following ida reversed code in c.
```
__int64 __fastcall worker_thread(__int64 a1)
{
...
...
  _DWORD v10[12];  // v10 is out of the for loop
...
...
  for ( i = 0; i < 12; ++i )
    v10[i] = open("/xxxxx", 0);
```
but in ninja here it is 
```
00002f58    int64_t worker_thread()
00002f58    {
...
...
00002f88        for (int32_t i = 0; i < 0xc; i += 1)
00002f88        {
00002f88            void var_d8;  // inside the loop
00002fa8            *(uint32_t*)(&var_d8 + ((int64_t)i << 2)) = open("/dev/null", 0);
00002f88        }
```
i dont know whethere i am right .
hoping we can take it care.

**Comment by negasora** [comment] 2024-12-20 01:20
What if you set the type of var_d8 correctly?

**Comment by bb33bb** [comment] 2024-12-20 01:34
> What if you set the type of var_d8 correctly?

maybe will change.
I am really too lazy so i made no change to the reversed code.

**Comment by psifertex** [comment] 2024-12-20 13:15
If it changes when you type it correctly then this is just a duplicate of https://github.com/Vector35/binaryninja-api/issues/2570 so I'm going to close it as such. Feel free to re-open with more information if not.

**Closed as not planned by psifertex** 2024-12-20 13:15 UTC
Labels: State: Duplicate

**Comment by bb33bb** [comment] 2024-12-22 13:50
> If it changes when you type it correctly then this is just a duplicate of #2570 so I'm going to close it as such. Feel free to re-open with more information if not.

I tried to change the type to be an array, then it will go out of the loop
```
00002f58    int64_t worker_thread()

00002f58    {
00002f58        int64_t x0;
00002f68        int64_t var_28 = x0;
00002f74        binder_enter_looper(client_a_fd);
00002f88        int64_t null_fd[0xc]; ////////////////////////!!!!!!!!!!!!!!out the scope ???
00002f88        
00002f88        for (int32_t i = 0; i < 0xc; i += 1)
00002f88            *(uint32_t*)(&null_fd + ((int64_t)i << 2)) = open("/dev/null", 0);

```
then the second try, i find the above is not right ,for the reason of type of null_fd[0]
it should be uint32_t, so after i retyped, the following code shows that :

```
00002f58    int64_t worker_thread()

00002f58    {
00002f58        int64_t x0;
00002f68        int64_t var_28 = x0;
00002f74        binder_enter_looper(client_a_fd);
00002f74        
00002f88        for (int32_t i = 0; i < 0xc; i += 1)
00002f88        {
00002f88            uint32_t null_fd[0xc];   // still in the for loop,   ////////////////////////!!!!!!!!!!!!!!out the scope ???
00002fa8            null_fd[(int64_t)i] = open("/dev/null", 0);
00002f88        }
```
