### ISSUE TITLE
Jump table creation failed for 16 bit binary

### ISSUE THREAD

**Issue by op2786** [Vector35/binaryninja-api#3519] opened 2022-10-11 13:40 UTC
- Binary Ninja Version: 3.1.3469
- OS: Windows
- OS Version: 10
- CPU Architecture: x64

File offset for function: 0x6331

![switch_fail](https://user-images.githubusercontent.com/109607896/195106616-424335da-b29a-4965-ac64-ef686eedfc91.PNG)

[binary.zip](https://github.com/Vector35/binaryninja-api/files/9756363/binary.zip)

**Comment by plafosse** [comment] 2023-01-02 18:41
This is a duplicate of #936 basically we have no support for memory segmentation at this time.

**Closed by plafosse** 2023-01-02 18:41 UTC
Labels: bug, duplicate, Effort: High, Impact: Medium
