### ISSUE TITLE
The default rendering of an integer data varible should consider its type information

### ISSUE THREAD

**Issue by bb33bb** [Vector35/binaryninja-api#6029] opened 2024-10-23 07:54 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.2.6262-dev Personal (5c271eff)
- OS: manjaro Latest x64
- OS Version: Linux version 6.10.13-3-MANJARO (builduser@fv-az1246-770) (gcc (GCC) 14.2.1 20240910, GNU ld (GNU Binutils) 2.43.0) #1 SMP PREEMPT_DYNAMIC Tue Oct  8 03:24:49 UTC 2024
- CPU Architecture: x64

**Bug Description:**

https://github.com/user-attachments/assets/5a442380-8aeb-4070-8ba8-2721061ef9bd

as u can see , we expect the number to be like 0xffffffffxxxxxxxx
but it is not go as we expected

**Comment by psifertex** [comment] 2024-10-23 12:10
Right now the display type of the variable is mostly separate from the type system type of the variable. You can fix this by right clicking the integer itself and changing the display type. 

That said, I agree the experience would be better if the display type for signedness was influenced by the actual type. Leaving the issue open to track that.

**Comment by bb33bb** [comment] 2024-10-28 06:30
> Right now the display type of the variable is mostly separate from the type system type of the variable. You can fix this by right clicking the integer itself and changing the display type.
> 
> That said, I agree the experience would be better if the display type for signedness was influenced by the actual type. Leaving the issue open to track that.

we can only use interaction method maybe.
I tried the api, also not successed.

**Comment by xusheng6** [comment] 2024-10-29 07:25
Thanks for the bug report! I have actually ran into this myself a few times, but I was busy working on other things and just let it slip. I should have noticed that we are ignoring the type information. Apparently we should consider the type info when the rendering type is set to default

**Comment by CouleeApps** [comment] 2024-10-29 13:59
This seems like a duplicate of #6044 which was fixed recently. Closing as fixed for now but can reopen if this is actually something else.

**Closed as completed by CouleeApps** 2024-10-29 13:59 UTC
Labels: State: Duplicate, Component: UI, Impact: Low, Effort: Low, UI: Linear
