### ISSUE TITLE
pdb loader crash

### ISSUE THREAD

**Issue by lucasduffey** [Vector35/binaryninja-api#767] opened 2017-08-14 15:19 UTC
**triggered on Ubuntu 16 LTS**
1) opened dll
2) loaded pdb via tools => load pdb

# relevant cmdline debug log 
```
> ~/binaryninja/binaryninja  --debug --stderr-log
Looking for PDB in same directory
Segmentation fault (core dumped)
```

# gdb
```
(gdb) r
Starting program: /home/user/binaryninja/binaryninja 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe3a39700 (LWP 5358)]
[New Thread 0x7fffd8b29700 (LWP 5359)]
[New Thread 0x7fffd7bff700 (LWP 5360)]
[New Thread 0x7fffd6bff700 (LWP 5361)]
[New Thread 0x7fffd59c3700 (LWP 5362)]
[New Thread 0x7fffd51c2700 (LWP 5363)]
[New Thread 0x7fffd3bff700 (LWP 5365)]
[New Thread 0x7fffd2bff700 (LWP 5366)]
[New Thread 0x7fffd1bff700 (LWP 5367)]
[New Thread 0x7fffd0bff700 (LWP 5368)]
[Thread 0x7fffd0bff700 (LWP 5368) exited]
[Thread 0x7fffd59c3700 (LWP 5362) exited]
[New Thread 0x7fffd59c3700 (LWP 5372)]
[New Thread 0x7fffd0bff700 (LWP 5374)]
[Thread 0x7fffd0bff700 (LWP 5374) exited]
[New Thread 0x7fffd0bff700 (LWP 5375)]
[New Thread 0x7fffca48a700 (LWP 5376)]
[Thread 0x7fffca48a700 (LWP 5376) exited]
[New Thread 0x7fffca48a700 (LWP 5377)]
[New Thread 0x7fffc7fff700 (LWP 5378)]
[New Thread 0x7fffc77fe700 (LWP 5379)]
[New Thread 0x7fffc6ffd700 (LWP 5380)]
[New Thread 0x7fffc37ff700 (LWP 5381)]
[Thread 0x7fffc37ff700 (LWP 5381) exited]
[Thread 0x7fffd1bff700 (LWP 5367) exited]

Thread 16 "binaryninja" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffca48a700 (LWP 5377)]
0x00007ffff3450cc0 in _IO_vfprintf_internal (s=s@entry=0x7fffca489720, format=<optimized out>, format@entry=0x7fffcf6b85e5 "Loading pdb from: %s: %s", ap=ap@entry=0x7fffca489878) at vfprintf.c:1632
1632	vfprintf.c: No such file or directory.
(gdb) bt
#0  0x00007ffff3450cc0 in _IO_vfprintf_internal (s=s@entry=0x7fffca489720, format=<optimized out>, format@entry=0x7fffcf6b85e5 "Loading pdb from: %s: %s", ap=ap@entry=0x7fffca489878) at vfprintf.c:1632
#1  0x00007ffff351a975 in __GI___vasprintf_chk (result_ptr=0x7fffca489858, flags=1, format=0x7fffcf6b85e5 "Loading pdb from: %s: %s", args=0x7fffca489878) at vasprintf_chk.c:66
#2  0x00007fffcf66c5bc in ?? () from /home/user/binaryninja/plugins/libloadpdb.so
#3  0x00007fffcf66c8e4 in BinaryNinja::LogInfo(char const*, ...) () from /home/user/binaryninja/plugins/libloadpdb.so
#4  0x00007fffcf608c00 in ?? () from /home/user/binaryninja/plugins/libloadpdb.so
#5  0x00007fffcf60b101 in ?? () from /home/user/binaryninja/plugins/libloadpdb.so
#6  0x00007fffcf64c739 in ?? () from /home/user/binaryninja/plugins/libloadpdb.so
#7  0x00007ffff6293eea in ?? () from /home/user/binaryninja/libbinaryninjacore.so.1
#8  0x00007ffff3da3c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff40746ba in start_thread (arg=0x7fffca48a700) at pthread_create.c:333
#10 0x00007ffff35093dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) i r
rax            0x0	0
rbx            0x7fffca489720	140736587142944
rcx            0xffffffffffffffff	-1
rdx            0x18	24
rsi            0x7fffca4896d8	140736587142872
rdi            0x1	1
rbp            0x7fffca489710	0x7fffca489710
rsp            0x7fffca4891a0	0x7fffca4891a0
r8             0x0	0
r9             0x56	86
r10            0x73	115
r11            0x1	1
r12            0x7fffcf6b85e5	140736673318373
r13            0x7fffca489878	140736587143288
r14            0x0	0
r15            0x7fffcf6b85f7	140736673318391
rip            0x7ffff3450cc0	0x7ffff3450cc0 <_IO_vfprintf_internal+6992>
eflags         0x10286	[ PF SF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

# last binja address in bt (0x00007fffcf66c5bc)
```
(gdb) x/40i 0x00007fffcf66c5bc - 0x40
   0x7fffcf66c57c <_ZNSt6vectorIN11BinaryNinja17FunctionGraphEdgeESaIS1_EEaSERKS3_+2044>:	dec    DWORD PTR [rdi]
   0x7fffcf66c57e:	(bad)  
   0x7fffcf66c57f:	add    BYTE PTR [rax-0x75],cl
   0x7fffcf66c582 <_ZN11BinaryNinja11LogListener16CloseLogCallbackEPv+2>:	(bad)  
   0x7fffcf66c583 <_ZN11BinaryNinja11LogListener16CloseLogCallbackEPv+3>:	mov    rax,QWORD PTR [rax+0x18]
   0x7fffcf66c587 <_ZN11BinaryNinja11LogListener16CloseLogCallbackEPv+7>:	jmp    rax
   0x7fffcf66c589:	nop
   0x7fffcf66c58a:	nop    WORD PTR [rax+rax*1+0x0]
   0x7fffcf66c590 <_ZN11BinaryNinja11LogListener19GetLogLevelCallbackEPv>:	mov    rax,QWORD PTR [rdi]
   0x7fffcf66c593 <_ZN11BinaryNinja11LogListener19GetLogLevelCallbackEPv+3>:	mov    rax,QWORD PTR [rax+0x20]
   0x7fffcf66c597 <_ZN11BinaryNinja11LogListener19GetLogLevelCallbackEPv+7>:	jmp    rax
   0x7fffcf66c599:	nop    DWORD PTR [rax+0x0]
   0x7fffcf66c5a0:	push   rbx
   0x7fffcf66c5a1:	mov    ebx,edi
   0x7fffcf66c5a3:	mov    rcx,rdx
   0x7fffcf66c5a6:	mov    rdx,rsi
   0x7fffcf66c5a9:	mov    esi,0x1
   0x7fffcf66c5ae:	sub    rsp,0x10
   0x7fffcf66c5b2:	lea    rdi,[rsp+0x8]
   0x7fffcf66c5b7:	call   0x7fffcf5f4b60 <__vasprintf_chk@plt>
   0x7fffcf66c5bc:	test   eax,eax
   0x7fffcf66c5be:	js     0x7fffcf66c5df
   0x7fffcf66c5c0:	mov    rdx,QWORD PTR [rsp+0x8]
   0x7fffcf66c5c5:	lea    rsi,[rip+0x4bf93]        # 0x7fffcf6b855f
   0x7fffcf66c5cc:	mov    edi,ebx
   0x7fffcf66c5ce:	xor    eax,eax
   0x7fffcf66c5d0:	call   0x7fffcf5f3a30 <BNLog@plt>
   0x7fffcf66c5d5:	mov    rdi,QWORD PTR [rsp+0x8]
   0x7fffcf66c5da:	call   0x7fffcf5ed800 <free@plt>
   0x7fffcf66c5df:	add    rsp,0x10
   0x7fffcf66c5e3:	pop    rbx
   0x7fffcf66c5e4:	ret    
   0x7fffcf66c5e5:	nop
   0x7fffcf66c5e6:	nop    WORD PTR cs:[rax+rax*1+0x0]
   0x7fffcf66c5f0 <_ZN11BinaryNinja11LogListener18LogMessageCallbackEPv10BNLogLevelPKc>:	push   r13
   0x7fffcf66c5f2 <_ZN11BinaryNinja11LogListener18LogMessageCallbackEPv10BNLogLevelPKc+2>:	push   r12
   0x7fffcf66c5f4 <_ZN11BinaryNinja11LogListener18LogMessageCallbackEPv10BNLogLevelPKc+4>:	mov    r12d,esi
   0x7fffcf66c5f7 <_ZN11BinaryNinja11LogListener18LogMessageCallbackEPv10BNLogLevelPKc+7>:	mov    rsi,rdx
   0x7fffcf66c5fa <_ZN11BinaryNinja11LogListener18LogMessageCallbackEPv10BNLogLevelPKc+10>:	push   rbp
   0x7fffcf66c5fb <_ZN11BinaryNinja11LogListener18LogMessageCallbackEPv10BNLogLevelPKc+11>:	push   rbx

```

**Comment by lucasduffey** [comment] 2017-08-14 15:19
let me know if you need any more details

**Comment by psifertex** [comment] 2017-08-14 15:57
Can you share the pdb/dll even if privately?

**Comment by lucasduffey** [comment] 2017-08-14 16:00
unfortunately not

**Comment by plafosse** [comment] 2017-08-14 16:08
Any chance you can tell me what the first parameter to "LogInfo" is?

**Comment by plafosse** [comment] 2017-08-14 16:10
Nevermind I can replicate the issue

**Comment by lucasduffey** [comment] 2017-08-14 18:39
the recent push fixed the crash I was having, but binja UI freezes (potentially indefinitely) in the middle of the pdb loading process.


the fix may have introduced a new bug - Currently, if I save a bndb file that loaded information from a pdb file it's crashing during the saving process.

**Comment by plafosse** [comment] 2017-08-16 18:59
I'm going to close this since the crash is fixed, and I haven't been able to reproduce any UI freeze, please submit a binary if you have one that causes analysis freezes.

**Closed by plafosse** 2017-08-16 18:59 UTC
