### ISSUE TITLE
ELF Mapping Symbols for ARM/Thumb Platforms Not Handled

### ISSUE THREAD

**Issue by quend** [Vector35/binaryninja-api#1913] opened 2020-08-18 17:16 UTC
In some cases, calling get_functions_containing returns two results, and only the first looks to be a valid result.

In the example below when calling get_functions_containing on 0x10d66 we get [<func: thumb2@0x109f4>, <func: thumb2@0x10814>]

The first result looks valid, the second doesn't.
[rprogramstore.zip](https://github.com/Vector35/binaryninja-api/files/5091789/rprogramstore.zip)

**Comment by psifertex** [comment] 2020-08-18 17:22
The API looks like it's doing the right thing -- I see 0x10d66 in both functions. Here's two screenshots:

<img width="1886" alt="Screen Shot 2020-08-18 at 1 22 00 PM" src="https://user-images.githubusercontent.com/140215/90544928-dded2f00-e155-11ea-8c77-326142d9af58.png">
<img width="1886" alt="Screen Shot 2020-08-18 at 1 22 11 PM" src="https://user-images.githubusercontent.com/140215/90544934-e180b600-e155-11ea-8c2f-460645aee65f.png">

Now, whether the /analysis/ is doing the right thing I'm not so sure of...

**Comment by psifertex** [comment] 2020-08-18 17:25
Yeah, I mean, looking at the control flow the first function has a:
```0001082a  8fe2       b       #0x10d4c``` 
which lands above that address
and the second function (which is main) does it via:
```00010cf2  47e0       b       #0x10d84```
Looks like the compiler is just doing some code-reuse?

**Comment by plafosse** [comment] 2020-08-18 17:26
Seems like this is because something (probably linearsweep) came through and created a function @ 0x00010814 which should not have been created.

**Comment by psifertex** [comment] 2020-08-18 17:34
To be clear I labelled this as "can't reproduce" because I can't reproduce a _problem_. The API behaves exact the way you said, I'm just asserting that's not an actual issue as I see both functions containing that address. (And fwiw, looking at those branches I'm not certain it's a linear sweep bug either? It might actually be a compiler doing that for real, though it could go either way)

I only tagged it that way in case @quend has other repoducers that do show an instance where this bug occurs, merely that this API doesn't demonstrate the bug as described above.

**Comment by quend** [comment] 2020-08-18 17:51
oh weird well thanks for looking into it, ill try and debug dynamically to see whats happening

**Comment by plafosse** [comment] 2020-08-19 18:20
As we've determined that the problem as stated in the issue is incorrect, I'm closing this as "won't fix". If it turns out there is a missing no-return or a problem with linearsweep please create a new issue.

**Comment by bpotchik** [comment] 2020-08-19 20:01
It looks like linear sweep is creating a thumb2 function at the start of 0x10814 which is really supposed to be an ARM stub. The incorrect arch creates some bad code that falls into the other chuck of code which is why the extra xref shows up.

**Comment by quend** [comment] 2020-08-19 20:50
Thanks Brian! Should I create a new issue to track this?

**Comment by bpotchik** [comment] 2020-08-19 20:53
Nope, I've got a fix incoming ;)

**Comment by bpotchik** [comment] 2020-08-20 00:03
Fixed in 2.1.2343-dev.

**Closed by bpotchik** 2020-08-20 00:03 UTC
Labels: bug
