### ISSUE TITLE
test + multiple cmov instructions causes duplicate conditional variables

### ISSUE THREAD

**Issue by duk-37** [Vector35/binaryninja-api#2901] opened 2022-01-30 18:07 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3238-dev
- OS: Windows 11
- OS Version: 22000.376

**Bug Description:**
A new conditional variable is created every time the result of a `test` instruction is used.

**Steps To Reproduce:**
Open the following assembly in any IL view:
```asm
test rdx, rdx

cmovne rdx, rcx
cmovne rdx, rcx
cmovne rdx, rcx
cmovne rdx, rcx
cmovne rdx, rcx

mov rax, rdx
ret
```

**Expected Behavior:**
Only one conditional variable is created.

**Screenshots:**
![image](https://user-images.githubusercontent.com/74797529/151711604-cb567717-ad0a-4c74-978c-46d03eb6db0d.png)
![image](https://user-images.githubusercontent.com/74797529/151711709-b151b48d-a05f-4e6a-a2ac-952e0f7a3606.png)
![image](https://user-images.githubusercontent.com/74797529/151711610-de51df0e-d608-4296-9a60-ccec76e2ba4f.png)

**Comment by rssor** [comment] 2022-01-30 20:14
Duplicate of #1720.

This is a missed optimization opportunity but is presently working as intended. When actual inlining of the condition into the use can’t occur (presently this is limited to immediately adjacent instructions) we spill to a temp cond for each use site for a variety of reasons relating to when the decision to spill has to be made and what is known about other uses at the time. It’s too conservative and could get away with only emitting the condition once but it’s been on the backburner since there’s no correctness impact making it a cosmetic issue.

**Closed by rssor** 2022-01-30 20:14 UTC
Labels: enhancement

**Comment by duk-37** [comment] 2022-01-30 21:22
Ah, missed that other issue, sorry.
