### ISSUE TITLE
Add Plugin Status to New Tab GUI

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#329] opened 2016-07-04 22:18 UTC
It would be SUPER helpful to have plugin information on the initial "New Tab" screen (the one that shows recently opened files and the version changelogs). My idea for this would be to basically copy World of WarCraft's plugin status stuff:
- Show what plugins are present
- Show which ones loaded successfully and which didn't
- Allow the user to see the error log(s) for those that didn't load
- Give the user the option to re-load some/all plugins

With this, it would also be helpful if one failing plugin didn't prevent ALL plugins from failing to load.

**Comment by psifertex** [comment] 2020-12-16 19:50
This request predates the current plugin manager and we've described the best-practices for plugin reloading here (https://docs.binary.ninja/guide/plugins.html#testing).

Given that, the only feature from this request we plan to implement is better status/visibility for plugins that need updating, though we're more likely to implement it in the status bar versus the new tab widget. 

Opening #2199 to track that and closing the rest of this as resolved.

**Closed by psifertex** 2020-12-16 19:50 UTC
Labels: enhancement, ui

**Comment by fuzyll** [comment] 2020-12-16 22:23
I'm not sure why or how, but I feel like I miscommunicated what I was looking for. #2199 doesn't cover most of my request at all.

The first part of my ticket is actually covered much better by #2200 - I want to see, at a glance, what I have installed and its current status when I start Binja. I could get that information from the plugin manager, yes, but I don't _want_ to open the plugin manager - I want to see the information at a glance. The plugin manager isn't useful for this information because:

1. The fonts are _massive_, for no discernable reason.
2. The descriptions aren't useful to me in this context - I've already installed these things.
3. The plugins are sorted by A-Z first instead of enabled/installed first, meaning I have to search for "enabled".

The second part of my ticket is related to figuring out why something is broken. If I do something stupid, like install the 6502 plugin and then delete `__init__.py` out of the `repositories/official/plugins/Vector35_6502` folder, I have no idea that I shouldn't expect that plugin to work prior to opening a file. The plugin manager says it's enabled and everything is in perfect working order. If I go try and open an NES ROM, it tells me that it predicts it's a PPC binary and there's no option for 6502 anywhere. As a user, I have zero idea why this plugin doesn't work, but the UI _swears_ it's installed.

The third part of my ticket is related to quickly reloading plugins. The linked documentation requires me to CTRL+F the word "reload" to even know where it is on the page. Then, following its instructions...this happens:

```
>>> import binaryninja
>>> reload(foo)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'reload' is not defined
```

`foo` isn't a real plugin name, but that's not the error: `reload` itself is not defined. That's because you've migrated away from python 2.7, so it could be fixed by just pointing out you want `importlib.reload` instead:

```
>>> import importlib
>>> importlib.reload(foo)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'foo' is not defined
```

...but that's not the point. The point is, from a user perspective, I just wanna click a button. The workflow _I'm_ looking for is something more like:

1. Click button in status bar that has a cog on it.
2. Mouse over the name of my plugin.
3. Either just click it to reload it, or click a thing that says "Reload" in another menu that pops out.

Or, better yet, if there's a way I can just click a single button to re-launch Binary Ninja and have it re-open my `.bndb` and put everything back the way I expect, that'd be cool, too. VS Code does this with the [Reload](https://marketplace.visualstudio.com/items?itemName=natqe.reload) extension, but I understand that it's a completely different situation and application.

Ultimately, I don't really care about the _specific_ implementation of these features...I've just really wanted them for quite some time.

**Comment by psifertex** [comment] 2020-12-17 03:03
RE reloading:

I linked to the online docs because the link is stable, but check the latest in dev where the docs were fixed a while ago:

https://github.com/Vector35/binaryninja-api/blob/dev/docs/guide/plugins.md#user-content-ui-elements:~:text=documented.-,Testing,changed.

The fragment it linked to was just at the bottom of the page which is why the previous link wasn't closer to where it was supposed to be. 

We have no plans to implement a reload button for plugins. Many plugins (all BVs and Architectures and some additional types) are not even reloadable, and some others may have side-effects. This makes a generic "reload" workflow inconsistent and possibly even more confusing to plugin developers (and especially users who may not know the effects of reloading any particular plugin unlike the plugin author) than just documenting this workflow with the caveats in the documentation. If you're developing a plugin, the current workflow works pretty well (I've written as many or more plugins than probably anyone else and I use it all the time!). If you're just a plugin user, you shouldn't need to reload very often anyway.  Hmm, then again, if we were to implement it, maybe hiding it behind the `Debug Mode` setting would be the way to go? I dunno, we've generally really wanted to avoid this since we discourage the practice because of the nature of having an extensible C++ core and python plugins interoperating. 

RE: Massive fonts: can you show a screenshot? I don't think I can reproduce that. Here's my plugin manager:
<img width="2032" alt="Screen Shot 2020-12-16 at 7 41 11 PM" src="https://user-images.githubusercontent.com/140215/102423272-a80e6900-3fd6-11eb-8e73-a13699b20273.png">

We're discussing internally what #2200 would look like, but I don't think it will be a full plugin list, much more of a very short status of plugin counts that with a click would take you to the appropriate plugin filter. 

Another part of the solution will come with what we're planning for 3.0 (or whatever comes after 2.3) when we plan to implement a VSCode style sidebar which will be a superset of find, plugins, symbols, etc.

That said, I made a snippet you might like in the interim, it's at least a much more concise list of plugins and their status: https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-list_plugins-py

(And of course it is color-blind aware 😉 )

It could really use the ability to trigger the plugin manager directly on a click though that would require converting it to a QWebEngine instead of `show_html_report` example, but that's probably worth doing since I don't have any existing snippets demonstrating that.

**Comment by fuzyll** [comment] 2020-12-17 07:47
Re: Docs, I didn't catch that - glad to see it's already been fixed!

Re: Reloading, I guess that makes sense..? When I'm writing stuff, though, I generally want to fix an error I've encountered and then reload to see the changes fairly immediately. I just close Binja and restart it if I'm doing something with a Binary View or Architecture. If there's no way around that because of the complexities involved, I agree that having a "reload" button is potentially useless. If it were useful for situations not involving those things, I agree it might be worthwhile to hide behind the `Debug Mode` flag.

Re: Fonts...

![image](https://user-images.githubusercontent.com/607452/102452700-c9884880-4008-11eb-8ff8-42dba0f73a4a.png)

This is from a fresh install on Windows 10, v2.2.2487, which should be current stable (which is also why I was pointing out the problems with the docs earlier - they don't actually match what's been shipped). (EDIT: And, while I was writing this, I just confirmed that v2.2.2579-dev has the same behavior.) Adjusting the font size in the settings menu doesn't seem to do anything to adjust it, either. I suspected it had something to do with display scaling (mine's set to 150%, but when I changed it, they were still huge. Fonts elsewhere in the UI are also wacky sizes as well (e.g. the buttons on the main tab when you launch the application have text twice the size of the "Decompiler is here!" section's body text). I can open up a separate ticket for this if this isn't normal/intended/not just my computer.

Re: Snippet, it's great and certainly solves part of the problem! I'm not sure it'd detect the theoretical problem I posed earlier, though, which was: If a plugin author accidentally pushes something that breaks, or I mistakenly do something to my own plugin that breaks, how do I know that a plugin is "Enabled, Broken" instead of "Enabled, Working"? My thought experiment with the 6502 plugin's `__init__.py` results in the plugin being marked as "Enabled", yet 100% unusable with no visible warnings. In fact, the log even states that it's `Loaded python3 plugin 'Vector35_6502'`, when it very clearly can't have since I deleted the only file that _actually_ matters...

Re: VSCode-style sidebar - yes please! VS Code has a pretty usable UI and I think Binja could benefit from stealing some of their ideas.

**Comment by psifertex** [comment] 2020-12-17 07:59
If the plugin breaks you already get a giant red error from the log error when the python fails so that shouldn't be a surprise even now.

Yeah, that font stuff is weird. Please file a separate issue so we can track it. 

Re: restarting/reloading there are several tricks that help. First, the workflow in the docs makes it up enter to reload which is pretty quick. Most of the time though I must restart BN with a hotkey, then 1 to open the last file (or, if you launch BN with a file from the CLI when you trigger the restart action it reopens the same file), then trigger my plugin via the action system. 

I mostly use that so no matter the plugin I have the same workflow, though for especially large files I do switch to the implib.reload method.

**Comment by fuzyll** [comment] 2020-12-19 01:12
I made #2201 yesterday to address the font problems.

I don't really have anything else to say, I guess! I agree you guys have the necessary functionality and documentation covered...I just still think there's room for improvement in the user experience. I also think it's pretty weird that a plugin without any actual code would say it's "loaded", but I'd also agree it's a pretty contrived example. I found some time to try a few other contrived examples today and they all showed up in the logs like I'd expect, and I haven't had things fail to show up otherwise (or I'd have made another ticket).

I'll patiently wait and see what yinz come up with for #2199 and #2220. 👍  Thanks!
