### ISSUE TITLE
Opening type list for Foundation causes Binary Ninja to rapidly consume unlimited amounts of memory

### ISSUE THREAD

**Issue by saagarjha** [Vector35/binaryninja-api#3728] opened 2022-12-12 11:06 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.2.3906-dev Personal (Build ID 40238088)
- OS: macOS
- OS Version: 13.1 (22C65)
- CPU Architecture: Apple silicon

**Bug Description:**
If I open the types tab for Foundation Binary Ninja quickly uses massive amounts of memory.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open Foundation from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation. Alternatively pick the one I have attached to this bug.
2. Click on the types tab.

**Expected Behavior:**
The type list shows up.

**Additional Information:**
Please add any other context about the problem here.
[Foundation.zip](https://github.com/Vector35/binaryninja-api/files/10207303/Foundation.zip)

**Comment by negasora** [comment] 2022-12-22 20:52
I can't reproduce this with `3.2.3937-dev` - are you still running into this problem?

**Comment by saagarjha** [comment] 2022-12-23 15:09
Yes. I tried disabling all plugins by launching Binary Ninja with the -p flag too and it didn't help, so I'm not sure if I have any additional configuration I can disable temporarily to try to figure out what's going on?

**Comment by negasora** [comment] 2022-12-27 06:27
This is because structure `class__TtC10Foundation7IOActor` has one member `void* $defaultActor` at offset `0xfeedfacf`, so we're trying to print padding for `0xfeedface` bytes. Trying to create, tokenize, and display ~4GB is definitely NOT the right approach here. The fix I have in mind is tracked by https://github.com/Vector35/binaryninja-api/issues/3758

**Comment by psifertex** [comment] 2022-12-28 01:05
Note we have another fix in testing tracked under https://github.com/Vector35/binaryninja-api/issues/3600

**Comment by negasora** [comment] 2023-01-21 20:52
This was fixed in builds >= 3.2.3971 (with #3600 )

**Closed by negasora** 2023-01-21 20:52 UTC
Labels: bug, ui, Impact: Medium
