### ISSUE TITLE
Highlight indent level for selected control block in linear view

### ISSUE THREAD

**Issue by 404d** [Vector35/binaryninja-api#2141] opened 2020-11-21 21:33 UTC
Note that this is an feature request to the existing indent guides.

With some larger/more complex code bodies for conditionals and loops, you may end up with some pretty long code sections combined with large amount of indents.

Adding some sort of way to distinguish the different lines would be helpful. Some solutions could be:
- Highlight clicked lines, like with flow arrows in graph view
- Using alternate styling for the selected control structure's indent, like in the screenshot below (...dd6 to ...de4)

![image](https://user-images.githubusercontent.com/451886/99887715-de123480-2c46-11eb-8135-a26bdc2ad8fb.png)

Some additional thoughts:
- Selecting an if/ifelse/else etc. could also highlight the corresponding indent level for all relevant conditions (e.g. the if-else on ...446 to ...def)
- Slightly increased linespacing above the first condition for a new indent level, to give some visual separation between unrelated if-statements (for example the two succeeding ifs in the screenshot)

**Comment by yrp604** [comment] 2020-11-21 21:59
I really like the alternative styling idea for the currently selected block. An additional idea: a keybind that can be used on first/last instructions to jump to their corresponding last/first instruction. E.g. in vim, if you have an open/closed paren or brace selected, '%' takes you to the matching close/open.

**Comment by psifertex** [comment] 2022-08-26 19:25
#2790 is a duplicate of this but has a higher upvote count so I'm closing this one in favor of that.

**Closed by psifertex** 2022-08-26 19:25 UTC
Labels: enhancement, ui, Impact: Low, Effort: Low
