### ISSUE TITLE
program crash when using floating python console with interactive usage

### ISSUE THREAD

**Issue by codingsnippets** [Vector35/binaryninja-api#1240] opened 2019-01-10 03:44 UTC
Binary Ninja Version: 1.1.1344 Personal, c25b2ebb
Platform: Ubuntu 18.04.1 LTS

To reproduce problem:
View -> Script Console 
```
>>> help() 
>>> # works fine
>>> modules
>>> # loading a few packages, then application crash
```

**Comment by psifertex** [comment] 2019-01-10 03:54
Does this still happen with the latest dev branch?

**Comment by codingsnippets** [comment] 2019-01-10 04:20
yes, just tried using:
Binary Ninja Version: 1.1.1462-dev Personal, 7fd03575
Same behavior.

**Comment by plafosse** [comment] 2019-01-16 20:06
Thanks for reporting the issue, we've been able to reproduce the issue.

**Comment by fuzyll** [comment] 2022-03-31 16:58
This doesn't repro for me on 3.0.3321-dev. I suspect it's been fixed for awhile, since the original report is over 3 years old. Closing this now.

**Closed by fuzyll** 2022-03-31 16:58 UTC
Labels: bug, crash, Impact: Low
