### ISSUE TITLE
Feature request: Adding comments in linear view

### ISSUE THREAD

**Issue by Leseratte10** [Vector35/binaryninja-api#1124] opened 2018-08-18 20:09 UTC
I'd like to have the functionality to add comments to variables in the linear view. When I open the linear view, and "change type" for a value, I can enter a name for the variable. However, the "Enter comment" option in the context menu doesn't work. I'd really like to have a way to add comments to a variable definition so I don't have to write huge unreadable variable names ...

**Comment by plafosse** [comment] 2019-01-14 17:35
This is actually a dupe of #466
@Arcnor's request is a new request though so I'll open a new ticket for that.

**Closed by plafosse** 2019-01-14 17:35 UTC

**Comment by Arcnor** [comment] 2019-01-14 19:33
Thanks @plafosse, can you link the new one here?

**Comment by plafosse** [comment] 2019-01-14 19:40
Yup #1244
