### ISSUE TITLE
"Create Function" for thumb2 is faulty

### ISSUE THREAD

**Issue by pr0me** [Vector35/binaryninja-api#2132] opened 2020-11-19 11:27 UTC
The "Make Function at this Address" context menu functionality seems to work incorrectly for thumb2. Even if specifying the correct architecture manually, the code (sometimes?) gets disassembled as ARM code, not as thumb.

Example: In the GIF you can see how I want to create a function at opcode \x2d\xe9\xf0\x47, which is a 
_push.w {r4, r5, r6, r7, r8, sb, sl, lr}_ in thumb. Instead, the newly created function disassembles the bytes as ARM, showing _ldrbmi lr, [r0, sp, lsr #18]!_ followed by _addlt r4, lr, r4, lsr_ for the bytes \xa4\x4c\x8e\xb0 where it should be _ldr r4, [pc, #0x290]_ for \xa4\x4c.

![binja_bug](https://user-images.githubusercontent.com/5177161/99660256-671c4680-2a62-11eb-8e6c-71ca1c7e4941.gif)

**Comment by jeffli678** [comment] 2020-11-19 14:04
Does it work correctly in hex editor? Also, I see you put a `sometimes?` there. Does it reproduce reliably, or by a certain probability?

**Comment by pr0me** [comment] 2020-11-19 15:09
What do you mean by 'work correctly in hex editor'?

It does reproduce 100% reliably for these bytes at this position. 
![Selection_009](https://user-images.githubusercontent.com/5177161/99682959-1adfff00-2a80-11eb-9678-07ed09f534fb.png)
![Selection_010](https://user-images.githubusercontent.com/5177161/99682991-2501fd80-2a80-11eb-9818-e2a28dc143b6.png)

The initial auto analysis of the binary fails (for some reason) to recognize these 12 bytes as thumb code. 
The subsequent bytes are correctly classified and disassembled. Also note, that after invoking "Make Function at this Address" on the missing bytes, there are multiple disassemblies given for the same address. 
The missing 12 bytes should be push, ldr, sub and b.w thumb instructions. 

I wrote 'sometimes' because I did not check the behavior at other locations or in other binaries.
I did now, and the observed behavior (at least for this raw thumb2 binary blob) is always the same, some bytes
seem to get omitted during initial analysis and when disassembling them manually - specifying 'thumb2' - it results in ARM code.

**Comment by nshp** [comment] 2020-11-19 16:35
While it is certainly unexpected that specifically choosing "thumb2" doesn't do the right thing, the intended behavior in general is: if you want a Thumb function, create a function at an odd address / the second byte in the function (i.e. click on the `e9` in your GIF). If you want an ARM function, create the function at the even address.

Not saying the menu options shouldn't be fixed, just giving you a workaround.

**Comment by psifertex** [comment] 2020-11-19 17:28
Yeah, ARM/Thumb is a weird architecture in that regard. Because the least significant bit is used to indicate architecture and it switches on the fly, the usual conventions in BN are slightly different. Otherwise there would be no way to transition between the two automatically during different call instructions. For now I'm going to close this as a wont-fix though we realize it's something that comes up frequently, it's not something that the current architecture can handle differently. 

If there are any suggestions for how we might better document this / make it easier to discover, we'd be very interested in ideas!

**Comment by pr0me** [comment] 2020-11-20 11:53
Thanks for the replies, I understand where that behavior is coming from but I agree with nshp that this is something which should be fixed in the UI. The current behavior is counter-intuitive at best and I can imagine situations in which it can quickly lead to mistakes when the user is not taking care.

I did not find the implementation in this repo or in the ARM core plugin, but here's a naive idea: when the user attempts to create a new function and selects 'thumb2' at an even offset, simply increment the address by one before disassembling.

**Comment by psifertex** [comment] 2020-11-20 15:45
After some internal discussion we think we have a better way forward that will resolve this, re-opening.

**Comment by bpotchik** [comment] 2020-11-22 00:27
Fixed in `2.2.2546-dev`.

**Closed by bpotchik** 2020-11-22 00:27 UTC
Labels: bug
