### ISSUE TITLE
get_strings improvements

### ISSUE THREAD

**Issue by devtty1er** [Vector35/binaryninja-api#1298] opened 2019-03-13 15:39 UTC
Binary Ninja Version: 1.1.1544-dev, e54a51f3
Platform: macOS 10.14

![https://imgur.com/OUwKzrh](https://imgur.com/download/OUwKzrh)
```
>>> bv.get_strings(0x15c8, 1)
[]
>>> bv.get_strings(0x15c7, 1)[0]
[<StringType.AsciiString: 0x15c7, len 0x8>]
>>> bv.get_strings(0x15c7, 1)[0].value
'@6Square'
```

[virtual.bndb](https://www.dropbox.com/s/07ud3u4qsrmmioa/virtual.bndb?dl=0) @ `0x15c8`

**Comment by psifertex** [comment] 2019-03-13 17:59
I can't reproduce the issue with a sample binary here. Is it just that binary that does it for you? Just that offset? Can you share the bndb?

**Comment by devtty1er** [comment] 2019-03-13 21:05
@psifertex [virtual.bndb](https://www.dropbox.com/s/07ud3u4qsrmmioa/virtual.bndb?dl=0) @ `0x15c8`

**Comment by psifertex** [comment] 2019-03-14 01:50
Ahh, perfect, thanks. So there's a few separate issues this points out actually that I'm going to track here:

- [ ] `get_strings` should better handle when a string exists at a starting location BEFORE the current address as long as it overlaps (in this case, our original strings sweep finds the string at 0x15c7 which is wrong, but just happens because there's a `@` character inside the previous pointer.
- [ ] When our naive strings sweep finds a string, if we later get better type information that supersedes it we should remove/update the original string type based on the better information (Bonus points: this should use our confidence system)
- [ ] A more moderate form of the previous step would be to adjust strings whenever we have information that creates other data references that overlap with the string to truncate the string to remove the overlapping characters. 

The simplest fix is likely the first one, but we'll track the others here too.

**Comment by psifertex** [comment] 2019-03-14 03:11
So we've been talking about it some more and I'm not convinced that the API /should/ include strings that start before the range specified. We might introduce a separate API that would do so, but this API is behaving as intended even if it's not quite as obvious. Of course, the second two improvements still remain.

**Comment by devtty1er** [comment] 2019-03-14 18:44
> I'm not convinced that the API /should/ include strings that start before the range specified.

I would argue that it doesn't... there just happens to be a valid ASCII byte right before the contextual start of the string, but I understand your preference to keep `bv.get_strings()` reflective of raw strings. Without getting into redefining the original string information based on type information or data references, I PR'd a separate API, `bv.get_ascii_string_at()` which will work even if the start of the string is in the middle of valid ASCII bytes. I think the long-term, intuitive fix would be to redefine string starts based on type information and/or data references, as you suggested, but this works for now.

**Comment by sraboy** [comment] 2019-03-22 15:58
> I think the long-term, intuitive fix (from an API usage standpoint) would be to redefine string starts based on type information and/or data references, as you suggested, but this works for now.

The current API should still be available as something like `get_strings(addr, raw=True)`. Maybe instead of `raw=True` or multiple similar functions, there should be a `get_strings(addr, style=some_BinaryViewType_default)` where `style` specifies raw, C-String, ASCII-only, etc.

**Comment by psifertex** [comment] 2019-03-22 17:20
Yeah, better support for different classes of strings in general is on our todo list and is a broader issue beyond just this. Most importantly we'd like for the definition of user-defined string formats which requires us to really think through which features/APIs we'd need now as much as possible. It's one reason we've held off making too many sweeping changes to the current string APIs since we want to make sure the next big set of changes encompass that as well.

**Comment by bpotchik** [comment] 2019-04-12 21:30
I've also added `get_string_at(self, addr, partial=False)` which returns any string that falls on the specified address. You can specify `partial` to retrieve the full or partial part. When it comes to partial behavior, I've only added support for AsciiString for now.

**Comment by psifertex** [comment] 2019-07-17 18:54
Gonna close this one out as I think all the relevant requested APIs exist and are better documented.

Long-term we're going to use #1334  to track the remaining issues.

**Closed by psifertex** 2019-07-17 18:54 UTC
Labels: core
