### ISSUE TITLE
Demangle gnu symbols in PE files

### ISSUE THREAD

**Issue by jrozner** [Vector35/binaryninja-api#2905] opened 2022-01-31 02:55 UTC
**What is the feature you'd like to have?**
Currently if PE files are compiled with GCC and have gnu symbol mangling symbols aren't demangled.

**Is your feature request related to a problem?**
If applicable, please provide a clear and concise description of what the problem is.

**Are any alternative solutions acceptable?**

**Additional Information:**
Please add any other context or screenshots that would help us understand your feature request here.
![Screenshot 2022-01-30 185513](https://user-images.githubusercontent.com/26415/151732914-9539145e-736b-4d7f-8390-bacb4fe80dfa.png)

**Comment by psifertex** [comment] 2022-01-31 03:16
The demanglers are available via https://api.binary.ninja/binaryninja.demangle-module.html#binaryninja.demangle.demangle_gnu3

A snippet could quickly rename all of the functions as a temporary work-around. Without testing, something like:
```
for f in bv.functions:
    f.name=demangle_gnu3(f.arch, f.name)
```
should help.

**Comment by plafosse** [comment] 2022-02-09 18:55
duplicate of #2405

**Closed by plafosse** 2022-02-09 18:55 UTC
Labels: duplicate, enhancement, demangler
