### ISSUE TITLE
UI: Interactive function stack view

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#1570] opened 2020-04-17 17:02 UTC
Please provide an interactive function stack view, similar to the existing structures interface.

Being able to change stack variable sizes, structure, and datatypes in a single view is sorely missing. Right now it's pretty difficult to properly size a stack buffer.

Something simliar to [IDA's "Stack View" ](https://i.stack.imgur.com/wB1ok.png)or [x64Dbg's stack](https://x64dbg.com/img/slide2.png).

**Comment by plafosse** [comment] 2020-04-27 16:14
This is a duplicate of #220

**Closed by plafosse** 2020-04-27 16:14 UTC
Labels: duplicate, enhancement, ui
