### ISSUE TITLE
A cruel and unusual punishment

### ISSUE THREAD

**Issue by joelreymont** [Vector35/binaryninja-api#5325] opened 2024-04-25 15:30 UTC
**Version and Platform (required):**
- Binary Ninja Version: 4.0.4958, ddff9339
- OS: macos
- OS Version: 14.4
- CPU Architecture: arm64

**Bug Description:**

Function signature in source code

```
static T_DjiReturnCode DjiUser_PrepareSystemEnvironment(void)
{
```

Function invocation in source code 

```
    T_DjiReturnCode returnCode;
    ...
    /*!< Step 1: Prepare system environment, such as osal, hal uart, console function and so on. */
    returnCode = DjiUser_PrepareSystemEnvironment();
    if (returnCode != DJI_ERROR_SYSTEM_MODULE_CODE_SUCCESS) {
        USER_LOG_ERROR("Prepare system environment error");
        return DJI_ERROR_SYSTEM_MODULE_CODE_SYSTEM_ERROR;
    }
```

A cruel and unusual punishment by BN HLL

```
00012d20      int64_t x0
00012d20      int128_t v0
00012d20      int128_t v1
00012d20      int128_t v2
00012d20      int128_t v3
00012d20      int128_t v4
00012d20      int128_t v5
00012d20      int128_t v6
00012d20      int128_t v7
00012d20      x0, v0, v1, v2, v3, v4, v5, v6, v7 = DjiUser_PrepareSystemEnvironment()
00012d30      if (x0 != 0)
00012d4c          DjiLogger_UserLogOutput(0, "[%s:%d) Prepare system environme…", "main", v0, v1, v2, v3, v4, v5, v6, v7)
00012d30      else
...
```

The function signature is correct

```
00013364  long unsigned int DjiUser_PrepareSystemEnvironment()
```

Contrast with IDA Pro

```
if ( DjiUser_PrepareSystemEnvironment() )
  {
    DjiLogger_UserLogOutput(0LL, "[%s:%d) Prepare system environment error", (const char *)_FUNCTION___3, 116LL);
  }
```

**Comment by psifertex** [comment] 2024-04-25 15:56
Is the `long unsigned int DjiUser_PrepareSystemEnvironment()` signature the default or did you enter it yourself? Trying to understand if default confidence might be at issue here. Seeing that as default decompilation doesn't surprise me (especially in the face of a variadic function), but the correct parameters being ignored does.

**Comment by psifertex** [comment] 2024-04-25 15:59
Can you hit `y` and then `<enter>` when selecting that particular token? Does that change the result? This should coerce the inferred low-confidence prototype into a user-type.

**Comment by joelreymont** [comment] 2024-04-25 16:02
Doesn't change anything. Should I send you the binary?

**Comment by psifertex** [comment] 2024-04-25 16:03
Sure.

**Comment by joelreymont** [comment] 2024-04-25 16:13
Sent the binary on Slack. Also, other functions have exactly the same issue, e.g. 

```
00012d5c          x0_3, v0_1, v1_1, v2_1, v3_1, v4_1, v5_1, v6_1, v7_1 = DjiUser_FillInUserInfo(userInfo: &userInfo)
00012d6c          if (x0_3 != 0)
```

This one is interesting in that the Change Type dialog fails to parse its own type spec. It puts the structure definition in the signature

```
long unsigned int DjiUser_FillInUserInfo(struct { char appName[0x20]; char appId[0x10]; char appKey[0x20]; char appLicense[0x200]; char developerAccount[0x40]; char baudRate[0x7]; }* userInfo)
```

I'll file another bug report once I have your internal database name to mention.

**Comment by joelreymont** [comment] 2024-04-25 16:22
The variadic function signature is 

```
void DjiLogger_UserLogOutput(E_DjiLoggerConsoleLogLevel level, const char *fmt, ...);
```

Does BN handle these correctly?

**Comment by psifertex** [comment] 2024-04-25 16:27
binary available internally as `major dine favor`

**Comment by psifertex** [comment] 2024-04-25 16:35
Looks like this is just a duplicate of "better heuristics for variadic functions" (#3916).

As soon as I change the prototype for the logger to:
```
void* DjiLogger_UserLogOutput(int32_t dunno, char* format, char* functionname, int32_t linenum, ...)
```

The output becomes:
<img width="1312" alt="Screenshot 2024-04-25 at 12 33 03" src="https://github.com/Vector35/binaryninja-api/assets/140215/8465fb71-696e-4503-a487-c4cee0eff487">

I'm closing this one in favor of the other for now, taking a look at the types now.

**Closed by psifertex** 2024-04-25 16:35 UTC
