### ISSUE TITLE
Implement proper handling of split registers in MLIL

### ISSUE THREAD

**Issue by quickcoldthought** [Vector35/binaryninja-api#939] opened 2018-02-16 20:26 UTC
I've shared a binary libips-bug.so over DM to peter.
In this binary for the function sub_578e0, the SSA form lifted for a div instruction at 0x583e9 appears to be incorrect.

On build 1062-dev it appears as:
![screen shot 2018-02-22 at 2 28 15 pm](https://user-images.githubusercontent.com/26824362/36562437-a7566636-17dc-11e8-829b-f796f84e73d8.png)

```
>>> current_mlil.ssa_form[1521].src.left
<il: edx_1#1:eax#0>
>>> current_mlil.ssa_form[1521].src.left.vars_read
[<ssa <var int32_t edx_1> version 1>, <ssa <var > version 0>]
>>> current_mlil.ssa_form[1521].src.left.high
<ssa <var int32_t edx_1> version 1>
>>> current_mlil.ssa_form[1521].src.left.low
<ssa <var > version 0>
>>> current_mlil.ssa_form[1521]
<il: temp0_3#3 = divu.dp.d(edx_1#1:eax#0, 0x18)>
```

Not only is the ssa var (for the low part of the MLIL_VAR_SPLIT_SSA) missing a name, the ssa_vars used seem wrong. Shouldn't it be getting the values from rax_69#86 and rdx_31#41 defined in that same basic block?  And shouldn't they be used with MLIL_VAR_SSA_FIELD instead of edx_1#1 and eax#0?

**Comment by amatus** [comment] 2018-02-23 15:40
Here's a minimal test case:
```
_start:
div ecx
ret
```
Everything below MLIL looks fine. In this example the MLIL is rendered in the UI as:
```
temp0 = divu.dp.d(edx:eax, arg4.ecx)
```
But both `edx` and `eax` are vars with no name:
```
>>> current_mlil[0].vars_read
[<var >, <var >, <var int32_t arg4>]
>>> current_mlil[0].vars_read[0].name
''
```

**Comment by plafosse** [comment] 2018-02-23 15:45
Split register access has some outstanding todo's. This is know just unimplemented. I'm going to change the issue to reflect the root cause.

**Comment by rssor** [comment] 2018-03-08 21:47
Fixed in build 1085. When converting lifted IL to low level IL, partial registers used as a source will be moved into temporary registers which are used as the actual operands passed to LLIL_REG_SPLIT.

**Closed by rssor** 2018-03-08 21:47 UTC
