### ISSUE TITLE
Some transform submenus don't work

### ISSUE THREAD

**Issue by toomanybananas** [Vector35/binaryninja-api#663] opened 2017-04-23 18:56 UTC
On version 1.0.712-dev Personal (on Windows), a few of the submenus in Edit -> Transform don't expand. Specifically, mousing over the Hash, Encrypt, and Decrypt options does nothing.

**Comment by plafosse** [comment] 2017-04-23 18:57
Duplicate of #544

**Closed by plafosse** 2017-04-23 18:57 UTC
