### ISSUE TITLE
enhanced windows platform support

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2849] opened 2022-01-19 18:23 UTC
Windows has lots of data structures regularly accessed off of FS and GS -- we need to enhance our windows platform support to apply the appropriate data structures at those locations to improve analysis of some libraries

**Comment by fuzyll** [comment] 2022-06-08 18:43
This is a duplicate of #1977, which we've earmarked for this next milestone anyway. Closing this in favor of that one.

**Comment by plafosse** [comment] 2022-10-05 17:26
I don't believe this should have been closed. #1977 is a likely pre-requsite for this one.

**Comment by plafosse** [comment] 2023-09-27 17:55
This is a duplicate of #1977 re-closing it 🤦

**Closed by plafosse** 2023-09-27 17:55 UTC
Labels: Type: Enhancement, Component: Core, Impact: Medium
