### ISSUE TITLE
Improved Default Type Libraries

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#3705] opened 2022-11-30 19:18 UTC
One of the biggest things that can affect our analysis is not starting with types we _should_ know because they're provided by the platform's SDK or are common to a language runtime (e.g. `libc`). We need to make a concerted effort to update our type libraries to provide these types by default. This issue is intended to track all of the type libraries we don't currently ship by default (or do, but have issues/need updated). This issue is _not_ intended to track more general type library improvements. That ticket is #3687.

**Comment by plafosse** [comment] 2024-01-10 14:00
This is actually a duplicate of https://github.com/Vector35/binaryninja-api/issues/3268

**Closed by plafosse** 2024-01-10 14:00 UTC
Labels: Type: Enhancement, Impact: High, Effort: High, Component: Type Libraries

**Comment by fuzyll** [comment] 2024-01-10 16:47
I don't know if this is a duplicate?

3268's goal was to make sure we had a `libc` for each platform/architecture (or perhaps some way to have a single `libc` that is shared amongst all platforms/architectures.

This issue's goal was to track things like `libc`, but also other things that users might expect to have available on a given platform.

I understand it was a little un-specific and broad in scope. So, I'm happy to make separate issues for things. But, an example would be libraries like `libcurl` and `libcrypt` and `libssl` that are pretty ubiquitous on Linux. Another example would be common frameworks on macOS that are shipped with the SDK.

**Comment by plafosse** [comment] 2025-09-17 12:34
Linux x86 libc is missing: setsockopt, ioctl, bind, socket
