### ISSUE TITLE
Callees are not serialized to BNDB

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#2531] opened 2021-06-28 23:54 UTC
**Binary Ninja Version**
All versions since callees were added

**Describe the bug**
When serializing the BNDB, functions callees are not saved. This can result in inconsistent analysis result between headless and the UI due to XXXX 

**To Reproduce**
1. Open an executable, save a BNDB
2. Check callees of any function whose callees include some generated by analysis
3. Do the same in the API/headless, get a different count

**Expected behavior**
Both methods should show the same data

**Comment by hanssl** [comment] 2021-06-30 19:03
Related bug: https://github.com/Vector35/binaryninja-api/issues/2532

**Comment by kristopax** [comment] 2021-09-30 19:14
This issue is more complex than originally thought.  While trying to reproduce the bug from the related issue #2530, I observed "interesting" behavior.  In VS Code, I single stepped through the script attached to that issue.  During the second pass of printing out the function call sites (from the binary view loaded from the previously saved BNDB file), if the variables pane (in VS Code) had the `func` variable expanded while it was live, then `func.call_sites` updated with the correct number of call sites. This leads me to believe that the issue does not appear to be the result of call sites not being explicitly saved, but rather incomplete analysis updates (which seem to get triggered by VS Code's variable viewer).

I'm moving this issue back to the backlog until someone with available time and more knowledge of BN internals can investigate and hopefully resolve.

**Comment by kristopax** [comment] 2021-10-01 23:46
Function callees (in the python api) are generated on-demand from the function call sites.  It turns out that the inconsistent results between headless and UI versions is the result of call sites not being properly saved when serializing snapshots to the BNDB.  BN was only saving call sites that had callees, so call sites that did not have any callee functions (e.g. indirect calls) did not get saved to the BNDB.   In the UI, simply navigating to a function causes the IL to get generated, which triggers the regeneration of all call sites (from the IL).  In the headless version, call site re-generation was not happening (unless the IL was explicitly accessed first), which meant that call sites were based on the ones loaded from the saved BNDB. As mentioned above, these call sites loaded from the BNDB did not include those call sites that did not have any callees, which led to the inconsistent results.  This behavior is now fixed in 2.4.3030.  Function call sites are now listed in the way they were intended to be ... for all the (headless or UI) world to see.

**Closed by kristopax** 2021-10-01 23:46 UTC
Labels: bug, Impact: Low, Effort: Low
