### ISSUE TITLE
Opcode Byte Display

### ISSUE THREAD

**Issue by bdarmofal** [Vector35/binaryninja-api#353] opened 2016-07-23 22:00 UTC
I need to be able to show opcode and operand bytes in graph view as is possible in IDA Pro.
Only having access to the instruction mnemonic is not good enough...

**Comment by psifertex** [comment] 2016-07-23 22:03
Ahh, I like the easy bugs. 

This is already fixed in the next release. 

![screen shot 2016-07-23 at 6 03 23 pm](https://cloud.githubusercontent.com/assets/140215/17080488/c6dff1de-50ff-11e6-8cd6-e6786ec22f0c.png)

**Closed by psifertex** 2016-07-23 22:03 UTC
Labels: enhancement

**Comment by bdarmofal** [comment] 2016-07-23 22:25
Would it be possible to ask for spaces between the bytes for readability?  Thanks!

**Comment by psifertex** [comment] 2016-07-23 23:31
Hmm, maybe. We're debating it internally. The problem is we already crop off x86 opcodes after 7 by default to keep the graph sizes manageable, but adding spaces would mean even less of the opcodes would be shown or the graphs would be even wider. 

Is the goal to just better understand which was the opcode versus operands? Or just to help reading individual bytes in general?

**Comment by bdarmofal** [comment] 2016-07-23 23:43
Identifying opcode vs operands would be the purpose of this.
Intel ISR manual shows spaces between opcode bytes so it would be nice to follow their convention.  Maybe include a feature to suppress opcode printing?  IDA offers a max number to print (0+) in its config.
