### ISSUE TITLE
"Navigate to main on open" takes precedence over "Prefer Triage View"

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#3154] opened 2022-06-01 03:28 UTC
**Version and Platform (required):**
- Binary Ninja Version: 3.1.3474-dev
- OS: macOS
- OS Version: 10.15.7
- CPU Architecture: x64

**Bug Description:**
When opening a binary with a symbol named `main`, but with "Always Prefer Triage Summary View" enabled, Triage view is not shown as the navigation to main closes it.

**Steps To Reproduce:**
1. Enable "Always Prefer Triage Summary View"
2. Enable "Navigate to Main Function when First Opening Binary"
3. Open any binary which contains a symbol named "main" (eg an executable)
4. Observe no Triage view
5. Open any binary which does not contain a symbol named "main" (eg a library)
6. Observe Triage view

**Expected Behavior:**
I expected _Always_ Prefer Triage View to ... Always prefer Triage.

**Comment by psifertex** [comment] 2022-06-01 04:36
Navigate to main is unrelated. This was a regression introduced in 3.0.

**Comment by psifertex** [comment] 2022-06-01 04:55
After some discussion there are two related issues:
1) navigate to main can cause this behavior, but even if it's told to ignore the triage setting
2) Save Default Layout can override all such settings and indeed is probably a far better functionality for saving such a preference. All of: `triage.preferSummaryView`, `ui.view.graph.preferred`, `ui.view.linear.il`, `ui.view.graph.il`, and `ui.sidebar.openOnStartup` can probably be removed in lieu of the simpler save current layout option since it will override them anyway.

**Comment by bpotchik** [comment] 2022-10-12 01:51
Fixed in `3.1.3622-dev`. as a result of #3375.

Navigation preference on load is as follows (excluding BNDBs):
1) Navigate to view location history, if available (`ui.files.restore.viewState` must be enabled)
2) Check `triage.preferSummaryView`
3) Check `ui.files.navigation.preferMain`

**Closed by bpotchik** 2022-10-12 01:51 UTC
Labels: bug, ui, Impact: Low, Effort: Low
